(() => {
  'use strict';
  const C=window.LAMOU_CONFIG,$=id=>document.getElementById(id),authView=$('authView'),portalView=$('portalView'),loginForm=$('loginForm'),recoveryForm=$('recoveryForm'),msg=$('authMessage'),logoutBtn=$('logoutBtn'),installPwaBtn=$('installPwaBtn'),connectionState=$('connectionState');
  let refreshTimer=null,installPrompt=null,session=null,activeTenant=null,linkType='';const enc=encodeURIComponent,fmt=v=>v?new Date(v).toLocaleString('pt-BR'):'—',safe=v=>String(v??''),nowSec=()=>Math.floor(Date.now()/1000);
  function setMessage(text='',type=''){msg.textContent=text;msg.className=`message ${type}`}function saveSession(s){session=s;localStorage.setItem('lamou_client_session',JSON.stringify(s))}function clearSession(){session=null;localStorage.removeItem('lamou_client_session');if(refreshTimer)clearInterval(refreshTimer)}function loadStored(){try{return JSON.parse(localStorage.getItem('lamou_client_session')||'null')}catch{return null}}
  async function authFetch(path,options={}){const r=await fetch(`${C.supabaseUrl}/auth/v1/${path}`,{...options,headers:{apikey:C.publishableKey,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.msg||d.message||d.error_description||d.error||`HTTP ${r.status}`);return d}
  async function rest(path,options={}){await ensureFreshSession();const r=await fetch(`${C.supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:C.publishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401){clearSession();showAuth('Sua sessão expirou. Entre novamente.');throw new Error('Sessão expirada')}const text=await r.text(),d=text?JSON.parse(text):null;if(!r.ok)throw new Error(d?.message||d?.hint||d?.error||`HTTP ${r.status}`);return d}
  async function ensureFreshSession(){if(!session)throw new Error('Sem sessão');if((session.expires_at||0)>nowSec()+60)return;if(!session.refresh_token)throw new Error('Sessão sem refresh token');saveSession(await authFetch('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})}))}
  async function login(email,password){const s=await authFetch('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(!s.user?.email_confirmed_at)throw new Error('Confirme seu e-mail antes de entrar.');saveSession(s);await bootPortal()}
  async function recover(email){await authFetch('recover',{method:'POST',body:JSON.stringify({email,redirect_to:location.origin+location.pathname})});setMessage('Se esse e-mail estiver cadastrado, enviaremos um link de recuperação.','ok')}
  function getHashParams(){return new URLSearchParams(location.hash.replace(/^#/,''))}
  async function completeLinkPassword(password){const hp=getHashParams(),token=hp.get('access_token'),refresh=hp.get('refresh_token')||'',expires=Number(hp.get('expires_in')||3600);if(!token)throw new Error('Link inválido ou expirado.');const user=await authFetch('user',{method:'PUT',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify({password})});history.replaceState(null,'',location.pathname);saveSession({access_token:token,refresh_token:refresh,expires_at:nowSec()+expires,user});setMessage(linkType==='invite'?'Senha definida. Abrindo seu ambiente…':'Senha alterada. Abrindo seu ambiente…','ok');await bootPortal()}
  async function findClientTenant(){const uid=session?.user?.id;if(!uid)throw new Error('Usuário não identificado.');const ms=await rest(`lamou_memberships?user_id=eq.${enc(uid)}&status=eq.ACTIVE&select=tenant_id,role,status`);if(!ms?.length)throw new Error('Sua conta ainda não está vinculada a um ambiente cliente.');for(const m of ms){const t=(await rest(`lamou_tenants?id=eq.${enc(m.tenant_id)}&select=id,slug,name,status`))?.[0];if(t&&t.slug!=='LAMOU')return {...t,membershipRole:m.role}}throw new Error('Esta conta não possui ambiente cliente.')}
  async function fetchState(){const t=activeTenant;if(!t)return;const id=enc(t.id),[apps,devices,deliveries]=await Promise.all([rest(`lamou_app_grants?tenant_id=eq.${id}&enabled=eq.true&select=app_key,app_name,approved_version,status&order=app_name.asc`),rest(`lamou_client_devices?tenant_id=eq.${id}&select=device_key,device_name,status,last_seen_at,core_version,app_version,platform&order=created_at.desc&limit=1`),rest(`lamou_delivery_records?tenant_id=eq.${id}&select=delivery_id,product,version,core_version,status,delivered_at,installed_at&order=created_at.desc&limit=1`)]);render({tenant:t,apps:apps||[],device:devices?.[0]||null,delivery:deliveries?.[0]||null});connectionState.textContent='Atualizado agora';document.body.classList.remove('offline')}
  function isOnlineDevice(d){return !!d?.last_seen_at&&Date.now()-new Date(d.last_seen_at).getTime()<C.offlineStaleMs}function escapeHtml(v){return safe(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function render(s){$('tenantName').textContent=s.tenant.name||s.tenant.slug;$('tenantBadge').textContent=s.tenant.status==='ACTIVE'?'ATIVO':safe(s.tenant.status);$('heroText').textContent='Seu portal é o ponto principal de acesso. O agente local aparece somente quando necessário.';$('productCount').textContent=String(s.apps.length);$('products').innerHTML=s.apps.length?s.apps.map(a=>`<div class="product"><strong>${escapeHtml(a.app_name)}</strong><span>LIBERADO${a.approved_version?' · '+escapeHtml(a.approved_version):''}</span></div>`).join(''):'<div class="empty">Nenhum produto foi liberado neste ambiente ainda.</div>';const online=isOnlineDevice(s.device);$('agentDot').classList.toggle('online',online);$('agentStatus').textContent=online?'Conectado':'Não conectado / opcional';$('lastSeen').textContent=fmt(s.device?.last_seen_at);$('deviceName').textContent=s.device?.device_name||s.device?.device_key||'—';$('platform').textContent=s.device?.platform||'—';$('agentCallout').textContent=online?'Agente Local detectado. Ele continuará apenas como ponte para recursos deste computador.':'O portal continua funcionando normalmente. Instale o Agente Local somente quando um produto LAMOU solicitar acesso a recursos deste computador.';const steps=[['Conta criada','Acesso por convite',true],['E-mail confirmado','Identidade validada',!!session?.user?.email_confirmed_at],['Ambiente ativo','Tenant isolado no CORE',s.tenant.status==='ACTIVE'],['Produtos liberados','Somente o que foi autorizado',s.apps.length>0],['Portal pronto','PWA no dispositivo',true],['Agente local','Somente quando necessário',online]];const pct=Math.round((steps.slice(0,5).filter(x=>x[2]).length/5)*100);$('journeyPct').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;let found=false;$('journey').innerHTML=steps.map((x,i)=>{const done=x[2],cur=!done&&!found?(found=true,true):false;return `<li class="${done?'done':cur?'current':''}"><div class="num">${done?'✓':i+1}</div><b>${escapeHtml(x[0])}</b><small>${escapeHtml(x[1])}</small></li>`}).join('')}
  function showAuth(text=''){authView.hidden=false;portalView.hidden=true;logoutBtn.hidden=true;if(text)setMessage(text,'error')}function showPortal(){authView.hidden=true;portalView.hidden=false;logoutBtn.hidden=false;setMessage('')}
  async function bootPortal(){showPortal();connectionState.textContent='Conectando…';try{activeTenant=await findClientTenant();await fetchState();if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>fetchState().catch(markOffline),C.refreshMs)}catch(e){clearSession();showAuth(e.message||'Não foi possível abrir seu ambiente.')}}function markOffline(){connectionState.textContent='Sem atualização';document.body.classList.add('offline')}
  loginForm.addEventListener('submit',async e=>{e.preventDefault();setMessage('Entrando…');try{await login($('email').value.trim(),$('password').value)}catch(err){setMessage(err.message,'error')}});$('forgotBtn').addEventListener('click',async()=>{const email=$('email').value.trim();if(!email)return setMessage('Digite seu e-mail primeiro.','error');try{await recover(email)}catch(err){setMessage(err.message,'error')}});recoveryForm.addEventListener('submit',async e=>{e.preventDefault();const p=$('newPassword').value,p2=$('newPassword2').value;if(p.length<8)return setMessage('Use pelo menos 8 caracteres.','error');if(p!==p2)return setMessage('As senhas não conferem.','error');try{await completeLinkPassword(p)}catch(err){setMessage(err.message,'error')}});logoutBtn.addEventListener('click',()=>{clearSession();activeTenant=null;showAuth();connectionState.textContent='Desconectado'});$('refreshBtn').addEventListener('click',()=>fetchState().catch(markOffline));window.addEventListener('online',()=>fetchState().catch(markOffline));window.addEventListener('offline',markOffline);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installPwaBtn.hidden=false});installPwaBtn.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installPwaBtn.hidden=true});
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const hp=getHashParams();linkType=hp.get('type')||'';if((linkType==='recovery'||linkType==='invite'||linkType==='signup')&&hp.get('access_token')){loginForm.hidden=true;recoveryForm.hidden=false;$('recoveryEyebrow').textContent=linkType==='invite'?'Convite LAMOU':'Recuperação';$('recoveryTitle').textContent=linkType==='invite'?'Defina sua senha para entrar':'Crie sua nova senha';setMessage(linkType==='invite'?'Convite validado. Agora defina sua própria senha.':'Link validado. Defina sua nova senha.','ok')}else{session=loadStored();if(session)bootPortal();else showAuth()}
})();
