(() => {
'use strict';

const STORE='lamou_v10_db';
const LAMOU_BASE='LAMOU é um projeto musical brasileiro de criação humana e direção artística, com IA usada como ferramenta de produção e expansão criativa.';
const GENRES=['Pop','Rock','Sertanejo','Forró','Gospel','Funk','Pagode / Samba','Axé','Eletrônica','Hip Hop / Rap','R&B / Soul','Latino','MPB','Outros'];
const MOODS=['Emocional','Dançante','Romântico','Espiritual','Intenso','Sexy','Chill','Debochado','Inspirador','Sombrio'];
const FORMATS=[['1:1','Capa'],['4:5','Feed vertical'],['9:16','Stories / vertical'],['16:9','Horizontal']];
const CHANNELS=[
{id:'spotify-artists',name:'Spotify for Artists',type:'Editorial',audience:'Editores oficiais do Spotify',country:'Global',lang:'PT/EN',cost:'Grátis',method:'Formulário oficial',url:'https://artists.spotify.com/',email:'',genres:['*'],ai:'Revisar',note:'Pitch editorial para lançamento elegível; ideal antes do lançamento.'},
{id:'groover',name:'Groover',type:'Rede profissional',audience:'Gravadoras, A&R, rádios, imprensa, sync, managers, DJs e bookers',country:'Global',lang:'PT/EN',cost:'Pago por contato',method:'Plataforma',url:'https://groover.co/pt/',email:'',genres:['*'],ai:'Revisar por profissional',note:'Escolha profissionais por gênero, país e objetivo.'},
{id:'dailyplaylists',name:'DailyPlaylists',type:'Playlists',audience:'Curadores de playlists',country:'Global',lang:'PT/EN',cost:'Grátis + planos',method:'Plataforma',url:'https://dailyplaylists.com/pt/',email:'info@dailyplaylists.com',genres:['*'],ai:'Revisar por curador',note:'Submissão para playlists; a faixa precisa estar lançada no Spotify.'},
{id:'soundplate',name:'Soundplate',type:'Playlists',audience:'Curadores independentes',country:'Global',lang:'EN',cost:'Grátis',method:'Plataforma',url:'https://play.soundplate.com/playlists/latest',email:'',genres:['*'],ai:'Categoria AI Generated disponível',note:'Envie somente para playlists compatíveis.'},
{id:'musosoup',name:'MusoSoup',type:'Imprensa / curadoria',audience:'Blogs, imprensa, playlists e rádios',country:'Global',lang:'EN',cost:'Misto',method:'Plataforma',url:'https://musosoup.com/artists-how-it-works',email:'',genres:['*'],ai:'Revisar',note:'Curadores interessados podem oferecer cobertura.'},
{id:'reverbnation',name:'ReverbNation Opportunities',type:'Indústria',audience:'A&R, selos, sync, festivais, rádio, imprensa e marcas',country:'Global',lang:'EN',cost:'Grátis + planos',method:'Plataforma',url:'https://www.reverbnation.com/band-promotion/opportunities',email:'',genres:['*'],ai:'Revisar por oportunidade',note:'Aplicar apenas quando houver fit.'},
{id:'bananas',name:'Bananas Music',type:'Curadoria brasileira',audience:'Curadores de playlists e music branding',country:'Brasil / Global',lang:'PT',cost:'Via Groover',method:'Groover',url:'https://bananas.mus.br/envie-sua-musica/',email:'',genres:['*'],ai:'Revisar',note:'Recebe música via Groover.'},
{id:'wegoout',name:'We Go Out',type:'Imprensa / lançamento',audience:'Editorial de música eletrônica',country:'Brasil',lang:'PT',cost:'Grátis',method:'Formulário',url:'https://wegoout.com.br/',email:'',genres:['Eletrônica'],ai:'Revisar',note:'Foco editorial em música eletrônica.'},
{id:'sun7',name:'Sun7 Label',type:'Gravadora / selo',audience:'Label e business musical',country:'Brasil',lang:'PT',cost:'Grátis para demo',method:'Formulário / e-mail',url:'https://www.sun7label.com/contato',email:'contato@sun7label.com',genres:['*'],ai:'Revisar',note:'Aceita links de demonstração.'},
{id:'progressive',name:'Progressive Generation',type:'Gravadora / A&R',audience:'A&R de música eletrônica',country:'Brasil',lang:'PT',cost:'Grátis',method:'E-mail',url:'https://progressivegeneration.com.br/label/demo/',email:'contato@progressivegeneration.com.br',genres:['Eletrônica'],ai:'Revisar',note:'Pede link privado + contexto da faixa.'},
{id:'paulinas',name:'Paulinas-COMEP',type:'Gravadora / editora',audience:'Música cristã/católica',country:'Brasil',lang:'PT',cost:'Grátis',method:'E-mail',url:'https://universo.paulinas.com.br/conteudo/envie-seu-projeto-paulinas-comep/61',email:'comep@paulinas.com.br',genres:['Gospel'],ai:'Revisar',note:'Aceita projeto musical e composições.'},
{id:'belem',name:'Gravadora Belém',type:'Gravadora',audience:'Mercado gospel pentecostal',country:'Brasil',lang:'PT',cost:'Revisar',method:'Página / e-mail',url:'https://gravadorabelem.com.br/',email:'contato@gravadorabelem.com.br',genres:['Gospel'],ai:'Revisar',note:'Segmento gospel/pentecostal.'},
{id:'dnbb',name:'DNBB Music Group',type:'Gravadora / A&R',audience:'Drum & Bass e Bass Music',country:'Brasil / Global',lang:'PT/EN',cost:'Grátis para demo',method:'Formulário / link',url:'https://dnbbrecords.com/',email:'',genres:['Eletrônica'],ai:'Revisar',note:'Pede áudio de alta qualidade e link privado.'},
{id:'midsummer',name:'Midsummer Madness',type:'Selo independente',audience:'Catálogo independente',country:'Brasil / Reino Unido',lang:'PT',cost:'Grátis',method:'Contato pelo site',url:'https://mmrecords.com.br/contato/',email:'',genres:['Rock','Pop','Eletrônica','Outros'],ai:'Revisar',note:'Enviar links, apresentação e material visual.'},
{id:'boxradio',name:'Box Radio',type:'Rádio',audience:'Programadores de rádio por gênero',country:'Global',lang:'EN',cost:'Revisar',method:'E-mail',url:'https://boxradio.net/pt/submitmusic',email:'hello@boxradio.net',genres:['*'],ai:'Revisar',note:'Pede link de download em nuvem e áudio de qualidade.'},
{id:'yourjazz',name:'Your Jazz Radio',type:'Rádio',audience:'Programação de jazz',country:'Global',lang:'EN',cost:'Revisar',method:'E-mail / formulário',url:'https://yourjazzradio.com/submit-music/',email:'artist@yourjazzradio.com',genres:['Outros'],ai:'Revisar',note:'Somente jazz.'},
{id:'undaground',name:'Tales From The Undaground Radio',type:'Rádio / promoção',audience:'DJs, rádio e público underground',country:'Global',lang:'EN',cost:'Misto',method:'Formulário',url:'https://www.djundagroundlive.com/',email:'',genres:['Hip Hop / Rap','R&B / Soul','Eletrônica','Outros'],ai:'Revisar',note:'Hip-hop, R&B, reggae, house e open format.'}
];

let mediaUrl='', audioUrl='', audioElement=null, rankingFingerprint=null, rankingMeta=null;

function id(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3200)}
function root(){return document.getElementById('appRoot')}
function pageHead(k,t,s){return `<div class="page-head"><div><div class="eyebrow">${esc(k)}</div><h1>${esc(t)}</h1><p>${esc(s)}</p></div></div>`}
function modal(h){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)Lamou.closeModal()"><section class="modal">${h}</section></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function fmtDate(x){try{return new Date(x).toLocaleString('pt-BR')}catch(_){return x||'—'}}
function markNav(v){document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view===v))}

function defaults(){return {
  profile:{displayName:'LAMOU',artistName:'LAMOU',artistUrl:'',artistImage:'',artistBio:LAMOU_BASE,artistStats:null,releases:[]},
  connections:{spotify:'red'},history:[],draft:null,radar:[],suppressed:[],rankings:[],webChannels:CHANNELS
}}
function freshDraft(mode,artist='LAMOU'){return {id:id(),mode,step:1,status:'draft',createdAt:new Date().toISOString(),url:'',title:'',artist,project:'',genre:'Pop',mood:'Emocional',story:'',cover:'',creativeSource:'spotify',creativeFormat:'1:1',mediaType:'image',mediaName:'',hookDuration:20,hooks:[],hook:null,audioName:'',fingerprint:null,description:'',hashtags:'',generation:0,channels:[],submitted:[],optOuts:[]}}
function normalizeDraft(input){if(!input||typeof input!=='object')return null;const d={...freshDraft(input.mode==='campaign'?'campaign':'quick',input.artist||'LAMOU'),...input};d.step=Math.max(1,Math.min(5,Number(d.step)||1));d.creativeFormat=FORMATS.some(([f])=>f===d.creativeFormat)?d.creativeFormat:'1:1';d.creativeSource=['spotify','upload-image','upload-video'].includes(d.creativeSource)?d.creativeSource:'spotify';d.hooks=Array.isArray(d.hooks)?d.hooks:[];d.submitted=Array.isArray(d.submitted)?d.submitted:[];d.optOuts=Array.isArray(d.optOuts)?d.optOuts:[];return d}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}')||{}, b=defaults();return {...b,...raw,profile:{...b.profile,...(raw.profile||{})},connections:{spotify:raw.connections?.spotify||'red'},history:Array.isArray(raw.history)?raw.history.filter(x=>['approved','sent'].includes(String(x.status||''))):[],suppressed:Array.isArray(raw.suppressed)?raw.suppressed:[],rankings:Array.isArray(raw.rankings)?raw.rankings:[],webChannels:CHANNELS,draft:normalizeDraft(raw.draft)}}catch(_){return defaults()}}
let state=loadState();
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function suppressedIds(){return new Set(state.suppressed.map(x=>x.channelId))}
function compatibleChannels(d){const blocked=suppressedIds();return CHANNELS.filter(c=>!blocked.has(c.id)&&(c.genres.includes('*')||c.genres.includes(d?.genre||'Pop')))}
function scoreChannel(c,d){let s=0;if(c.genres.includes(d.genre))s+=5;if(c.genres.includes('*'))s+=2;if(/^Grátis/.test(c.cost))s+=2;if(c.country.includes('Brasil'))s+=2;if(/Editorial|Playlists|Rede profissional/.test(c.type))s+=1;return s}
function recommend(d){const a=compatibleChannels(d).sort((x,y)=>scoreChannel(y,d)-scoreChannel(x,d));d.channels=(d.mode==='campaign'?a:a.slice(0,Math.min(7,a.length))).map(c=>c.id)}
function channel(cid){return CHANNELS.find(c=>c.id===cid)}

async function ensureSession(){let dv=localStorage.getItem('lamou_device_id');if(!dv){dv=id()+'-'+Date.now();localStorage.setItem('lamou_device_id',dv)}try{await fetch('/api/session/device',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:dv})})}catch(_){}}
async function refreshProfile(){try{const q=new URLSearchParams({artist:state.profile.artistName||'LAMOU',artistUrl:state.profile.artistUrl||''});const r=await fetch('/api/profile/summary?'+q,{credentials:'include',cache:'no-store'});if(!r.ok)return;const x=await r.json();if(x.connections)state.connections={spotify:x.connections.spotify||state.connections.spotify||'red'};if(x.artist){state.profile.artistName=x.artist.name||state.profile.artistName;state.profile.artistUrl=x.artist.url||state.profile.artistUrl;state.profile.artistImage=x.artist.image||state.profile.artistImage;state.profile.artistStats=x.artist.stats||state.profile.artistStats;state.profile.releases=Array.isArray(x.artist.releases)?x.artist.releases:state.profile.releases}save()}catch(_){}}
async function boot(){document.getElementById('appShell')?.classList.remove('hidden');document.getElementById('bottomNav')?.classList.remove('hidden');document.getElementById('headerUser').textContent=state.profile.displayName||'LAMOU';await ensureSession();await refreshProfile();home()}

function stats(){const h=state.history, sub=h.flatMap(x=>x.submitted||[]);return {approved:h.length,quick:h.filter(x=>x.mode==='quick').length,campaigns:h.filter(x=>x.mode==='campaign').length,sent:sub.length,destinations:new Set(sub.map(x=>x.channelId)).size,optouts:state.suppressed.length}}
function spotifyDashboard(){const a=state.profile.artistStats||{}, rel=state.profile.releases||[];return `<section class="card spotify-dashboard"><div class="spotify-profile-head"><div class="spotify-photo">${state.profile.artistImage?`<img src="${esc(state.profile.artistImage)}" alt="">`:'🎵'}</div><div class="spotify-profile-copy"><div class="eyebrow">DASHBOARD · SPOTIFY</div><h2>${esc(state.profile.artistName||'LAMOU')}</h2><p class="sub">${state.connections.spotify==='green'?'Perfil conectado ao catálogo do Spotify.':'Conecte o Spotify para buscar foto e discografia.'}</p>${state.profile.artistUrl?`<a class="spotify-attribution" href="${esc(state.profile.artistUrl)}" target="_blank" rel="noopener">● Spotify ↗</a>`:''}</div><span class="status ${state.connections.spotify==='green'?'green':'red'}">${state.connections.spotify==='green'?'● Conectado':'● Desconectado'}</span></div><div class="metric-strip"><div><b>${a.albums??'—'}</b><small>Álbuns</small></div><div><b>${a.singles??'—'}</b><small>Singles/EPs</small></div><div><b>${a.releases??rel.length??'—'}</b><small>Lançamentos</small></div><div><b>${a.tracks??'—'}</b><small>Faixas nas publicações</small></div></div><div class="album-chips">${rel.slice(0,12).map(r=>`<a href="${esc(r.url||state.profile.artistUrl||'#')}" target="_blank" rel="noopener" class="album-chip">${r.image?`<img src="${esc(r.image)}" alt="">`:''}<span><b>${esc(r.name)}</b><small>${esc(r.type||'lançamento')} · ${esc(r.releaseDate||'')}</small></span></a>`).join('')||'<span class="mini">Os títulos dos lançamentos aparecerão aqui quando o perfil artístico for identificado.</span>'}</div><div class="row" style="margin-top:14px"><button class="primary-button" onclick="Lamou.connect('spotify')">${state.connections.spotify==='green'?'↻ Atualizar Spotify':'Conectar Spotify'}</button><button class="ghost-button" onclick="Lamou.openUser()">Perfil LAMOU</button></div></section>`}
function appDashboard(){const s=stats();return `<section class="card dashboard-card"><div class="eyebrow">DASHBOARD · LAMOU</div><h2>Desempenho do app</h2><p class="sub">Aprovação, envios confirmados e pedidos para não receber mais.</p><div class="stats"><div class="stat"><b>${s.approved}</b><small>Aprovados</small></div><div class="stat"><b>${s.sent}</b><small>Envios</small></div><div class="stat"><b>${s.destinations}</b><small>Destinos</small></div><div class="stat"><b>${s.optouts}</b><small>Não enviar mais</small></div></div></section>`}
function home(){markNav('');root().innerHTML=`${pageHead('LAMOU','Seu painel musical','Spotify primeiro. Depois, o que o LAMOU fez com sua divulgação.')}${spotifyDashboard()}<div style="height:14px"></div>${appDashboard()}<section class="card" style="margin-top:14px"><h2>O que você quer fazer?</h2><div class="mode-grid"><button class="choice-card" onclick="Lamou.go('new')"><span class="feature-icon">✦</span><strong>Nova música</strong><small>Rápida ou campanha → criativo → hook → IA → aprovação.</small></button><button class="choice-card" onclick="Lamou.go('history')"><span class="feature-icon">◷</span><strong>Histórico</strong><small>Materiais aprovados e destinos.</small></button><button class="choice-card" onclick="Lamou.go('results')"><span class="feature-icon">⌁</span><strong>Resultados</strong><small>Envios, opt-outs e Ranking Técnico IA.</small></button></div></section>`}

function go(v){if(v==='new'){state.draft=null;cleanup();save();markNav('new');renderNew();return}markNav(v);if(v==='home')home();else if(v==='history')renderHistory();else if(v==='results')renderResults()}
function startMode(m){state.draft=freshDraft(m,state.profile.artistName||'LAMOU');recommend(state.draft);save();renderNew()}
function cleanup(){if(mediaUrl){URL.revokeObjectURL(mediaUrl);mediaUrl=''}if(audioUrl){URL.revokeObjectURL(audioUrl);audioUrl=''}audioElement=null}
function discardDraft(){state.draft=null;cleanup();save();renderNew()}
function syncDraft(){const d=state.draft;if(!d)return;[['songUrl','url'],['songTitle','title'],['songArtist','artist'],['songProject','project'],['songGenre','genre'],['songMood','mood'],['songStory','story'],['descriptionText','description'],['hashtagsText','hashtags']].forEach(([e,k])=>{const n=document.getElementById(e);if(n)d[k]=String(n.value||'').trim()});save()}
function back(){syncDraft();if(state.draft){state.draft.step=Math.max(1,state.draft.step-1);save();renderNew()}}
function next(n){syncDraft();if(state.draft){state.draft.step=n;save();renderNew()}}
function nextSong(){syncDraft();const d=state.draft;if(!d.title)return toast('Informe o nome da música.');recommend(d);d.step=2;save();renderNew()}
function nextCreative(){const d=state.draft;if(d.creativeSource==='spotify'&&!d.cover)return toast('Busque a música no Spotify ou escolha imagem/vídeo.');if(/^upload/.test(d.creativeSource)&&!d.mediaName)return toast('Selecione a imagem ou vídeo.');d.step=3;save();renderNew()}
function progress(step){return `<div class="flow-progress">${['Música','Criativo','Hook','IA','Aprovação'].map((n,i)=>`<div class="flow-step ${step===i+1?'on':step>i+1?'done':''}"><b>${i+1}</b><span>${n}</span></div>`).join('')}</div>`}
function renderNew(){if(!state.draft){root().innerHTML=`${pageHead('NOVA MÚSICA','Como você quer divulgar?','Escolha primeiro: divulgação rápida ou campanha.')}<div class="mode-grid two-mode"><button class="choice-card mode-quick" onclick="Lamou.startMode('quick')"><span class="feature-icon">⚡</span><strong>Divulgação rápida</strong><small>Prioriza os destinos mais compatíveis.</small></button><button class="choice-card mode-campaign" onclick="Lamou.startMode('campaign')"><span class="feature-icon">◎</span><strong>Criar campanha</strong><small>Usa todos os destinos compatíveis, exceto os bloqueados.</small></button></div>`;return}const d=state.draft,label=d.mode==='campaign'?'Campanha':'Divulgação rápida';root().innerHTML=`${pageHead(label,d.title||'Nova música','Música → Criativo → Hook → IA → Aprovação final.')}${progress(d.step)}${d.step===1?stepSong(d):d.step===2?stepCreative(d):d.step===3?stepHook(d):d.step===4?stepAI(d):stepApproval(d)}`;restoreMedia()}
function stepSong(d){return `<section class="card wizard-card step-blue"><div class="step-no">1 · MÚSICA</div><h2>Qual faixa vamos trabalhar?</h2><div class="field"><label>Link Spotify</label><div class="row"><input id="songUrl" style="flex:1" value="${esc(d.url)}" placeholder="https://open.spotify.com/track/..."><button class="primary-button" onclick="Lamou.loadTrack()">Buscar</button></div></div>${d.cover?`<div class="track-preview"><img src="${esc(d.cover)}"><div><b>${esc(d.title)}</b><small>${esc(d.artist)}</small></div></div>`:''}<div class="two" style="margin-top:12px"><div class="field"><label>Música</label><input id="songTitle" value="${esc(d.title)}"></div><div class="field"><label>Artista</label><input id="songArtist" value="${esc(d.artist)}"></div><div class="field"><label>CD / álbum / projeto de origem</label><input id="songProject" value="${esc(d.project)}"></div><div class="field"><label>Gênero</label><select id="songGenre">${GENRES.map(g=>`<option ${g===d.genre?'selected':''}>${g}</option>`).join('')}</select></div><div class="field"><label>Clima</label><select id="songMood">${MOODS.map(m=>`<option ${m===d.mood?'selected':''}>${m}</option>`).join('')}</select></div></div><div class="field"><label>Contexto da música</label><textarea id="songStory">${esc(d.story)}</textarea></div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.discardDraft()">Cancelar</button><button class="primary-button" onclick="Lamou.nextSong()">Criativo →</button></div></section>`}
async function loadTrack(){syncDraft();const d=state.draft;if(!d.url)return toast('Cole o link do Spotify.');try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(d.url));if(!r.ok)throw 0;const x=await r.json();d.title=x.title||d.title;d.artist=(x.author_name||d.artist||'LAMOU').replace(/Spotify/gi,'').trim();d.cover=x.thumbnail_url||d.cover;save();renderNew();toast('Música identificada.')}catch(_){toast('Link salvo. Preencha os dados manualmente se necessário.')}}
function stepCreative(d){return `<section class="card wizard-card step-lilac"><div class="step-no">2 · CRIATIVO</div><h2>Formato e imagem/vídeo</h2><div class="format-grid">${FORMATS.map(([f,n])=>`<button class="format-choice ${d.creativeFormat===f?'on':''}" onclick="Lamou.setFormat('${f}')"><b>${f}</b><span>${n}</span></button>`).join('')}</div><div class="creative-options" style="margin-top:12px"><button class="creative-option ${d.creativeSource==='spotify'?'on':''}" onclick="Lamou.chooseCreative('spotify')">🎵<b>Capa Spotify</b><small>${d.cover?'Disponível':'Busque a faixa primeiro'}</small></button><label class="creative-option ${d.creativeSource==='upload-image'?'on':''}">🖼️<b>Imagem</b><small>JPG/PNG/WebP</small><input hidden type="file" accept="image/*" onchange="Lamou.loadMedia(event,'image')"></label><label class="creative-option ${d.creativeSource==='upload-video'?'on':''}">🎬<b>Vídeo</b><small>MP4/WebM</small><input hidden type="file" accept="video/*" onchange="Lamou.loadMedia(event,'video')"></label></div><div id="creativePreview" class="creative-stage" style="margin-top:14px;aspect-ratio:${d.creativeFormat.replace(':','/')}">${previewCreative(d)}</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="primary-button" onclick="Lamou.nextCreative()">Definir hook →</button></div></section>`}
function previewCreative(d){if(d.creativeSource==='spotify'&&d.cover)return `<img src="${esc(d.cover)}"><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.project||d.genre)}</small></div>`;if(d.mediaName)return `<div class="empty"><b>${esc(d.mediaName)}</b><br>Arquivo selecionado.</div>`;return '<div class="empty">Escolha a capa, uma imagem ou um vídeo.</div>'}
function setFormat(f){state.draft.creativeFormat=f;save();renderNew()}
function chooseCreative(s){state.draft.creativeSource=s;save();renderNew()}
function loadMedia(e,t){const f=e.target.files?.[0];if(!f)return;if(mediaUrl)URL.revokeObjectURL(mediaUrl);mediaUrl=URL.createObjectURL(f);state.draft.creativeSource=t==='video'?'upload-video':'upload-image';state.draft.mediaType=t;state.draft.mediaName=f.name;save();renderNew()}
function restoreMedia(){const d=state.draft;if(!d||d.step!==2||!mediaUrl)return;const st=document.getElementById('creativePreview');if(!st)return;st.innerHTML=d.mediaType==='video'?`<video src="${mediaUrl}" controls playsinline></video>`:`<img src="${mediaUrl}">`}
function stepHook(d){return `<section class="card wizard-card step-peach"><div class="step-no">3 · HOOK</div><h2>Trecho mais forte</h2><p class="sub">O áudio é analisado no aparelho. O mesmo vetor técnico pode ser usado depois no Ranking IA.</p><div class="two"><div class="field"><label>Áudio</label><input type="file" accept="audio/*" onchange="Lamou.analyseAudio(event)"><small>${esc(d.audioName||'Nenhum arquivo carregado.')}</small></div><div class="field"><label>Duração</label><select onchange="Lamou.setHookDuration(this.value)">${[15,20,30].map(v=>`<option value="${v}" ${d.hookDuration===v?'selected':''}>${v}s</option>`).join('')}</select></div></div><div class="hook-list">${renderHooks(d)}</div><div class="two" style="margin-top:12px"><div class="field"><label>Início manual (s)</label><input id="manualStart" type="number" min="0" step=".5"></div><div class="field"><label>&nbsp;</label><button class="ghost-button" onclick="Lamou.manualHook()">Usar trecho manual</button></div></div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="primary-button" onclick="Lamou.next(4)">Criar descrição →</button></div></section>`}
function renderHooks(d){if(!d.hooks?.length)return '<div class="empty">Envie o áudio ou marque manualmente.</div>';return d.hooks.map((h,i)=>`<button class="hook-item ${d.hook?.start===h.start&&!d.hook?.manual?'on':''}" onclick="Lamou.pickHook(${i})"><div><b>${['Hook principal','Hook alternativo','Hook de apoio'][i]}</b><small>${time(h.start)}–${time(h.end)} · força ${Math.round(h.score*100)}%</small></div><span>Usar</span></button>`).join('')}
function time(s){s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function setHookDuration(v){state.draft.hookDuration=Number(v)||20;save()}
async function fingerprintFile(file){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw new Error('audio');const ctx=new Ctx(),buf=await ctx.decodeAudioData(await file.arrayBuffer()),chs=buf.numberOfChannels,sr=buf.sampleRate,hop=Math.max(256,Math.floor(sr*.5)),windows=[];let peak=0,sum=0,n=0,clip=0,diffSum=0,prev=0,zcr=0;const a=buf.getChannelData(0);for(let i=0;i<a.length;i+=4){const x=a[i];peak=Math.max(peak,Math.abs(x));sum+=x*x;n++;if(Math.abs(x)>.995)clip++;if((x>=0)!=(prev>=0))zcr++;diffSum+=(x-prev)*(x-prev);prev=x}for(let i=0;i<a.length;i+=hop){let s=0,c=0;for(let j=i;j<Math.min(a.length,i+hop);j+=8){s+=a[j]*a[j];c++}windows.push(Math.sqrt(s/Math.max(1,c)))}const rms=Math.sqrt(sum/Math.max(1,n)),mean=windows.reduce((x,y)=>x+y,0)/Math.max(1,windows.length),sd=Math.sqrt(windows.reduce((s,x)=>s+(x-mean)**2,0)/Math.max(1,windows.length));let trans=0;for(let i=1;i<windows.length;i++)trans+=Math.max(0,windows[i]-windows[i-1]);trans/=Math.max(1,windows.length-1);const q=Math.max(1,Math.floor(windows.length/4)),qm=[0,1,2,3].map(k=>{const z=windows.slice(k*q,k===3?windows.length:(k+1)*q);return z.reduce((s,x)=>s+x,0)/Math.max(1,z.length)}),structure=(Math.max(...qm)-Math.min(...qm))/Math.max(.0001,mean),hook=Math.max(...windows,mean)/Math.max(.0001,mean);let stereo=0;if(chs>1){const b=buf.getChannelData(1);let d=0,t=0;for(let i=0;i<Math.min(a.length,b.length);i+=16){d+=(a[i]-b[i])**2;t+=a[i]**2+b[i]**2}stereo=Math.sqrt(d/Math.max(.0001,t))}await ctx.close();return {duration:buf.duration,peak,rms,crest:peak/Math.max(.0001,rms),dynamicSpread:sd/Math.max(.0001,mean),transient:trans/Math.max(.0001,mean),structure,hook,brightness:Math.sqrt(diffSum/Math.max(1,n))/Math.max(.0001,rms),stereo,clipping:clip/Math.max(1,n),zcr:zcr/Math.max(1,n)}}
function clamp(x,a=0,b=1){return Math.max(a,Math.min(b,x))}
function technicalScore(f,genre='Pop'){const quality=100*(1-clamp(f.clipping*80))*.45+100*clamp((f.peak-.65)/.3)*.55,dynamics=100*clamp(1-Math.abs(f.crest-2.8)/2.8)*.55+100*clamp(1-Math.abs(f.dynamicSpread-.35)/.5)*.45,balance=100*clamp(1-Math.abs(clamp(f.brightness/2)-.5)/.6)*.65+100*clamp(f.stereo/.8)*.35,consistency=100*clamp(1-Math.abs(f.dynamicSpread-.3)/.8),impact=100*clamp(f.transient/.7)*.5+100*clamp((f.hook-1)/1.4)*.5,structure=100*clamp(f.structure/1.2),weights=genre==='Eletrônica'?[.18,.12,.18,.14,.22,.16]:genre==='Gospel'||genre==='Sertanejo'?[.18,.22,.16,.12,.14,.18]:[.2,.18,.17,.15,.16,.14],vals=[quality,dynamics,balance,consistency,impact,structure],overall=Math.round(vals.reduce((s,v,i)=>s+v*weights[i],0));return {overall,dimensions:{Qualidade:Math.round(quality),Dinâmica:Math.round(dynamics),'Equilíbrio espectral/estéreo':Math.round(balance),Consistência:Math.round(consistency),'Impacto / hook':Math.round(impact),'Estrutura / contraste':Math.round(structure)}}}
async function analyseAudio(e){const f=e.target.files?.[0];if(!f)return;state.draft.audioName=f.name;try{const fp=await fingerprintFile(f);state.draft.fingerprint=fp;const dur=state.draft.hookDuration||20,starts=[Math.max(0,fp.duration*.18),Math.max(0,fp.duration*.45),Math.max(0,fp.duration*.68)].map((x,i)=>({start:Math.round(x*2)/2,end:Math.min(fp.duration,Math.round(x*2)/2+dur),score:[.86,.78,.72][i]}));state.draft.hooks=starts;state.draft.hook=starts[0];save();renderNew();toast('Áudio analisado e vetor técnico salvo.')}catch(_){save();toast('Não consegui analisar o áudio. Use o hook manual.')}}
function pickHook(i){const h=state.draft.hooks[i];if(h){state.draft.hook={...h,manual:false};save();renderNew()}}
function manualHook(){const s=Math.max(0,Number(document.getElementById('manualStart')?.value)||0);state.draft.hook={start:s,end:s+(state.draft.hookDuration||20),manual:true};save();renderNew()}
function fallbackDescription(d){const a=d.artist||'LAMOU',p=d.project?` no projeto ${d.project}`:'',st=d.story?` ${d.story}`:'';return `${a} apresenta “${d.title}”${p}: uma faixa ${String(d.mood||'marcante').toLowerCase()} que transforma identidade, direção humana e produção em uma mensagem direta.${st}`.slice(0,520)}
function fallbackTags(d){return ['LAMOU',d.title,d.project,d.genre,'MusicaBrasileira','NovaMusica','ArtistaIndependente'].filter(Boolean).map(x=>'#'+String(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'')).join(' ')}
async function generateDescription(){syncDraft();const d=state.draft;d.generation=(d.generation||0)+1;let text='',tags='';try{const r=await fetch('/api/ai',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'copy',context:{identity:state.profile.artistBio||LAMOU_BASE,artist:d.artist,title:d.title,project:d.project,genre:d.genre,mood:d.mood,story:d.story,format:d.creativeFormat,hook:d.hook,generation:d.generation,instruction:'Crie apresentação sucinta e poderosa. Explique LAMOU, o projeto/álbum e a faixa sem inventar fatos. Termine com hashtags relevantes.'}})});if(r.ok){const x=await r.json(),raw=String(x.text||'').trim(),lines=raw.split(/\n+/);tags=lines.filter(x=>x.includes('#')).join(' ').trim();text=lines.filter(x=>!x.includes('#')).join(' ').trim()}}catch(_){}d.description=text||fallbackDescription(d);d.hashtags=tags||fallbackTags(d);save();renderNew();toast(`Versão ${d.generation} criada.`)}
function stepAI(d){return `<section class="card wizard-card step-cyan"><div class="step-no">4 · IA</div><h2>Descrição + hashtags</h2><p class="sub">Se não gostar, gere outra versão. Tudo continua editável.</p><div class="row"><button class="primary-button" onclick="Lamou.generateDescription()">✨ ${d.generation?'Gerar outra versão':'Gerar descrição'}</button><span class="status blue">Versão ${d.generation||0}</span></div><div class="field" style="margin-top:12px"><label>Descrição — editável</label><textarea id="descriptionText">${esc(d.description)}</textarea></div><div class="field"><label>Hashtags — editáveis</label><textarea id="hashtagsText" style="min-height:80px">${esc(d.hashtags)}</textarea></div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="primary-button" onclick="Lamou.next(5)">Aprovação final →</button></div></section>`}
function channelRows(d){return compatibleChannels(d).map(c=>`<label class="channel-item ${d.channels.includes(c.id)?'on':''}"><div><b>${esc(c.name)}</b><small>${esc(c.type)} · ${esc(c.audience)}</small></div><span>${esc(c.cost)}</span><span>${esc(c.country)}</span><input type="checkbox" ${d.channels.includes(c.id)?'checked':''} onchange="Lamou.toggleChannel('${c.id}',this.checked)"></label>`).join('')||'<div class="empty">Nenhum destino ativo compatível. Revise a lista de bloqueados no Perfil.</div>'}
function toggleChannel(cid,on){const a=state.draft.channels,i=a.indexOf(cid);if(on&&i<0)a.push(cid);if(!on&&i>=0)a.splice(i,1);save()}
function stepApproval(d){const fp=d.fingerprint?technicalScore(d.fingerprint,d.genre):null;return `<section class="card wizard-card step-green"><div class="step-no">5 · APROVAÇÃO FINAL</div><h2>Confira tudo</h2><div class="review-grid"><div class="review-block"><b>Música</b>${esc(d.title)}<small>${esc(d.artist)} · ${esc(d.project||'Sem projeto informado')}</small></div><div class="review-block"><b>Modo</b>${d.mode==='campaign'?'Campanha':'Divulgação rápida'}</div><div class="review-block"><b>Criativo</b>${esc(d.creativeFormat)} · ${esc(d.mediaType)}</div><div class="review-block"><b>Hook</b>${d.hook?`${time(d.hook.start)}–${time(d.hook.end)}`:'Não definido'}</div>${fp?`<div class="review-block"><b>Índice técnico</b>${fp.overall}/100<small>Disponível depois no Ranking IA.</small></div>`:''}</div><div class="review-block" style="margin-top:10px"><b>Descrição</b>${esc(d.description)}<small>${esc(d.hashtags)}</small></div><h3 style="margin-top:16px">Destinos selecionados</h3><p class="sub">Destinos marcados como “não quer receber mais” não aparecem.</p><div class="channel-list">${channelRows(d)}</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="publish-button" onclick="Lamou.approveFinal()">✓ APROVAR E CONCLUIR</button></div></section>`}
function approveFinal(){syncDraft();const d=state.draft;if(!d.description)return toast('Gere ou escreva a descrição antes de aprovar.');state.history.unshift({id:id(),status:'approved',approvedAt:new Date().toISOString(),mode:d.mode,url:d.url,title:d.title,artist:d.artist,project:d.project,genre:d.genre,creativeFormat:d.creativeFormat,hook:d.hook,description:d.description,hashtags:d.hashtags,channels:[...d.channels],submitted:[],optOuts:[],fingerprint:d.fingerprint||null});state.draft=null;cleanup();save();toast('Material aprovado.');renderHistory()}
function renderHistory(){markNav('history');root().innerHTML=`${pageHead('HISTÓRICO','Materiais aprovados','Abra um item para enviar, registrar envio ou bloquear quem pediu para não receber mais.')}<section class="card"><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item"><div><b>${esc(h.title)}</b><small>${fmtDate(h.approvedAt)} · ${h.mode==='campaign'?'Campanha':'Rápida'}</small></div><span class="status green">${h.status==='sent'?'Com envios':'Aprovado'}</span><span>${(h.submitted||[]).length} envio(s)</span><div class="history-actions"><button onclick="Lamou.viewHistory('${h.id}')">Abrir</button><button onclick="Lamou.removeHistory('${h.id}')">Remover</button></div></div>`).join(''):'<div class="empty">Nenhum material aprovado.</div>'}</div></section>`}
function emailHref(c,h){const subject=`Apresentação musical — ${h.title} — ${h.artist}`,body=`${h.description}\n\n${h.hashtags}\n\nSpotify: ${h.url}`;return `mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function viewHistory(hid){const h=state.history.find(x=>x.id===hid);if(!h)return;const blocked=suppressedIds();modal(`<div class="modal-head"><div><div class="eyebrow">DIVULGAÇÃO</div><h2>${esc(h.title)}</h2><p class="sub">${esc(h.project||h.genre)}</p></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="notice"><b>${esc(h.description)}</b><br>${esc(h.hashtags)}</div><h3 style="margin-top:16px">Destinos</h3><div class="channel-list">${(h.channels||[]).map(cid=>{const c=channel(cid);if(!c)return'';const sent=(h.submitted||[]).some(x=>x.channelId===cid),opt=blocked.has(cid);return `<div class="outreach-row"><div><b>${esc(c.name)}</b><small>${esc(c.audience)} · ${esc(c.method)}</small>${c.email?`<small>${esc(c.email)}</small>`:''}</div><div class="outreach-actions">${c.email?`<a class="ghost-button" href="${emailHref(c,h)}">E-mail</a>`:`<a class="ghost-button" href="${esc(c.url)}" target="_blank" rel="noopener">Abrir</a>`}<button class="${sent?'ghost-button':'primary-button'}" ${sent?'disabled':''} onclick="Lamou.markSent('${hid}','${cid}')">${sent?'✓ Enviado':'Marcar enviado'}</button><button class="optout-button" ${opt?'disabled':''} onclick="Lamou.suppressChannel('${cid}','${hid}')">${opt?'Removido':'Não quer receber mais'}</button></div></div>`}).join('')}</div>`)}
function markSent(hid,cid){const h=state.history.find(x=>x.id===hid);if(!h)return;if(!(h.submitted||[]).some(x=>x.channelId===cid))h.submitted.push({channelId:cid,date:new Date().toISOString()});h.status='sent';save();viewHistory(hid);toast('Envio registrado.')}
function suppressChannel(cid,hid){const c=channel(cid);if(!c)return;if(!confirm(`${c.name}: registrar que não deseja receber mais material e remover das próximas listas?`))return;if(!state.suppressed.some(x=>x.channelId===cid))state.suppressed.push({channelId:cid,name:c.name,date:new Date().toISOString(),reason:'recipient_opt_out'});const h=state.history.find(x=>x.id===hid);if(h&&!h.optOuts?.some(x=>x.channelId===cid)){h.optOuts=h.optOuts||[];h.optOuts.push({channelId:cid,date:new Date().toISOString()})}if(state.draft)state.draft.channels=state.draft.channels.filter(x=>x!==cid);save();viewHistory(hid);toast('Destino removido das próximas divulgações.')}
function unsuppress(cid){state.suppressed=state.suppressed.filter(x=>x.channelId!==cid);save();openUser();toast('Destino reativado.')}
function removeHistory(hid){if(!confirm('Remover do Histórico?'))return;state.history=state.history.filter(x=>x.id!==hid);save();renderHistory()}
function renderResults(){markNav('results');const s=stats();root().innerHTML=`${pageHead('RESULTADOS','O que realmente aconteceu','Sem popularidade inventada: envios confirmados, destinos e opt-outs.')}${appDashboard()}<section class="card" style="margin-top:14px"><div class="stats"><div class="stat"><b>${s.quick}</b><small>Rápidas</small></div><div class="stat"><b>${s.campaigns}</b><small>Campanhas</small></div><div class="stat"><b>${s.destinations}</b><small>Destinos enviados</small></div><div class="stat"><b>${s.optouts}</b><small>Não enviar mais</small></div></div></section>${optOutSection()}${rankingBox()}`}
function optOutSection(){return `<section class="card" style="margin-top:14px"><h2>Não enviar mais</h2><p class="sub">Pedidos registrados são removidos automaticamente de futuras divulgações.</p><div class="history-list">${state.suppressed.length?state.suppressed.map(o=>`<div class="history-item"><div><b>${esc(o.name||channel(o.channelId)?.name||o.channelId)}</b><small>${fmtDate(o.date)}</small></div><span class="status red">Bloqueado</span><span>Opt-out</span><div></div></div>`).join(''):'<div class="empty">Nenhum pedido de opt-out registrado.</div>'}</div></section>`}
function rankingBox(){const options=GENRES.map(g=>`<option>${g}</option>`).join('');return `<section class="card ranking-card" style="margin-top:14px"><div class="row between"><div><div class="eyebrow">RANKING TÉCNICO IA</div><h2>Global e por estilo — sem plays, views ou crítica</h2><p class="sub">O link identifica a faixa. A avaliação usa somente o vetor técnico do áudio carregado no LAMOU.</p></div><span class="status blue">Modelo técnico v1</span></div><div class="two"><div class="field"><label>Link Spotify da música</label><div class="row"><input id="rankUrl" style="flex:1" placeholder="https://open.spotify.com/track/..."><button class="ghost-button" onclick="Lamou.identifyRank()">Identificar</button></div></div><div class="field"><label>Estilo</label><select id="rankGenre">${options}</select></div></div><div id="rankMeta" class="mini"></div><div class="field"><label>Áudio para análise técnica (se o vetor ainda não estiver salvo)</label><input type="file" accept="audio/*" onchange="Lamou.rankAudio(event)"></div><button class="primary-button" onclick="Lamou.runRanking()">◎ Criar ranking técnico</button><div id="rankResult" style="margin-top:14px"></div><div class="notice warn" style="margin-top:12px">A posição global só é publicada com amostra mínima de referência: 100 músicas com IA no conjunto global e 30 no estilo. Antes disso o app mostra a nota técnica, mas não inventa colocação mundial.</div></section>`}
async function identifyRank(){const u=document.getElementById('rankUrl')?.value.trim();if(!u)return toast('Cole o link do Spotify.');try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(u));if(!r.ok)throw 0;const x=await r.json();rankingMeta={url:u,title:x.title||'Faixa',artist:(x.author_name||'').replace(/Spotify/gi,'').trim(),cover:x.thumbnail_url||''};const hist=state.history.find(h=>h.url===u&&h.fingerprint);if(hist)rankingFingerprint=hist.fingerprint;document.getElementById('rankMeta').innerHTML=`<b>${esc(rankingMeta.title)}</b> · ${esc(rankingMeta.artist)}${hist?' · vetor técnico encontrado no Histórico':''}`;toast('Faixa identificada.')}catch(_){toast('Não consegui identificar este link.')}}
async function rankAudio(e){const f=e.target.files?.[0];if(!f)return;try{rankingFingerprint=await fingerprintFile(f);toast('Áudio analisado para o Ranking.')}catch(_){toast('Não consegui analisar este áudio.')}}
async function runRanking(){const u=document.getElementById('rankUrl')?.value.trim(),g=document.getElementById('rankGenre')?.value||'Pop';if(!rankingMeta||rankingMeta.url!==u)await identifyRank();if(!rankingFingerprint){const hist=state.history.find(h=>h.url===u&&h.fingerprint);if(hist)rankingFingerprint=hist.fingerprint}if(!rankingFingerprint)return toast('Para ranking técnico, envie o áudio uma vez ou use uma faixa já analisada em Nova música.');const sc=technicalScore(rankingFingerprint,g);let pos=null;try{const r=await fetch('/api/ranking/position',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({genre:g,score:sc.overall})});if(r.ok)pos=await r.json()}catch(_){}const globalText=pos?.global?.eligible?`#${pos.global.rank} de ${pos.global.total}`:`Amostra ${pos?.global?.total||0}/100`,styleText=pos?.style?.eligible?`#${pos.style.rank} de ${pos.style.total}`:`Amostra ${pos?.style?.total||0}/30`,dims=Object.entries(sc.dimensions).map(([k,v])=>`<div class="rank-dim"><span>${esc(k)}</span><div><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');document.getElementById('rankResult').innerHTML=`<div class="rank-hero"><div><small>ÍNDICE TÉCNICO IA</small><b>${sc.overall}</b><span>/100</span></div><div><small>GLOBAL</small><strong>${globalText}</strong></div><div><small>${esc(g.toUpperCase())}</small><strong>${styleText}</strong></div></div><div class="rank-dims">${dims}</div><label class="consent-row"><input id="aiReferenceConsent" type="checkbox"> Esta música usa IA e autorizo adicionar somente o vetor técnico anônimo à base de referência.</label><button class="ghost-button" onclick="Lamou.contributeRanking(${sc.overall},'${esc(g)}')">Adicionar à base mundial do LAMOU</button>`;state.rankings.unshift({id:id(),date:new Date().toISOString(),url:u,title:rankingMeta?.title||'Faixa',artist:rankingMeta?.artist||'',genre:g,score:sc.overall,dimensions:sc.dimensions,global:pos?.global||null,style:pos?.style||null});save()}
async function contributeRanking(score,genre){if(!document.getElementById('aiReferenceConsent')?.checked)return toast('Marque a autorização primeiro.');const u=document.getElementById('rankUrl')?.value.trim()||rankingMeta?.url||id();try{const r=await fetch('/api/ranking/contribute',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({genre,score,trackKey:u,aiGenerated:true,fingerprint:rankingFingerprint})});if(!r.ok)throw 0;toast('Vetor técnico anônimo adicionado à referência.')}catch(_){toast('Não foi possível adicionar à base agora.')}}
function openUser(){const rel=state.profile.releases||[];modal(`<div class="modal-head"><div><div class="eyebrow">PERFIL LAMOU</div><h2>Identidade + Spotify</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="profile-spotify-box"><div class="spotify-photo">${state.profile.artistImage?`<img src="${esc(state.profile.artistImage)}">`:'🎵'}</div><div><b>${esc(state.profile.artistName)}</b><small>${rel.length} lançamento(s) carregado(s)</small></div></div><div class="two"><div class="field"><label>Nome exibido</label><input id="profileName" value="${esc(state.profile.displayName)}"></div><div class="field"><label>Nome artístico</label><input id="profileArtist" value="${esc(state.profile.artistName)}"></div></div><div class="field"><label>Link do perfil de artista no Spotify (recomendado para evitar homônimos)</label><input id="profileArtistUrl" value="${esc(state.profile.artistUrl||'')}" placeholder="https://open.spotify.com/artist/..."></div><div class="field"><label>Descrição-base da IA</label><textarea id="profileBio">${esc(state.profile.artistBio||LAMOU_BASE)}</textarea></div><div class="row"><button class="primary-button" onclick="Lamou.saveUser()">Salvar e atualizar Spotify</button><button class="ghost-button" onclick="Lamou.connect('spotify')">Conectar Spotify</button></div><h3 style="margin-top:18px">Álbuns / singles</h3><div class="album-chips">${rel.map(r=>`<span class="album-chip">${r.image?`<img src="${esc(r.image)}">`:''}<span><b>${esc(r.name)}</b><small>${esc(r.type||'')}</small></span></span>`).join('')||'<span class="mini">Nada carregado ainda.</span>'}</div><h3 style="margin-top:18px">Não enviar mais</h3><div class="history-list">${state.suppressed.length?state.suppressed.map(o=>`<div class="history-item"><div><b>${esc(o.name||channel(o.channelId)?.name||o.channelId)}</b><small>${fmtDate(o.date)}</small></div><span class="status red">Bloqueado</span><span></span><button class="ghost-button" onclick="Lamou.unsuppress('${o.channelId}')">Reativar</button></div>`).join(''):'<div class="mini">Nenhum destino bloqueado.</div>'}</div>`)}
async function saveUser(){state.profile.displayName=document.getElementById('profileName')?.value.trim()||'LAMOU';state.profile.artistName=document.getElementById('profileArtist')?.value.trim()||'LAMOU';state.profile.artistUrl=document.getElementById('profileArtistUrl')?.value.trim()||'';state.profile.artistBio=document.getElementById('profileBio')?.value.trim()||LAMOU_BASE;save();try{await fetch('/api/profile',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:state.profile.displayName,artistName:state.profile.artistName,artistUrl:state.profile.artistUrl})})}catch(_){}await refreshProfile();document.getElementById('headerUser').textContent=state.profile.displayName;closeModal();home();toast('Perfil atualizado.')}
function menu(){modal(`<div class="modal-head"><div><div class="eyebrow">LAMOU</div><h2>Menu</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="mode-grid"><button class="choice-card" onclick="Lamou.closeModal();Lamou.openUser()"><span class="feature-icon">♫</span><strong>Perfil + Spotify</strong><small>Foto, discografia e identidade.</small></button><button class="choice-card" onclick="Lamou.closeModal();Lamou.runTests()"><span class="feature-icon">✓</span><strong>Diagnóstico</strong><small>Checar funções principais.</small></button></div>`)}
function runTests(){const t=[['Spotify único',Object.keys(state.connections).length===1],['Opt-out',typeof suppressChannel==='function'],['Ranking técnico',typeof technicalScore==='function'],['Áudio local',!!(window.AudioContext||window.webkitAudioContext)],['Aprovação final',typeof approveFinal==='function']];modal(`<div class="modal-head"><h2>Diagnóstico</h2><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="test-list">${t.map(([n,o])=>`<div class="test-item"><b>${n}</b><span class="status ${o?'green':'red'}">${o?'OK':'Falhou'}</span></div>`).join('')}</div>`)}
function connect(p){if(p!=='spotify')return toast('Somente Spotify é conectado.');if(window.LamouIntegration?.connect)return window.LamouIntegration.connect('spotify');toast('Integração Spotify carregando.')}
window.Lamou={go,startMode,discardDraft,back,next,nextSong,nextCreative,loadTrack,setFormat,chooseCreative,loadMedia,setHookDuration,analyseAudio,pickHook,manualHook,generateDescription,toggleChannel,approveFinal,viewHistory,markSent,suppressChannel,unsuppress,removeHistory,identifyRank,rankAudio,runRanking,contributeRanking,openUser,saveUser,menu,runTests,connect,closeModal};
document.addEventListener('click',e=>{if(e.target.closest('#lamouMenuBtn'))menu()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
boot();
})();