(() => {
'use strict';

const STORE='lamou_v10_db';
const LAMOU_BASE='LAMOU é um projeto musical brasileiro de criação humana e direção artística, com IA usada como ferramenta de produção e expansão criativa.';
const GENRES=['Pop','Rock','Sertanejo','Forró','Gospel','Funk','Pagode / Samba','Axé','Eletrônica','Hip Hop / Rap','R&B / Soul','Latino','MPB','Outros'];
const MOODS=['Emocional','Dançante','Romântico','Espiritual','Intenso','Sexy','Chill','Debochado','Inspirador','Sombrio'];
const FORMATS=[['1:1','Capa'],['4:5','Feed vertical'],['9:16','Stories / vertical'],['16:9','Horizontal']];

const CHANNELS=[
{id:'spotify-artists',name:'Spotify for Artists',type:'Editorial',audience:'Editores oficiais do Spotify',country:'Global',lang:'PT/EN',cost:'Grátis',method:'Formulário oficial',url:'https://artists.spotify.com/',email:'',genres:['*'],ai:'Revisar',note:'Pitch editorial para lançamento elegível; ideal antes do lançamento.',verified:'2026-08-15'},
{id:'groover',name:'Groover',type:'Rede profissional',audience:'Gravadoras, A&R, rádios, imprensa, sync, managers, DJs e bookers',country:'Global',lang:'PT/EN',cost:'Pago por contato',method:'Plataforma',url:'https://groover.co/pt/',email:'',genres:['*'],ai:'Revisar por profissional',note:'Escolha profissionais por gênero, país e objetivo.',verified:'2026-08-15'},
{id:'dailyplaylists',name:'DailyPlaylists',type:'Playlists',audience:'Curadores de playlists',country:'Global',lang:'PT/EN',cost:'Grátis + planos',method:'Plataforma',url:'https://dailyplaylists.com/pt/',email:'info@dailyplaylists.com',genres:['*'],ai:'Revisar por curador',note:'Mais de 18 mil playlists; a faixa precisa estar lançada no Spotify.',verified:'2026-08-15'},
{id:'soundplate',name:'Soundplate',type:'Playlists',audience:'Curadores independentes',country:'Global',lang:'EN',cost:'Grátis',method:'Plataforma',url:'https://play.soundplate.com/playlists/latest',email:'',genres:['*'],ai:'Categoria AI Generated disponível',note:'Centenas de curadores; envie apenas para playlists compatíveis.',verified:'2026-08-15'},
{id:'musosoup',name:'MusoSoup',type:'Imprensa / curadoria',audience:'Blogs, imprensa, playlists e rádios',country:'Global',lang:'EN',cost:'Envio grátis; campanha pode ser paga',method:'Plataforma',url:'https://musosoup.com/artists-how-it-works',email:'',genres:['*'],ai:'Revisar',note:'Curadores interessados fazem ofertas de cobertura; você decide quais aceitar.',verified:'2026-08-15'},
{id:'reverbnation',name:'ReverbNation Opportunities',type:'Indústria',audience:'A&R, selos, sync, festivais, rádio, imprensa e marcas',country:'Global',lang:'EN',cost:'Grátis + planos / oportunidades',method:'Plataforma',url:'https://www.reverbnation.com/band-promotion/opportunities',email:'',genres:['*'],ai:'Revisar por oportunidade',note:'Oportunidades de indústria; aplicar apenas quando houver fit.',verified:'2026-08-15'},
{id:'bananas',name:'Bananas Music',type:'Curadoria brasileira',audience:'Curadores de playlists e music branding',country:'Brasil / Global',lang:'PT',cost:'Via Groover',method:'Groover',url:'https://bananas.mus.br/envie-sua-musica/',email:'',genres:['*'],ai:'Revisar',note:'Recebe música somente via Groover; pode entrar em playlists e projetos de música ambiente.',verified:'2026-08-15'},
{id:'wegoout',name:'We Go Out',type:'Imprensa / lançamento',audience:'Público e editorial de música eletrônica',country:'Brasil',lang:'PT',cost:'Grátis',method:'Formulário',url:'https://wegoout.com.br/',email:'',genres:['Eletrônica'],ai:'Revisar',note:'Formulário “Envie seu lançamento”; foco editorial em música eletrônica e cultura de festas.',verified:'2026-08-15'},
{id:'sun7',name:'Sun7 Label',type:'Gravadora / selo',audience:'Label, administração autoral e business musical',country:'Brasil',lang:'PT',cost:'Grátis para enviar demo',method:'Formulário / e-mail público',url:'https://www.sun7label.com/contato',email:'contato@sun7label.com',genres:['*'],ai:'Revisar',note:'Aceita links; não enviar MP3 físico/anexo como substituto do link.',verified:'2026-08-15'},
{id:'progressive',name:'Progressive Generation',type:'Gravadora / A&R',audience:'A&R de música eletrônica',country:'Brasil',lang:'PT',cost:'Grátis',method:'E-mail público',url:'https://progressivegeneration.com.br/label/demo/',email:'contato@progressivegeneration.com.br',genres:['Eletrônica'],ai:'Revisar',note:'Pede link privado do SoundCloud com download habilitado + artista, faixa, gênero e contexto.',verified:'2026-08-15'},
{id:'paulinas',name:'Paulinas-COMEP',type:'Gravadora / editora',audience:'Produção e repertório de música cristã/católica',country:'Brasil',lang:'PT',cost:'Grátis',method:'E-mail público',url:'https://universo.paulinas.com.br/conteudo/envie-seu-projeto-paulinas-comep/61',email:'comep@paulinas.com.br',genres:['Gospel'],ai:'Revisar',note:'Aceita projeto musical ou composições; pede apresentação, objetivo, público e dados autorais.',verified:'2026-08-15'},
{id:'belem',name:'Gravadora Belém',type:'Gravadora',audience:'Mercado gospel pentecostal',country:'Brasil',lang:'PT',cost:'Grátis / revisar condições',method:'Página “Envie sua música” / e-mail',url:'https://gravadorabelem.com.br/',email:'contato@gravadorabelem.com.br',genres:['Gospel'],ai:'Revisar',note:'Canal voltado ao segmento evangélico/pentecostal.',verified:'2026-08-15'},
{id:'dnbb',name:'DNBB Music Group',type:'Gravadora / A&R',audience:'A&R de Drum & Bass e Bass Music',country:'Brasil / Global',lang:'PT/EN',cost:'Grátis para demo',method:'Formulário / link privado',url:'https://dnbbrecords.com/',email:'',genres:['Eletrônica'],ai:'Revisar',note:'Pede WAV/MP3 de alta qualidade, BPM/tom, bio curta e link privado.',verified:'2026-08-15'},
{id:'midsummer',name:'Midsummer Madness',type:'Selo independente',audience:'Selo / catálogo independente',country:'Brasil / Reino Unido',lang:'PT',cost:'Grátis',method:'Contato pelo site / e-mail',url:'https://mmrecords.com.br/contato/',email:'',genres:['Rock','Pop','Eletrônica','Outros'],ai:'Revisar',note:'Enviar link das músicas, contatos, texto sobre o artista e foto/vídeo; não enviar MP3 por e-mail.',verified:'2026-08-15'},
{id:'boxradio',name:'Box Radio',type:'Rádio',audience:'Programadores de rádios por gênero',country:'Global',lang:'EN',cost:'Apoio/doação priorizado',method:'E-mail público',url:'https://boxradio.net/pt/submitmusic',email:'hello@boxradio.net',genres:['*'],ai:'Revisar',note:'Pede link de download em nuvem, áudio de alta qualidade e fit com uma das rádios.',verified:'2026-08-15'},
{id:'yourjazz',name:'Your Jazz Radio',type:'Rádio',audience:'Programação de jazz',country:'Global',lang:'EN',cost:'Revisar',method:'Formulário / e-mail público',url:'https://yourjazzradio.com/submit-music/',email:'artist@yourjazzradio.com',genres:['Outros'],ai:'Revisar',note:'Somente jazz; pede metadados, bio/one-sheet e contatos.',verified:'2026-08-15'},
{id:'undaground',name:'Tales From The Undaground Radio',type:'Rádio / promoção',audience:'DJs, rádio e público underground',country:'Global',lang:'EN',cost:'Opção inicial grátis + pagos',method:'Formulário',url:'https://www.djundagroundlive.com/',email:'',genres:['Hip Hop / Rap','R&B / Soul','Eletrônica','Outros'],ai:'Revisar',note:'Hip-hop, R&B, reggae, house e open format; considerar rádio/DJ pool.',verified:'2026-08-15'}
];

let mediaObjectUrl='';
let audioObjectUrl='';
let audioElement=null;

function defaults(){return {accounts:{},current:null,profile:{displayName:'LAMOU',email:'',artistUrl:'',artistName:'LAMOU',artistImage:'',artistStats:null,artistBio:LAMOU_BASE},connections:{spotify:'red'},history:[],draft:null,radar:[],webChannels:CHANNELS};}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function id(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function toast(msg){const e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3200)}
function fmtDate(x){try{return new Date(x).toLocaleString('pt-BR')}catch(_){return x||'—'}}
function root(){return document.getElementById('appRoot')}
function currentAccount(){return state.current?state.accounts?.[state.current]:null}
function pageHead(kicker,title,sub){return `<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div></div>`}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)Lamou.closeModal()"><section class="modal">${html}</section></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function showApp(){document.getElementById('loginShell')?.classList.add('hidden');document.getElementById('appShell')?.classList.remove('hidden');document.getElementById('bottomNav')?.classList.remove('hidden')}
function markNav(view){document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view===view))}
function save(){if(state.current&&state.accounts?.[state.current])state.accounts[state.current].workspace={profile:state.profile,connections:state.connections,history:state.history,draft:state.draft,radar:state.radar};localStorage.setItem(STORE,JSON.stringify(state))}
function freshDraft(mode,artistName='LAMOU'){const d={id:id(),mode,step:1,status:'draft',createdAt:new Date().toISOString(),url:'',title:'',artist:artistName||'LAMOU',project:'',genre:'Pop',mood:'Emocional',story:'',cover:'',creativeSource:'spotify',creativeFormat:'1:1',mediaType:'image',mediaName:'',hookDuration:20,hooks:[],hook:null,audioName:'',description:'',hashtags:'',generation:0,channels:[],submitted:[]};applyRecommendedChannels(d);return d}
function normalizeDraft(input){if(!input||typeof input!=='object')return null;const base=freshDraft(input.mode==='campaign'?'campaign':'quick',input.artist||'LAMOU');const d={...base,...input};d.mode=d.mode==='campaign'?'campaign':'quick';d.step=Math.max(1,Math.min(5,Number(d.step)||1));d.creativeFormat=FORMATS.some(([f])=>f===d.creativeFormat)?d.creativeFormat:'1:1';d.creativeSource=['spotify','upload-image','upload-video'].includes(d.creativeSource)?d.creativeSource:'spotify';d.mediaType=d.mediaType==='video'?'video':'image';d.hookDuration=[15,20,30].includes(Number(d.hookDuration))?Number(d.hookDuration):20;d.hooks=Array.isArray(d.hooks)?d.hooks:[];d.channels=Array.isArray(d.channels)?d.channels.filter(cid=>CHANNELS.some(c=>c.id===cid)):[];d.submitted=Array.isArray(d.submitted)?d.submitted:[];d.generation=Number(d.generation)||0;if(!d.channels.length)applyRecommendedChannels(d);return d}
function db(){try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}')||{},base=defaults();return {...base,...raw,profile:{...base.profile,...(raw.profile||{})},connections:{spotify:raw.connections?.spotify||'red'},history:Array.isArray(raw.history)?raw.history.filter(x=>['approved','sent'].includes(String(x.status||''))):[],draft:normalizeDraft(raw.draft),radar:Array.isArray(raw.radar)?raw.radar:[],webChannels:CHANNELS}}catch(_){return defaults()}}
let state=db();

function compatibleChannels(d){const genre=d?.genre||'Pop';return CHANNELS.filter(c=>c.genres.includes('*')||c.genres.includes(genre))}
function scoreChannel(c,d){let s=0;if(c.genres.includes(d.genre))s+=5;if(c.genres.includes('*'))s+=2;if(c.cost==='Grátis'||c.cost.startsWith('Grátis'))s+=2;if(c.country.includes('Brasil'))s+=2;if(c.type.includes('Editorial')||c.type.includes('Playlists')||c.type.includes('Rede profissional'))s+=1;return s}
function applyRecommendedChannels(d){const list=compatibleChannels(d).sort((a,b)=>scoreChannel(b,d)-scoreChannel(a,d));d.channels=(d.mode==='campaign'?list:list.slice(0,Math.min(7,list.length))).map(c=>c.id)}
function channelById(cid){return CHANNELS.find(c=>c.id===cid)}
function audienceCounts(channels){const groups={};for(const c of channels){const key=c.type||'Outros';groups[key]=(groups[key]||0)+1}return groups}

async function ensureSession(){let device=localStorage.getItem('lamou_device_id');if(!device){device=(crypto.randomUUID?crypto.randomUUID():id())+'-'+Date.now();localStorage.setItem('lamou_device_id',device)}try{await fetch('/api/session/device',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:device})})}catch(_){}}
async function boot(){showApp();document.getElementById('headerUser').textContent=state.profile.displayName||currentAccount()?.name||'LAMOU';await ensureSession();await refreshRemoteProfile();go('home')}

function appStats(){const approved=state.history.filter(x=>['approved','sent'].includes(x.status));const submitted=approved.flatMap(x=>x.submitted||[]);return {approved:approved.length,campaigns:approved.filter(x=>x.mode==='campaign').length,quick:approved.filter(x=>x.mode==='quick').length,sent:submitted.length,destinations:new Set(submitted.map(x=>x.channelId)).size}}
function spotifyDashboard(){const a=state.profile.artistStats||{};return `<section class="card spotify-dashboard"><div class="row between"><div><div class="eyebrow">DASHBOARD · SPOTIFY</div><h2>${esc(state.profile.artistName||'LAMOU')}</h2><p class="sub">Dados disponíveis do artista e status da única conexão do app.</p></div><span class="status ${state.connections.spotify==='green'?'green':'red'}">${state.connections.spotify==='green'?'● Conectado':'● Desconectado'}</span></div><div class="metric-strip"><div><b>${a.albums??'—'}</b><small>Álbuns</small></div><div><b>${a.tracks??'—'}</b><small>Músicas</small></div><div><b>${a.topTrack?esc(a.topTrack):'—'}</b><small>Destaque disponível</small></div><div><b>${a.streams??'—'}</b><small>Streams verificados</small></div></div><div class="row" style="margin-top:14px"><button class="primary-button" onclick="Lamou.connect('spotify')">${state.connections.spotify==='green'?'↻ Atualizar Spotify':'Conectar Spotify'}</button><button class="ghost-button" onclick="Lamou.openUser()">Perfil LAMOU</button></div></section>`}
function appDashboard(){const s=appStats();return `<section class="card dashboard-card"><div class="eyebrow">DASHBOARD · LAMOU</div><h2>Desempenho do app</h2><p class="sub">Só entra aqui o que passou pela aprovação final e os envios que você confirmou.</p><div class="stats"><div class="stat"><b>${s.approved}</b><small>Aprovados</small></div><div class="stat"><b>${s.quick}</b><small>Divulgações rápidas</small></div><div class="stat"><b>${s.campaigns}</b><small>Campanhas</small></div><div class="stat"><b>${s.sent}</b><small>Envios confirmados</small></div></div></section>`}
function home(){markNav('');root().innerHTML=`${pageHead('LAMOU','Seu painel musical','Spotify primeiro. Depois, o resultado do trabalho feito dentro do LAMOU.')}${spotifyDashboard()}<div style="height:14px"></div>${appDashboard()}<section class="card" style="margin-top:14px"><h2>O que você quer fazer?</h2><p class="sub">Nova música sempre começa escolhendo Divulgação rápida ou Criar campanha.</p><div class="mode-grid"><button class="choice-card" onclick="Lamou.go('new')"><span class="choice-icon">＋</span><strong>Nova música</strong><small>Rápida ou campanha → criativo → hook → IA → aprovação final.</small></button><button class="choice-card" onclick="Lamou.go('history')"><span class="choice-icon">◷</span><strong>Histórico</strong><small>Somente materiais aprovados.</small></button><button class="choice-card" onclick="Lamou.go('results')"><span class="choice-icon">◎</span><strong>Resultados</strong><small>Envios confirmados e destinos alcançados.</small></button></div></section>`}

function go(view){if(view==='new'){state.draft=null;cleanupMedia();save();markNav('new');renderNew();return}markNav(view);if(view==='home')home();else if(view==='history')renderHistory();else if(view==='results'||view==='radar')renderResults()}
function startMode(mode){state.draft=freshDraft(mode,state.profile.artistName||'LAMOU');save();renderNew()}
function discardDraft(){state.draft=null;cleanupMedia();save();renderNew()}
function cleanupMedia(){if(mediaObjectUrl){URL.revokeObjectURL(mediaObjectUrl);mediaObjectUrl=''}if(audioObjectUrl){URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=''}audioElement=null}
function syncDraft(){const d=state.draft;if(!d)return;const map=[['songUrl','url'],['songTitle','title'],['songArtist','artist'],['songProject','project'],['songGenre','genre'],['songMood','mood'],['songStory','story'],['descriptionText','description'],['hashtagsText','hashtags']];for(const [eid,key] of map){const e=document.getElementById(eid);if(e)d[key]=String(e.value||'').trim()}save()}
function back(){syncDraft();if(!state.draft)return;state.draft.step=Math.max(1,state.draft.step-1);save();renderNew()}
function next(step){syncDraft();if(!state.draft)return;state.draft=normalizeDraft(state.draft);state.draft.step=step;save();renderNew()}
function nextFromSong(){syncDraft();const d=state.draft;if(!d.title.trim())return toast('Informe o nome da música.');if(!d.artist.trim())d.artist='LAMOU';applyRecommendedChannels(d);d.step=2;save();renderNew()}
function nextFromCreative(){const d=normalizeDraft(state.draft);if(!d)return;if(d.creativeSource==='spotify'&&!d.cover){d.creativeSource='upload-image';state.draft=d;save();renderNew();return toast('A capa do Spotify não foi carregada. Escolha uma imagem ou vídeo para continuar.')}if((d.creativeSource==='upload-image'||d.creativeSource==='upload-video')&&!d.mediaName){state.draft=d;save();return toast('Selecione o arquivo de imagem ou vídeo.')}d.step=3;state.draft=d;save();renderNew()}
function actions(nextStep,label='Continuar',handler='next'){const call=handler==='creative'?'Lamou.nextFromCreative()':`Lamou.next(${nextStep})`;return `<div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><div class="row"><button class="ghost-button" onclick="Lamou.discardDraft()">Cancelar</button><button class="primary-button" onclick="${call}">${esc(label)} →</button></div></div>`}

function renderNew(){markNav('new');if(!state.draft){root().innerHTML=`${pageHead('NOVA MÚSICA','Como você quer divulgar?','Escolha primeiro o alcance. Depois você segue pelo mesmo fluxo criativo.')}`+`<div class="mode-grid" style="grid-template-columns:repeat(2,1fr)"><button class="choice-card" onclick="Lamou.startMode('quick')"><span class="choice-icon">⚡</span><strong>Divulgação rápida</strong><small>Destinos essenciais e compatíveis com o estilo.</small></button><button class="choice-card" onclick="Lamou.startMode('campaign')"><span class="choice-icon">🌍</span><strong>Criar campanha</strong><small>Todos os destinos profissionais compatíveis encontrados pelo LAMOU.</small></button></div>`;return}state.draft=normalizeDraft(state.draft);const d=state.draft,label=d.mode==='campaign'?'Campanha':'Divulgação rápida';root().innerHTML=`${pageHead(label,d.title||'Nova música','Música → Criativo → Hook → IA → Aprovação final.')}${progress(d.step)}${d.step===1?stepSong(d):d.step===2?stepCreative(d):d.step===3?stepHook(d):d.step===4?stepAI(d):stepApproval(d)}`;restoreMediaPreview()}
function progress(step){const names=['Música','Criativo','Hook','IA','Aprovação'];return `<div class="flow-progress">${names.map((n,i)=>`<div class="flow-step ${step===i+1?'on':step>i+1?'done':''}"><b>${i+1}</b><span>${n}</span></div>`).join('')}</div>`}

function stepSong(d){return `<section class="card wizard-card step-blue"><div class="step-no">1 · MÚSICA</div><h2>Qual faixa vamos trabalhar?</h2><p class="sub">Use o Spotify ou preencha manualmente. O CD/álbum/projeto entra no contexto da IA e nunca é inventado.</p><div class="field"><label>Link Spotify</label><div class="row"><input id="songUrl" style="flex:1" value="${esc(d.url)}" placeholder="https://open.spotify.com/track/..."><button class="primary-button" onclick="Lamou.loadTrack()">Buscar</button></div></div>${d.cover?`<div class="track-preview"><img src="${esc(d.cover)}" alt=""><div><b>${esc(d.title||'Faixa')}</b><small>${esc(d.artist)}</small></div></div>`:''}<div class="two" style="margin-top:12px"><div class="field"><label>Música</label><input id="songTitle" value="${esc(d.title)}" placeholder="Nome da faixa"></div><div class="field"><label>Artista</label><input id="songArtist" value="${esc(d.artist)}"></div><div class="field"><label>CD / álbum / projeto de origem</label><input id="songProject" value="${esc(d.project)}" placeholder="Ex.: Vende-se... / single / EP"></div><div class="field"><label>Gênero</label><select id="songGenre">${GENRES.map(g=>`<option ${g===d.genre?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div class="field"><label>Clima</label><select id="songMood">${MOODS.map(m=>`<option ${m===d.mood?'selected':''}>${esc(m)}</option>`).join('')}</select></div></div><div class="field"><label>O que a IA precisa saber sobre esta música?</label><textarea id="songStory" placeholder="Tema, história, mensagem, diferencial, momento da faixa...">${esc(d.story)}</textarea></div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.discardDraft()">Cancelar</button><button class="primary-button" onclick="Lamou.nextFromSong()">Criativo →</button></div></section>`}
async function loadTrack(){syncDraft();const d=state.draft;if(!d.url)return toast('Cole o link do Spotify.');try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(d.url));if(!r.ok)throw new Error('spotify');const x=await r.json();d.title=x.title||d.title;d.artist=(x.author_name||d.artist||'LAMOU').replace(/Spotify/gi,'').trim();d.cover=x.thumbnail_url||d.cover;save();renderNew();toast('Música identificada no Spotify.')}catch(_){save();toast('Link salvo. Você pode preencher os dados manualmente.')}}

function stepCreative(d){return `<section class="card wizard-card step-lilac"><div class="step-no">2 · CRIATIVO</div><h2>Formato e imagem/vídeo</h2><p class="sub">Escolha o formato e a mídia. O botão abaixo avança para o Hook somente quando o criativo estiver válido.</p><div class="format-grid">${FORMATS.map(([f,n])=>`<button class="format-choice ${d.creativeFormat===f?'on':''}" onclick="Lamou.setFormat('${f}')"><b>${f}</b><span>${n}</span></button>`).join('')}</div><div class="creative-options" style="margin-top:12px"><button class="creative-option ${d.creativeSource==='spotify'?'on':''}" onclick="Lamou.chooseCreative('spotify')">🎵<b>Capa Spotify</b><small>${d.cover?'Capa disponível.':'Busque a música no Spotify antes.'}</small></button><label class="creative-option ${d.creativeSource==='upload-image'?'on':''}">🖼️<b>Subir imagem</b><small>JPG, PNG ou WebP.</small><input type="file" accept="image/*" style="display:none" onchange="Lamou.loadMedia(event,'image')"></label><label class="creative-option ${d.creativeSource==='upload-video'?'on':''}">🎬<b>Subir vídeo</b><small>MP4/WebM e formatos aceitos pelo navegador.</small><input type="file" accept="video/*" style="display:none" onchange="Lamou.loadMedia(event,'video')"></label></div><div id="creativePreview" class="creative-stage creative-${d.creativeFormat.replace(':','x')}" style="margin-top:14px;aspect-ratio:${d.creativeFormat.replace(':','/')}" data-source="${esc(d.creativeSource)}">${creativePreviewHTML(d)}</div>${actions(3,'Definir hook','creative')}</section>`}
function creativePreviewHTML(d){if(d.creativeSource==='spotify'&&d.cover)return `<img src="${esc(d.cover)}" alt=""><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.project||d.genre)}</small></div>`;if(d.mediaName)return `<div class="empty"><b>${esc(d.mediaName)}</b><br>Arquivo selecionado nesta sessão.</div>`;return `<div class="empty">Escolha a capa do Spotify, uma imagem ou um vídeo.</div>`}
function setFormat(f){state.draft=normalizeDraft(state.draft);state.draft.creativeFormat=f;save();renderNew()}
function chooseCreative(source){const d=normalizeDraft(state.draft);d.creativeSource=source;if(source==='spotify')d.mediaType='image';state.draft=d;save();renderNew()}
function loadMedia(e,type){const f=e.target.files?.[0];if(!f)return;if(mediaObjectUrl)URL.revokeObjectURL(mediaObjectUrl);mediaObjectUrl=URL.createObjectURL(f);const d=normalizeDraft(state.draft);d.creativeSource=type==='video'?'upload-video':'upload-image';d.mediaType=type;d.mediaName=f.name;state.draft=d;save();renderNew()}
function restoreMediaPreview(){const d=state.draft;if(!d||d.step!==2||!mediaObjectUrl)return;const stage=document.getElementById('creativePreview');if(!stage)return;stage.innerHTML=d.mediaType==='video'?`<video src="${mediaObjectUrl}" controls playsinline></video><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.creativeFormat)}</small></div>`:`<img src="${mediaObjectUrl}" alt=""><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.creativeFormat)}</small></div>`}

function stepHook(d){return `<section class="card wizard-card step-peach"><div class="step-no">3 · HOOK</div><h2>Qual trecho apresenta melhor a música?</h2><p class="sub">Envie o áudio para o LAMOU sugerir até três trechos pela energia/dinâmica. Ou escolha manualmente.</p><div class="two"><div class="field"><label>Áudio da música</label><input type="file" accept="audio/*" onchange="Lamou.analyseAudio(event)"><small>${esc(d.audioName||'Nenhum áudio carregado nesta sessão.')}</small></div><div class="field"><label>Duração do hook</label><select onchange="Lamou.setHookDuration(this.value)">${[15,20,30].map(v=>`<option value="${v}" ${d.hookDuration===v?'selected':''}>${v} segundos</option>`).join('')}</select></div></div><div id="hookCandidates" class="hook-list">${renderHooks(d)}</div><div class="two" style="margin-top:12px"><div class="field"><label>Início manual (segundos)</label><input id="manualStart" type="number" min="0" step="0.5" value="${d.hook?.manual?d.hook.start:''}" placeholder="Ex.: 42"></div><div class="field"><label>&nbsp;</label><button class="ghost-button" onclick="Lamou.useManualHook()">Usar trecho manual</button></div></div>${actions(4,'Criar descrição')}</section>`}
function renderHooks(d){if(!d.hooks?.length)return `<div class="empty">Envie o áudio para receber sugestões, ou defina um início manual.</div>`;return d.hooks.map((h,i)=>`<button class="hook-item ${d.hook?.start===h.start&&!d.hook?.manual?'on':''}" onclick="Lamou.pickHook(${i})"><div><b>${['Hook principal','Hook alternativo','Hook de apoio'][i]||'Hook'}</b><small>${formatTime(h.start)}–${formatTime(h.end)} · energia ${Math.round((h.score||0)*100)}%</small></div><span>${d.hook?.start===h.start&&!d.hook?.manual?'✓':'Usar'}</span></button>`).join('')}
function setHookDuration(v){state.draft.hookDuration=Number(v)||20;save()}
async function analyseAudio(e){const file=e.target.files?.[0];if(!file)return;const d=state.draft;d.audioName=file.name;try{if(audioObjectUrl)URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=URL.createObjectURL(file);audioElement=new Audio(audioObjectUrl);const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw new Error('audio');const ctx=new Ctx(),buf=await ctx.decodeAudioData(await file.arrayBuffer()),arr=buf.getChannelData(0),windowSamples=Math.max(1,Math.floor(buf.sampleRate*.5)),energy=[];for(let i=0;i<arr.length;i+=windowSamples){let sum=0,n=0;for(let j=i;j<Math.min(i+windowSamples,arr.length);j+=8){sum+=arr[j]*arr[j];n++}energy.push(Math.sqrt(sum/Math.max(1,n)))}const mx=Math.max(...energy,0.000001),norm=energy.map(x=>x/mx),dur=d.hookDuration||20,nw=Math.max(1,Math.round(dur/.5)),c=[];for(let i=1;i<norm.length-nw;i++){const seg=norm.slice(i,i+nw),mean=seg.reduce((a,b)=>a+b,0)/seg.length,peak=Math.max(...seg),rise=Math.max(0,seg[Math.min(4,seg.length-1)]-(norm[i-1]||0));c.push({start:i*.5,end:Math.min(buf.duration,i*.5+dur),score:Math.min(1,mean*.7+peak*.2+rise*.1)})}c.sort((a,b)=>b.score-a.score);d.hooks=[];for(const x of c){if(d.hooks.every(y=>Math.abs(y.start-x.start)>Math.max(8,dur*.6))){d.hooks.push(x);if(d.hooks.length===3)break}}d.hook=d.hooks[0]||{start:0,end:Math.min(dur,buf.duration),score:.5};await ctx.close();save();renderNew();toast('Hooks sugeridos.')}catch(_){save();renderNew();toast('Não consegui analisar este áudio. Você pode marcar o hook manualmente.')}}
function pickHook(i){const d=state.draft,h=d.hooks?.[i];if(!h)return;d.hook={...h,manual:false};save();renderNew()}
function useManualHook(){const d=state.draft,start=Math.max(0,Number(document.getElementById('manualStart')?.value)||0);d.hook={start,end:start+(d.hookDuration||20),score:null,manual:true};save();renderNew();toast('Hook manual selecionado.')}
function formatTime(s){s=Math.max(0,Math.floor(Number(s)||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

function localDescription(d){const versions=[
`${d.artist||'LAMOU'} apresenta “${d.title||'esta faixa'}”${d.project?`, do projeto ${d.project}`:''}: ${String(d.mood||'uma').toLowerCase()} em forma de música, com identidade própria e direção humana. ${d.story||'Uma faixa feita para chegar em quem reconhece verdade, personalidade e emoção.'}`,
`“${d.title||'Nova música'}” abre mais uma janela do universo de ${d.artist||'LAMOU'}${d.project?` em ${d.project}`:''}. ${d.story||`Uma faixa ${String(d.mood||'marcante').toLowerCase()} que transforma ideia, sentimento e produção em uma assinatura musical direta.`}`,
`${d.artist||'LAMOU'} transforma ${d.story?d.story.toLowerCase():'uma ideia íntima'} em “${d.title||'uma nova faixa'}”${d.project?`, parte de ${d.project}`:''}. Curta no texto, forte na identidade: uma música para ouvir e lembrar.`
];return versions[(Math.max(1,d.generation)-1)%versions.length]}
function localHashtags(d){const raw=['LAMOU',d.title,d.project,d.genre,'MusicaBrasileira','NovaMusica','ArtistaIndependente'].filter(Boolean).map(x=>'#'+String(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]/g,''));return [...new Set(raw)].join(' ')}
function parseAIText(raw,d){const text=String(raw||'').trim();if(!text)return null;const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);const hashLines=lines.filter(x=>x.startsWith('#')||/#[A-Za-zÀ-ÿ0-9_]+/.test(x));let description=lines.filter(x=>!hashLines.includes(x)).join(' ').replace(/\s+/g,' ').trim();let hashtags=hashLines.join(' ').match(/#[A-Za-zÀ-ÿ0-9_]+/g)?.join(' ')||'';if(!description)description=text.replace(/#[A-Za-zÀ-ÿ0-9_]+/g,'').trim();if(!hashtags)hashtags=localHashtags(d);return {description,hashtags}}
async function generateDescription(){syncDraft();const d=state.draft;d.generation=(d.generation||0)+1;const context={artistIdentity:state.profile.artistBio||LAMOU_BASE,artist:d.artist||'LAMOU',track:d.title,project:d.project||'single',genre:d.genre,mood:d.mood,story:d.story||'',creativeFormat:d.creativeFormat,hook:d.hook?`${formatTime(d.hook.start)}-${formatTime(d.hook.end)}`:'não definido',previousDescription:d.description||'',version:d.generation,instruction:'Crie uma NOVA versão diferente da anterior. Texto em português, sucinto e poderoso, 2 a 4 frases. Apresente LAMOU, situe o CD/álbum/projeto somente se informado, apresente a música e termine com hashtags relevantes. Não invente biografia, números, prêmios, gravadoras ou fatos.'};let parsed=null;try{const r=await fetch('/api/ai',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'copy',context})});if(r.ok){const x=await r.json();parsed=parseAIText(x.text||x.result||x.response,d)}}catch(_){}d.description=parsed?.description||localDescription(d);d.hashtags=parsed?.hashtags||localHashtags(d);save();renderNew();toast(parsed?`Versão ${d.generation} criada pela IA.`:`Versão ${d.generation} criada com fallback local.`)}
function stepAI(d){const channels=compatibleChannels(d);const groups=audienceCounts(channels);return `<section class="card wizard-card step-yellow"><div class="step-no">4 · IA</div><div class="row between"><div><h2>Descrição do LAMOU + projeto + música</h2><p class="sub">Sucinta, poderosa e editável. Se não gostar, gere outra versão.</p></div><span class="status blue">Versão ${d.generation||0}</span></div><div class="row"><button class="primary-button" onclick="Lamou.generateDescription()">✨ ${d.generation?'Gerar outra versão':'Gerar descrição'}</button></div><div class="field" style="margin-top:12px"><label>Descrição — você pode editar</label><textarea id="descriptionText" style="min-height:150px">${esc(d.description)}</textarea></div><div class="field"><label>Hashtags — você pode editar</label><textarea id="hashtagsText" style="min-height:90px">${esc(d.hashtags)}</textarea></div><div class="notice"><b>${channels.length} destinos compatíveis encontrados para ${esc(d.genre)}.</b><br>${Object.entries(groups).map(([k,v])=>`${esc(k)}: ${v}`).join(' · ')}</div>${actions(5,'Aprovação final')}</section>`}

function toggleChannel(cid){const d=state.draft,i=d.channels.indexOf(cid);i<0?d.channels.push(cid):d.channels.splice(i,1);save();renderNew()}
function stepApproval(d){syncDraft();const compatible=compatibleChannels(d);return `<section class="card wizard-card step-cyan"><div class="step-no">5 · APROVAÇÃO FINAL</div><h2>Confira tudo antes de concluir</h2><div class="review-grid"><div class="review-block"><b>Música</b>${esc(d.title||'—')}<small>${esc(d.artist||'LAMOU')}${d.project?' · '+esc(d.project):''}</small></div><div class="review-block"><b>Modalidade</b>${d.mode==='campaign'?'Campanha':'Divulgação rápida'}</div><div class="review-block"><b>Criativo</b>${esc(d.creativeFormat)} · ${d.mediaType==='video'?'Vídeo':'Imagem'}</div><div class="review-block"><b>Hook</b>${d.hook?`${formatTime(d.hook.start)}–${formatTime(d.hook.end)}`:'Não definido'}</div></div><div class="review-block" style="margin-top:12px"><b>Descrição</b>${esc(d.description||'Ainda não gerada.')}</div><div class="review-block" style="margin-top:10px"><b>Hashtags</b>${esc(d.hashtags||'—')}</div><h3 style="margin-top:18px">Destinos recomendados</h3><p class="sub">O LAMOU selecionou pelo gênero e pela modalidade. Você pode tirar ou adicionar antes de aprovar.</p><div class="channel-list">${compatible.map(c=>`<button class="channel-item ${d.channels.includes(c.id)?'on':''}" onclick="Lamou.toggleChannel('${c.id}')"><div><b>${esc(c.name)}</b><small>${esc(c.type)} · ${esc(c.audience)}</small></div><span>${esc(c.country)}</span><span>${esc(c.cost)}</span><span>${d.channels.includes(c.id)?'✓':'＋'}</span></button>`).join('')}</div><div class="notice warn" style="margin-top:12px">Aprovar salva o plano no Histórico. Não significa que os destinos externos já receberam a música; cada envio só vira resultado quando você o confirmar no Histórico.</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="publish-button" onclick="Lamou.approveFinal()">✓ APROVAR E CONCLUIR</button></div></section>`}
function approveFinal(){syncDraft();const d=state.draft;if(!d.description.trim())return toast('Gere ou escreva a descrição antes de aprovar.');if(!d.channels.length)return toast('Selecione pelo menos um destino.');state.history.unshift({id:id(),status:'approved',approvedAt:new Date().toISOString(),mode:d.mode,title:d.title||'Música',artist:d.artist||'LAMOU',project:d.project||'',genre:d.genre,mood:d.mood,url:d.url,cover:d.cover,creativeFormat:d.creativeFormat,mediaType:d.mediaType,mediaName:d.mediaName,hook:d.hook,description:d.description,hashtags:d.hashtags,generation:d.generation,channels:[...d.channels],submitted:[]});state.draft=null;cleanupMedia();save();toast('Aprovado e salvo no Histórico.');renderHistory()}

function renderHistory(){markNav('history');root().innerHTML=`${pageHead('HISTÓRICO','Materiais aprovados','Rascunho e versão rejeitada da IA não entram aqui.')}<section class="card"><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item"><div><b>${esc(h.title)}</b><small>${fmtDate(h.approvedAt)} · ${h.mode==='campaign'?'Campanha':'Rápida'} · ${esc(h.project||h.genre||'')}</small></div><span class="status blue">Aprovado</span><span>${h.submitted?.length||0}/${h.channels?.length||0} enviados</span><div class="history-actions"><button onclick="Lamou.viewHistory('${h.id}')">Abrir</button><button onclick="Lamou.removeHistory('${h.id}')">Remover</button></div></div>`).join(''):'<div class="empty">Nenhum material aprovado ainda.</div>'}</div></section>`}
function mailtoFor(c,h){const subject=`LAMOU — ${h.title}${h.project?' · '+h.project:''}`;const body=`Olá,\n\n${h.description}\n\n${h.hashtags}\n\nSpotify: ${h.url||'link disponível sob solicitação'}\n\nObrigado pela escuta.`;return `mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function openDestination(c,h){if(c.email){location.href=mailtoFor(c,h);return}window.open(c.url,'_blank','noopener')}
function viewHistory(hid){const h=state.history.find(x=>x.id===hid);if(!h)return;const selected=(h.channels||[]).map(channelById).filter(Boolean);modal(`<div class="modal-head"><div><div class="eyebrow">${h.mode==='campaign'?'CAMPANHA':'DIVULGAÇÃO RÁPIDA'}</div><h2>${esc(h.title)}</h2><p class="sub">${esc(h.artist)}${h.project?' · '+esc(h.project):''}</p></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="review-block"><b>Descrição aprovada</b>${esc(h.description)}<small>${esc(h.hashtags)}</small></div><h3 style="margin-top:16px">Para onde enviar</h3><div class="channel-list" style="margin-top:9px">${selected.map(c=>{const sent=(h.submitted||[]).some(x=>x.channelId===c.id);return `<div class="channel-item"><div><b>${esc(c.name)}</b><small>${esc(c.audience)} · ${esc(c.method)}${c.email?' · '+esc(c.email):''}</small></div><span>${esc(c.cost)}</span><button class="ghost-button" onclick="Lamou.openDestination('${h.id}','${c.id}')">${c.email?'Preparar e-mail':'Abrir'}</button><button class="${sent?'ghost-button':'primary-button'}" ${sent?'disabled':''} onclick="Lamou.markSent('${h.id}','${c.id}')">${sent?'✓ Enviado':'Marcar enviado'}</button></div>`}).join('')}</div><div class="notice" style="margin-top:12px">O LAMOU prepara o texto e abre o canal oficial. Login, CAPTCHA, pagamento ou decisão editorial continuam sob seu controle.</div>`)}
function openDestinationById(hid,cid){const h=state.history.find(x=>x.id===hid),c=channelById(cid);if(!h||!c)return;openDestination(c,h)}
function markSent(hid,cid){const h=state.history.find(x=>x.id===hid);if(!h)return;h.submitted=h.submitted||[];if(!h.submitted.some(x=>x.channelId===cid))h.submitted.push({channelId:cid,date:new Date().toISOString()});h.status=h.submitted.length?'sent':'approved';save();viewHistory(hid);toast('Envio confirmado no Resultado.')}
function removeHistory(hid){if(!confirm('Remover este material do Histórico do LAMOU?'))return;state.history=state.history.filter(x=>x.id!==hid);save();renderHistory()}

function renderResults(){markNav('results');const s=appStats(),sent=state.history.flatMap(h=>(h.submitted||[]).map(x=>({...x,title:h.title,mode:h.mode}))),counts=CHANNELS.map(c=>({c,n:sent.filter(x=>x.channelId===c.id).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n);root().innerHTML=`${pageHead('RESULTADOS','O que realmente foi enviado','Sem alcance inventado. Aqui só entra envio que você marcou como concluído.')}${appDashboard()}<section class="card" style="margin-top:14px"><div class="stats"><div class="stat"><b>${s.quick}</b><small>Rápidas aprovadas</small></div><div class="stat"><b>${s.campaigns}</b><small>Campanhas aprovadas</small></div><div class="stat"><b>${s.sent}</b><small>Envios confirmados</small></div><div class="stat"><b>${s.destinations}</b><small>Destinos diferentes</small></div></div></section><section class="card" style="margin-top:14px"><h2>Destinos alcançados</h2><div class="history-list">${counts.length?counts.map(x=>`<div class="history-item"><div><b>${esc(x.c.name)}</b><small>${esc(x.c.type)} · ${esc(x.c.audience)}</small></div><span>${x.n} envio(s)</span><span>${esc(x.c.country)}</span><span class="status green">Confirmado</span></div>`).join(''):'<div class="empty">Nenhum envio confirmado ainda.</div>'}</div></section>`}

function openUser(){modal(`<div class="modal-head"><div><div class="eyebrow">PERFIL LAMOU</div><h2>Spotify + identidade do artista</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="two"><div class="field"><label>Nome exibido</label><input id="profileName" value="${esc(state.profile.displayName||'LAMOU')}"></div><div class="field"><label>Nome artístico</label><input id="profileArtist" value="${esc(state.profile.artistName||'LAMOU')}"></div></div><div class="field"><label>Descrição-base usada pela IA</label><textarea id="profileBio" style="min-height:130px">${esc(state.profile.artistBio||LAMOU_BASE)}</textarea></div><div class="row"><button class="primary-button" onclick="Lamou.saveUser()">Salvar</button><button class="ghost-button" onclick="Lamou.connect('spotify')">${state.connections.spotify==='green'?'Reconectar Spotify':'Conectar Spotify'}</button></div><div class="notice" style="margin-top:12px">A IA usa esta descrição como identidade fixa. O projeto/CD e a história da faixa são informados em cada música.</div>`)}
function saveUser(){state.profile.displayName=document.getElementById('profileName')?.value.trim()||'LAMOU';state.profile.artistName=document.getElementById('profileArtist')?.value.trim()||'LAMOU';state.profile.artistBio=document.getElementById('profileBio')?.value.trim()||LAMOU_BASE;save();document.getElementById('headerUser').textContent=state.profile.displayName;closeModal();toast('Perfil salvo.')}
async function refreshRemoteProfile(){try{const r=await fetch('/api/profile/summary',{credentials:'include',cache:'no-store'});if(!r.ok)return;const x=await r.json();if(x.artist){state.profile.artistName=x.artist.name||state.profile.artistName;state.profile.artistImage=x.artist.image||state.profile.artistImage;state.profile.artistStats=x.artist.stats||state.profile.artistStats}if(x.connections)state.connections={spotify:x.connections.spotify||state.connections.spotify||'red'};save()}catch(_){} }
async function runTests(){const d=normalizeDraft({mode:'quick',step:2});const tests=[['Interface',!!root()],['Spotify único',Object.keys(state.connections).length===1&&'spotify'in state.connections],['Nova música começa na escolha',typeof startMode==='function'],['Criativo normalizado',d.creativeFormat==='1:1'&&d.creativeSource==='spotify'],['Avanço Criativo',typeof nextFromCreative==='function'],['Gerar novamente',typeof generateDescription==='function'],['Aprovação final',typeof approveFinal==='function'],['Base de destinos',CHANNELS.length>=15]];modal(`<div class="modal-head"><h2>Diagnóstico</h2><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="test-list">${tests.map(([n,ok])=>`<div class="test-item"><b>${esc(n)}</b><span class="status ${ok?'green':'red'}">${ok?'OK':'Falhou'}</span></div>`).join('')}</div>`)}
function connect(provider){if(provider!=='spotify')return toast('Somente Spotify é conectado ao LAMOU.');if(window.LamouIntegration?.connect)return window.LamouIntegration.connect('spotify');toast('Integração Spotify carregando.')}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copiado.')).catch(()=>toast('Não foi possível copiar automaticamente.'))}

window.Lamou={go,startMode,discardDraft,back,next,nextFromSong,nextFromCreative,syncDraft,loadTrack,setFormat,chooseCreative,loadMedia,setHookDuration,analyseAudio,pickHook,useManualHook,generateDescription,toggleChannel,approveFinal,viewHistory,openDestination:openDestinationById,markSent,removeHistory,openUser,saveUser,runTests,connect,closeModal,copyText};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
boot();
})();