(() => {
'use strict';

const STORE='lamou_v10_db';
const SESSION='lamou_v10_session';
const LAMOU_BASE='LAMOU é um projeto musical brasileiro de criação humana e direção artística, com IA usada como ferramenta de produção e expansão criativa.';
const GENRES=['Pop','Rock','Sertanejo','Forró','Gospel','Funk','Pagode / Samba','Axé','Eletrônica','Hip Hop / Rap','R&B / Soul','Latino','MPB','Outros'];
const MOODS=['Emocional','Dançante','Romântico','Espiritual','Intenso','Sexy','Chill','Debochado','Inspirador','Sombrio'];
const FORMATS=[['1:1','Capa'],['4:5','Feed vertical'],['9:16','Stories / vertical'],['16:9','Horizontal']];
const CHANNELS=[
  {id:'spotify-artists',name:'Spotify for Artists',type:'Editores oficiais do Spotify',audience:'Editores / playlists',country:'Global',lang:'PT/EN',cost:'Grátis',url:'https://artists.spotify.com/',note:'Para lançamentos inéditos elegíveis. Faça o pitch antes do lançamento.'},
  {id:'dailyplaylists',name:'DailyPlaylists',type:'Submissão para playlists',audience:'Curadores de playlists',country:'Global',lang:'EN',cost:'Grátis + planos',url:'https://dailyplaylists.com/',note:'Curadores que aceitam submissões. Priorize playlists compatíveis com o estilo.'},
  {id:'soundplate',name:'Soundplate',type:'Submissão para playlists',audience:'Curadores independentes',country:'Global',lang:'EN',cost:'Grátis',url:'https://play.soundplate.com/playlists/latest',note:'Submissões para playlists independentes.'},
  {id:'groover',name:'Groover',type:'Rede profissional de música',audience:'Gravadoras, A&R, rádios, imprensa, sync, managers e bookers',country:'Global',lang:'PT/EN',cost:'Pago por contato',url:'https://groover.co/pt/',note:'Profissionais selecionados por perfil e objetivo.'},
  {id:'musosoup',name:'MusoSoup',type:'Imprensa e curadoria',audience:'Blogs, imprensa, playlists e rádios',country:'Global',lang:'EN',cost:'Misto',url:'https://musosoup.com/artists-how-it-works',note:'Curadores interessados podem oferecer cobertura.'},
  {id:'reverbnation',name:'ReverbNation Opportunities',type:'Oportunidades da indústria',audience:'Selos, A&R, sync, festivais, imprensa e parceiros',country:'Global',lang:'EN',cost:'Grátis + planos',url:'https://www.reverbnation.com/band-promotion/opportunities',note:'Oportunidades profissionais por perfil e objetivo.'}
];

let mediaObjectUrl='';
let audioObjectUrl='';
let audioElement=null;

function defaults(){return {accounts:{},current:null,profile:{displayName:'LAMOU',email:'',artistUrl:'',artistName:'LAMOU',artistImage:'',artistStats:null,artistBio:LAMOU_BASE},connections:{spotify:'red'},history:[],draft:null,radar:[],webChannels:CHANNELS};}
function db(){try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}')||{},base=defaults();return {...base,...raw,profile:{...base.profile,...(raw.profile||{})},connections:{spotify:raw.connections?.spotify||'red'},history:Array.isArray(raw.history)?raw.history.filter(x=>['approved','sent'].includes(String(x.status||''))):[],radar:Array.isArray(raw.radar)?raw.radar:[],webChannels:CHANNELS};}catch(_){return defaults()}}
let state=db();
function save(){if(state.current&&state.accounts?.[state.current])state.accounts[state.current].workspace={profile:state.profile,connections:state.connections,history:state.history,draft:state.draft,radar:state.radar};localStorage.setItem(STORE,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function id(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function toast(msg){const e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3200)}
function fmtDate(x){try{return new Date(x).toLocaleString('pt-BR')}catch(_){return x||'—'}}
function currentAccount(){return state.current?state.accounts?.[state.current]:null}
function root(){return document.getElementById('appRoot')}
function showApp(){document.getElementById('loginShell')?.classList.add('hidden');document.getElementById('appShell')?.classList.remove('hidden');document.getElementById('bottomNav')?.classList.remove('hidden')}
function markNav(view){document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view===view))}
function pageHead(kicker,title,sub){return `<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div></div>`}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)Lamou.closeModal()"><section class="modal">${html}</section></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}

async function ensureSession(){let device=localStorage.getItem('lamou_device_id');if(!device){device=(crypto.randomUUID?crypto.randomUUID():id())+'-'+Date.now();localStorage.setItem('lamou_device_id',device)}try{await fetch('/api/session/device',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:device})})}catch(_){}}
async function boot(){showApp();document.getElementById('headerUser').textContent=state.profile.displayName||currentAccount()?.name||'LAMOU';await ensureSession();await refreshRemoteProfile();go('home')}

function appStats(){const approved=state.history.filter(x=>['approved','sent'].includes(x.status));const campaigns=approved.filter(x=>x.mode==='campaign');const quick=approved.filter(x=>x.mode==='quick');const submitted=approved.flatMap(x=>x.submitted||[]);const unique=new Set(submitted.map(x=>x.channelId));const audiences=new Set(approved.flatMap(x=>(x.channels||[]).map(cid=>CHANNELS.find(c=>c.id===cid)?.audience).filter(Boolean)));return {approved:approved.length,campaigns:campaigns.length,quick:quick.length,sent:submitted.length,destinations:unique.size,audiences:audiences.size}}
function spotifyDashboard(){const a=state.profile.artistStats||{};return `<section class="card spotify-dashboard"><div class="row between"><div><div class="eyebrow">DASHBOARD · SPOTIFY</div><h2>${esc(state.profile.artistName||'LAMOU')}</h2><p class="sub">Primeiro, os dados do seu artista no Spotify.</p></div><span class="status ${state.connections.spotify==='green'?'green':'red'}">${state.connections.spotify==='green'?'● Conectado':'● Desconectado'}</span></div><div class="metric-strip"><div><b>${a.albums??'—'}</b><small>Álbuns</small></div><div><b>${a.tracks??'—'}</b><small>Músicas</small></div><div><b>${a.topTrack?esc(a.topTrack):'—'}</b><small>Destaque disponível</small></div><div><b>${a.streams??'—'}</b><small>Streams verificados</small></div></div><div class="row" style="margin-top:14px"><button class="primary-button" onclick="Lamou.connect('spotify')">${state.connections.spotify==='green'?'↻ Atualizar Spotify':'Conectar Spotify'}</button><button class="ghost-button" onclick="Lamou.openUser()">Perfil LAMOU</button></div></section>`}
function appDashboard(){const s=appStats();return `<section class="card dashboard-card"><div class="eyebrow">DASHBOARD · LAMOU</div><h2>Desempenho do app</h2><p class="sub">Só materiais aprovados e envios que você confirmou.</p><div class="stats"><div class="stat"><b>${s.approved}</b><small>Aprovados</small></div><div class="stat"><b>${s.campaigns}</b><small>Campanhas</small></div><div class="stat"><b>${s.sent}</b><small>Envios confirmados</small></div><div class="stat"><b>${s.destinations}</b><small>Destinos alcançados</small></div></div></section>`}
function home(){markNav('');root().innerHTML=`${pageHead('LAMOU','Seu painel musical','Spotify primeiro. Depois, o resultado do trabalho feito dentro do LAMOU.')}${spotifyDashboard()}<div style="height:14px"></div>${appDashboard()}<section class="card" style="margin-top:14px"><h2>O que você quer fazer?</h2><p class="sub">Um fluxo único e limpo para preparar a divulgação da música.</p><div class="mode-grid"><button class="choice-card" onclick="Lamou.go('new')"><span class="choice-icon">＋</span><strong>Nova música</strong><small>Rápida ou campanha, criativo, hook, IA e aprovação final.</small></button><button class="choice-card" onclick="Lamou.go('history')"><span class="choice-icon">◷</span><strong>Histórico</strong><small>Somente materiais que passaram pela aprovação final.</small></button><button class="choice-card" onclick="Lamou.go('results')"><span class="choice-icon">◎</span><strong>Resultados</strong><small>Envios confirmados e alcance por destino.</small></button></div></section>`}

function go(view){markNav(view);if(view==='home')home();else if(view==='new')renderNew();else if(view==='history')renderHistory();else if(view==='results'||view==='radar')renderResults()}
function freshDraft(mode){return {id:id(),mode,step:1,status:'draft',createdAt:new Date().toISOString(),url:'',title:'',artist:state.profile.artistName||'LAMOU',project:'',genre:'Pop',mood:'Emocional',story:'',cover:'',creativeSource:'spotify',creativeFormat:'1:1',mediaType:'image',mediaName:'',hookDuration:20,hooks:[],hook:null,audioName:'',description:'',hashtags:'',generation:0,channels:mode==='campaign'?CHANNELS.map(x=>x.id):['spotify-artists','dailyplaylists','soundplate'],submitted:[]}}
function startMode(mode){state.draft=freshDraft(mode);save();renderNew()}
function discardDraft(){state.draft=null;save();cleanupMedia();renderNew()}
function cleanupMedia(){if(mediaObjectUrl){URL.revokeObjectURL(mediaObjectUrl);mediaObjectUrl=''}if(audioObjectUrl){URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=''}audioElement=null}
function back(){syncDraft();if(!state.draft)return;state.draft.step=Math.max(1,state.draft.step-1);save();renderNew()}
function next(step){syncDraft();state.draft.step=step;save();renderNew()}
function syncDraft(){const d=state.draft;if(!d)return;const map=[['songUrl','url'],['songTitle','title'],['songArtist','artist'],['songProject','project'],['songGenre','genre'],['songMood','mood'],['songStory','story'],['descriptionText','description'],['hashtagsText','hashtags']];for(const [eid,key] of map){const e=document.getElementById(eid);if(e)d[key]=e.value.trim()}save()}
function actions(nextStep,label='Continuar'){return `<div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><div class="row"><button class="ghost-button" onclick="Lamou.discardDraft()">Cancelar</button><button class="primary-button" onclick="Lamou.next(${nextStep})">${esc(label)} →</button></div></div>`}

function renderNew(){markNav('new');if(!state.draft){root().innerHTML=`${pageHead('NOVA MÚSICA','Como você quer divulgar?','Escolha apenas o alcance. Depois o fluxo é o mesmo para criativo, hook, IA e aprovação.')}
<div class="mode-grid" style="grid-template-columns:repeat(2,1fr)"><button class="choice-card" onclick="Lamou.startMode('quick')"><span class="choice-icon">⚡</span><strong>Divulgação rápida</strong><small>Prepara a música para os destinos essenciais.</small></button><button class="choice-card" onclick="Lamou.startMode('campaign')"><span class="choice-icon">🌍</span><strong>Criar campanha</strong><small>Prepara alcance ampliado para todos os canais profissionais do LAMOU.</small></button></div>`;return}const d=state.draft;const label=d.mode==='campaign'?'Campanha':'Divulgação rápida';root().innerHTML=`${pageHead(label,d.title||'Nova música','Música → formato → mídia → hook → IA → aprovação final.')}${progress(d.step)}${d.step===1?stepSong(d):d.step===2?stepCreative(d):d.step===3?stepHook(d):d.step===4?stepAI(d):stepApproval(d)}`;restoreMediaPreview()}
function progress(step){const names=['Música','Criativo','Hook','IA','Aprovação'];return `<div class="flow-progress">${names.map((n,i)=>`<div class="flow-step ${step===i+1?'on':step>i+1?'done':''}"><b>${i+1}</b><span>${n}</span></div>`).join('')}</div>`}
function stepSong(d){return `<section class="card wizard-card step-blue"><div class="step-no">1 · MÚSICA</div><h2>Qual faixa vamos trabalhar?</h2><p class="sub">O Spotify ajuda a identificar. O contexto do CD/álbum/projeto é usado pela IA e nunca é inventado.</p><div class="field"><label>Link Spotify</label><div class="row"><input id="songUrl" style="flex:1" value="${esc(d.url)}" placeholder="https://open.spotify.com/track/..."><button class="primary-button" onclick="Lamou.loadTrack()">Buscar</button></div></div>${d.cover?`<div class="track-preview"><img src="${esc(d.cover)}" alt=""><div><b>${esc(d.title||'Faixa')}</b><small>${esc(d.artist)}</small></div></div>`:''}<div class="two" style="margin-top:12px"><div class="field"><label>Música</label><input id="songTitle" value="${esc(d.title)}" placeholder="Nome da faixa"></div><div class="field"><label>Artista</label><input id="songArtist" value="${esc(d.artist)}"></div><div class="field"><label>CD / álbum / projeto de origem</label><input id="songProject" value="${esc(d.project)}" placeholder="Ex.: Vende-se... / single / EP"></div><div class="field"><label>Gênero</label><select id="songGenre">${GENRES.map(g=>`<option ${g===d.genre?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div class="field"><label>Clima</label><select id="songMood">${MOODS.map(m=>`<option ${m===d.mood?'selected':''}>${esc(m)}</option>`).join('')}</select></div></div><div class="field"><label>O que a IA precisa saber sobre esta música?</label><textarea id="songStory" placeholder="Tema, história, mensagem, diferencial, momento da faixa...">${esc(d.story)}</textarea></div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.discardDraft()">Cancelar</button><button class="primary-button" onclick="Lamou.next(2)">Criativo →</button></div></section>`}
async function loadTrack(){syncDraft();const d=state.draft;if(!d.url)return toast('Cole o link do Spotify.');try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(d.url));if(!r.ok)throw 0;const x=await r.json();d.title=x.title||d.title;d.artist=(x.author_name||d.artist||'').replace(/Spotify/gi,'').trim();d.cover=x.thumbnail_url||d.cover;save();renderNew();toast('Música identificada no Spotify.')}catch(_){save();toast('Link salvo. Você pode preencher os dados manualmente.')}}

function stepCreative(d){return `<section class="card wizard-card step-lilac"><div class="step-no">2 · CRIATIVO</div><h2>Formato e imagem/vídeo</h2><p class="sub">Escolha primeiro o formato. Depois use a capa do Spotify, uma imagem ou um vídeo.</p><div class="format-grid">${FORMATS.map(([f,n])=>`<button class="format-choice ${d.creativeFormat===f?'on':''}" onclick="Lamou.setFormat('${f}')"><b>${f}</b><span>${n}</span></button>`).join('')}</div><div class="creative-options" style="margin-top:12px"><button class="creative-option ${d.creativeSource==='spotify'?'on':''}" onclick="Lamou.chooseCreative('spotify')">🎵<b>Capa Spotify</b><small>Usar a capa carregada.</small></button><label class="creative-option ${d.creativeSource==='upload-image'?'on':''}">🖼️<b>Subir imagem</b><small>JPG, PNG ou WebP.</small><input type="file" accept="image/*" style="display:none" onchange="Lamou.loadMedia(event,'image')"></label><label class="creative-option ${d.creativeSource==='upload-video'?'on':''}">🎬<b>Subir vídeo</b><small>Prévia do vídeo.</small><input type="file" accept="video/*" style="display:none" onchange="Lamou.loadMedia(event,'video')"></label></div><div id="creativePreview" class="creative-stage creative-${d.creativeFormat.replace(':','x')}" style="margin-top:14px;aspect-ratio:${d.creativeFormat.replace(':','/')}" data-source="${esc(d.creativeSource)}">${creativePreviewHTML(d)}</div>${actions(3,'Definir hook')}</section>`}
function creativePreviewHTML(d){if(d.creativeSource==='spotify'&&d.cover)return `<img src="${esc(d.cover)}" alt=""><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.project||d.genre)}</small></div>`;if(d.mediaName)return `<div class="empty"><b>${esc(d.mediaName)}</b><br>Arquivo selecionado nesta sessão.</div>`;return `<div class="empty">Escolha a capa, uma imagem ou um vídeo.</div>`}
function setFormat(f){state.draft.creativeFormat=f;save();renderNew()}
function chooseCreative(source){state.draft.creativeSource=source;if(source==='spotify')state.draft.mediaType='image';save();renderNew()}
function loadMedia(e,type){const f=e.target.files?.[0];if(!f)return;if(mediaObjectUrl)URL.revokeObjectURL(mediaObjectUrl);mediaObjectUrl=URL.createObjectURL(f);const d=state.draft;d.creativeSource=type==='video'?'upload-video':'upload-image';d.mediaType=type;d.mediaName=f.name;save();renderNew()}
function restoreMediaPreview(){const d=state.draft;if(!d||d.step!==2||!mediaObjectUrl)return;const stage=document.getElementById('creativePreview');if(!stage)return;stage.innerHTML=d.mediaType==='video'?`<video src="${mediaObjectUrl}" controls playsinline></video><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.creativeFormat)}</small></div>`:`<img src="${mediaObjectUrl}" alt=""><div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.creativeFormat)}</small></div>`}

function stepHook(d){return `<section class="card wizard-card step-peach"><div class="step-no">3 · HOOK</div><h2>Qual trecho apresenta melhor a música?</h2><p class="sub">Envie o áudio para o LAMOU sugerir até três trechos pela energia/dinâmica. Você também pode escolher manualmente.</p><div class="two"><div class="field"><label>Áudio da música</label><input type="file" accept="audio/*" onchange="Lamou.analyseAudio(event)"><small>${esc(d.audioName||'Nenhum áudio carregado nesta sessão.')}</small></div><div class="field"><label>Duração do hook</label><select onchange="Lamou.setHookDuration(this.value)">${[15,20,30].map(v=>`<option value="${v}" ${d.hookDuration===v?'selected':''}>${v} segundos</option>`).join('')}</select></div></div><div id="hookCandidates" class="hook-list">${renderHooks(d)}</div><div class="two" style="margin-top:12px"><div class="field"><label>Início manual (segundos)</label><input id="manualStart" type="number" min="0" step="0.5" value="${d.hook?.manual?d.hook.start:''}" placeholder="Ex.: 42"></div><div class="field"><label>&nbsp;</label><button class="ghost-button" onclick="Lamou.useManualHook()">Usar trecho manual</button></div></div>${actions(4,'Criar descrição')}</section>`}
function renderHooks(d){if(!d.hooks?.length)return `<div class="empty">Envie o áudio para receber sugestões de hook.</div>`;return d.hooks.map((h,i)=>`<button class="hook-item ${d.hook?.start===h.start&&!d.hook?.manual?'on':''}" onclick="Lamou.pickHook(${i})"><div><b>${['Hook principal','Hook alternativo','Hook de apoio'][i]||'Hook'}</b><small>${formatTime(h.start)}–${formatTime(h.end)} · energia ${Math.round((h.score||0)*100)}%</small></div><span>${d.hook?.start===h.start&&!d.hook?.manual?'✓':'Usar'}</span></button>`).join('')}
function setHookDuration(v){state.draft.hookDuration=Number(v)||20;save()}
async function analyseAudio(e){const file=e.target.files?.[0];if(!file)return;const d=state.draft;d.audioName=file.name;if(audioObjectUrl)URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=URL.createObjectURL(file);audioElement=new Audio(audioObjectUrl);toast('Analisando o áudio…');try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const buf=await ctx.decodeAudioData(await file.arrayBuffer());const data=buf.getChannelData(0),windowSamples=Math.max(1,Math.floor(buf.sampleRate*.5)),energy=[];for(let i=0;i<data.length;i+=windowSamples){let sum=0,n=0;for(let j=i;j<Math.min(i+windowSamples,data.length);j+=8){sum+=data[j]*data[j];n++}energy.push(Math.sqrt(sum/Math.max(1,n)))}const max=Math.max(...energy,0.000001);const norm=energy.map(x=>x/max),dur=d.hookDuration||20,span=Math.max(1,Math.round(dur/.5)),cands=[];for(let i=0;i<Math.max(1,norm.length-span);i++){const seg=norm.slice(i,i+span),mean=seg.reduce((a,b)=>a+b,0)/Math.max(1,seg.length),peak=Math.max(...seg),rise=Math.max(0,(seg[2]||seg[0]||0)-(norm[Math.max(0,i-2)]||0));cands.push({start:i*.5,end:Math.min(buf.duration,i*.5+dur),score:Math.min(1,mean*.65+peak*.25+rise*.25)})}cands.sort((a,b)=>b.score-a.score);d.hooks=[];for(const c of cands){if(d.hooks.every(h=>Math.abs(h.start-c.start)>12)){d.hooks.push(c);if(d.hooks.length===3)break}}d.hook=d.hooks[0]||{start:0,end:Math.min(dur,buf.duration),score:.5};await ctx.close();save();renderNew();toast('Hooks sugeridos.')}catch(_){save();renderNew();toast('Não consegui analisar esse formato. Você pode definir o hook manualmente.')}}
function pickHook(i){const h=state.draft.hooks?.[i];if(!h)return;state.draft.hook={...h};save();renderNew();if(audioElement){audioElement.currentTime=h.start;audioElement.play().catch(()=>{});clearTimeout(pickHook.t);pickHook.t=setTimeout(()=>audioElement.pause(),Math.max(1000,(h.end-h.start)*1000))}}
function useManualHook(){const start=Math.max(0,Number(document.getElementById('manualStart')?.value||0)),dur=state.draft.hookDuration||20;state.draft.hook={start,end:start+dur,manual:true,score:null};save();renderNew();toast('Hook manual selecionado.')}
function formatTime(s){s=Math.max(0,Math.floor(Number(s)||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

function localDescription(d,variant=0){const artist=state.profile.artistName||d.artist||'LAMOU',bio=state.profile.artistBio||LAMOU_BASE,project=d.project?` Do ${d.project},`:'',story=d.story?` ${d.story.trim()}`:'';const variants=[`${bio}${project} “${d.title||'esta faixa'}” chega com uma identidade ${String(d.mood||'marcante').toLowerCase()} dentro de ${d.genre||'sua linguagem musical'}.${story} Uma música curta na apresentação, grande na intenção — feita para chegar a quem reconhece personalidade, emoção e direção artística.`,`LAMOU transforma composição, direção humana e tecnologia em identidade musical.${project} “${d.title||'esta música'}” traduz ${String(d.mood||'emoção').toLowerCase()} em ${d.genre||'música'} com propósito.${story} Ouça com atenção: a força está no detalhe, no hook e na assinatura do projeto.`,`${artist} apresenta “${d.title||'esta faixa'}”.${project} ${String(d.genre||'Música')} de atmosfera ${String(d.mood||'marcante').toLowerCase()}, criada com direção artística humana e IA como ferramenta.${story} Uma faixa pensada para permanecer depois do primeiro play.`];return variants[variant%variants.length]}
function localTags(d){const clean=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]/g,'');return ['#LAMOU','#NovaMusica',`#${clean(d.genre)||'Musica'}`,d.project?`#${clean(d.project)}`:'',`#${clean(d.mood)||'SomNovo'}`,'#MusicaBrasileira','#HumanDirectedAI'].filter(Boolean).join(' ')}
async function generateDescription(){syncDraft();const d=state.draft;d.generation=(d.generation||0)+1;const context={artist:state.profile.artistName||d.artist||'LAMOU',artist_description:state.profile.artistBio||LAMOU_BASE,project_or_album:d.project||'',track:d.title,genre:d.genre,mood:d.mood,story:d.story||'',creative_format:d.creativeFormat,hook:d.hook?`${formatTime(d.hook.start)}-${formatTime(d.hook.end)}`:'',generation:d.generation,instruction:'Crie uma descrição em português, sucinta e poderosa, de 2 a 4 frases. Apresente primeiro o LAMOU, mencione o CD/álbum/projeto de origem somente se informado, depois valorize a música sem inventar fatos. Finalize com uma linha separada contendo 5 a 8 hashtags relevantes. Não use clichês vazios. Gere uma versão nova a cada tentativa.'};let output='';try{const r=await fetch('/api/ai',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'copy',context})});if(r.ok){const x=await r.json();output=String(x.text||x.result||'').trim()}}catch(_){}if(output){const lines=output.split(/\n+/).map(x=>x.trim()).filter(Boolean),hashLines=lines.filter(x=>x.includes('#')),bodyLines=lines.filter(x=>!x.includes('#'));d.description=bodyLines.join(' ')||localDescription(d,d.generation-1);d.hashtags=hashLines.join(' ').match(/#[\p{L}\p{N}_-]+/gu)?.join(' ')||localTags(d)}else{d.description=localDescription(d,d.generation-1);d.hashtags=localTags(d)}save();renderNew();toast(d.generation>1?'Nova versão criada.':'Descrição criada.')}
function stepAI(d){return `<section class="card wizard-card step-yellow"><div class="row between"><div><div class="step-no">4 · IA</div><h2>Descrição curta, forte e com identidade</h2><p class="sub">A IA usa LAMOU + projeto/CD + música + clima + hook. Se não gostar, gere outra. Os campos continuam editáveis.</p></div><span class="status blue">Versão ${d.generation||0}</span></div><div class="notice"><b>Base do artista:</b> ${esc(state.profile.artistBio||LAMOU_BASE)}${d.project?`<br><b>Projeto/CD:</b> ${esc(d.project)}`:''}</div><div class="row" style="margin-top:12px"><button class="primary-button" onclick="Lamou.generateDescription()">✨ ${d.generation?'Gerar outra versão':'Gerar descrição'}</button><button class="ghost-button" onclick="Lamou.openUser()">Editar base do LAMOU</button></div><div class="field" style="margin-top:12px"><label>Descrição — editável</label><textarea id="descriptionText" oninput="Lamou.syncDraft()" style="min-height:150px" placeholder="A descrição aparecerá aqui.">${esc(d.description)}</textarea></div><div class="field"><label>Hashtags — editáveis</label><textarea id="hashtagsText" oninput="Lamou.syncDraft()" style="min-height:88px" placeholder="#LAMOU #NovaMusica">${esc(d.hashtags)}</textarea></div><div class="notice warn">Gerar novamente cria outra versão. Nada entra no Histórico até você passar pela Aprovação Final.</div>${actions(5,'Aprovação final')}</section>`}

function stepApproval(d){const selected=CHANNELS.filter(c=>d.channels.includes(c.id));return `<section class="card wizard-card step-cyan"><div class="step-no">5 · APROVAÇÃO FINAL</div><h2>Confira tudo antes de concluir</h2><div class="review-grid"><div class="review-block"><b>Música</b>${esc(d.title||'—')}<small>${esc(d.artist||'LAMOU')}${d.project?' · '+esc(d.project):''}</small></div><div class="review-block"><b>Tipo</b>${d.mode==='campaign'?'Campanha':'Divulgação rápida'}<small>${selected.length} destinos profissionais preparados</small></div><div class="review-block"><b>Formato</b>${esc(d.creativeFormat)}<small>${esc(d.mediaName||d.creativeSource==='spotify'?'Capa Spotify':d.creativeSource)}</small></div><div class="review-block"><b>Hook</b>${d.hook?`${formatTime(d.hook.start)}–${formatTime(d.hook.end)}`:'Não definido'}<small>${d.hook?.manual?'Escolhido manualmente':'Sugerido pela análise'}</small></div></div><div class="review-block" style="margin-top:12px"><b>Descrição aprovada</b><p>${esc(d.description||'Nenhuma descrição gerada.')}</p><small>${esc(d.hashtags||'')}</small></div><details style="margin-top:12px"><summary><b>Ver destinos da divulgação (${selected.length})</b></summary><div class="channel-list" style="margin-top:10px">${selected.map(c=>`<div class="channel-item"><div><b>${esc(c.name)}</b><small>${esc(c.audience)}</small></div><span>${esc(c.country)}</span><span>${esc(c.cost)}</span><span class="status green">Preparado</span></div>`).join('')}</div></details><div class="notice" style="margin-top:12px">Aprovar conclui o material dentro do LAMOU e o envia ao Histórico. Os destinos externos só contam em Resultados quando você confirmar que realmente fez o envio.</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar e editar</button><button class="publish-button" onclick="Lamou.approveFinal()">✓ APROVAR E CONCLUIR</button></div></section>`}
function approveFinal(){syncDraft();const d=state.draft;if(!d.title)return toast('Informe o nome da música.');if(!d.description)return toast('Gere ou escreva a descrição antes de aprovar.');const item={...d,id:id(),status:'approved',approvedAt:new Date().toISOString(),submitted:[]};delete item.hooks;state.history.unshift(item);state.draft=null;cleanupMedia();save();toast('Material aprovado e salvo no Histórico.');go('history')}

function renderHistory(){markNav('history');root().innerHTML=`${pageHead('HISTÓRICO','Materiais aprovados','Rascunhos e versões rejeitadas não aparecem aqui.')}<section class="card"><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item"><div><b>${esc(h.title)}</b><small>${fmtDate(h.approvedAt||h.createdAt)} · ${h.mode==='campaign'?'Campanha':'Rápida'}</small></div><span class="status green">Aprovado</span><span>${(h.submitted||[]).length} envios</span><div class="history-actions"><button onclick="Lamou.viewHistory('${h.id}')">Abrir</button><button onclick="Lamou.removeHistory('${h.id}')">Remover</button></div></div>`).join(''):'<div class="empty">Nenhuma música aprovada ainda.</div>'}</div></section>`}
function viewHistory(hid){const h=state.history.find(x=>x.id===hid);if(!h)return;const selected=CHANNELS.filter(c=>(h.channels||[]).includes(c.id));modal(`<div class="modal-head"><div><div class="eyebrow">MATERIAL APROVADO</div><h2>${esc(h.title)}</h2><p class="sub">${esc(h.project||h.artist||'LAMOU')}</p></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="review-block"><b>Descrição</b><p>${esc(h.description||'')}</p><small>${esc(h.hashtags||'')}</small></div><h3 style="margin-top:16px">Destinos</h3><div class="channel-list" style="margin-top:8px">${selected.map(c=>{const sent=(h.submitted||[]).find(x=>x.channelId===c.id);return `<div class="channel-item"><div><b>${esc(c.name)}</b><small>${esc(c.audience)}</small></div><span>${sent?`Enviado ${fmtDate(sent.date)}`:'Pendente'}</span><a class="ghost-button" href="${esc(c.url)}" target="_blank" rel="noopener">Abrir</a><button class="${sent?'ghost-button':'primary-button'}" ${sent?'disabled':''} onclick="Lamou.markSent('${h.id}','${c.id}')">${sent?'✓ Enviado':'Marcar enviado'}</button></div>`}).join('')}</div>`)}
function markSent(hid,cid){const h=state.history.find(x=>x.id===hid);if(!h)return;h.submitted=Array.isArray(h.submitted)?h.submitted:[];if(!h.submitted.some(x=>x.channelId===cid))h.submitted.push({channelId:cid,date:new Date().toISOString()});h.status='sent';save();viewHistory(hid);toast('Envio confirmado nos Resultados.')}
function removeHistory(hid){if(!confirm('Remover este material aprovado do Histórico do LAMOU?'))return;state.history=state.history.filter(x=>x.id!==hid);save();renderHistory()}

function renderResults(){markNav('results');const s=appStats(),sent=state.history.flatMap(h=>(h.submitted||[]).map(x=>({...x,title:h.title,mode:h.mode})));const counts=CHANNELS.map(c=>({c,n:sent.filter(x=>x.channelId===c.id).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n);root().innerHTML=`${pageHead('RESULTADOS','O que realmente foi feito','Sem número inventado: aqui só aparece aprovação e envio que você confirmou.')}${appDashboard()}<section class="card" style="margin-top:14px"><div class="stats"><div class="stat"><b>${s.quick}</b><small>Rápidas aprovadas</small></div><div class="stat"><b>${s.campaigns}</b><small>Campanhas aprovadas</small></div><div class="stat"><b>${s.sent}</b><small>Envios confirmados</small></div><div class="stat"><b>${s.destinations}</b><small>Destinos diferentes</small></div></div></section><section class="card" style="margin-top:14px"><h2>Destinos alcançados</h2><p class="sub">Quantidade de envios que você confirmou por destino.</p><div class="history-list">${counts.length?counts.map(x=>`<div class="history-item"><div><b>${esc(x.c.name)}</b><small>${esc(x.c.audience)}</small></div><span>${x.n} envio(s)</span><span>${esc(x.c.country)}</span><span class="status green">Confirmado</span></div>`).join(''):'<div class="empty">Nenhum envio confirmado ainda. Abra um item do Histórico, faça a submissão no destino e marque como enviado.</div>'}</div></section>`}

function openUser(){modal(`<div class="modal-head"><div><div class="eyebrow">PERFIL LAMOU</div><h2>Spotify + identidade do artista</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="two"><div class="field"><label>Nome exibido</label><input id="profileName" value="${esc(state.profile.displayName||'LAMOU')}"></div><div class="field"><label>Nome artístico</label><input id="profileArtist" value="${esc(state.profile.artistName||'LAMOU')}"></div></div><div class="field"><label>Descrição-base usada pela IA</label><textarea id="profileBio" style="min-height:130px">${esc(state.profile.artistBio||LAMOU_BASE)}</textarea></div><div class="row"><button class="primary-button" onclick="Lamou.saveUser()">Salvar</button><button class="ghost-button" onclick="Lamou.connect('spotify')">${state.connections.spotify==='green'?'Reconectar Spotify':'Conectar Spotify'}</button></div><div class="notice" style="margin-top:12px">A IA usa esta descrição como identidade fixa do LAMOU. O CD/álbum/projeto continua sendo informado em cada música.</div>`)}
function saveUser(){state.profile.displayName=document.getElementById('profileName')?.value.trim()||'LAMOU';state.profile.artistName=document.getElementById('profileArtist')?.value.trim()||'LAMOU';state.profile.artistBio=document.getElementById('profileBio')?.value.trim()||LAMOU_BASE;save();document.getElementById('headerUser').textContent=state.profile.displayName;closeModal();toast('Perfil salvo.')}
async function refreshRemoteProfile(){try{const r=await fetch('/api/profile/summary',{credentials:'include',cache:'no-store'});if(!r.ok)return;const x=await r.json();if(x.artist){state.profile.artistName=x.artist.name||state.profile.artistName;state.profile.artistImage=x.artist.image||state.profile.artistImage;state.profile.artistStats=x.artist.stats||state.profile.artistStats}if(x.connections)state.connections={spotify:x.connections.spotify||state.connections.spotify||'red'};save()}catch(_){}}
async function runTests(){const tests=[['Interface',!!root()],['Spotify único',Object.keys(state.connections).length===1&&'spotify'in state.connections],['Fluxo de aprovação',typeof approveFinal==='function'],['Gerar novamente',typeof generateDescription==='function'],['Hook de áudio',!!(window.AudioContext||window.webkitAudioContext)],['Resultados reais',state.history.every(x=>['approved','sent'].includes(x.status))]];modal(`<div class="modal-head"><h2>Diagnóstico</h2><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="test-list">${tests.map(([n,ok])=>`<div class="test-item"><b>${esc(n)}</b><span class="status ${ok?'green':'red'}">${ok?'OK':'Falhou'}</span></div>`).join('')}</div>`)}
function connect(provider){if(provider!=='spotify')return toast('Somente Spotify é conectado ao LAMOU.');if(window.LamouIntegration?.connect)return window.LamouIntegration.connect('spotify');toast('Integração Spotify carregando.')}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copiado.')).catch(()=>toast('Não foi possível copiar automaticamente.'))}

window.Lamou={go,startMode,discardDraft,back,next,syncDraft,loadTrack,setFormat,chooseCreative,loadMedia,setHookDuration,analyseAudio,pickHook,useManualHook,generateDescription,approveFinal,viewHistory,markSent,removeHistory,openUser,saveUser,runTests,connect,closeModal,copyText};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
boot();
})();
