async function analyseAudio(e){
 let f=e.target.files?.[0];if(!f)return;audioStatus.className='status yellow';audioStatus.textContent='Analisando…';
 try{if(S.audioUrl)URL.revokeObjectURL(S.audioUrl);S.audioUrl=URL.createObjectURL(f);audio.src=S.audioUrl;audio.style.display='block';let ac=new AudioContext(),buf=await ac.decodeAudioData(await f.arrayBuffer()),d=buf.getChannelData(0),step=Math.floor(buf.sampleRate*.5),en=[];
 for(let i=0;i<d.length;i+=step){let sum=0,n=0;for(let j=i;j<Math.min(i+step,d.length);j+=8){sum+=d[j]*d[j];n++}en.push(Math.sqrt(sum/Math.max(1,n)))}let mx=Math.max(...en,1e-8);S.energy=en.map(x=>x/mx);S.duration=buf.duration;draw(S.energy);score();audioStatus.className='status green';audioStatus.textContent=Math.floor(buf.duration/60)+':'+String(Math.floor(buf.duration%60)).padStart(2,'0')+' analisado';await ac.close()}catch(err){audioStatus.className='status red';audioStatus.textContent='Formato não suportado';toast('Tente MP3 ou WAV.')}
}
function score(){if(!S.energy?.length)return;let goal=hookGoal.value,ws=goal==='short'?15:goal==='long'?30:20,n=Math.round(ws/.5),c=[];for(let i=2;i<S.energy.length-n-2;i++){let seg=S.energy.slice(i,i+n),mean=avg(seg),peak=Math.max(...seg),rise=Math.max(0,seg[Math.min(4,seg.length-1)]-S.energy[i-2]),pos=i*.5/S.duration,sc=mean*.6+peak*.2+rise*.12+(pos>.12&&pos<.82?.1:0)+(goal==='drop'?rise*.28:0);c.push({start:i*.5,end:Math.min(S.duration,i*.5+ws),score:sc})}c.sort((a,b)=>b.score-a.score);S.hooks=[];for(let x of c)if(S.hooks.every(y=>Math.abs(y.start-x.start)>14)){S.hooks.push(x);if(S.hooks.length===3)break}S.hook=S.hooks[0];renderHooks();updateHookBadge();save()}
function rescore(){score()}
function renderHooks(){hooks.innerHTML=S.hooks.map((h,i)=>`<div class="hook ${S.hook?.start===h.start?'on':''}"><div><b>${['🥇 Hook principal','🥈 Hook alternativo','🥉 Hook de apoio'][i]}</b><br><small>${fmt(h.start)}–${fmt(h.end)} • energia/dinâmica</small></div><div class="row"><button class="btn" onclick="useHook(${i});previewHook()">▶</button><button class="btn soft" onclick="useHook(${i})">Usar</button></div></div>`).join('')}
function useHook(i){S.hook=S.hooks[i];renderHooks();updateHookBadge();save()}
function manualHook(){S.hook={start:+mstart.value||0,end:(+mstart.value||0)+(+mdur.value||20),manual:true};renderHooks();updateHookBadge();toast('Trecho manual selecionado.');save()}
function previewHook(){if(!audio.src)return toast('Envie o áudio primeiro.');let h=S.hook||{start:0,end:20};audio.currentTime=h.start;audio.play();clearTimeout(window.ht);window.ht=setTimeout(()=>audio.pause(),Math.max(1000,(h.end-h.start)*1000))}
function draw(a){let c=wave.getContext('2d'),w=wave.width,h=wave.height;c.clearRect(0,0,w,h);c.strokeStyle='#7073ef';c.beginPath();a.forEach((v,i)=>{let x=i/(a.length-1)*w,y=v*h*.42;c.moveTo(x,h/2-y);c.lineTo(x,h/2+y)});c.stroke()}
function effective(c){let p=production.value;if(c.ai==='no'&&p==='ai')return'red';if(c.ai==='no'&&p==='assist')return'yellow';return c.perm}
function filterChannels(){let q=(search?.value||'').toLowerCase(),t=ctype?.value||'',pm=perm?.value||'',fr=free?.value||'',g=genre.value;channelsEl=document.getElementById('channels');let list=channels.filter(c=>(!q||(c.name+' '+c.note+' '+c.genres).toLowerCase().includes(q))&&(!t||c.type===t)&&(!pm||effective(c)===pm)&&(!fr||c.cost===fr)&&(!g||c.genres.includes(g)||c.genres.includes('Outros')));channelsEl.innerHTML=list.map(c=>{let e=effective(c),sel=S.selected.includes(c.id);return`<div class="channel"><div><b>${c.name}</b><br><small>${c.note}</small></div><span class="status green">Grátis</span><span class="status ${e}">${e==='green'?'🟢 Permitido':e==='yellow'?'🟡 Revisar':'🔴 Não usar'}</span><div class="row"><label class="chip ${sel?'on':''}"><input style="display:none" type="checkbox" ${sel?'checked':''} onchange="selectChannel('${c.id}',this)">Selecionar</label><button class="btn" onclick="openChannel('${c.id}')">Abrir</button></div></div>`}).join('')||'<div class="notice">Nenhum canal compatível.</div>'}
function selectChannel(id,c){let i=S.selected.indexOf(id);c.checked&&i<0?S.selected.push(id):!c.checked&&i>=0?S.selected.splice(i,1):0;filterChannels();save()}
function openChannel(id){let c=channels.find(x=>x.id===id);if(effective(c)==='red')return toast('Canal incompatível com a política atual desta produção.');window.open(c.url,'_blank','noopener');log('Submissão aberta',c.name)}
function prepareExternal(){if(!S.selected.length)return toast('Selecione canais.');makeCopy();log('Divulgação externa',S.selected.length+' canais');toast('Divulgação preparada. Abra as rotas selecionadas para concluir onde houver login/formulário.')}

function creativeMode(m){S.creativeMode=m;document.querySelectorAll('.creative-type').forEach(x=>x.classList.toggle('on',x.dataset.creative===m));applyCreativeChoice();save()}
function creativeFormat(f,el){S.creativeFormat=f;document.querySelectorAll('.format').forEach(x=>x.classList.toggle('on',x.dataset.format===f));const map={'1:1':'1/1','4:5':'4/5','9:16':'9/16','16:9':'16/9'};creativeStage.style.aspectRatio=map[f]||'1/1';creativePlayBadge.textContent=f;save()}
function loadCreativeImage(e){const f=e.target.files?.[0];if(!f)return;if(S.creativeImageUrl&&S.creativeImageSource==='upload')URL.revokeObjectURL(S.creativeImageUrl);S.creativeImageUrl=URL.createObjectURL(f);S.creativeImageSource='upload';creativeImage.src=S.creativeImageUrl;S.creativeMode='image';creativeMode('image');creativeStatus.className='status green';creativeStatus.textContent='Imagem carregada';applyCreativeChoice();save()}
function loadCreativeVideo(e){const f=e.target.files?.[0];if(!f)return;if(S.creativeVideoUrl)URL.revokeObjectURL(S.creativeVideoUrl);S.creativeVideoUrl=URL.createObjectURL(f);S.creativeVideoName=f.name;creativeVideo.src=S.creativeVideoUrl;S.creativeMode='video';creativeMode('video');creativeStatus.className='status green';creativeStatus.textContent='Vídeo carregado';applyCreativeChoice();save()}
function useSpotifyCover(silent=false){if(!S.cover){if(!silent)toast('Busque a música no Spotify primeiro para carregar a capa.');return}if(S.creativeImageUrl&&S.creativeImageSource==='upload')URL.revokeObjectURL(S.creativeImageUrl);S.creativeImageUrl=S.cover;S.creativeImageSource='spotify';creativeImage.src=S.cover;if(S.creativeMode!=='auto')S.creativeMode='image';document.querySelectorAll('.creative-type').forEach(x=>x.classList.toggle('on',x.dataset.creative===S.creativeMode));creativeStatus.className='status green';creativeStatus.textContent='Capa do Spotify';applyCreativeChoice();save()}
function applyCreativeChoice(){let m=S.creativeMode;if(m==='auto')m=S.creativeVideoUrl?'video':S.creativeImageUrl?'image':S.cover?'image':'none';creativePlaceholder.style.display='none';creativeImage.style.display='none';creativeVideo.style.display='none';if(m==='video'&&S.creativeVideoUrl){creativeVideo.src=S.creativeVideoUrl;creativeVideo.style.display='block';creativeStatus.className='status green';creativeStatus.textContent='Vídeo pronto'}else if(m==='image'&&(S.creativeImageUrl||S.cover)){let src=S.creativeImageUrl||S.cover;creativeImage.src=src;creativeImage.style.display='block';creativeStatus.className='status green';creativeStatus.textContent=S.creativeImageSource==='spotify'?'Capa do Spotify':'Imagem pronta'}else{creativePlaceholder.style.display='grid';creativeStatus.className='status gray';creativeStatus.textContent='Sem criativo'}updateCreativeOverlay();updateHookBadge()}
function updateCreativeOverlay(){if(!window.creativeOverlayTitle)return;creativeOverlayTitle.textContent=creativeTitle.value||S.title||'Nova música';creativeOverlayCTA.textContent=creativeCTA.value||'Ouça no Spotify'}
function toggleSyncHook(el){S.syncHook=!S.syncHook;el.classList.toggle('on',S.syncHook);save()}
function updateHookBadge(){if(!window.creativeHookBadge)return;creativeHookBadge.textContent=S.hook?'Hook: '+fmt(S.hook.start)+'–'+fmt(S.hook.end):'Hook: ainda não selecionado'}
async function playCreativePreview(){applyCreativeChoice();updateHookBadge();let m=S.creativeMode==='auto'?(S.creativeVideoUrl?'video':(S.creativeImageUrl||S.cover)?'image':'none'):S.creativeMode;if(m==='none')return toast('Escolha uma imagem, vídeo ou a capa do Spotify.');if(m==='video'&&S.creativeVideoUrl){creativeVideo.currentTime=0;creativeVideo.muted=true;try{await creativeVideo.play()}catch(e){}}if(S.syncHook&&audio.src){let h=S.hook||{start:0,end:Math.min(20,S.duration||20)};audio.currentTime=h.start;try{await audio.play()}catch(e){}clearTimeout(window.creativeTimer);window.creativeTimer=setTimeout(()=>stopCreativePreview(),Math.max(1200,(h.end-h.start)*1000))}else if(m==='video'&&S.creativeVideoUrl){clearTimeout(window.creativeTimer);window.creativeTimer=setTimeout(()=>stopCreativePreview(),15000)}log('Criativo visualizado',S.creativeMode+' • '+S.creativeFormat)}
function stopCreativePreview(){try{creativeVideo.pause()}catch(e){}try{audio.pause()}catch(e){}clearTimeout(window.creativeTimer)}
function restoreCreative(){if(!document.getElementById('creativeStage'))return;document.querySelectorAll('.creative-type').forEach(x=>x.classList.toggle('on',x.dataset.creative===S.creativeMode));document.querySelectorAll('.format').forEach(x=>x.classList.toggle('on',x.dataset.format===S.creativeFormat));creativeFormat(S.creativeFormat||'1:1',document.querySelector('.format[data-format="'+(S.creativeFormat||'1:1')+'"]'));if(S.creativeImageSource==='spotify'&&S.creativeImageUrl)creativeImage.src=S.creativeImageUrl;if(S.title)creativeTitle.value=S.title;syncHookBtn.classList.toggle('on',S.syncHook!==false);S.syncHook=S.syncHook!==false;applyCreativeChoice()}

function makeCopy(){let l=copyLang.value||'Português',t=tone.value||'impact',o=words[l],txt=o[t];if(Array.isArray(txt))txt=txt[Math.floor(Math.random()*txt.length)];txt=txt.replace('{g}',subgenre.value||genre.value);copy.innerText=(txt+'\n'+(S.title||'')+'\n'+tracked(true)).trim();return copy.innerText}
function tracked(silent=true){if(!S.url){if(!silent)toast('Carregue a música primeiro.');return''}let u=new URL(S.url);u.searchParams.set('utm_source',source.value);u.searchParams.set('utm_medium','organic');u.searchParams.set('utm_campaign',campaignName.value||'lamou_launch');let out=trackingBase.value?trackingBase.value+encodeURIComponent(u.toString()):u.toString();document.getElementById('tracked').innerText=out;if(!silent&&!trackingBase.value)toast('UTM criado. Para contar cliques externos, configure o redirecionador.');return out}
function createQuick(){if(!S.url)return toast('Carregue a música primeiro.');makeCopy();log('Publicação criada',S.quick.join(', '));toast('Publicação pronta.')}
async function shareNow(){let text=makeCopy();if(navigator.share)try{await navigator.share({title:S.title||'LAMOU',text,url:S.url});log('Compartilhamento','Web Share');return}catch(e){}copyText(text)}
function buildCampaign(){if(!S.camp.length)return toast('Selecione plataformas.');let d=+days.value,ins=intensity.value,n=ins==='high'?d:ins==='normal'?Math.max(4,Math.round(d/7*4)):Math.max(2,Math.round(d/7*2)),goals=['Apresentar música','Destacar hook','Gerar saves','Compartilhar','Reforçar Spotify'];calendar.innerHTML=Array.from({length:n},(_,i)=>{let day=Math.round(i*(d-1)/Math.max(1,n-1))+1;return`<div class="cal"><b>Dia ${day}</b><span>${S.camp[i%S.camp.length]}</span><span>${goals[i%goals.length]}</span></div>`}).join('');log('Campanha criada',d+' dias • '+n+' posts');toast('Campanha criada.')}
function mailCopy(){location.href='mailto:?subject='+encodeURIComponent('Sugestão musical — '+(S.title||'LAMOU'))+'&body='+encodeURIComponent(makeCopy());log('E-mail preparado','mailto')}
function log(action,channel){S.history.unshift({date:new Date().toISOString(),action,channel});S.history=S.history.slice(0,120);save();renderHistory()}
function renderHistory(){aActions.textContent=S.history.length;aChannels.textContent=new Set(S.history.map(x=>x.channel)).size;aCampaigns.textContent=S.history.filter(x=>x.action.includes('Campanha')).length;history.innerHTML=S.history.length?`<table><tr><th>Data</th><th>Ação</th><th>Canal</th></tr>${S.history.slice(0,10).map(x=>`<tr><td>${new Date(x.date).toLocaleString('pt-BR')}</td><td>${x.action}</td><td>${x.channel}</td></tr>`).join('')}</table>`:'<div class="notice">Nenhuma ação ainda.</div>'}
function csv(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader;r.onload=()=>{let lines=r.result.split(/\r?\n/).filter(Boolean),del=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',',heads=lines[0].split(del).map(x=>x.replaceAll('"','')),keys=['stream','listener','ouvin','save','salv','playlist','follower','seguidor'],sum={};heads.forEach((h,i)=>{if(keys.some(k=>h.toLowerCase().includes(k)))sum[h]=0});for(let j=1;j<lines.length;j++){let row=lines[j].split(del);heads.forEach((h,i)=>{if(h in sum){let v=Number((row[i]||'').replace(/[^\d.-]/g,''));if(Number.isFinite(v))sum[h]+=v}})}csvResult.innerHTML=Object.keys(sum).length?Object.entries(sum).map(([k,v])=>`<b>${k}:</b> ${Math.round(v).toLocaleString('pt-BR')}`).join('<br>'):'CSV carregado; nenhuma coluna reconhecida automaticamente.';log('CSV Spotify importado',f.name)};r.readAsText(f)}
function copyText(t){navigator.clipboard?.writeText(t).then(()=>toast('Copiado.')).catch(()=>toast('Não foi possível copiar automaticamente.'))}
function toast(t){let x=document.getElementById('toast');x.innerText=t;x.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove('show'),2600)}
function go(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
function avg(a){return a.reduce((s,x)=>s+x,0)/Math.max(1,a.length)}function fmt(s){s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
document.addEventListener('DOMContentLoaded',()=>{initAccess();init()});

/* ===== LAMOU UX ENHANCEMENTS ===== */
filterChannels=function(){
 let q=(document.getElementById('search')?.value||'').toLowerCase(),t=document.getElementById('ctype')?.value||'',pm=document.getElementById('perm')?.value||'',fr=document.getElementById('free')?.value||'',g=document.getElementById('genre')?.value||'',prod=document.getElementById('production')?.value||'human';
 let box=document.getElementById('channels');if(!box)return;
 let list=channels.filter(c=>(!q||(c.name+' '+c.note+' '+c.genres).toLowerCase().includes(q))&&(!t||c.type===t)&&(!pm||effective(c)===pm)&&(!fr||c.cost===fr)&&(!g||c.genres.includes(g)||c.genres.includes('Outros')));
 list.sort((a,b)=>{let ap=(a.priority||0)+(prod!=='human'&&a.ai==='yes'?25:0),bp=(b.priority||0)+(prod!=='human'&&b.ai==='yes'?25:0);return bp-ap});
 box.innerHTML=list.map(c=>{let e=effective(c),sel=S.selected.includes(c.id),cost=c.cost==='free'?'<span class="status green">Grátis</span>':'<span class="status yellow">Revisar custo</span>',rank=c.name.includes('PRIORIDADE IA')?'<span class="status ai-rank">🏆 Ranking IA</span>':'';return`<div class="channel ${c.name.includes('PRIORIDADE IA')?'ai-ranking-channel':''}"><div><b>${c.name}</b><br><small>${c.note}</small></div><div>${rank}${cost}</div><span class="status ${e}">${e==='green'?'🟢 Permitido':e==='yellow'?'🟡 Revisar':'🔴 Não usar'}</span><div class="row"><label class="chip ${sel?'on':''}"><input style="display:none" type="checkbox" ${sel?'checked':''} onchange="selectChannel('${c.id}',this)">Selecionar</label><button class="btn" onclick="openChannel('${c.id}')">Abrir</button></div></div>`}).join('')||'<div class="notice">Nenhum canal compatível.</div>';
};

renderHistory=function(){
 const rows=S.history||[];
 if(window.aActions)aActions.textContent=rows.length;
 if(window.aChannels)aChannels.textContent=new Set(rows.map(x=>x.channel).filter(Boolean)).size;
 if(window.aCampaigns)aCampaigns.textContent=rows.filter(x=>String(x.action).includes('Campanha')).length;
 const pub=rows.filter(x=>x.status==='Finalizado no painel'||String(x.action).includes('PUBLICADO / FINALIZADO')).length;
 const p=document.getElementById('aPublished');if(p)p.textContent=pub;
 if(!window.history)return;
 history.innerHTML=rows.length?`<table><tr><th>Data / hora</th><th>Música</th><th>Modo</th><th>Canais</th><th>Status</th></tr>${rows.slice(0,15).map(x=>`<tr><td>${new Date(x.date).toLocaleString('pt-BR')}</td><td>${x.title||S.title||'—'}</td><td>${x.mode||x.action||'—'}</td><td>${x.channel||'—'}</td><td>${x.status?`<span class="status green">${x.status}</span>`:(x.action||'—')}</td></tr>`).join('')}</table>`:'<div class="notice">Nenhuma ação ainda.</div>';
};

function currentModeName(){const m=document.querySelector('.mode.on')?.dataset.mode||'quick';return m==='quick'?'Publicação rápida':m==='campaign'?'Campanha':'Divulgar agora'}
function currentChannels(){const m=document.querySelector('.mode.on')?.dataset.mode||'quick';if(m==='quick')return S.quick||[];if(m==='campaign')return S.camp||[];return(S.selected||[]).map(id=>channels.find(c=>c.id===id)?.name).filter(Boolean)}
function refreshFinalChecklist(){
 const box=document.getElementById('finalChecklist');if(!box)return;
 const ch=currentChannels(),hasCreative=!!(S.creativeImageUrl||S.creativeVideoUrl||S.cover),hasHook=!!S.hook,hasCopy=document.getElementById('copy')?.innerText&&!document.getElementById('copy').innerText.includes('Carregue uma música');
 box.innerHTML=`<div class="final-check ${S.url?'ok':'no'}">${S.url?'✓':'!'} Música</div><div class="final-check ${hasHook?'ok':'warn'}">${hasHook?'✓':'•'} Hook</div><div class="final-check ${hasCreative?'ok':'warn'}">${hasCreative?'✓':'•'} Criativo</div><div class="final-check ${ch.length?'ok':'no'}">${ch.length?'✓':'!'} ${ch.length} canal(is)</div><div class="final-check ${hasCopy?'ok':'warn'}">${hasCopy?'✓':'•'} Mensagem</div>`;
}
function finalizePublication(){
 if(!S.url)return toast('Antes de finalizar, carregue a música do Spotify.');
 const ch=currentChannels();if(!ch.length)return toast('Selecione pelo menos um canal ou plataforma.');
 try{makeCopy()}catch(e){}
 const modeName=currentModeName(),now=new Date().toISOString(),entry={date:now,action:'PUBLICADO / FINALIZADO',mode:modeName,channel:ch.join(', '),title:S.title||'Faixa Spotify',url:S.url,status:'Finalizado no painel'};
 S.history.unshift(entry);S.history=S.history.slice(0,120);S.lastPublication=entry;save();renderHistory();refreshFinalChecklist();
 const stamp=document.getElementById('finalStamp');if(stamp)stamp.innerHTML=`✅ <b>Finalizado em ${new Date(now).toLocaleString('pt-BR')}</b><br>${entry.title} • ${modeName} • ${ch.length} canal(is)`;
 toast('Finalizado e registrado no histórico com data e hora.');
 setTimeout(()=>document.getElementById('analytics')?.scrollIntoView({behavior:'smooth'}),550);
}

document.addEventListener('DOMContentLoaded',()=>{
 const st=document.createElement('style');st.textContent=`
 .stepzone-1{background:linear-gradient(145deg,#f4faff,#eaf5ff)!important;border-color:#cfe6fb!important}.stepzone-2{background:linear-gradient(145deg,#f4fff8,#eaf9f0)!important;border-color:#ccebd9!important}.stepzone-3{background:linear-gradient(145deg,#faf7ff,#f0ebff)!important;border-color:#ddd3ff!important}.stepzone-4{background:linear-gradient(145deg,#fff9f3,#fff0e4)!important;border-color:#f5d9c1!important}.stepzone-5{background:linear-gradient(145deg,#fffef4,#fff8d9)!important;border-color:#efe3ae!important}.stepzone-results{background:linear-gradient(145deg,#f3fdff,#e7f9fb)!important;border-color:#ccebee!important}
 .ai-ranking-channel{border:1.5px solid #cdbdff!important;background:linear-gradient(145deg,#fff,#f7f3ff)!important;box-shadow:0 8px 22px #6752c412}.status.ai-rank{background:#eee8ff;color:#5a43b8;margin-right:5px}
 .finalize-card{grid-column:span 12;background:linear-gradient(135deg,#151827,#272c45)!important;color:#fff!important;border-color:#353b59!important}.finalize-card .sub{color:#c3c8d7}.finalize-card .btn.publish-final{font-size:1.05rem;padding:14px 22px;background:linear-gradient(135deg,#6f72ff,#8b68ff);color:#fff;border:0;box-shadow:0 12px 28px #6f72ff42}.final-checks{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.final-check{padding:7px 10px;border-radius:999px;font-size:.78rem;font-weight:760;background:#ffffff12;border:1px solid #ffffff1c}.final-check.ok{background:#1c8c5a33;border-color:#66d8a044}.final-check.warn{background:#b8871733;border-color:#e6b95a44}.final-check.no{background:#c1445033;border-color:#ff849044}.final-stamp{margin-top:12px;padding:11px 13px;border-radius:13px;background:#ffffff0d;color:#e8ebf4}.section-accent{height:5px;border-radius:999px;margin:-3px 0 15px}.stepzone-1 .section-accent{background:#66aee8}.stepzone-2 .section-accent{background:#59b77d}.stepzone-3 .section-accent{background:#8f76dd}.stepzone-4 .section-accent{background:#e09a61}.stepzone-5 .section-accent{background:#d9bd45}
 `;document.head.appendChild(st);
 document.querySelectorAll('main .card').forEach(card=>{const h=card.querySelector('h2')?.textContent.trim()||'';let n='';if(h.startsWith('1.')||h==='Identidade da faixa')n='1';else if(h.startsWith('2.')||h==='Idioma e mercado')n='2';else if(h.startsWith('3.'))n='3';else if(h.startsWith('4.')||card.id==='quickPanel'||card.id==='campaignPanel'||card.id==='externalPanel')n='4';else if(h.startsWith('5.')||h.includes('Link da campanha'))n='5';else if(card.id==='analytics')card.classList.add('stepzone-results');if(n){card.classList.add('stepzone-'+n);const a=document.createElement('div');a.className='section-accent';card.insertBefore(a,card.children[1]||null)}});
 const ext=document.getElementById('externalPanel'),toolbar=ext?.querySelector('.toolbar');if(ext&&toolbar&&!document.getElementById('aiRankingSpotlight')){const spot=document.createElement('div');spot.id='aiRankingSpotlight';spot.className='notice';spot.style.marginBottom='12px';spot.innerHTML='<b>🏆 Rankings de música com IA — prioridade alta</b><br>SIQA, aiFyMusic, Rebel AI, Music Idol AI, AI Music League, NEX e Songaition ficam em evidência para faixas com IA.<div class="row" style="margin-top:9px"><button class="btn soft" id="showAiRanks">Mostrar só rankings IA</button><button class="btn" id="clearAiRanks">Mostrar todos</button></div>';ext.insertBefore(spot,toolbar);document.getElementById('showAiRanks').onclick=()=>{document.getElementById('search').value='PRIORIDADE IA';filterChannels()};document.getElementById('clearAiRanks').onclick=()=>{document.getElementById('search').value='';filterChannels()}};
 const analytics=document.getElementById('analytics');if(analytics&&!document.getElementById('finalizeCard')){const final=document.createElement('section');final.id='finalizeCard';final.className='card finalize-card';final.innerHTML='<div><h2>✅ Tudo pronto?</h2><p class="sub">Confira o resumo e use o botão final para registrar a divulgação como concluída no painel.</p></div><div id="finalChecklist" class="final-checks"></div><div class="row"><button class="btn publish-final" onclick="finalizePublication()">🚀 PUBLICAR E FINALIZAR</button><button class="btn" onclick="refreshFinalChecklist()">Revisar checklist</button></div><div class="notice warn" style="margin-top:12px">Neste estágio, “Publicar e finalizar” confirma e registra o fluxo no LAMOU Music Promoter. O disparo automático real para redes depende das integrações OAuth/API que estamos preparando.</div><div id="finalStamp" class="final-stamp">Ainda não finalizado nesta sessão.</div>';analytics.parentNode.insertBefore(final,analytics)};
 const stats=analytics?.querySelector('.stats');if(stats&&!document.getElementById('aPublished')){const s=document.createElement('div');s.className='stat';s.innerHTML='<b id="aPublished">0</b><small>Finalizadas</small>';stats.appendChild(s)};
 refreshFinalChecklist();filterChannels();renderHistory();
});