/* LAMOU v7.3 — visual artist dashboard + simple user switcher */
(() => {
'use strict';
const USERS='lamou_users_v6', ACTIVE='lamou_active_user_v6', PROFILE='lamou_artist_profile_v5', PREFIX='lamou_project_v6_';
const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(_){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const users=()=>load(USERS,[]);
function current(){const list=users(),id=localStorage.getItem(ACTIVE)||'';return list.find(u=>u.id===id)||list[0]||null}
function projects(u){return (u?.projects||[]).map(p=>({p,d:load(`${PREFIX}${u.id}_${p.id}`,{})}))}
function breakdown(u){const map={};projects(u).forEach(({d})=>{const g=d.subgenre||d.genre||'Não classificado';map[g]=(map[g]||0)+1});return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function summary(u){const p=load(PROFILE,{}),c=p.catalog||{};const pr=projects(u);let actions=0,camps=0;pr.forEach(({d})=>{const h=d.history||[];actions+=h.length;camps+=h.filter(x=>/campanha/i.test(String(x.action||''))).length});return{albums:Number(c.albums||0),singles:Number(c.singles||0),tracks:Number(c.tracks||0),projects:pr.length,actions,camps,artist:c.artist||u?.name||'Artista',image:c.image||''}}
function hideRedundantArtistStep(){
 const panel=document.getElementById('artistProfilePanel');if(panel)panel.style.display='none';
 const hub=document.getElementById('strategyHub');if(hub){[...hub.querySelectorAll('.strategy-btn')].forEach(b=>{if(/Perfil do artista/i.test(b.textContent))b.style.display='none'});const title=hub.querySelector('.strategy-head p');if(title)title.textContent='Seu perfil já está identificado. Escolha somente o que deseja fazer com esta música.'}
}
function enhanceHome(){
 const home=document.getElementById('lamouHomeV64'),u=current();if(!home||!u)return;const s=summary(u),genres=breakdown(u);
 let old=document.getElementById('artistRealityV73');if(old)old.remove();
 const box=document.createElement('div');box.id='artistRealityV73';box.className='artist-reality-v73';
 const max=Math.max(1,...genres.map(x=>x[1]));
 box.innerHTML=`<div class="artist-reality-head"><div class="artist-reality-id">${s.image?`<img src="${esc(s.image)}" alt="${esc(s.artist)}">`:'<span>♫</span>'}<div><small>VISÃO DO ARTISTA</small><h3>${esc(s.artist)}</h3><p>Resumo automático do perfil e do catálogo já vinculado.</p></div></div><button class="btn" id="switchUserV73">${esc(u.name)} ▾</button></div>
 <div class="artist-real-kpis"><div><b>${s.albums}</b><span>Álbuns</span></div><div><b>${s.singles}</b><span>Singles/EPs</span></div><div><b>${s.tracks}</b><span>Faixas no catálogo</span></div><div><b>${s.projects}</b><span>Trabalhos no LAMOU</span></div><div><b>${s.actions}</b><span>Ações realizadas</span></div><div><b>—</b><span>Streams/visualizações*</span></div></div>
 <div class="artist-style-block"><div><h4>Distribuição por estilo</h4><small>Baseada nas classificações dos seus trabalhos no LAMOU.</small></div><div class="artist-style-list">${genres.length?genres.map(([g,n])=>`<div class="artist-style-row"><div><b>${esc(g)}</b><span>${n} música${n===1?'':'s'}</span></div><div class="artist-style-track"><i style="width:${Math.max(8,Math.round(n/max*100))}%"></i></div></div>`).join(''):'<div class="notice">Ainda não há músicas classificadas por estilo.</div>'}</div></div>
 <div class="artist-data-note">*O Spotify Web API público não entrega contagem total de streams/visualizações do artista. Esse número só deve aparecer quando houver uma fonte autorizada, como Spotify for Artists/relatório importado ou outra integração oficial. O LAMOU não inventa esse dado.</div>`;
 const q=home.querySelector('.lamou-question');home.insertBefore(box,q||home.lastChild);box.querySelector('#switchUserV73').onclick=openSwitcher;
}
function openSwitcher(){
 let m=document.getElementById('userSwitcherV73');if(!m){m=document.createElement('div');m.id='userSwitcherV73';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet user-switch-sheet"><div class="lamou-connect-head"><div><h2>👤 Usuário</h2><p>Continue com o perfil atual, troque ou cadastre outro.</p></div><button>×</button></div><div id="userSwitcherBodyV73"></div></div>`;document.body.appendChild(m);m.querySelector('.lamou-connect-head button').onclick=()=>m.classList.remove('on');m.onclick=e=>{if(e.target===m)m.classList.remove('on')}}
 const list=users(),u=current(),body=m.querySelector('#userSwitcherBodyV73');body.innerHTML=`<div class="current-user-v73"><small>USUÁRIO ATUAL</small><b>${esc(u?.name||'')}</b><span>Perfil mantido automaticamente.</span></div><div class="user-list-v73">${list.filter(x=>x.id!==u?.id).map(x=>`<button data-user="${esc(x.id)}"><b>${esc(x.name)}</b><small>Trocar para este usuário</small></button>`).join('')}</div><div class="lamou-actions"><button class="btn p" id="keepUserV73">Manter ${esc(u?.name||'usuário')}</button><button class="btn" id="newUserV73">＋ Cadastrar novo usuário</button></div>`;
 body.querySelector('#keepUserV73').onclick=()=>m.classList.remove('on');body.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{localStorage.setItem(ACTIVE,b.dataset.user);m.classList.remove('on');location.reload()});body.querySelector('#newUserV73').onclick=()=>{m.classList.remove('on');if(typeof window.openLamouNewUser==='function')window.openLamouNewUser();else alert('Cadastro de novo usuário ainda não carregou.')};m.classList.add('on')
}
function simplifyHeaderUser(){const row=document.querySelector('.top .row');if(!row)return;const chip=[...row.querySelectorAll('button')].find(b=>/👤/.test(b.textContent)||/^LAMOU\b/i.test(b.textContent.trim()));if(chip){const u=current();chip.innerHTML=`👤 ${esc(u?.name||'Usuário')} ▾`;chip.onclick=openSwitcher;chip.title='Trocar ou cadastrar usuário'}}
function newMusicBehavior(){const home=document.getElementById('lamouHomeV64');if(home){const btn=home.querySelector('#homeNew');if(btn)btn.addEventListener('click',()=>setTimeout(()=>{hideRedundantArtistStep();const first=[...document.querySelectorAll('main.grid > section')].find(s=>s.style.display!=='none'&&s.id!=='strategyHub'&&s.id!=='lamouManager');first?.scrollIntoView({behavior:'smooth',block:'start'})},350),{capture:true})}}
function styles(){if(document.getElementById('dashboardV73Styles'))return;const s=document.createElement('style');s.id='dashboardV73Styles';s.textContent=`.artist-reality-v73{margin:18px 0;padding:18px;border:1px solid #e3e6ef;border-radius:18px;background:linear-gradient(145deg,#fff,#f8f9ff)}.artist-reality-head,.artist-reality-id{display:flex;align-items:center;justify-content:space-between;gap:12px}.artist-reality-id{justify-content:flex-start}.artist-reality-id img,.artist-reality-id>span{width:58px;height:58px;border-radius:16px;object-fit:cover;display:grid;place-items:center;background:#5c5ff2;color:#fff;font-size:28px}.artist-reality-id small{font-weight:850;letter-spacing:.1em;color:#686bea}.artist-reality-id h3{margin:2px 0;font-size:1.45rem}.artist-reality-id p{margin:0;color:#687080}.artist-real-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:16px 0}.artist-real-kpis>div{padding:12px;border:1px solid #e5e7ee;border-radius:13px;background:#fff}.artist-real-kpis b,.artist-real-kpis span{display:block}.artist-real-kpis b{font-size:1.5rem}.artist-real-kpis span{font-size:.76rem;color:#687080}.artist-style-block{display:grid;grid-template-columns:220px 1fr;gap:18px;padding-top:14px;border-top:1px solid #e7e9ef}.artist-style-block h4{margin:0 0 3px}.artist-style-block small{color:#687080}.artist-style-list{display:grid;gap:8px}.artist-style-row>div:first-child{display:flex;justify-content:space-between;gap:10px}.artist-style-row span{font-size:.78rem;color:#687080}.artist-style-track{height:8px;background:#eceefa;border-radius:999px;overflow:hidden;margin-top:5px}.artist-style-track i{display:block;height:100%;background:#686bea;border-radius:999px}.artist-data-note{margin-top:14px;font-size:.75rem;color:#737987}.current-user-v73{padding:14px;background:#f7f8ff;border-radius:13px;margin:14px 0}.current-user-v73 small,.current-user-v73 b,.current-user-v73 span{display:block}.current-user-v73 small{color:#686bea;font-weight:850}.current-user-v73 b{font-size:1.25rem;margin:3px 0}.current-user-v73 span{color:#687080}.user-list-v73{display:grid;gap:8px}.user-list-v73 button{padding:12px;border:1px solid #e5e7ee;border-radius:12px;background:#fff;text-align:left}.user-list-v73 b,.user-list-v73 small{display:block}.user-list-v73 small{color:#687080;margin-top:3px}@media(max-width:800px){.artist-real-kpis{grid-template-columns:repeat(3,1fr)}.artist-style-block{grid-template-columns:1fr}.artist-reality-head{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{styles();hideRedundantArtistStep();enhanceHome();simplifyHeaderUser();newMusicBehavior()},1500));
window.openLamouUserSwitcher=openSwitcher;
})();