/* LAMOU Music Promoter v8.1 — simplify user controls + contextual clear */
(() => {
'use strict';
const USERS='lamou_users_v6',ACTIVE='lamou_active_user_v6',AP='lamou_active_project_v6',PREFIX='lamou_project_v6_';
const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(_){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function users(){return load(USERS,[])}
function current(){const id=localStorage.getItem(ACTIVE)||'';const list=users();return list.find(u=>u.id===id)||list[0]||null}
function projectKey(){const u=current(),pid=localStorage.getItem(AP)||'';return u&&pid?`${PREFIX}${u.id}_${pid}`:''}
function removeUserUIFromBody(){
 ['userSwitcherV73','artistProfileModalV71','newUserModalV72'].forEach(id=>document.getElementById(id)?.classList.remove('on'));
 document.querySelectorAll('#lamouHomeV64 #switchUserV73,#lamouHomeV64 #openArtistProfileV71,#lamouHomeV64 #manageConnections').forEach(el=>el.remove());
 document.querySelectorAll('main button').forEach(b=>{if(/Trocar usuário|Cadastrar novo usuário|Novo usuário|Editar usuário|Excluir usuário|Limpar usuário/i.test(b.textContent||''))b.style.display='none'});
}
function openUserMenu(){let m=document.getElementById('userTopMenuV81');if(!m){m=document.createElement('div');m.id='userTopMenuV81';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>👤 Usuário</h2><p>Gerencie o perfil somente aqui.</p></div><button data-close>×</button></div><div id="userTopBodyV81"></div></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.classList.remove('on');m.onclick=e=>{if(e.target===m)m.classList.remove('on')}}const u=current(),list=users();const body=m.querySelector('#userTopBodyV81');body.innerHTML=`<div class="v81-current"><small>USUÁRIO ATUAL</small><b>${esc(u?.name||'Usuário')}</b></div><div class="v81-user-actions"><button class="btn p" id="keepV81">Manter ${esc(u?.name||'usuário')}</button><button class="btn" id="switchV81">Trocar usuário</button><button class="btn" id="addV81">＋ Cadastrar usuário</button><button class="btn" id="editV81">✎ Modificar usuário</button></div><div id="userSwitchListV81" class="v81-user-list" style="display:none">${list.filter(x=>x.id!==u?.id).map(x=>`<button data-uid="${esc(x.id)}"><b>${esc(x.name)}</b><small>Usar este perfil</small></button>`).join('')||'<div class="notice">Nenhum outro usuário cadastrado.</div>'}</div>`;body.querySelector('#keepV81').onclick=()=>m.classList.remove('on');body.querySelector('#switchV81').onclick=()=>{const x=body.querySelector('#userSwitchListV81');x.style.display=x.style.display==='none'?'grid':'none'};body.querySelectorAll('[data-uid]').forEach(b=>b.onclick=()=>{localStorage.setItem(ACTIVE,b.dataset.uid);m.classList.remove('on');location.reload()});body.querySelector('#addV81').onclick=()=>{m.classList.remove('on');if(typeof window.openLamouNewUser==='function')window.openLamouNewUser();else simpleNewUser()};body.querySelector('#editV81').onclick=()=>editUser();m.classList.add('on')}
function simpleNewUser(){const name=prompt('Nome do novo usuário/artista:');if(!name?.trim())return;const list=users(),id='user_'+Date.now().toString(36);list.push({id,name:name.trim(),createdAt:new Date().toISOString(),projects:[]});save(USERS,list);localStorage.setItem(ACTIVE,id);location.reload()}
function editUser(){const u=current();if(!u)return;const name=prompt('Nome do usuário:',u.name||'');if(!name?.trim())return;const list=users(),i=list.findIndex(x=>x.id===u.id);if(i<0)return;list[i].name=name.trim();save(USERS,list);location.reload()}
function header(){const row=document.querySelector('.top .row');if(!row)return;let ub=document.getElementById('userTopV81');const u=current();if(!ub){ub=document.createElement('button');ub.id='userTopV81';row.prepend(ub)}ub.textContent=`👤 ${u?.name||'Usuário'}`;ub.onclick=openUserMenu;ub.title='Trocar, cadastrar ou modificar usuário';[...row.querySelectorAll('button')].forEach(b=>{if(b!==ub&&(/👤/.test(b.textContent)||/^LAMOU\b/i.test(b.textContent.trim())))b.style.display='none'});}
function resetSection(section){if(!section)return;section.querySelectorAll('input').forEach(i=>{if(i.type==='file')i.value='';else if(i.type==='checkbox'||i.type==='radio')i.checked=false;else i.value=i.defaultValue||''});section.querySelectorAll('select').forEach(s=>s.selectedIndex=0);section.querySelectorAll('textarea').forEach(t=>t.value='');section.querySelectorAll('.on').forEach(x=>{if(!x.classList.contains('panel'))x.classList.remove('on')});}
function addClearButtons(){document.querySelectorAll('main.grid > section.card').forEach((s,idx)=>{if(s.id==='lamouHomeV64'||s.id==='analytics'||s.id==='hosting'||s.querySelector('.v81-clear'))return;const h=s.querySelector('h2');if(!h)return;const b=document.createElement('button');b.className='btn v81-clear';b.textContent='🧹 Limpar';b.title='Limpar apenas esta caixa';b.onclick=()=>{if(confirm(`Limpar os dados desta seção?`)){resetSection(s);toast('Seção limpa.')}};const holder=h.parentElement?.classList.contains('row')?h.parentElement:h.parentElement;holder?.appendChild(b);});}
function clearCurrentMusic(){if(!confirm('Limpar todos os dados da música atual e começar esta música do zero?'))return;const k=projectKey();if(k)localStorage.removeItem(k);localStorage.removeItem('lamou');location.reload()}
function homeActions(){const home=document.getElementById('lamouHomeV64');if(!home)return;const actions=home.querySelector('.lamou-home-actions');if(!actions)return;if(!document.getElementById('homeClearV81')){const b=document.createElement('button');b.id='homeClearV81';b.innerHTML='<span>🧹</span><b>Limpar música atual</b><small>Zera somente os dados do trabalho atual.</small>';b.onclick=clearCurrentMusic;actions.appendChild(b)}}
function keepTestOnlyTop(){document.querySelectorAll('main button').forEach(b=>{if(/Rodar teste|Teste do sistema|🧪 Teste/i.test(b.textContent||''))b.style.display='none'});const row=document.querySelector('.top .row');if(!row)return;const test=[...row.querySelectorAll('button')].find(b=>/Teste/i.test(b.textContent));if(test)test.style.display=''}
function toast(m){if(typeof window.toast==='function')window.toast(m);else console.log(m)}
function styles(){if(document.getElementById('v81Styles'))return;const s=document.createElement('style');s.id='v81Styles';s.textContent=`.v81-current{padding:14px;border-radius:13px;background:#f7f8ff;margin:14px 0}.v81-current small,.v81-current b{display:block}.v81-current small{font-size:.72rem;font-weight:850;color:#686bea}.v81-current b{font-size:1.25rem;margin-top:3px}.v81-user-actions{display:flex;gap:8px;flex-wrap:wrap}.v81-user-list{gap:8px;margin-top:12px}.v81-user-list button{padding:12px;border:1px solid #e5e7ee;border-radius:12px;background:#fff;text-align:left}.v81-user-list b,.v81-user-list small{display:block}.v81-user-list small{color:#687080}.v81-clear{float:right;margin-left:10px;font-size:.76rem;padding:6px 9px!important}.lamou-home-actions{grid-template-columns:repeat(4,1fr)!important}@media(max-width:850px){.lamou-home-actions{grid-template-columns:1fr 1fr!important}}@media(max-width:560px){.lamou-home-actions{grid-template-columns:1fr!important}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{styles();removeUserUIFromBody();header();homeActions();addClearButtons();keepTestOnlyTop()},1900));
window.openLamouUserMenu=openUserMenu;
})();