(() => {
'use strict';

const STORE='lamou_v10_db';
const SESSION='lamou_v10_session';
const GENRES={
  'Pop':['Pop','Indie Pop','Electropop','Latin Pop'],
  'Rock':['Rock','Indie Rock','Alternative Rock','Hard Rock'],
  'Sertanejo':['Sertanejo','Universitário','Romântico','Raiz'],
  'Forró':['Forró','Piseiro','Xote','Baião'],
  'Gospel':['Adoração','Pentecostal','Gospel Pop','Worship','Gospel animado','Christian Hip Hop'],
  'Funk':['Funk BH','Mandelão','Funk Pop'],
  'Pagode / Samba':['Pagode','Pagode romântico','Samba'],
  'Axé':['Axé','Samba-reggae','Afropop baiano'],
  'Eletrônica':['House','EDM','Techno','Dance'],
  'Hip Hop / Rap':['Hip Hop','Rap','Trap'],
  'R&B / Soul':['R&B','Soul','Neo Soul'],
  'Latino':['Reggaeton','Latin Pop','Cumbia','Bachata'],
  'MPB':['MPB','Bossa Nova'],
  'Outros':['Folk','Jazz','Lo-fi','Reggae','Afrobeats','Country']
};
const SOCIAL=['Instagram','TikTok','YouTube Shorts','Facebook','Threads'];
const WEB_SEED=[
  {id:'siqa',name:'SIQA AI Music Chart',type:'Ranking IA',country:'Global',lang:'EN',cost:'Revisar',ai:'Aceita IA',status:'yellow',url:'https://www.thesiqa.com/siqa-chart-submission',verified:'2026-08-14'},
  {id:'soundplate-ai',name:'Soundplate — AI Generated',type:'Playlist / submissão',country:'Global',lang:'EN',cost:'Grátis',ai:'Aceita IA',status:'green',url:'https://play.soundplate.com/',verified:'2026-08-14'},
  {id:'soundplate',name:'Soundplate',type:'Playlist / submissão',country:'Global',lang:'EN',cost:'Grátis',ai:'Revisar política',status:'yellow',url:'https://soundplate.com/submit-music-to-playlists/',verified:'2026-08-14'},
  {id:'daily',name:'DailyPlaylists',type:'Playlist / diretório',country:'Global',lang:'EN',cost:'Grátis + planos',ai:'Revisar por playlist',status:'yellow',url:'https://dailyplaylists.com/',verified:'2026-08-14'},
  {id:'indiemono',name:'Indiemono',type:'Curadoria / playlist',country:'Global',lang:'EN',cost:'Grátis',ai:'Não aceita IA gerada',status:'red',url:'https://indiemono.com/',verified:'2026-08-14'},
  {id:'submithub',name:'SubmitHub',type:'Blogs / curadores',country:'Global',lang:'EN',cost:'Misto',ai:'Depende do canal',status:'yellow',url:'https://www.submithub.com/',verified:'2026-08-14'}
];

function defaults(){return {accounts:{},current:null,profile:{displayName:'LAMOU',email:'',adCode:'',artistUrl:'',artistName:'',artistImage:'',artistStats:null,localAI:false},connections:{spotify:'red',instagram:'red',tiktok:'red',youtube:'red',facebook:'red',threads:'red',amuse:'yellow'},history:[],draft:null,radar:[],webChannels:WEB_SEED,ai:{provider:'heurística local',quota:null,resetAt:null},tests:[]};}
function db(){try{return Object.assign(defaults(),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch(_){return defaults()}}
let state=db();
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function id(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}
function fmtDate(x){try{return new Date(x).toLocaleString('pt-BR')}catch(_){return x||'—'}}
function currentAccount(){return state.current?state.accounts[state.current]:null}
function showApp(on){document.getElementById('loginShell').classList.toggle('hidden',on);document.getElementById('appShell').classList.toggle('hidden',!on)}
function root(){return document.getElementById('appRoot')}
function nav(show=true){document.getElementById('bottomNav').classList.toggle('hidden',!show)}
function markNav(view){document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('on',b.dataset.view===view))}

async function pbkdf2(password,saltB64){const enc=new TextEncoder();const salt=saltB64?Uint8Array.from(atob(saltB64),c=>c.charCodeAt(0)):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:150000},key,256);const hash=btoa(String.fromCharCode(...new Uint8Array(bits)));return {salt:btoa(String.fromCharCode(...salt)),hash}}

function renderAuth(mode='login'){
  const box=document.getElementById('authView');
  const tabs=`<div class="auth-tabs"><button class="${mode==='login'?'on':''}" onclick="Lamou.auth('login')">Entrar</button><button class="${mode==='register'?'on':''}" onclick="Lamou.auth('register')">Primeiro acesso</button><button class="${mode==='forgot'?'on':''}" onclick="Lamou.auth('forgot')">Esqueci a senha</button></div>`;
  if(mode==='login')box.innerHTML=`${tabs}<h1 class="auth-title">Bem-vindo ao LAMOU</h1><p class="auth-sub">Entre com seu usuário e senha.</p><div class="field"><label>Usuário ou e-mail</label><input id="loginUser" autocomplete="username"></div><div class="field"><label>Senha</label><input id="loginPass" type="password" autocomplete="current-password" onkeydown="if(event.key==='Enter')Lamou.login()"></div><label class="row mini" style="color:#cbd3e5;margin:4px 0 12px"><input id="rememberDevice" type="checkbox" style="width:auto"> Lembrar este aparelho</label><button class="primary-button wide" onclick="Lamou.login()">Entrar</button><div id="authError" class="auth-error"></div><div class="auth-note">A versão publicada usa hash PBKDF2 no modo local. A autenticação centralizada e recuperação por e-mail entram no backend Cloudflare.</div>`;
  else if(mode==='register')box.innerHTML=`${tabs}<h1 class="auth-title">Criar acesso</h1><p class="auth-sub">Cadastre o usuário deste perfil.</p><div class="field"><label>Nome</label><input id="regName"></div><div class="field"><label>E-mail</label><input id="regEmail" type="email"></div><div class="field"><label>Usuário</label><input id="regUser"></div><div class="field"><label>Nova senha</label><input id="regPass" type="password"></div><div class="field"><label>Confirmar senha</label><input id="regPass2" type="password"></div><button class="primary-button wide" onclick="Lamou.register()">Cadastrar</button><div id="authError" class="auth-error"></div><div class="auth-note">Senha não é salva em texto puro. O e-mail de verificação será ativado no backend de produção.</div>`;
  else box.innerHTML=`${tabs}<h1 class="auth-title">Recuperar acesso</h1><p class="auth-sub">Informe o e-mail cadastrado.</p><div class="field"><label>E-mail</label><input id="forgotEmail" type="email"></div><button class="primary-button wide" onclick="Lamou.forgot()">Enviar recuperação</button><div id="authError" class="auth-error"></div><div class="auth-note">O envio real de e-mail depende do serviço de autenticação no backend. O app não finge que enviou quando a integração não existe.</div>`;
}

async function login(){const u=document.getElementById('loginUser').value.trim().toLowerCase(),p=document.getElementById('loginPass').value,e=document.getElementById('authError');const key=Object.keys(state.accounts).find(k=>k.toLowerCase()===u||state.accounts[k].email?.toLowerCase()===u);if(!key){e.textContent='Usuário não encontrado.';return}const a=state.accounts[key],h=await pbkdf2(p,a.salt);if(h.hash!==a.hash){e.textContent='Senha incorreta.';return}state.current=key;save();sessionStorage.setItem(SESSION,key);if(document.getElementById('rememberDevice').checked)localStorage.setItem(SESSION,key);bootUser()}
async function register(){const name=document.getElementById('regName').value.trim(),email=document.getElementById('regEmail').value.trim().toLowerCase(),user=document.getElementById('regUser').value.trim(),p=document.getElementById('regPass').value,p2=document.getElementById('regPass2').value,e=document.getElementById('authError');if(!name||!email||!user||p.length<8){e.textContent='Preencha os campos e use senha com pelo menos 8 caracteres.';return}if(p!==p2){e.textContent='As senhas não conferem.';return}if(state.accounts[user]){e.textContent='Esse usuário já existe.';return}const h=await pbkdf2(p);state.accounts[user]={name,email,salt:h.salt,hash:h.hash,createdAt:new Date().toISOString()};state.current=user;state.profile.displayName=name;state.profile.email=email;save();sessionStorage.setItem(SESSION,user);bootUser()}
function forgot(){const email=document.getElementById('forgotEmail').value.trim();document.getElementById('authError').textContent=email?'Recuperação por e-mail ainda precisa da conexão do backend Cloudflare. Nenhum e-mail falso foi enviado.':'Informe o e-mail.'}
function logout(){sessionStorage.removeItem(SESSION);localStorage.removeItem(SESSION);state.current=null;save();showApp(false);nav(false);renderAuth('login')}

function bootUser(){const a=currentAccount();if(!a){logout();return}showApp(true);document.getElementById('headerUser').textContent=a.name||state.current;nav(true);go('home');refreshRemoteProfile();}

function pageHead(kicker,title,sub){return `<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div></div>`}
function home(){markNav('');const stats=summary();const artist=state.profile.artistStats;root().innerHTML=`${pageHead('PAINEL','Olá, '+(currentAccount()?.name||'LAMOU'),'Seu perfil artístico primeiro; desempenho do LAMOU logo abaixo.')}
<div class="grid">
<section class="card span7 artist-card"><div class="row between"><div class="artist-top"><div class="artist-avatar">${state.profile.artistImage?`<img src="${esc(state.profile.artistImage)}" alt="">`:'L'}</div><div><h2>${esc(state.profile.artistName||'Perfil do artista')}</h2><p class="sub">${state.profile.artistUrl?'Perfil conectado':'Conecte Spotify/distribuidora no seu usuário para carregar o catálogo.'}</p></div></div><span class="status ${state.connections.spotify==='green'?'green':'red'}">${state.connections.spotify==='green'?'● conectado':'● não conectado'}</span></div><div class="metric-strip"><div><b>${artist?.albums??'—'}</b><small>Álbuns</small></div><div><b>${artist?.tracks??'—'}</b><small>Músicas</small></div><div><b>${artist?.topTrack?esc(artist.topTrack):'—'}</b><small>Mais forte disponível</small></div><div><b>${artist?.streams??'—'}</b><small>Streams verificados</small></div></div><div class="notice" style="margin-top:12px">O app só mostra métricas que a fonte conectada realmente fornece. Dados privados indisponíveis aparecem como “—”.</div></section>
<section class="card span5 dashboard-card"><h2>Dashboard LAMOU</h2><p class="sub">Somente ações finalizadas entram aqui.</p><div class="stats"><div class="stat"><b>${stats.total}</b><small>Finalizadas</small></div><div class="stat"><b>${stats.quick}</b><small>Rápidas</small></div><div class="stat"><b>${stats.campaign}</b><small>Campanhas</small></div><div class="stat"><b>${stats.web}</b><small>Web</small></div></div><div class="spark">${[35,48,30,63,52,78,60,72].map(v=>`<i style="height:${v}%"></i>`).join('')}</div></section>
<section class="card"><div class="row between"><div><h2>Começar</h2><p class="sub">Três áreas, sem misturar os fluxos.</p></div></div><div class="mode-grid"><button class="choice-card" onclick="Lamou.go('new')"><span class="choice-icon">＋</span><strong>Nova música</strong><small>Divulgação rápida, campanha ou divulgação na Web.</small></button><button class="choice-card" onclick="Lamou.go('history')"><span class="choice-icon">◷</span><strong>Histórico</strong><small>Resultados e registros concluídos.</small></button><button class="choice-card" onclick="Lamou.go('radar')"><span class="choice-icon">◎</span><strong>Radar</strong><small>Avaliação técnica de IA do seu catálogo.</small></button></div></section></div>`}
function summary(){return {total:state.history.length,quick:state.history.filter(x=>x.mode==='quick').length,campaign:state.history.filter(x=>x.mode==='campaign').length,web:state.history.filter(x=>x.mode==='web').length}}

function go(view){markNav(view);if(view==='home')home();else if(view==='new')renderNew();else if(view==='history')renderHistory();else if(view==='radar')renderRadar()}
function freshDraft(mode){return {id:id(),mode,step:2,status:'draft',createdAt:new Date().toISOString(),url:'',title:'',artist:'',cover:'',genre:'Pop',subgenre:'Pop',mood:'Dançante',production:'assist',creative:'auto',creativePreview:'',creativeKind:'',hooks:[],hook:null,audioFeatures:null,message:'',hashtags:'',channels:[],strategy:null,strategies:[],plan:[],webSelected:[]}}
function startMode(mode){state.draft=freshDraft(mode);save();renderNew()}
function discardDraft(){state.draft=null;save();renderNew()}
function renderNew(){markNav('new');if(!state.draft){root().innerHTML=`${pageHead('NOVA MÚSICA','O que você quer fazer?','Escolha primeiro o tipo. Só depois aparecem as etapas necessárias.')}
<div class="mode-grid"><button class="choice-card" onclick="Lamou.startMode('quick')"><span class="choice-icon">🚀</span><strong>Divulgação rápida</strong><small>Uma publicação direta, simples e revisada antes de finalizar.</small></button><button class="choice-card" onclick="Lamou.startMode('campaign')"><span class="choice-icon">📅</span><strong>Campanha</strong><small>Três estratégias de IA e plano completo da campanha escolhida.</small></button><button class="choice-card" onclick="Lamou.startMode('web')"><span class="choice-icon">🌐</span><strong>Divulgação na Web</strong><small>Sites, blogs, revistas, playlists, rankings IA e outros canais permitidos.</small></button></div>`;return}const d=state.draft;let body='';if(d.step===2)body=stepSong(d);else if(d.step===3)body=stepCreative(d);else if(d.step===4)body=stepHook(d);else if(d.mode==='quick'&&d.step===5)body=stepMessage(d);else if(d.mode==='quick'&&d.step===6)body=stepChannels(d);else if(d.mode==='quick'&&d.step===7)body=stepReview(d);else if(d.mode==='campaign'&&d.step===5)body=stepStrategies(d);else if(d.mode==='campaign'&&d.step===6)body=stepCampaignReview(d);else if(d.mode==='web'&&d.step===5)body=stepWeb(d);else if(d.mode==='web'&&d.step===6)body=stepWebReview(d);root().innerHTML=`${pageHead('NOVA MÚSICA',modeName(d.mode),'Rascunho automático ativo. Ele não entra no Histórico nem no Dashboard.')}${body}`}
function modeName(m){return m==='quick'?'Divulgação rápida':m==='campaign'?'Campanha':'Divulgação na Web'}
function back(){if(!state.draft)return;state.draft.step=Math.max(2,state.draft.step-1);save();renderNew()}
function next(step){state.draft.step=step;save();renderNew()}
function actions(nextStep,label='Continuar'){return `<div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><div class="row"><button class="ghost-button" onclick="Lamou.discardDraft()">Descartar rascunho</button><button class="primary-button" onclick="Lamou.next(${nextStep})">${esc(label)} →</button></div></div>`}
function genreOptions(sel){return Object.keys(GENRES).map(g=>`<option ${g===sel?'selected':''}>${esc(g)}</option>`).join('')}
function subOptions(g,sel){return (GENRES[g]||[]).map(s=>`<option ${s===sel?'selected':''}>${esc(s)}</option>`).join('')}
function stepSong(d){return `<div class="wizard"><section class="card wizard-card step-blue"><div class="step-no">Etapa 1 · Música</div><h2>Qual faixa vamos trabalhar?</h2><p class="sub">Cole o link do Spotify. O nome, artista e capa são carregados quando disponíveis.</p><div class="row"><div class="field" style="flex:1;margin:0"><label>Link da música</label><input id="songUrl" value="${esc(d.url)}" placeholder="https://open.spotify.com/track/..."></div><button class="primary-button" onclick="Lamou.loadTrack()">Buscar</button></div>${d.title?`<div class="track-preview" style="margin-top:12px">${d.cover?`<img src="${esc(d.cover)}" alt="">`:''}<div><b>${esc(d.title)}</b><small>${esc(d.artist)}</small></div></div>`:''}</section><section class="card wizard-card step-green"><div class="step-no">Etapa 2 · Identidade</div><h2>Como essa música se encaixa?</h2><div class="two" style="margin-top:12px"><div class="field"><label>Gênero</label><select id="genre" onchange="Lamou.genreChanged()">${genreOptions(d.genre)}</select></div><div class="field"><label>Subgênero</label><select id="subgenre">${subOptions(d.genre,d.subgenre)}</select></div><div class="field"><label>Clima</label><select id="mood"><option>Dançante</option><option>Emocional</option><option>Espiritual</option><option>Romântico</option><option>Sexy</option><option>Intenso</option><option>Chill</option></select></div><div class="field"><label>Produção</label><select id="production"><option value="human">Humana</option><option value="assist" selected>Humana + IA assistida</option><option value="ai">IA gerada / human-directed AI</option></select></div></div>${actions(3)}</section></div>`}
async function loadTrack(){const d=state.draft,url=document.getElementById('songUrl').value.trim();if(!url)return toast('Cole o link da música.');d.url=url;try{const r=await fetch('https://open.spotify.com/oembed?url='+encodeURIComponent(url));if(!r.ok)throw 0;const x=await r.json();d.title=x.title||'Faixa Spotify';d.artist=(x.author_name||'').replace('Spotify','').trim();d.cover=x.thumbnail_url||'';toast('Música carregada.')}catch(_){d.title='Faixa pelo link';d.artist='';toast('Link salvo. Metadados não ficaram disponíveis agora.')}save();renderNew()}
function genreChanged(){const d=state.draft;d.genre=document.getElementById('genre').value;d.subgenre=(GENRES[d.genre]||[])[0]||'';save();renderNew()}
function syncIdentity(){const d=state.draft;if(document.getElementById('genre'))d.genre=document.getElementById('genre').value;if(document.getElementById('subgenre'))d.subgenre=document.getElementById('subgenre').value;if(document.getElementById('mood'))d.mood=document.getElementById('mood').value;if(document.getElementById('production'))d.production=document.getElementById('production').value;save()}
function stepCreative(d){return `<section class="card wizard-card step-lilac"><div class="step-no">Criativo</div><h2>Qual imagem ou vídeo vai representar a faixa?</h2><p class="sub">A IA pode sugerir o caminho; você também pode usar a capa ou enviar mídia.</p><div class="creative-options"><button class="creative-option ${d.creative==='auto'?'on':''}" onclick="Lamou.creative('auto')">✨<b> IA escolher</b><small>Usa contexto da música.</small></button><button class="creative-option ${d.creative==='spotify'?'on':''}" onclick="Lamou.creative('spotify')">🎵<b> Capa Spotify</b><small>Usa a capa carregada.</small></button><button class="creative-option ${d.creative==='image'?'on':''}" onclick="Lamou.creative('image')">🖼️<b> Nova imagem</b><small>Envie uma arte.</small></button><button class="creative-option ${d.creative==='video'?'on':''}" onclick="Lamou.creative('video')">🎬<b> Novo vídeo</b><small>Envie um vídeo.</small></button></div><div class="two" style="margin-top:12px"><div class="field"><label>Imagem</label><input type="file" accept="image/*" onchange="Lamou.media(event,'image')"></div><div class="field"><label>Vídeo</label><input type="file" accept="video/*" onchange="Lamou.media(event,'video')"></div></div><div class="creative-stage" style="margin-top:12px">${d.creativePreview?(d.creativeKind==='video'?`<video src="${esc(d.creativePreview)}" autoplay muted loop playsinline></video>`:`<img src="${esc(d.creativePreview)}" alt="">`):d.cover?`<img src="${esc(d.cover)}" alt="">`:'Prévia do criativo'}<div class="creative-overlay"><b>${esc(d.title||'Sua música')}</b><small>${esc(d.genre+' · '+d.subgenre)}</small></div></div>${actions(4)}</section>`}
function creative(type){const d=state.draft;d.creative=type;if(type==='spotify'&&d.cover){d.creativePreview=d.cover;d.creativeKind='image'}if(type==='auto'&&!d.creativePreview&&d.cover){d.creativePreview=d.cover;d.creativeKind='image'}save();renderNew()}
function media(ev,kind){const f=ev.target.files?.[0];if(!f)return;const d=state.draft;d.creative=kind;d.creativeKind=kind;d.creativePreview=URL.createObjectURL(f);d.mediaName=f.name;save();renderNew()}
function stepHook(d){return `<section class="card wizard-card step-peach"><div class="row between"><div><div class="step-no">Hook</div><h2>Qual trecho chama mais atenção?</h2></div><span class="status ${d.hook?'green':'gray'}">${d.hook?'Hook escolhido':'Aguardando áudio'}</span></div><p class="sub">Envie a faixa. A análise local sugere três trechos; você escolhe um.</p><div class="field"><label>Arquivo de áudio</label><input type="file" accept="audio/*" onchange="Lamou.analyseHook(event)"></div><div class="hook-list" style="margin-top:12px">${d.hooks.length?d.hooks.map((h,i)=>`<button class="hook-item ${d.hook?.start===h.start?'on':''}" onclick="Lamou.pickHook(${i})"><b>Opção ${i+1} · ${h.start}s–${h.end}s</b><small>${esc(h.reason)}</small></button>`).join(''):'<div class="notice">Envie o áudio para gerar as três opções.</div>'}</div>${actions(d.mode==='quick'?5:d.mode==='campaign'?5:5,d.mode==='campaign'?'Criar estratégias':d.mode==='web'?'Selecionar Web':'Criar mensagem')}</section>`}
async function analyseHook(ev){const f=ev.target.files?.[0];if(!f)return;toast('Analisando áudio no aparelho…');try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const buf=await ctx.decodeAudioData(await f.arrayBuffer());const data=buf.getChannelData(0),dur=buf.duration,win=Math.min(20,Math.max(10,dur/8)),count=80,scores=[];for(let k=0;k<count;k++){const start=(dur-win)*k/(count-1),a=Math.floor(start*buf.sampleRate),b=Math.min(data.length,Math.floor((start+win)*buf.sampleRate));let sum=0,peak=0;const step=Math.max(1,Math.floor((b-a)/8000));for(let i=a;i<b;i+=step){const v=Math.abs(data[i]);sum+=v*v;peak=Math.max(peak,v)}const rms=Math.sqrt(sum/Math.max(1,(b-a)/step));const pos=start/dur;const score=rms*100+peak*18+(pos>.18&&pos<.75?5:0);scores.push({start,score,rms,peak})}scores.sort((a,b)=>b.score-a.score);const chosen=[];for(const s of scores){if(chosen.every(c=>Math.abs(c.start-s.start)>win*.8)){chosen.push(s);if(chosen.length===3)break}}state.draft.hooks=chosen.map((s,i)=>({start:Math.round(s.start),end:Math.round(Math.min(dur,s.start+win)),reason:i===0?'Maior combinação de energia e impacto':i===1?'Boa dinâmica e posição na faixa':'Alternativa forte com contraste'}));state.draft.audioFeatures={duration:dur,rms:chosen[0]?.rms||0,peak:chosen[0]?.peak||0,name:f.name};if(!state.draft.hook)state.draft.hook=state.draft.hooks[0];await ctx.close();save();renderNew()}catch(e){toast('Não foi possível analisar esse áudio.') }}
function pickHook(i){state.draft.hook=state.draft.hooks[i];save();renderNew()}

async function aiText(kind,context){const payload={kind,context};try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){const x=await r.json();state.ai.provider=x.provider||'Cloudflare AI';state.ai.quota=x.quota??state.ai.quota;state.ai.resetAt=x.resetAt??state.ai.resetAt;save();return x.text||x.result}}catch(_){}
if(state.profile.localAI){try{if(globalThis.LanguageModel?.create){const lm=await LanguageModel.create();const out=await lm.prompt('Responda em português de forma curta. '+JSON.stringify(payload));state.ai.provider='IA do aparelho';save();return out}}catch(_){}}
state.ai.provider='heurística local';save();if(kind==='copy')return `${context.title||'Nova música'} chegou com ${context.genre||'uma identidade própria'}. ${context.mood||'Energia'} para ouvir agora.\n\n#${String(context.genre||'musica').replace(/\W/g,'')} #NovaMusica #LAMOU #OuçaAgora`;if(kind==='strategy')return null;return ''}
async function generateMessage(){syncIdentity();const d=state.draft;const text=await aiText('copy',d);const parts=String(text||'').split(/\n\n+/);d.message=parts[0]||text;d.hashtags=parts.slice(1).join(' ')||'#LAMOU #NovaMusica';save();renderNew()}
function stepMessage(d){return `<section class="card wizard-card step-yellow"><div class="row between"><div><div class="step-no">Mensagem</div><h2>Descrição e hashtags</h2></div><span class="ai-source">IA: ${esc(state.ai.provider)}</span></div><p class="sub">A IA usa música, estilo, produção, criativo e hook para escrever a divulgação.</p><div class="row"><button class="primary-button" onclick="Lamou.generateMessage()">✨ Criar com IA</button>${state.ai.resetAt?`<span class="status yellow">Crédito volta: ${esc(fmtDate(state.ai.resetAt))}</span>`:''}</div><div class="field" style="margin-top:12px"><label>Descrição</label><textarea id="messageText" oninput="Lamou.editMessage()">${esc(d.message)}</textarea></div><div class="field"><label>Hashtags</label><textarea id="hashtagsText" oninput="Lamou.editMessage()">${esc(d.hashtags)}</textarea></div>${actions(6,'Escolher canais')}</section>`}
function editMessage(){state.draft.message=document.getElementById('messageText').value;state.draft.hashtags=document.getElementById('hashtagsText').value;save()}
function stepChannels(d){return `<section class="card wizard-card step-cyan"><div class="step-no">Canais</div><h2>Onde você quer divulgar?</h2><div class="row" style="margin:10px 0"><button class="ghost-button" onclick="Lamou.selectAllSocial()">✓ Selecionar todos</button></div><div class="channel-list">${SOCIAL.map(c=>`<button class="channel-item ${d.channels.includes(c)?'on':''}" onclick="Lamou.toggleSocial('${c}')"><b>${esc(c)}</b><small>${state.connections[providerKey(c)]==='green'?'Conectado':'Precisa conectar'}</small><span class="status ${state.connections[providerKey(c)]==='green'?'green':'red'}">${state.connections[providerKey(c)]==='green'?'OK':'Off'}</span><span>${d.channels.includes(c)?'✓':'＋'}</span></button>`).join('')}</div>${actions(7,'Revisar')}</section>`}
function providerKey(c){return c==='Instagram'?'instagram':c==='TikTok'?'tiktok':c.startsWith('YouTube')?'youtube':c==='Facebook'?'facebook':'threads'}
function toggleSocial(c){const a=state.draft.channels,i=a.indexOf(c);i<0?a.push(c):a.splice(i,1);save();renderNew()}
function selectAllSocial(){state.draft.channels=[...SOCIAL];save();renderNew()}
function reviewCommon(d){return `<div class="review-grid"><div class="review-block"><b>Música</b>${esc(d.title||'Link informado')}<small>${esc(d.genre+' · '+d.subgenre)}</small></div><div class="review-block"><b>Hook</b>${d.hook?`${d.hook.start}s–${d.hook.end}s`:'Não definido'}</div><div class="review-block"><b>Criativo</b>${esc(d.creative)}</div><div class="review-block"><b>IA</b>${esc(state.ai.provider)}</div></div>`}
function stepReview(d){return `<section class="card wizard-card step-cyan"><div class="step-no">Revisão final</div><h2>Confira antes de publicar</h2>${reviewCommon(d)}<div class="review-block" style="margin-top:10px"><b>Mensagem</b>${esc(d.message)}<small>${esc(d.hashtags)}</small></div><div class="review-block" style="margin-top:10px"><b>Canais</b>${d.channels.map(esc).join(', ')||'Nenhum'}</div><div class="notice warn" style="margin-top:12px">Só entra no Histórico e no Dashboard depois de publicação confirmada e salvamento. Se a publicação externa falhar, o registro não será contado como concluído.</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="publish-button" onclick="Lamou.publishCurrent()">🚀 PUBLICAR E SALVAR</button></div></section>`}

async function generateStrategies(){const d=state.draft;const ai=await aiText('strategy',d);d.strategies=ai&&Array.isArray(ai)?ai:[{id:1,name:'Campanha 1 · Impacto curto',why:'Concentrar atenção nos primeiros dias.',days:7,intensity:'Alta',channels:['Instagram','TikTok','YouTube Shorts']},{id:2,name:'Campanha 2 · Construção',why:'Criar repetição gradual e testar diferentes mensagens.',days:14,intensity:'Normal',channels:['Instagram','TikTok','Facebook','Threads']},{id:3,name:'Campanha 3 · Catálogo',why:'Alongar a presença e trabalhar públicos diferentes.',days:30,intensity:'Leve',channels:['Instagram','YouTube Shorts','Facebook','Threads']}];save();renderNew()}
function chooseStrategy(i){const d=state.draft;d.strategy=d.strategies[i];const s=d.strategy;d.plan=Array.from({length:Math.min(8,Math.max(4,Math.ceil(s.days/3)))},(_,k)=>({day:Math.round(1+k*(s.days-1)/Math.max(1,Math.min(7,k+1))),channel:s.channels[k%s.channels.length],type:k%3===0?'Hook principal':k%3===1?'Criativo alternativo':'Reforço / CTA',copy:`${d.title||'A faixa'} · publicação ${k+1}`}));save();renderNew()}
function stepStrategies(d){if(!d.strategies.length)return `<section class="card wizard-card step-yellow"><div class="step-no">Estratégia</div><h2>A IA vai criar três campanhas</h2><p class="sub">Cada uma deve ter objetivo, duração, intensidade, canais e lógica diferentes.</p><button class="primary-button" onclick="Lamou.generateStrategies()">✨ Criar Campanha 1, 2 e 3</button>${actions(4,'Voltar ao hook')}</section>`;return `<section class="card wizard-card step-yellow"><div class="step-no">Estratégia</div><h2>Escolha a melhor estratégia</h2><div class="strategy-list" style="margin-top:12px">${d.strategies.map((s,i)=>`<button class="strategy-item ${d.strategy?.id===s.id?'on':''}" onclick="Lamou.chooseStrategy(${i})"><b>${esc(s.name)}</b><small>${esc(s.why)} · ${s.days} dias · ${esc(s.intensity)}</small></button>`).join('')}</div>${d.strategy?`<div class="notice" style="margin-top:12px"><b>Plano escolhido:</b> ${esc(d.strategy.name)}. A próxima tela mostra cada item.</div>`:''}<div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="primary-button" ${d.strategy?'':'disabled'} onclick="Lamou.next(6)">Ver plano completo →</button></div></section>`}
function stepCampaignReview(d){return `<section class="card wizard-card step-cyan"><div class="step-no">Plano completo</div><h2>${esc(d.strategy?.name||'Campanha')}</h2>${reviewCommon(d)}<div class="history-list" style="margin-top:12px">${d.plan.map((p,i)=>`<div class="history-item"><div><b>Item ${i+1} · Dia ${p.day}</b><small>${esc(p.type)}</small></div><span>${esc(p.channel)}</span><span>${esc(p.copy)}</span><span class="status blue">planejado</span></div>`).join('')}</div><div class="notice warn" style="margin-top:12px">Campanha só entra no Histórico depois de PUBLICAR E SALVAR com confirmação das plataformas.</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="publish-button" onclick="Lamou.publishCurrent()">🚀 PUBLICAR E SALVAR</button></div></section>`}

function toggleWeb(idv){const a=state.draft.webSelected,i=a.indexOf(idv);i<0?a.push(idv):a.splice(i,1);save();renderNew()}
function selectAllWeb(){state.draft.webSelected=state.webChannels.filter(x=>x.status!=='red').map(x=>x.id);save();renderNew()}
function stepWeb(d){return `<section class="card wizard-card step-yellow"><div class="row between"><div><div class="step-no">Web</div><h2>Escolha os canais externos</h2></div><span class="status green">Revalidação: 10 dias</span></div><p class="sub">Revistas, blogs, sites, curadores, playlists, diretórios e rankings IA. Vermelho não é selecionável.</p><div class="row"><button class="ghost-button" onclick="Lamou.selectAllWeb()">✓ Selecionar permitidos/revisáveis</button></div><div class="channel-list" style="margin-top:12px">${state.webChannels.map(c=>`<button class="channel-item ${d.webSelected.includes(c.id)?'on':''}" ${c.status==='red'?'disabled':''} onclick="Lamou.toggleWeb('${c.id}')"><div><b>${esc(c.name)}</b><small>${esc(c.type)} · ${esc(c.country)} · verificado ${esc(c.verified)}</small></div><span>${esc(c.cost)}</span><span>${esc(c.ai)}</span><span class="status ${c.status}">${c.status==='green'?'Permitido':c.status==='yellow'?'Revisar':'Não usar'}</span></button>`).join('')}</div><div class="notice" style="margin-top:12px">O pitch será adaptado por destino. Sem spam, bypass de CAPTCHA/login, compra de streams ou promessa de playlist garantida.</div>${actions(6,'Revisar envios')}</section>`}
function stepWebReview(d){const selected=state.webChannels.filter(c=>d.webSelected.includes(c.id));return `<section class="card wizard-card step-cyan"><div class="step-no">Revisão Web</div><h2>Plano de divulgação externa</h2>${reviewCommon(d)}<div class="history-list" style="margin-top:12px">${selected.map(c=>`<div class="history-item"><div><b>${esc(c.name)}</b><small>${esc(c.type)}</small></div><span>${esc(c.country)}</span><span>${esc(c.cost)}</span><span class="status ${c.status}">${c.status==='green'?'Pronto':'Revisar'}</span></div>`).join('')||'<div class="empty">Nenhum canal selecionado.</div>'}</div><div class="notice warn" style="margin-top:12px">Sites que exigem login, CAPTCHA ou submissão manual não serão automatizados indevidamente. O app só marca como enviado quando houver confirmação.</div><div class="wizard-actions"><button class="ghost-button" onclick="Lamou.back()">← Voltar</button><button class="publish-button" onclick="Lamou.publishCurrent()">🌐 ENVIAR/PUBLICAR E SALVAR</button></div></section>`}

async function publishCurrent(){const d=state.draft;if(!d)return;let target=[];if(d.mode==='quick')target=d.channels.map(providerKey);if(d.mode==='campaign')target=(d.strategy?.channels||[]).map(providerKey);const missing=target.filter(k=>state.connections[k]!=='green');if(d.mode!=='web'&&missing.length){toast('Há canais sem conexão. Nada foi salvo no Histórico.');openUser();return}try{const r=await fetch('/api/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(r.ok){const res=await r.json();if(res.ok===false)throw new Error('publish');complete(d,res);return}}catch(_){}
if(d.mode==='web'){toast('A integração de envio Web ainda precisa do backend; nada foi marcado como concluído.');return}toast('Backend de publicação ainda não está conectado; nada entrou no Histórico.')}
function complete(d,res={}){state.history.unshift({id:id(),mode:d.mode,title:d.title||'Música',artist:d.artist||'',date:new Date().toISOString(),status:'published',channels:d.mode==='web'?d.webSelected:d.mode==='campaign'?(d.strategy?.channels||[]):d.channels,metrics:res.metrics||{clicks:0,unique:0,countries:[],devices:[]},aiComment:res.aiComment||'Aguardando dados suficientes para avaliar a efetividade.',strategy:d.strategy||null,log:res.log||[]});if(d.audioFeatures)state.radar.push({id:id(),title:d.title||d.audioFeatures.name,genre:d.genre,subgenre:d.subgenre,features:d.audioFeatures,score:technicalScore(d.audioFeatures),version:new Date().toISOString()});state.draft=null;save();toast('Publicado e salvo.');home()}

function renderHistory(){markNav('history');root().innerHTML=`${pageHead('HISTÓRICO','Somente o que foi finalizado','Rascunhos e processos abandonados não aparecem aqui.')}<section class="card"><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item"><div><b>${esc(h.title)}</b><small>${fmtDate(h.date)} · ${esc(modeName(h.mode))}</small></div><span class="status green">${esc(h.status)}</span><span>${(h.metrics?.clicks||0)} cliques</span><div class="history-actions"><button onclick="Lamou.viewHistory('${h.id}')">Ver</button><button onclick="Lamou.removeHistory('${h.id}')">Remover</button></div></div>`).join(''):'<div class="empty">Ainda não há ações publicadas e salvas.</div>'}</div></section>`}
function viewHistory(hid){const h=state.history.find(x=>x.id===hid);if(!h)return;modal(`<div class="modal-head"><div><h2>${esc(h.title)}</h2><p class="sub">${esc(modeName(h.mode))} · ${fmtDate(h.date)}</p></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="stats"><div class="stat"><b>${h.metrics?.clicks||0}</b><small>Cliques</small></div><div class="stat"><b>${h.metrics?.unique||0}</b><small>Únicos</small></div><div class="stat"><b>${h.metrics?.countries?.length||0}</b><small>Países</small></div><div class="stat"><b>${h.channels?.length||0}</b><small>Canais</small></div></div><div class="notice" style="margin-top:12px"><b>Comentário da IA</b><br>${esc(h.aiComment||'Aguardando dados.')}</div><h3 style="margin-top:16px">Log de publicação</h3><div class="test-list" style="margin-top:8px">${h.log?.length?h.log.map(l=>`<div class="test-item"><b>${esc(l.channel)}</b><span class="status ${l.ok?'green':'red'}">${l.ok?'Publicado':'Falhou'}</span><small>${esc(l.message||'')}</small></div>`).join(''):'<div class="empty">Sem log externo disponível.</div>'}</div><div class="notice warn" style="margin-top:12px">Remover do Histórico não significa apagar uma publicação externa. Exclusão externa só deve acontecer pela API oficial da plataforma quando suportada.</div>`)}
function removeHistory(hid){if(!confirm('Remover este registro do Histórico do LAMOU?'))return;state.history=state.history.filter(x=>x.id!==hid);save();renderHistory()}

function technicalScore(f){const rms=Math.min(100,(f.rms||.12)*420);const peak=Math.min(100,(f.peak||.8)*100);const duration=Math.max(45,100-Math.abs((f.duration||180)-190)/2.5);return Math.round(rms*.35+peak*.25+duration*.2+78*.2)}
function renderRadar(){markNav('radar');const list=[...state.radar].sort((a,b)=>b.score-a.score);root().innerHTML=`${pageHead('RADAR TÉCNICO','Como suas músicas se posicionam tecnicamente?','Sem SIQA, plays, likes, votos ou popularidade. Apenas avaliação técnica de IA e referências do mesmo estilo quando a base estiver conectada.')}<section class="card"><div class="row between"><div><h2>Analisar novas versões</h2><p class="sub">A IA identifica o estilo quando possível; você não precisa escolher um ranking externo.</p></div><span class="ai-source">IA: ${esc(state.ai.provider)}</span></div><div class="field"><label>Áudios para análise técnica</label><input type="file" accept="audio/*" multiple onchange="Lamou.radarFiles(event)"></div><div class="notice" style="margin-top:10px">Brasil/global serão exibidos apenas quando houver uma base técnica de referência real no AI Engine/Vectorize. O app não inventa posição mundial.</div></section><section class="card" style="margin-top:14px"><h2>Ranking técnico do seu catálogo</h2><div class="radar-list" style="margin-top:12px">${list.length?list.map((r,i)=>radarRow(r,i)).join(''):'<div class="empty">Ainda não há análises técnicas salvas.</div>'}</div></section>`}
function radarRow(r,i){const p=Math.min(100,Math.max(0,r.score));return `<div class="radar-item"><div class="row between"><div><b>${i+1}º · ${esc(r.title)}</b><small>${esc(r.genre||'Estilo em análise')} · versão ${fmtDate(r.version)}</small></div><span class="radar-score">${p}/100</span></div><div class="radar-bars"><div class="radar-bar"><span>Produção</span><i style="--v:${Math.min(100,p+3)}%"></i><b>${Math.min(100,p+3)}</b></div><div class="radar-bar"><span>Dinâmica</span><i style="--v:${Math.max(0,p-6)}%"></i><b>${Math.max(0,p-6)}</b></div><div class="radar-bar"><span>Hook</span><i style="--v:${Math.max(0,p-2)}%"></i><b>${Math.max(0,p-2)}</b></div><div class="radar-bar"><span>Identidade</span><i style="--v:${Math.min(100,p+5)}%"></i><b>${Math.min(100,p+5)}</b></div></div><div class="notice" style="margin-top:10px">${p>=85?'Faixa tecnicamente forte. Próximo passo: comparar com benchmarks reais do mesmo estilo.':p>=70?'Boa base técnica, com espaço para melhorar dinâmica e impacto.':'A análise sugere revisar produção, dinâmica e definição do hook antes de comparar globalmente.'}</div></div>`}
async function radarFiles(ev){const files=[...(ev.target.files||[])];for(const f of files){try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const b=await ctx.decodeAudioData(await f.arrayBuffer()),d=b.getChannelData(0),step=Math.max(1,Math.floor(d.length/30000));let sum=0,peak=0;for(let i=0;i<d.length;i+=step){const v=Math.abs(d[i]);sum+=v*v;peak=Math.max(peak,v)}const n=Math.ceil(d.length/step),features={duration:b.duration,rms:Math.sqrt(sum/n),peak,name:f.name};const style=await inferStyle(f.name,features);state.radar.push({id:id(),title:f.name.replace(/\.[^.]+$/,''),genre:style,features,score:technicalScore(features),version:new Date().toISOString()});await ctx.close()}catch(_){toast('Um dos áudios não pôde ser analisado.')}}save();renderRadar()}
async function inferStyle(name,features){try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'classify-style',context:{name,features}})});if(r.ok){const x=await r.json();return x.style||'Não classificado'}}catch(_){}const n=name.toLowerCase();if(n.includes('funk'))return'Funk';if(n.includes('gospel')||n.includes('adora'))return'Gospel';if(n.includes('samba')||n.includes('pagode'))return'Pagode / Samba';if(n.includes('axe')||n.includes('axé'))return'Axé';return'Não classificado'}

function openUser(){const c=state.connections;modal(`<div class="modal-head"><div><div class="eyebrow">USUÁRIO</div><h2>${esc(currentAccount()?.name||'LAMOU')}</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="two"><div class="field"><label>Nome</label><input id="profileName" value="${esc(state.profile.displayName||'')}"></div><div class="field"><label>E-mail</label><input id="profileEmail" value="${esc(state.profile.email||currentAccount()?.email||'')}"></div><div class="field"><label>Código AD</label><input id="profileAD" value="${esc(state.profile.adCode||'')}" placeholder="Código AD / identificação"></div><div class="field"><label>Perfil do artista</label><input id="profileArtist" value="${esc(state.profile.artistUrl||'')}" placeholder="Link do perfil"></div></div><label class="row mini" style="margin:7px 0 13px"><input id="localAI" type="checkbox" style="width:auto" ${state.profile.localAI?'checked':''}> Autorizar IA disponível no aparelho como fallback quando a IA gratuita online não estiver disponível.</label><div class="row"><button class="primary-button" onclick="Lamou.saveUser()">Salvar usuário</button><button class="ghost-button" onclick="Lamou.changePasswordModal()">Mudar senha</button><button class="ghost-button" onclick="Lamou.connectAll()">Conectar todos</button></div><h3 style="margin-top:18px">Conexões</h3><div class="connection-grid" style="margin-top:9px">${Object.keys(c).map(k=>connectionCard(k,c[k])).join('')}</div><div class="notice" style="margin-top:12px">“Conectar todos” inicia as autorizações uma a uma. Plataformas que exigem consentimento próprio não podem ser autorizadas silenciosamente.</div>`)}
function connectionCard(k,s){const names={spotify:'Spotify',instagram:'Instagram',tiktok:'TikTok',youtube:'YouTube',facebook:'Facebook',threads:'Threads',amuse:'Amuse / distribuidora'};return `<div class="connection"><div class="row between"><b>${esc(names[k]||k)}</b><span class="status ${s}">${s==='green'?'Conectado':s==='yellow'?'Aguardando':'Não conectado'}</span></div><small>${s==='green'?'Autorização válida':s==='yellow'?'Integração/renovação pendente':'OAuth necessário'}</small><div class="connection-actions"><button onclick="Lamou.connect('${k}')">Conectar</button></div></div>`}
function saveUser(){state.profile.displayName=document.getElementById('profileName').value.trim();state.profile.email=document.getElementById('profileEmail').value.trim();state.profile.adCode=document.getElementById('profileAD').value.trim();state.profile.artistUrl=document.getElementById('profileArtist').value.trim();state.profile.localAI=document.getElementById('localAI').checked;save();document.getElementById('headerUser').textContent=state.profile.displayName||currentAccount()?.name;closeModal();refreshRemoteProfile();toast('Usuário salvo.')}
function connect(provider){fetch(`/api/oauth/${encodeURIComponent(provider)}/start`,{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(x=>{if(x.url)location.href=x.url;else toast('Conexão indisponível.')}).catch(()=>toast(`${provider}: backend OAuth ainda não conectado.`))}
async function connectAll(){for(const k of Object.keys(state.connections)){if(state.connections[k]!=='green'){toast(`Próxima autorização: ${k}`);connect(k);break}}}
function changePasswordModal(){modal(`<div class="modal-head"><h2>Mudar senha</h2><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div class="field"><label>Senha atual</label><input id="oldPass" type="password"></div><div class="field"><label>Nova senha</label><input id="newPass" type="password"></div><div class="field"><label>Confirmar nova senha</label><input id="newPass2" type="password"></div><button class="primary-button" onclick="Lamou.changePassword()">Alterar senha</button><div id="passMsg" class="mini" style="margin-top:8px"></div>`)}
async function changePassword(){const a=currentAccount(),old=document.getElementById('oldPass').value,n=document.getElementById('newPass').value,n2=document.getElementById('newPass2').value,msg=document.getElementById('passMsg');const h=await pbkdf2(old,a.salt);if(h.hash!==a.hash){msg.textContent='Senha atual incorreta.';return}if(n.length<8||n!==n2){msg.textContent='Nova senha inválida ou confirmação diferente.';return}const nh=await pbkdf2(n);a.salt=nh.salt;a.hash=nh.hash;save();msg.textContent='Senha alterada.'}

async function refreshRemoteProfile(){try{const r=await fetch('/api/profile/summary',{credentials:'include'});if(!r.ok)return;const x=await r.json();if(x.artist){state.profile.artistName=x.artist.name||state.profile.artistName;state.profile.artistImage=x.artist.image||'';state.profile.artistStats=x.artist.stats||null}if(x.connections)state.connections={...state.connections,...x.connections};save();if(!document.getElementById('appShell').classList.contains('hidden')&&document.querySelector('.artist-card'))home()}catch(_){}}

async function runTests(){const tests=[
 ['Interface principal',()=>!!document.getElementById('appRoot')],
 ['Criptografia do navegador',()=>!!crypto?.subtle],
 ['Persistência local',()=>{localStorage.setItem('lamou_test','1');const ok=localStorage.getItem('lamou_test')==='1';localStorage.removeItem('lamou_test');return ok}],
 ['Áudio / Web Audio',()=>!!(window.AudioContext||window.webkitAudioContext)],
 ['PWA / Service Worker',()=>('serviceWorker'in navigator)],
 ['Rascunho automático',()=>state.draft===null||state.draft.status==='draft'],
 ['Regra do Histórico',()=>state.history.every(x=>x.status==='published')],
 ['Conexões registradas',()=>Object.keys(state.connections).length>=5],
 ['Backend',async()=>{try{const r=await fetch('/api/health',{cache:'no-store'});return r.ok}catch(_){return false}}],
 ['IA online',async()=>{try{const r=await fetch('/api/ai/health',{cache:'no-store'});return r.ok}catch(_){return false}}]
];
modal(`<div class="modal-head"><div><div class="eyebrow">DIAGNÓSTICO</div><h2>Rodando testes…</h2></div><button class="icon-button" onclick="Lamou.closeModal()">×</button></div><div id="testResults" class="test-list"></div>`);const out=document.getElementById('testResults');for(const [name,fn] of tests){let ok=false;try{ok=await fn()}catch(_){ok=false}const el=document.createElement('div');el.className='test-item';el.innerHTML=`<b>${esc(name)}</b><span class="status ${ok?'green':'red'}">${ok?'OK':'Falhou'}</span><small>${ok?'Funcionando':'Precisa de configuração/correção'}</small>`;out.appendChild(el)} }

function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)Lamou.closeModal()"><section class="modal">${html}</section></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}

const Lamou={auth:renderAuth,login,register,forgot,logout,go,startMode,discardDraft,back,next,loadTrack,genreChanged,creative,media,analyseHook,pickHook,generateMessage,editMessage,toggleSocial,selectAllSocial,generateStrategies,chooseStrategy,toggleWeb,selectAllWeb,publishCurrent,viewHistory,removeHistory,radarFiles,openUser,saveUser,connect,connectAll,changePasswordModal,changePassword,runTests,closeModal};
window.Lamou=Lamou;

window.addEventListener('beforeunload',()=>{if(state.draft){syncIdentity();save()}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
const remembered=sessionStorage.getItem(SESSION)||localStorage.getItem(SESSION);if(remembered&&state.accounts[remembered]){state.current=remembered;bootUser()}else{showApp(false);renderAuth('login')}
})();
