/* LAMOU v7.2 — automatic artist profile + catalog + simple user registration */
(() => {
'use strict';
const USERS_KEY='lamou_users_v6',ACTIVE_USER_KEY='lamou_active_user_v6',PROFILE_KEY='lamou_artist_profile_v5',TOKEN_KEY='lamou_spotify_pkce_v2';
const LAMOU_ARTIST_ID='1fEv1hrrhccjjUP3vpOQk4';
const LAMOU_ARTIST_URL=`https://open.spotify.com/artist/${LAMOU_ARTIST_ID}`;
const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(_){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function currentUser(){const users=load(USERS_KEY,[]),id=localStorage.getItem(ACTIVE_USER_KEY)||'';return users.find(u=>u.id===id)||users[0]||null}
function isLamou(u){return String(u?.name||'').trim().toUpperCase()==='LAMOU'}
function ensureArtistIdentity(){const u=currentUser();if(!u)return;let users=load(USERS_KEY,[]),i=users.findIndex(x=>x.id===u.id);if(i>=0&&isLamou(u)){users[i].spotifyArtistId=LAMOU_ARTIST_ID;users[i].spotifyArtistProfile=LAMOU_ARTIST_URL;save(USERS_KEY,users)}let p=load(PROFILE_KEY,{});if(isLamou(u)){p.spotifyUrl=LAMOU_ARTIST_URL;p.verifiedArtistId=LAMOU_ARTIST_ID;save(PROFILE_KEY,p)}const input=document.getElementById('artistSpotifyUrl');if(input&&isLamou(u)){input.value=LAMOU_ARTIST_URL;input.closest('.field')?.style.setProperty('display','none');try{window.artistLinkChanged?.()}catch(_){}}}
async function directTopTracks(){const t=load(TOKEN_KEY,null);if(!t?.access_token)return[];try{const r=await fetch(`https://api.spotify.com/v1/artists/${LAMOU_ARTIST_ID}/top-tracks?market=BR`,{headers:{Authorization:'Bearer '+t.access_token}});if(!r.ok)return[];const d=await r.json();return d.tracks||[]}catch(_){return[]}}
async function refreshSpotifyCatalog(){ensureArtistIdentity();const u=currentUser();if(!isLamou(u))return;const p=load(PROFILE_KEY,{});const token=load(TOKEN_KEY,null);if(token){try{const input=document.getElementById('artistSpotifyUrl');if(input)input.value=LAMOU_ARTIST_URL;await window.confirmArtistProfile?.()}catch(_){}}setTimeout(updateHomeSpotifySummary,700)}
function catalog(){return load(PROFILE_KEY,{}).catalog||null}
async function updateHomeSpotifySummary(){const home=document.getElementById('lamouHomeV64'),u=currentUser();if(!home||!isLamou(u))return;const c=catalog(),top=await directTopTracks();let block=document.getElementById('spotifySummaryV72');if(!block){block=document.createElement('div');block.id='spotifySummaryV72';block.className='spotify-summary-v72';const q=home.querySelector('.lamou-question');home.insertBefore(block,q)}if(!c){block.innerHTML=`<div class="spotify-summary-head"><div><small>SPOTIFY DO ARTISTA</small><h3>LAMOU</h3></div><button class="btn p" id="syncLamouV72">↻ Sincronizar Spotify</button></div><div class="notice">Seu perfil artístico já está vinculado. Conecte/autorize o Spotify uma vez para carregar automaticamente discografia e métricas do catálogo.</div>`;block.querySelector('#syncLamouV72').onclick=()=>window.startSpotifyAuth?.();return}const releases=c.recent||[];block.innerHTML=`<div class="spotify-summary-head"><div><small>SPOTIFY DO ARTISTA</small><h3>${esc(c.artist||'LAMOU')}</h3></div><button class="btn" id="openSpotifyProfileV72">Abrir perfil</button></div><div class="spotify-kpis-v72"><div><b>${Number(c.albums||0)}</b><span>Álbuns</span></div><div><b>${Number(c.singles||0)}</b><span>Singles/EPs</span></div><div><b>${Number(c.tracks||0)}</b><span>Faixas no catálogo</span></div><div><b>${top.length}</b><span>Top faixas lidas</span></div></div><div class="spotify-columns-v72"><div><h4>Lançamentos recentes</h4>${releases.length?releases.slice(0,6).map(x=>`<div class="spotify-row-v72"><b>${esc(x.name)}</b><small>${esc(x.release_date||'')} • ${esc(x.album_type||'')}</small></div>`).join(''):'<div class="notice">Nenhum lançamento carregado.</div>'}</div><div><h4>Mais bem colocadas no Spotify</h4>${top.length?top.slice(0,6).map((x,i)=>`<div class="spotify-row-v72"><b>${i+1}. ${esc(x.name)}</b><small>${Number(x.popularity||0)}/100 de popularidade Spotify</small></div>`).join(''):'<div class="notice">Autorize o Spotify para consultar as faixas mais fortes do perfil.</div>'}</div></div>`;block.querySelector('#openSpotifyProfileV72').onclick=()=>window.open(LAMOU_ARTIST_URL,'_blank','noopener')}
function openNewUser(){let m=document.getElementById('newUserModalV72');if(!m){m=document.createElement('div');m.id='newUserModalV72';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>＋ Cadastrar novo usuário</h2><p>Preencha uma vez. Depois o perfil fica salvo e entra direto.</p></div><button>×</button></div><div class="profile-new-v72"><div class="field"><label>Nome do artista/usuário</label><input id="newUserNameV72" placeholder="Ex.: Fulano"></div><div class="field"><label>Spotify User ID (opcional)</label><input id="newUserSpotifyIdV72" placeholder="ID da conta"></div><div class="field"><label>Perfil artístico Spotify (opcional)</label><input id="newUserArtistV72" placeholder="https://open.spotify.com/artist/..."></div><div class="lamou-actions"><button class="btn p" id="saveNewUserV72">Salvar usuário</button><button class="btn" id="cancelNewUserV72">Cancelar</button></div></div></div>`;document.body.appendChild(m);m.querySelector('.lamou-connect-head button').onclick=()=>m.classList.remove('on');m.querySelector('#cancelNewUserV72').onclick=()=>m.classList.remove('on');m.querySelector('#saveNewUserV72').onclick=()=>{const name=m.querySelector('#newUserNameV72').value.trim();if(!name)return alert('Informe o nome do usuário/artista.');const sid=m.querySelector('#newUserSpotifyIdV72').value.trim(),artist=m.querySelector('#newUserArtistV72').value.trim();const users=load(USERS_KEY,[]),id='user_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);users.push({id,name,spotifyUserId:sid,spotifyProfile:sid?`https://open.spotify.com/user/${sid}`:'',spotifyArtistProfile:artist,createdAt:new Date().toISOString(),projects:[]});save(USERS_KEY,users);localStorage.setItem(ACTIVE_USER_KEY,id);m.classList.remove('on');location.reload()}}m.classList.add('on')}
function openProfile(){let m=document.getElementById('artistProfileModalV71');const u=currentUser(),p=load(PROFILE_KEY,{}),c=p.catalog;if(!u)return;if(!m){m=document.createElement('div');m.id='artistProfileModalV71';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>👤 Perfil do artista</h2><p>Seu perfil já identificado pelo LAMOU.</p></div><button id="profileCloseV71">×</button></div><div id="profileBodyV71"></div></div>`;document.body.appendChild(m);m.querySelector('#profileCloseV71').onclick=()=>m.classList.remove('on')}const artistUrl=isLamou(u)?LAMOU_ARTIST_URL:(u.spotifyArtistProfile||p.spotifyUrl||'');m.querySelector('#profileBodyV71').innerHTML=`<div class="profile-v71-card"><div><small>PERFIL ATIVO</small><h3>${esc(u.name||'Artista')}</h3></div><div class="profile-v71-grid"><div><span>Spotify User ID</span><b>${esc(u.spotifyUserId||'Não informado')}</b></div><div><span>Perfil artístico</span><b>${artistUrl?`<a href="${esc(artistUrl)}" target="_blank" rel="noopener">Abrir Spotify do artista</a>`:'Não vinculado'}</b></div><div><span>Álbuns</span><b>${c?Number(c.albums||0):'—'}</b></div><div><span>Faixas no catálogo</span><b>${c?Number(c.tracks||0):'—'}</b></div></div><div class="lamou-actions"><button class="btn p" id="profileSyncV72">↻ Sincronizar Spotify</button><button class="btn" id="profileConnectionsV71">🔗 Contas conectadas</button><button class="btn" id="profileNewUserV72">＋ Cadastrar novo usuário</button><button class="btn" id="profileHomeV71">Fechar</button></div></div>`;m.querySelector('#profileSyncV72').onclick=()=>refreshSpotifyCatalog();m.querySelector('#profileConnectionsV71').onclick=()=>document.getElementById('manageConnections')?.click();m.querySelector('#profileNewUserV72').onclick=openNewUser;m.querySelector('#profileHomeV71').onclick=()=>m.classList.remove('on');m.classList.add('on')}
function removeDuplicateProfileUI(){const panel=document.getElementById('artistProfilePanel');if(panel)panel.style.display='none';const manager=document.getElementById('lamouManager');if(manager)manager.style.display='none'}
function hook(){ensureArtistIdentity();removeDuplicateProfileUI();const top=document.querySelector('.top .row');if(top){const chip=[...top.querySelectorAll('button')].find(b=>/👤/.test(b.textContent)||/^LAMOU$/i.test(b.textContent.trim()));if(chip){chip.onclick=openProfile;chip.title='Abrir perfil do artista'}}const home=document.getElementById('lamouHomeV64');if(home&&!document.getElementById('openArtistProfileV71')){const w=home.querySelector('.lamou-welcome>div');if(w){const b=document.createElement('button');b.id='openArtistProfileV71';b.className='btn';b.textContent='👤 Perfil';b.onclick=openProfile;w.appendChild(b)}}updateHomeSpotifySummary()}
function styles(){if(document.getElementById('profileV72Styles'))return;const s=document.createElement('style');s.id='profileV72Styles';s.textContent=`.profile-v71-card{padding-top:14px}.profile-v71-card h3{font-size:1.55rem;margin:3px 0 14px}.profile-v71-card>div>small,.spotify-summary-head small{font-weight:850;letter-spacing:.1em;color:#686bea}.profile-v71-grid,.spotify-kpis-v72{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.profile-v71-grid>div,.spotify-kpis-v72>div{padding:12px;border:1px solid #e5e7ee;border-radius:12px;background:#fafbff}.profile-v71-grid span,.profile-v71-grid b,.spotify-kpis-v72 b,.spotify-kpis-v72 span{display:block}.profile-v71-grid span,.spotify-kpis-v72 span{font-size:.77rem;color:#687080;margin-bottom:4px}.spotify-summary-v72{margin:18px 0;padding:16px;border:1px solid #e1e5ef;border-radius:16px;background:#fcfdff}.spotify-summary-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.spotify-summary-head h3{margin:3px 0}.spotify-kpis-v72{margin:13px 0}.spotify-kpis-v72 b{font-size:1.4rem}.spotify-columns-v72{display:grid;grid-template-columns:1fr 1fr;gap:14px}.spotify-row-v72{padding:9px 0;border-bottom:1px solid #eceef3}.spotify-row-v72 b,.spotify-row-v72 small{display:block}.spotify-row-v72 small{color:#687080}.profile-new-v72{display:grid;gap:10px;padding-top:14px}@media(max-width:700px){.profile-v71-grid,.spotify-kpis-v72{grid-template-columns:1fr 1fr}.spotify-columns-v72{grid-template-columns:1fr}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{styles();hook();refreshSpotifyCatalog()},1100));window.openLamouArtistProfile=openProfile;window.openLamouNewUser=openNewUser;
})();