/* LAMOU v7.1 — artist profile entry fix */
(() => {
'use strict';
const USERS_KEY='lamou_users_v6',ACTIVE_USER_KEY='lamou_active_user_v6',PROFILE_KEY='lamou_artist_profile_v5';
const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(_){return f}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function currentUser(){const users=load(USERS_KEY,[]),id=localStorage.getItem(ACTIVE_USER_KEY)||'';return users.find(u=>u.id===id)||users[0]||null}
function openProfile(){let m=document.getElementById('artistProfileModalV71');const u=currentUser(),p=load(PROFILE_KEY,{});if(!u)return;if(!m){m=document.createElement('div');m.id='artistProfileModalV71';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>👤 Perfil do artista</h2><p>Identidade do usuário e dados artísticos salvos.</p></div><button id="profileCloseV71">×</button></div><div id="profileBodyV71"></div></div>`;document.body.appendChild(m);m.querySelector('#profileCloseV71').onclick=()=>m.classList.remove('on');m.onclick=e=>{if(e.target===m)m.classList.remove('on')}}const body=m.querySelector('#profileBodyV71');const artistUrl=p.spotifyUrl||'';body.innerHTML=`<div class="profile-v71-card"><div><small>USUÁRIO</small><h3>${esc(u.name||'Artista')}</h3></div><div class="profile-v71-grid"><div><span>Spotify User ID</span><b>${esc(u.spotifyUserId||'Não informado')}</b></div><div><span>Perfil Spotify do usuário</span><b>${u.spotifyProfile?`<a href="${esc(u.spotifyProfile)}" target="_blank" rel="noopener">Abrir perfil</a>`:'Não informado'}</b></div><div><span>Perfil artístico Spotify</span><b>${artistUrl?`<a href="${esc(artistUrl)}" target="_blank" rel="noopener">Abrir artista</a>`:'Ainda não vinculado'}</b></div><div><span>Status da autorização</span><b>${esc(p.spotifyStatus||'Não conectado')}</b></div></div><div class="lamou-actions"><button class="btn p" id="profileConnectSpotifyV71">${artistUrl?'Reconectar Spotify':'Conectar perfil artístico'}</button><button class="btn" id="profileConnectionsV71">🔗 Contas conectadas</button><button class="btn" id="profileHomeV71">Fechar</button></div><div class="notice" style="margin-top:12px">O seu usuário LAMOU já fica salvo. Para catálogo e métricas de artista, o Spotify exige um endereço do tipo <b>/artist/...</b>; o endereço <b>/user/...</b> identifica a conta do usuário e não substitui o perfil artístico.</div></div>`;body.querySelector('#profileConnectSpotifyV71').onclick=()=>{if(typeof window.startSpotifyAuth==='function')window.startSpotifyAuth();else alert('Integração Spotify ainda não carregou.')};body.querySelector('#profileConnectionsV71').onclick=()=>{const b=document.getElementById('manageConnections');if(b)b.click();else alert('Contas conectadas ainda não carregaram.')};body.querySelector('#profileHomeV71').onclick=()=>m.classList.remove('on');m.classList.add('on')}
function hook(){const top=document.querySelector('.top .row');if(top){const chip=[...top.querySelectorAll('button')].find(b=>/👤/.test(b.textContent)||/LAMOU/i.test(b.textContent));if(chip){chip.onclick=openProfile;chip.title='Abrir perfil do artista'}}const home=document.getElementById('lamouHomeV64');if(home&&!document.getElementById('openArtistProfileV71')){const w=home.querySelector('.lamou-welcome>div');if(w){const b=document.createElement('button');b.id='openArtistProfileV71';b.className='btn';b.textContent='👤 Ver perfil do artista';b.onclick=openProfile;w.appendChild(b)}}}
function styles(){if(document.getElementById('profileV71Styles'))return;const s=document.createElement('style');s.id='profileV71Styles';s.textContent=`.profile-v71-card{padding-top:14px}.profile-v71-card h3{font-size:1.55rem;margin:3px 0 14px}.profile-v71-card>div>small{font-weight:850;letter-spacing:.1em;color:#686bea}.profile-v71-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.profile-v71-grid>div{padding:12px;border:1px solid #e5e7ee;border-radius:12px;background:#fafbff}.profile-v71-grid span,.profile-v71-grid b{display:block}.profile-v71-grid span{font-size:.77rem;color:#687080;margin-bottom:4px}.profile-v71-grid b{word-break:break-word}.profile-v71-grid a{color:#5558d9}@media(max-width:650px){.profile-v71-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{styles();hook()},1000));window.openLamouArtistProfile=openProfile;
})();