/* LAMOU v7.2 — profile entry + fixed top Test loader */
(() => {
'use strict';
const USERS='lamou_users_v6',ACTIVE='lamou_active_user_v6',PROFILE='lamou_artist_profile_v5';
const ARTIST_ID='1fEv1hrrhccjjUP3vpOQk4',ARTIST_URL=`https://open.spotify.com/artist/${ARTIST_ID}`;
const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(_){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function current(){const us=load(USERS,[]),id=localStorage.getItem(ACTIVE)||'';return us.find(x=>x.id===id)||us[0]||null}
function isLamou(u){return String(u?.name||'').trim().toUpperCase()==='LAMOU'}
function ensure(){const u=current();if(!u)return;let us=load(USERS,[]),i=us.findIndex(x=>x.id===u.id);if(i>=0&&isLamou(u)){us[i].spotifyArtistId=ARTIST_ID;us[i].spotifyArtistProfile=ARTIST_URL;save(USERS,us);let p=load(PROFILE,{});p.spotifyUrl=ARTIST_URL;p.verifiedArtistId=ARTIST_ID;save(PROFILE,p)}const input=document.getElementById('artistSpotifyUrl');if(input&&isLamou(u)){input.value=ARTIST_URL;input.closest('.field')?.style.setProperty('display','none')}}
function openNewUser(){let m=document.getElementById('newUserModalV72');if(!m){m=document.createElement('div');m.id='newUserModalV72';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>＋ Novo usuário</h2><p>Cadastre uma vez. Depois o perfil fica salvo.</p></div><button>×</button></div><div class="profile-new-v72"><div class="field"><label>Nome do artista/usuário</label><input id="nuName"></div><div class="field"><label>Spotify User ID</label><input id="nuSid"></div><div class="field"><label>Perfil artístico Spotify</label><input id="nuArtist" placeholder="https://open.spotify.com/artist/..."></div><div class="lamou-actions"><button class="btn p" id="nuSave">Salvar</button><button class="btn" id="nuCancel">Cancelar</button></div></div></div>`;document.body.appendChild(m);m.querySelector('.lamou-connect-head button').onclick=()=>m.classList.remove('on');m.querySelector('#nuCancel').onclick=()=>m.classList.remove('on');m.querySelector('#nuSave').onclick=()=>{const name=m.querySelector('#nuName').value.trim();if(!name)return alert('Informe o nome.');const sid=m.querySelector('#nuSid').value.trim(),artist=m.querySelector('#nuArtist').value.trim(),us=load(USERS,[]),id='user_'+Date.now().toString(36);us.push({id,name,spotifyUserId:sid,spotifyProfile:sid?`https://open.spotify.com/user/${sid}`:'',spotifyArtistProfile:artist,createdAt:new Date().toISOString(),projects:[]});save(USERS,us);localStorage.setItem(ACTIVE,id);location.reload()}}m.classList.add('on')}
function openProfile(){const u=current();if(!u)return;let m=document.getElementById('artistProfileModalV72');if(!m){m=document.createElement('div');m.id='artistProfileModalV72';m.className='lamou-connect-modal';m.innerHTML=`<div class="lamou-connect-sheet"><div class="lamou-connect-head"><div><h2>👤 Perfil do artista</h2><p>Identidade e conexões do perfil ativo.</p></div><button>×</button></div><div id="profileBodyV72"></div></div>`;document.body.appendChild(m);m.querySelector('.lamou-connect-head button').onclick=()=>m.classList.remove('on')}const p=load(PROFILE,{}),c=p.catalog||{},artist=isLamou(u)?ARTIST_URL:(u.spotifyArtistProfile||p.spotifyUrl||'');m.querySelector('#profileBodyV72').innerHTML=`<div class="profile-v72"><small>PERFIL ATIVO</small><h3>${esc(u.name)}</h3><div class="profile-grid-v72"><div><span>Spotify User ID</span><b>${esc(u.spotifyUserId||'Não informado')}</b></div><div><span>Perfil artístico</span><b>${artist?`<a href="${esc(artist)}" target="_blank">Abrir Spotify</a>`:'Não vinculado'}</b></div><div><span>Álbuns</span><b>${c.albums??'—'}</b></div><div><span>Faixas</span><b>${c.tracks??'—'}</b></div></div><div class="lamou-actions"><button class="btn p" id="profileSpotifyV72">↻ Sincronizar Spotify</button><button class="btn" id="profileConnV72">🔗 Contas conectadas</button><button class="btn" id="profileNewV72">＋ Novo usuário</button><button class="btn" id="profileCloseBtnV72">Fechar</button></div></div>`;m.querySelector('#profileSpotifyV72').onclick=()=>window.startSpotifyAuth?.();m.querySelector('#profileConnV72').onclick=()=>document.getElementById('manageConnections')?.click();m.querySelector('#profileNewV72').onclick=openNewUser;m.querySelector('#profileCloseBtnV72').onclick=()=>m.classList.remove('on');m.classList.add('on')}
function hookProfile(){ensure();document.getElementById('artistProfilePanel')?.style.setProperty('display','none');document.getElementById('lamouManager')?.style.setProperty('display','none');const row=document.querySelector('.top .row');if(row){const chip=[...row.querySelectorAll('button')].find(b=>/👤/.test(b.textContent)||/^LAMOU$/i.test(b.textContent.trim()));if(chip){chip.onclick=openProfile;chip.title='Abrir perfil do artista'}}const home=document.getElementById('lamouHomeV64');if(home&&!document.getElementById('openArtistProfileV72')){const w=home.querySelector('.lamou-welcome>div');if(w){const b=document.createElement('button');b.id='openArtistProfileV72';b.className='btn';b.textContent='👤 Perfil';b.onclick=openProfile;w.appendChild(b)}}}
function loadTestCenter(){if(document.querySelector('script[src="header-test-v72.js"]'))return;const s=document.createElement('script');s.src='header-test-v72.js';document.body.appendChild(s)}
function styles(){if(document.getElementById('profileV72Styles'))return;const s=document.createElement('style');s.id='profileV72Styles';s.textContent=`.profile-v72{padding-top:14px}.profile-v72>small{font-weight:850;letter-spacing:.1em;color:#686bea}.profile-v72 h3{font-size:1.55rem;margin:4px 0 14px}.profile-grid-v72{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.profile-grid-v72>div{padding:12px;border:1px solid #e5e7ee;border-radius:12px;background:#fafbff}.profile-grid-v72 span,.profile-grid-v72 b{display:block}.profile-grid-v72 span{font-size:.77rem;color:#687080;margin-bottom:4px}.profile-new-v72{display:grid;gap:10px;padding-top:14px}@media(max-width:700px){.profile-grid-v72{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{styles();hookProfile();loadTestCenter()},1000));
window.openLamouArtistProfile=openProfile;window.openLamouNewUser=openNewUser;
})();