(() => {
'use strict';

const VERSION='13.0.0';
const STORE='lamou_v10_db';
let installPrompt=null;
let realHooks=[];
let hookDuration=20;
const autoGenerated=new Set();

const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch(_){return {}}};
const write=d=>localStorage.setItem(STORE,JSON.stringify(d));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const modal=h=>{const root=document.getElementById('modalRoot');if(root)root.innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)LamouRuntime.close()"><section class="modal">${h}</section></div>`};
const toast=m=>{const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3600)};
async function api(path, options={}){
  try{
    const r=await fetch(path,{credentials:'include',cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});
    let data={};try{data=await r.json()}catch(_){}
    return {ok:r.ok,status:r.status,data};
  }catch(_){return {ok:false,status:0,data:{error:'Sem resposta do servidor.'}}}
}
function close(){const root=document.getElementById('modalRoot');if(root)root.innerHTML=''}
function field(label,id,type='text',extra=''){return `<div class="field"><label>${esc(label)}</label><input id="${id}" type="${type}" ${extra}></div>`}

async function accountMenu(){
  const me=await api('/api/auth/me');
  const user=me.ok?me.data.user:null;
  const local=!!user?.localDevice;
  modal(`<div class="modal-head"><div><div class="eyebrow">LAMOU · v${VERSION}</div><h2>Menu</h2></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
  <div class="notice"><b>${user?esc(user.displayName||user.username):'Sessão não identificada'}</b><br><span class="mini">${local?'Sessão local deste aparelho. Entre na sua conta para manter conexões e histórico entre dispositivos.':user?`@${esc(user.username)}`:'Faça login novamente.'}</span></div>
  <div class="mode-grid" style="margin-top:14px">
    <button class="choice-card" onclick="LamouRuntime.account()"><span class="feature-icon">👤</span><strong>${local?'Entrar / criar conta':'Minha conta'}</strong><small>${local?'Troque a sessão local por seu usuário.':'Sair ou trocar usuário.'}</small></button>
    <button class="choice-card" onclick="LamouRuntime.profile()"><span class="feature-icon">♫</span><strong>Perfil + Spotify</strong><small>Identidade, catálogo e conexão.</small></button>
    <button class="choice-card" onclick="LamouRuntime.diagnostics()"><span class="feature-icon">✓</span><strong>Diagnóstico real</strong><small>Worker, D1, IA, sessão e Spotify.</small></button>
    <button class="choice-card" onclick="LamouRuntime.install()"><span class="feature-icon">⬇</span><strong>Instalar app</strong><small>Adicionar o LAMOU ao celular.</small></button>
  </div>`);
}
function account(){
  api('/api/auth/me').then(me=>{
    const user=me.ok?me.data.user:null;
    if(user&&!user.localDevice){
      modal(`<div class="modal-head"><div><div class="eyebrow">CONTA</div><h2>${esc(user.displayName||user.username)}</h2><p class="sub">@${esc(user.username)} · ${esc(user.email||'')}</p></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
      <div class="row"><button class="primary-button" onclick="LamouRuntime.showLogin()">Trocar usuário</button><button class="ghost-button" onclick="LamouRuntime.logout()">Sair</button></div>`);
    }else showLogin();
  });
}
function showLogin(){
  modal(`<div class="modal-head"><div><div class="eyebrow">CONTA LAMOU</div><h2>Entrar</h2><p class="sub">Seu Spotify e seus dados ficam ligados ao seu usuário, não a uma sessão descartável.</p></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
  ${field('Usuário ou e-mail','rtIdentity')}${field('Senha','rtPassword','password','autocomplete="current-password"')}
  <div class="row"><button class="primary-button" onclick="LamouRuntime.login()">Entrar</button><button class="ghost-button" onclick="LamouRuntime.showRegister()">Criar conta</button></div>
  <button class="link-button" style="margin-top:10px" onclick="LamouRuntime.showForgot()">Esqueci a senha</button>`);
}
function showRegister(){
  modal(`<div class="modal-head"><div><div class="eyebrow">CONTA LAMOU</div><h2>Criar conta</h2></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
  ${field('Nome exibido','rtDisplay')}${field('Usuário','rtUsername')}${field('E-mail','rtEmail','email','autocomplete="email"')}${field('Senha (mín. 8 caracteres)','rtNewPassword','password','autocomplete="new-password"')}
  <div class="row"><button class="primary-button" onclick="LamouRuntime.register()">Criar e entrar</button><button class="ghost-button" onclick="LamouRuntime.showLogin()">Já tenho conta</button></div>`);
}
function showForgot(){
  modal(`<div class="modal-head"><div><div class="eyebrow">RECUPERAÇÃO</div><h2>Redefinir senha</h2></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
  ${field('E-mail','rtForgotEmail','email','autocomplete="email"')}
  <div class="row"><button class="primary-button" onclick="LamouRuntime.forgot()">Solicitar recuperação</button><button class="ghost-button" onclick="LamouRuntime.showLogin()">Voltar</button></div>`);
}
async function login(){
  const identity=document.getElementById('rtIdentity')?.value.trim(),password=document.getElementById('rtPassword')?.value||'';
  if(!identity||!password)return toast('Preencha usuário/e-mail e senha.');
  const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({identity,password})});
  if(!r.ok)return toast(r.data?.error||'Não foi possível entrar.');
  sessionStorage.removeItem('lamou_state_synced_v13');close();toast('Conta conectada.');setTimeout(()=>location.reload(),200);
}
async function register(){
  const displayName=document.getElementById('rtDisplay')?.value.trim(),username=document.getElementById('rtUsername')?.value.trim(),email=document.getElementById('rtEmail')?.value.trim(),password=document.getElementById('rtNewPassword')?.value||'';
  if(!displayName||!username||!email||password.length<8)return toast('Preencha todos os campos; a senha precisa ter ao menos 8 caracteres.');
  const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({displayName,username,email,password})});
  if(!r.ok)return toast(r.data?.error||'Não foi possível criar a conta.');
  sessionStorage.removeItem('lamou_state_synced_v13');close();toast('Conta criada.');setTimeout(()=>location.reload(),200);
}
async function forgot(){
  const email=document.getElementById('rtForgotEmail')?.value.trim();if(!email)return toast('Informe o e-mail.');
  const r=await api('/api/auth/forgot',{method:'POST',body:JSON.stringify({email})});
  toast(r.data?.message||'Se o e-mail estiver cadastrado, a recuperação será processada.');
}
async function logout(){
  await persistState();
  const r=await api('/api/auth/logout',{method:'POST',body:'{}'});
  if(!r.ok)return toast(r.data?.error||'Não foi possível sair.');
  sessionStorage.removeItem('lamou_state_synced_v13');close();setTimeout(()=>location.reload(),150);
}
function profile(){close();window.Lamou?.openUser?.()}

async function diagnostics(){
  modal(`<div class="modal-head"><div><div class="eyebrow">DIAGNÓSTICO REAL</div><h2>Checando o app…</h2></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div><div class="empty">Consultando Worker e serviços.</div>`);
  const [d,ai]=await Promise.all([api('/api/diagnostics'),api('/api/ai/health')]);
  const x=d.data||{};
  const rows=[
    ['Worker v13',d.ok&&x.version===VERSION],
    ['D1',!!x.db?.ready],
    ['Sessão',!!x.session?.authenticated],
    ['Workers AI',!!(x.ai?.bound&&ai.ok)],
    ['Chave de criptografia',!!x.tokenEncryptionKeyConfigured],
    ['Spotify Client ID',!!x.spotifyClientIdConfigured],
    ['Spotify conectado',x.spotify==='connected']
  ];
  modal(`<div class="modal-head"><div><div class="eyebrow">DIAGNÓSTICO REAL</div><h2>Estado do LAMOU</h2><p class="sub">Isto consulta o backend de verdade; não é teste de botão.</p></div><button class="icon-button" onclick="LamouRuntime.close()">×</button></div>
  <div class="test-list">${rows.map(([n,ok])=>`<div class="test-item"><b>${esc(n)}</b><span class="status ${ok?'green':'red'}">${ok?'OK':'Atenção'}</span></div>`).join('')}</div>
  <div class="notice" style="margin-top:12px"><b>Sessão</b><br>${x.session?.authenticated?(x.session.localDevice?'Local do aparelho':esc(x.session.displayName||x.session.username)):'Não autenticada'}<br><span class="mini">Tabelas D1: ${Number(x.db?.tables||0)} · Spotify: ${esc(x.spotify||'indisponível')}</span></div>`);
}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
async function install(){
  if(installPrompt){const p=installPrompt;installPrompt=null;await p.prompt();return}
  toast('Se o botão de instalação do navegador não aparecer, use “Adicionar à tela inicial” no menu do navegador.');
}

function mergeState(remote){
  const local=read();
  const rh=Array.isArray(remote?.history)?remote.history:[], lh=Array.isArray(local.history)?local.history:[];
  const rs=Array.isArray(remote?.suppressed)?remote.suppressed:[], ls=Array.isArray(local.suppressed)?local.suppressed:[];
  const rr=Array.isArray(remote?.rankings)?remote.rankings:[], lr=Array.isArray(local.rankings)?local.rankings:[];
  const union=(a,b,key='id')=>{
    const m=new Map();for(const x of a||[])if(x&&x[key]!=null)m.set(String(x[key]),x);for(const x of b||[])if(x&&x[key]!=null)m.set(String(x[key]),{...(m.get(String(x[key]))||{}),...x});return [...m.values()];
  };
  const next={...local,history:union(rh,lh),suppressed:union(rs,ls,'channelId'),rankings:union(rr,lr)};
  const before=JSON.stringify({history:lh,suppressed:ls,rankings:lr});
  const after=JSON.stringify({history:next.history,suppressed:next.suppressed,rankings:next.rankings});
  if(before!==after){write(next);return true}return false;
}
async function syncState(){
  const me=await api('/api/auth/me');if(!me.ok)return;
  const r=await api('/api/state');if(!r.ok)return;
  const changed=mergeState(r.data?.state||{});
  if(changed&&!sessionStorage.getItem('lamou_state_synced_v13')){
    sessionStorage.setItem('lamou_state_synced_v13','1');location.reload();return;
  }
  await persistState();
}
async function persistState(){
  const d=read();
  return api('/api/state',{method:'PUT',body:JSON.stringify({state:{history:d.history||[],suppressed:d.suppressed||[],rankings:d.rankings||[]}})});
}
function wrapPersistence(name){
  const fn=window.Lamou?.[name];if(typeof fn!=='function'||fn.__v13)return;
  const wrapped=function(...args){const out=fn.apply(this,args);Promise.resolve(out).finally(()=>setTimeout(()=>persistState(),20));return out};
  wrapped.__v13=true;window.Lamou[name]=wrapped;
}

async function enrichTrack(){
  const original=enrichTrack.original;if(!original)return;
  await original();
  const url=document.getElementById('songUrl')?.value.trim();if(!url)return;
  const r=await api('/api/spotify/track?url='+encodeURIComponent(url));
  if(!r.ok)return;
  const t=r.data?.track||{};
  const project=document.getElementById('songProject');if(project&&!project.value.trim()&&t.album)project.value=t.album;
  const story=document.getElementById('songStory');
  if(story&&!story.value.trim()&&t.releaseDate){const type=t.albumType==='single'?'single':t.albumType==='album'?'álbum':t.albumType||'lançamento';story.value=`Faixa do ${type} “${t.album||''}”, lançado em ${t.releaseDate}.`.replace('“”, ','').trim()}
  toast(t.album?`Metadados carregados · ${t.album}`:'Metadados do Spotify carregados.');
}

async function computeRealHooks(file,duration){
  const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return[];
  const ctx=new Ctx();
  try{
    const buf=await ctx.decodeAudioData(await file.arrayBuffer());
    const sr=buf.sampleRate, len=buf.length, channels=buf.numberOfChannels, frame=Math.max(256,Math.floor(sr*.25));
    const env=[];
    for(let i=0;i<len;i+=frame){let sum=0,n=0;for(let j=i;j<Math.min(len,i+frame);j+=16){let s=0;for(let c=0;c<channels;c++)s+=buf.getChannelData(c)[j]||0;s/=Math.max(1,channels);sum+=s*s;n++}env.push(Math.sqrt(sum/Math.max(1,n)))}
    if(!env.length)return[];
    const frames=Math.max(1,Math.round(duration/.25)),step=Math.max(1,Math.round(1/.25)),candidates=[];
    for(let i=0;i<env.length;i+=step){const end=Math.min(env.length,i+frames);if(end-i<Math.max(2,frames*.55))break;let energy=0,transient=0;for(let k=i;k<end;k++){energy+=env[k];if(k>i)transient+=Math.max(0,env[k]-env[k-1])}energy/=(end-i);transient/=Math.max(1,end-i-1);candidates.push({i,energy,transient})}
    const maxE=Math.max(...candidates.map(x=>x.energy),1e-6),maxT=Math.max(...candidates.map(x=>x.transient),1e-6);
    for(const x of candidates)x.score=.72*(x.energy/maxE)+.28*(x.transient/maxT);
    candidates.sort((a,b)=>b.score-a.score);
    const chosen=[];
    for(const x of candidates){const start=x.i*.25;if(chosen.some(y=>Math.abs(y.start-start)<duration*.6))continue;chosen.push({start:Math.round(start*2)/2,end:Math.min(buf.duration,Math.round(start*2)/2+duration),score:x.score});if(chosen.length===3)break}
    return chosen;
  }finally{await ctx.close().catch(()=>{})}
}
async function analyseAudioReal(e){
  const file=e.target.files?.[0];if(!file)return;
  const original=analyseAudioReal.original;if(original)await original(e);
  const d=read().draft;hookDuration=Number(d?.hookDuration||20);
  try{
    realHooks=await computeRealHooks(file,hookDuration);
    if(!realHooks.length)return;
    const input=document.getElementById('manualStart');if(input)input.value=realHooks[0].start;
    window.Lamou?.manualHook?.();
    setTimeout(renderRealHooks,0);
    toast('Hook recalculado pelo áudio real.');
  }catch(_){toast('A análise técnica foi salva, mas não consegui recalcular o hook.')}
}
function renderRealHooks(){
  const list=document.querySelector('.hook-list');if(!list)return;
  if(realHooks.length){list.innerHTML=realHooks.map((h,i)=>`<button class="hook-item ${i===0?'on':''}" onclick="LamouRuntime.useHook(${i})"><div><b>${['Hook principal','Hook alternativo','Hook de apoio'][i]}</b><small>${fmtTime(h.start)}–${fmtTime(h.end)} · energia relativa ${Math.round(h.score*100)}%</small></div><span>Usar</span></button>`).join('');return}
  const d=read().draft;
  const suspicious=Array.isArray(d?.hooks)&&d.hooks.length===3&&d.hooks.every((h,i)=>Math.abs(Number(h.score)-[.86,.78,.72][i])<.0001);
  if(suspicious)list.innerHTML='<div class="empty">Recarregue o áudio para recalcular os hooks com a análise real desta versão.</div>';
}
function fmtTime(s){s=Math.max(0,Math.floor(Number(s)||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function useHook(i){const h=realHooks[i];if(!h)return;const input=document.getElementById('manualStart');if(input)input.value=h.start;window.Lamou?.manualHook?.();setTimeout(()=>{renderRealHooks();document.querySelectorAll('.hook-item').forEach((n,j)=>n.classList.toggle('on',j===i))},0)}

function maybeAutoAI(){
  const step=document.querySelector('.step-no');if(!step||!/^4\s*·\s*IA/.test(step.textContent||''))return;
  const d=read().draft;if(!d||d.description||Number(d.generation||0)>0||autoGenerated.has(d.id))return;
  autoGenerated.add(d.id);setTimeout(()=>window.Lamou?.generateDescription?.(),120);
}
function patchLamou(){
  if(!window.Lamou)return;
  ['approveFinal','markSent','suppressChannel','unsuppress','removeHistory','runRanking'].forEach(wrapPersistence);
  if(!enrichTrack.original&&typeof window.Lamou.loadTrack==='function'){enrichTrack.original=window.Lamou.loadTrack;window.Lamou.loadTrack=enrichTrack}
  if(!analyseAudioReal.original&&typeof window.Lamou.analyseAudio==='function'){analyseAudioReal.original=window.Lamou.analyseAudio;window.Lamou.analyseAudio=analyseAudioReal}
}

document.addEventListener('click',e=>{
  if(e.target.closest('#lamouMenuBtn')){e.preventDefault();e.stopImmediatePropagation();accountMenu()}
},true);

const observer=new MutationObserver(()=>{patchLamou();renderRealHooks();maybeAutoAI()});
observer.observe(document.documentElement,{subtree:true,childList:true});
patchLamou();
setTimeout(syncState,350);
if('serviceWorker' in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.update().catch(()=>{}))).catch(()=>{});

window.LamouRuntime={close,account,showLogin,showRegister,showForgot,login,register,forgot,logout,profile,diagnostics,install,useHook,persistState};
})();
