(() => {
'use strict';
const STORE='lamou_v10_db';
const SESSION='lamou_v10_session';
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch(_){return {}}};
const write=d=>localStorage.setItem(STORE,JSON.stringify(d));
const clean=v=>String(v||'').replace(/[&<>"']/g,'');

function blankWorkspace(account={}){return {profile:{displayName:account.name||'LAMOU',email:account.email||'',artistUrl:'',artistName:'',artistImage:'',artistStats:null},connections:{spotify:'red'},history:[],draft:null,radar:[]}}
function archiveCurrent(data){if(data.current&&data.accounts?.[data.current])data.accounts[data.current].workspace={profile:data.profile||{},connections:{spotify:data.connections?.spotify||'red'},history:Array.isArray(data.history)?data.history:[],draft:data.draft||null,radar:Array.isArray(data.radar)?data.radar:[]}}
function loadWorkspace(data,key){const a=data.accounts[key];const w=a.workspace||blankWorkspace(a);data.profile=w.profile||blankWorkspace(a).profile;data.connections={spotify:w.connections?.spotify||'red'};data.history=Array.isArray(w.history)?w.history:[];data.draft=w.draft||null;data.radar=Array.isArray(w.radar)?w.radar:[];data.current=key;write(data);localStorage.setItem(SESSION,key);sessionStorage.setItem(SESSION,key)}
function bootstrap(){const data=read();if(!data.accounts||typeof data.accounts!=='object')data.accounts={};if(!Object.keys(data.accounts).length)data.accounts['lamou-local']={name:'LAMOU',email:'',createdAt:new Date().toISOString(),localOnly:true};const keys=Object.keys(data.accounts);const current=data.current&&data.accounts[data.current]?data.current:(localStorage.getItem(SESSION)&&data.accounts[localStorage.getItem(SESSION)]?localStorage.getItem(SESSION):keys[0]);if(data.accounts[current]?.workspace)loadWorkspace(data,current);else{data.current=current;const base=blankWorkspace(data.accounts[current]);data.profile={...base.profile,...(data.profile||{})};data.connections={spotify:data.connections?.spotify||'red'};data.history=Array.isArray(data.history)?data.history:[];data.radar=Array.isArray(data.radar)?data.radar:[];write(data);localStorage.setItem(SESSION,current);sessionStorage.setItem(SESSION,current)}}
function modal(html){const r=document.getElementById('modalRoot');if(r)r.innerHTML=`<div class="modal-backdrop" data-close-menu><section class="modal">${html}</section></div>`}
function close(){const r=document.getElementById('modalRoot');if(r)r.innerHTML=''}
function menu(){const d=read(),a=d.accounts?.[d.current]||{};modal(`<div class="modal-head"><div><div class="eyebrow">LAMOU</div><h2>${clean(a.name||d.profile?.displayName||'LAMOU')}</h2><p class="sub">Spotify é a única conexão do app.</p></div><button class="icon-button" data-action="close">×</button></div><div class="mode-grid" style="grid-template-columns:repeat(2,1fr)"><button class="choice-card" data-action="profile"><span class="choice-icon">🎵</span><strong>Perfil + Spotify</strong><small>Editar perfil e conectar o Spotify.</small></button><button class="choice-card" data-action="users"><span class="choice-icon">👤</span><strong>Usuários</strong><small>Trocar ou criar perfil local.</small></button><button class="choice-card" data-action="install"><span class="choice-icon">⬇️</span><strong>Instalar app</strong><small>Adicionar à tela inicial.</small></button><button class="choice-card" data-action="tests"><span class="choice-icon">🧪</span><strong>Teste</strong><small>Checar as funções principais.</small></button></div>`)}
function users(){const d=read();const rows=Object.keys(d.accounts||{}).map(k=>{const a=d.accounts[k],active=k===d.current;return `<button class="channel-item ${active?'on':''}" style="grid-template-columns:1fr auto" data-user-key="${encodeURIComponent(k)}"><div><b>${clean(a.name||k)}</b><small>${clean(a.email||'')}</small></div><span class="status ${active?'green':'gray'}">${active?'Ativo':'Trocar'}</span></button>`}).join('');modal(`<div class="modal-head"><div><div class="eyebrow">USUÁRIOS</div><h2>Perfil local</h2></div><button class="icon-button" data-action="close">×</button></div><div class="channel-list">${rows}</div><div class="row" style="margin-top:14px"><button class="primary-button" data-action="create-user">＋ Novo usuário</button><button class="ghost-button" data-action="edit-user">Editar atual</button></div>`)}
function switchUser(key){const d=read();if(!d.accounts?.[key])return;archiveCurrent(d);loadWorkspace(d,key);location.reload()}
function createUser(){const name=prompt('Nome do artista/usuário:');if(!name?.trim())return;const email=(prompt('E-mail (opcional):','')||'').trim();const d=read();archiveCurrent(d);const key='user_'+Date.now().toString(36);d.accounts[key]={name:name.trim(),email,createdAt:new Date().toISOString(),localOnly:true};d.accounts[key].workspace=blankWorkspace(d.accounts[key]);loadWorkspace(d,key);location.reload()}
function editUser(){const d=read(),a=d.accounts?.[d.current];if(!a)return;const name=prompt('Nome:',a.name||'LAMOU');if(!name?.trim())return;const email=prompt('E-mail:',a.email||'');a.name=name.trim();a.email=String(email??a.email??'').trim();d.profile=d.profile||{};d.profile.displayName=a.name;d.profile.email=a.email;write(d);location.reload()}
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});async function installApp(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice.catch(()=>{});deferredInstall=null;return}alert('No navegador, use a opção “Instalar app” ou “Adicionar à tela inicial”.')}
bootstrap();
window.LamouUserManager={menu,users,close,switchUser,createUser,editUser};window.LamouInstall={install:installApp};
document.addEventListener('click',e=>{if(e.target.closest('#lamouMenuBtn')){menu();return}if(e.target.matches('[data-close-menu]')){close();return}const u=e.target.closest('[data-user-key]');if(u){switchUser(decodeURIComponent(u.dataset.userKey));return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close')close();else if(a==='profile'){close();setTimeout(()=>window.Lamou?.openUser(),0)}else if(a==='users')users();else if(a==='create-user')createUser();else if(a==='edit-user')editUser();else if(a==='tests'){close();setTimeout(()=>window.Lamou?.runTests(),0)}else if(a==='install')installApp()});
})();