/* LAMOU Music Promoter — UX v6.4
   Home = identified user summary + 3 clear choices: New music, History, Market Radar.
   System Test stays only in the top utility area.
   Existing v6.3 functions remain underneath; this layer reorganizes visibility/context.
*/
(() => {
'use strict';
const USERS='lamou_users_v6', ACTIVE='lamou_active_user_v6', AP='lamou_active_project_v6', PREFIX='lamou_project_v6_';
const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(_){return f}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function user(){const id=localStorage.getItem(ACTIVE)||'';return load(USERS,[]).find(x=>x.id===id)||load(USERS,[])[0]||null}
function key(uid,pid){return `${PREFIX}${uid}_${pid}`}
function allProjectData(u){return (u?.projects||[]).map(p=>({p,d:load(key(u.id,p.id),{})}))}
function metrics(u){const a=allProjectData(u);let actions=0,classified=0,campaigns=0,channels=new Set(),hooks=0;for(const {d} of a){const h=d.history||[];actions+=h.length;hooks+=(d.hooks||[]).length;if(d.genre||d.subgenre||d.production)classified++;campaigns+=h.filter(x=>/campanha/i.test(String(x.action||''))).length;h.forEach(x=>{if(x.channel)channels.add(x.channel)})}return{songs:a.length,classified,actions,campaigns,channels:channels.size,hooks}}
function hideWorkspace(){document.querySelectorAll('main.grid > section').forEach(s=>s.style.display='none')}
function showWorkspace(){document.getElementById('lamouHomeV64')?.remove();document.querySelectorAll('main.grid > section').forEach(s=>{if(s.id!=='hosting'&&s.id!=='analytics'&&!/O que é automático hoje\?/i.test(s.textContent))s.style.display='' });window.scrollTo({top:0,behavior:'smooth'})}
function newMusic(){try{if(typeof window.createBlankProject==='function')return window.createBlankProject(true)}catch(_){};const top=[...document.querySelectorAll('.top button')].find(b=>/Nova música/i.test(b.textContent));if(top){top.click();setTimeout(showWorkspace,180)}else showWorkspace()}
function clickHeader(label){const b=[...document.querySelectorAll('.top button')].find(x=>x.textContent.includes(label));if(b)b.click()}
function radar(){let m=document.getElementById('lamouRadarV64');if(!m){m=document.createElement('div');m.id='lamouRadarV64';m.className='lamou-modal';m.innerHTML=`<div class="lamou-sheet"><div class="lamou-head"><div><h2>🌐 Radar de Mercado</h2><p>Visão geral da presença das suas músicas por ranking, categoria e estilo.</p></div><button class="lamou-x">×</button></div><div class="lamou-radar-note"><b>O que o Radar consulta</b><br>SQIA e outros charts/rankings públicos configurados, além dos dados já registrados no LAMOU. Resultados externos só aparecem quando houver fonte verificável — sem inventar posição.</div><div class="lamou-radar-filters"><select id="radarGenre"><option>Todos os estilos</option></select><select id="radarCategory"><option>Todas as categorias</option><option>Geral</option><option>IA</option><option>Brasil</option><option>Por gênero</option></select><button class="btn p" id="radarSearch">🔎 Verificar mercado</button></div><div id="radarOut" class="lamou-empty">Selecione os filtros e toque em <b>Verificar mercado</b>. A busca externa será usada quando o backend/fonte correspondente estiver conectado.</div></div>`;document.body.appendChild(m);m.querySelector('.lamou-x').onclick=()=>m.classList.remove('on');m.onclick=e=>{if(e.target===m)m.classList.remove('on')};const genres=[...new Set(allProjectData(user()).map(x=>x.d.genre).filter(Boolean))];const sel=m.querySelector('#radarGenre');genres.forEach(g=>sel.insertAdjacentHTML('beforeend',`<option>${esc(g)}</option>`));m.querySelector('#radarSearch').onclick=()=>{const u=user(),data=allProjectData(u);const g=sel.value;const rows=data.filter(x=>g==='Todos os estilos'||x.d.genre===g);m.querySelector('#radarOut').innerHTML=rows.length?`<b>${rows.length} música(s) no recorte.</b><br>Dados internos prontos. Rankings externos precisam ser consultados por fonte conectada para mostrar posição atual real.`:'Nenhuma música encontrada neste recorte.'}}m.classList.add('on')}
function home(){const main=document.querySelector('main.grid');if(!main)return;document.getElementById('lamouHomeV64')?.remove();hideWorkspace();const u=user();if(!u)return;const x=metrics(u);const h=document.createElement('section');h.id='lamouHomeV64';h.className='card lamou-home-v64';h.innerHTML=`<div class="lamou-welcome"><div><small>PERFIL ATIVO</small><h2>Olá, ${esc(u.name)}.</h2><p>Seu perfil foi identificado. Aqui está o panorama do seu trabalho antes de começar.</p></div><div class="lamou-profile-dot">♫</div></div><div class="lamou-kpis"><div><b>${x.songs}</b><span>Músicas</span></div><div><b>${x.classified}</b><span>Classificadas</span></div><div><b>${x.actions}</b><span>Ações</span></div><div><b>${x.campaigns}</b><span>Campanhas</span></div><div><b>${x.channels}</b><span>Canais usados</span></div><div><b>${x.hooks}</b><span>Hooks analisados</span></div></div><h3 class="lamou-question">O que você quer fazer agora?</h3><div class="lamou-home-actions"><button id="homeNew"><span>＋</span><b>Nova música</b><small>Começar uma nova análise e divulgação.</small></button><button id="homeHistory"><span>🕘</span><b>Histórico</b><small>Ver seus trabalhos e abrir o resultado de cada um.</small></button><button id="homeRadar"><span>🌐</span><b>Radar de Mercado</b><small>Ver rankings, categorias, estilos e desempenho geral.</small></button></div>`;main.prepend(h);h.querySelector('#homeNew').onclick=()=>{newMusic();showWorkspace()};h.querySelector('#homeHistory').onclick=()=>clickHeader('Histórico');h.querySelector('#homeRadar').onclick=radar}
function header(){const row=document.querySelector('.top .row');if(!row)return;const buttons=[...row.querySelectorAll('button')];buttons.forEach(b=>{if(/Nova música|Histórico/i.test(b.textContent))b.style.display='none'});const test=buttons.find(b=>/Teste/i.test(b.textContent));if(test){test.style.display='';test.title='Teste do sistema'};const u=buttons.find(b=>/👤/.test(b.textContent));if(u)u.onclick=home}
function style(){if(document.getElementById('v64style'))return;const s=document.createElement('style');s.id='v64style';s.textContent=`.lamou-home-v64{grid-column:1/-1!important;padding:24px!important}.lamou-welcome{display:flex;justify-content:space-between;gap:20px;align-items:center}.lamou-welcome small{font-weight:850;letter-spacing:.12em;color:#686bea}.lamou-welcome h2{font-size:2rem;margin:5px 0}.lamou-welcome p{margin:0;color:#687080}.lamou-profile-dot{width:64px;height:64px;border-radius:20px;display:grid;place-items:center;background:#5c5ff2;color:white;font-size:30px;font-weight:900}.lamou-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin:22px 0}.lamou-kpis>div{border:1px solid #e4e7ef;border-radius:15px;padding:13px;background:#fafbff}.lamou-kpis b,.lamou-kpis span{display:block}.lamou-kpis b{font-size:1.55rem}.lamou-kpis span{font-size:.78rem;color:#687080}.lamou-question{margin:25px 0 11px}.lamou-home-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.lamou-home-actions button{text-align:left;padding:18px;border:1px solid #e1e4ee;border-radius:17px;background:white;cursor:pointer;transition:.15s}.lamou-home-actions button:hover{transform:translateY(-2px);box-shadow:0 10px 28px #1111}.lamou-home-actions span,.lamou-home-actions b,.lamou-home-actions small{display:block}.lamou-home-actions span{font-size:1.7rem;margin-bottom:9px}.lamou-home-actions b{font-size:1.05rem}.lamou-home-actions small{color:#687080;margin-top:4px;line-height:1.35}.lamou-radar-note{margin:16px 0;padding:14px;border-radius:13px;background:#f6f7ff}.lamou-radar-filters{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin:12px 0}@media(max-width:760px){.lamou-kpis{grid-template-columns:repeat(3,1fr)}.lamou-home-actions{grid-template-columns:1fr}.lamou-radar-filters{grid-template-columns:1fr}.lamou-profile-dot{display:none}}`;document.head.appendChild(s)}
window.addEventListener('load',()=>setTimeout(()=>{style();header();home()},350));
})();