import { ensureSchema } from './schema-v10.js';

const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
const enc=new TextEncoder();
const SPOTIFY_SCOPES='user-read-email user-read-private';

function b64(bytes){return btoa(String.fromCharCode(...bytes))}
function unb64(value){return Uint8Array.from(atob(value),c=>c.charCodeAt(0))}
function b64url(bytes){return b64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256Bytes(value){const d=await crypto.subtle.digest('SHA-256',enc.encode(value));return new Uint8Array(d)}
async function sha256(value){return b64(await sha256Bytes(value))}
async function passwordHash(password,saltB64){const salt=saltB64?unb64(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:210000},key,256);return {salt:b64(salt),hash:b64(new Uint8Array(bits))}}
function cookie(req,name){const raw=req.headers.get('cookie')||'';const hit=raw.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return hit?decodeURIComponent(hit.slice(name.length+1)):''}
function sessionCookie(token,maxAge=60*60*24*30){return `lamou_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function body(req){try{return await req.json()}catch(_){return {}}}
async function currentUser(req,env){const token=cookie(req,'lamou_session');if(!token)return null;const hash=await sha256(token);return env.DB.prepare(`SELECT u.id,u.username,u.email,u.display_name,u.email_verified FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`).bind(hash,now()).first()}
async function createSession(userId,env){const token=b64url(crypto.getRandomValues(new Uint8Array(32)));const hash=await sha256(token);const expires=new Date(Date.now()+30*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(uid(),userId,hash,expires,now()).run();return token}
function nextUtcReset(){const d=new Date();d.setUTCDate(d.getUTCDate()+1);d.setUTCHours(0,0,0,0);return d.toISOString()}

async function tokenKey(env){const secret=String(env.TOKEN_ENCRYPTION_KEY||'');if(secret.length<24)throw new Error('TOKEN_ENCRYPTION_KEY ausente ou curta');const raw=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptToken(value,env){if(!value)return null;const key=await tokenKey(env),iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(value));return `v1.${b64(iv)}.${b64(new Uint8Array(cipher))}`}
async function decryptToken(value,env){if(!value)return '';const [v,ivB64,cipherB64]=String(value).split('.');if(v!=='v1'||!ivB64||!cipherB64)throw new Error('Token criptografado inválido');const key=await tokenKey(env);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(ivB64)},key,unb64(cipherB64));return new TextDecoder().decode(plain)}
function oauthRedirect(req,status,reason=''){const u=new URL('/',new URL(req.url).origin);u.searchParams.set('oauth','spotify');u.searchParams.set('status',status);if(reason)u.searchParams.set('reason',reason);return Response.redirect(u.toString(),302)}

async function register(req,env){const x=await body(req);const username=String(x.username||'').trim(),email=String(x.email||'').trim().toLowerCase(),display=String(x.displayName||x.name||'').trim(),password=String(x.password||'');if(!username||!email||!display||password.length<8)return json({error:'Dados inválidos.'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE username=? OR email=? LIMIT 1').bind(username,email).first();if(exists)return json({error:'Usuário ou e-mail já cadastrado.'},409);const h=await passwordHash(password),userId=uid(),t=now();await env.DB.prepare('INSERT INTO users(id,username,email,display_name,password_hash,password_salt,email_verified,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)').bind(userId,username,email,display,h.hash,h.salt,t,t).run();await env.DB.prepare('INSERT INTO artist_profiles(id,user_id,artist_name,artist_url,ad_code,artist_image,metadata_json,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid(),userId,'','','','',JSON.stringify({}),t).run();const token=await createSession(userId,env);return json({ok:true,user:{id:userId,username,email,displayName:display},emailVerification:'pending'},201,{'set-cookie':sessionCookie(token)})}
async function login(req,env){const x=await body(req),identity=String(x.identity||x.username||x.email||'').trim(),password=String(x.password||'');const user=await env.DB.prepare('SELECT * FROM users WHERE lower(username)=lower(?) OR lower(email)=lower(?) LIMIT 1').bind(identity,identity).first();if(!user)return json({error:'Credenciais inválidas.'},401);const h=await passwordHash(password,user.password_salt);if(h.hash!==user.password_hash)return json({error:'Credenciais inválidas.'},401);const token=await createSession(user.id,env);return json({ok:true,user:{id:user.id,username:user.username,email:user.email,displayName:user.display_name,emailVerified:!!user.email_verified}},200,{'set-cookie':sessionCookie(token)})}
async function logout(req,env){const token=cookie(req,'lamou_session');if(token){const hash=await sha256(token);await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(hash).run()}return json({ok:true},200,{'set-cookie':sessionCookie('',0)})}
async function changePassword(req,env,user){const x=await body(req),oldPass=String(x.currentPassword||''),newPass=String(x.newPassword||'');if(newPass.length<8)return json({error:'Nova senha inválida.'},400);const row=await env.DB.prepare('SELECT password_hash,password_salt FROM users WHERE id=?').bind(user.id).first();const old=await passwordHash(oldPass,row.password_salt);if(old.hash!==row.password_hash)return json({error:'Senha atual incorreta.'},403);const h=await passwordHash(newPass);await env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(h.hash,h.salt,now(),user.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id).run();const token=await createSession(user.id,env);return json({ok:true},200,{'set-cookie':sessionCookie(token)})}
async function forgot(req,env){const x=await body(req),email=String(x.email||'').trim().toLowerCase();const user=await env.DB.prepare('SELECT id,email,display_name FROM users WHERE email=? LIMIT 1').bind(email).first();if(user){const token=b64url(crypto.getRandomValues(new Uint8Array(32))),hash=await sha256(token),expires=new Date(Date.now()+30*60000).toISOString();await env.DB.prepare('INSERT INTO password_resets(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(uid(),user.id,hash,expires,now()).run();if(env.RECOVERY_API_URL&&env.RECOVERY_API_TOKEN){await fetch(env.RECOVERY_API_URL,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.RECOVERY_API_TOKEN}`},body:JSON.stringify({to:user.email,name:user.display_name,token})}).catch(()=>{})}}return json({ok:true,message:'Se o e-mail estiver cadastrado, a recuperação será enviada.'})}

async function refreshSpotifyConnection(env,c){if(!c||c.provider!=='spotify'||c.status!=='connected'||!c.refresh_token_enc)return c;const expiry=Date.parse(c.expires_at||'');if(Number.isFinite(expiry)&&expiry>Date.now()+5*60*1000)return c;try{const refreshToken=await decryptToken(c.refresh_token_enc,env);const form=new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshToken,client_id:env.SPOTIFY_CLIENT_ID});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!r.ok)return c;const t=await r.json();const accessEnc=await encryptToken(t.access_token,env);const refreshEnc=t.refresh_token?await encryptToken(t.refresh_token,env):c.refresh_token_enc;const expiresAt=new Date(Date.now()+Math.max(60,Number(t.expires_in||3600)-60)*1000).toISOString();await env.DB.prepare('UPDATE connections SET access_token_enc=?,refresh_token_enc=?,expires_at=?,scopes=?,status=?,updated_at=? WHERE id=?').bind(accessEnc,refreshEnc,expiresAt,t.scope||c.scopes||SPOTIFY_SCOPES,'connected',now(),c.id).run();return {...c,access_token_enc:accessEnc,refresh_token_enc:refreshEnc,expires_at:expiresAt,scopes:t.scope||c.scopes||SPOTIFY_SCOPES,status:'connected'}}catch(_){return c}}

async function profile(req,env,user){const p=await env.DB.prepare('SELECT * FROM artist_profiles WHERE user_id=?').bind(user.id).first();const rows=await env.DB.prepare('SELECT id,provider,status,access_token_enc,refresh_token_enc,expires_at,scopes,provider_account FROM connections WHERE user_id=?').bind(user.id).all();const conn={};for(let c of rows.results||[]){if(c.provider==='spotify')c=await refreshSpotifyConnection(env,c);conn[c.provider]=c.status==='connected'&&(!c.expires_at||c.expires_at>now())?'green':c.status==='connected'?'yellow':'red'}let meta={};try{meta=JSON.parse(p?.metadata_json||'{}')}catch(_){}return json({user,artist:{name:p?.artist_name||'',image:p?.artist_image||'',url:p?.artist_url||'',stats:meta.stats||null},connections:conn})}

async function ai(req,env,user){if(!env.AI)return json({error:'AI binding indisponível',provider:'nenhuma'},503);const x=await body(req),kind=String(x.kind||'copy'),context=x.context||{};let prompt='';if(kind==='copy')prompt=`Você é o LAMOU AI Engine. Crie em português uma legenda curta de divulgação musical e uma linha separada com hashtags. Não invente fatos. Contexto: ${JSON.stringify(context)}`;else if(kind==='classify-style')prompt=`Classifique tecnicamente o estilo musical mais provável usando somente estas pistas. Se não houver base suficiente, responda Não classificado. Retorne apenas o estilo. Pistas: ${JSON.stringify(context)}`;else prompt=`Crie três estratégias distintas de campanha musical com objetivo, dias, intensidade e canais. Não invente métricas. Contexto: ${JSON.stringify(context)}`;try{const result=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{messages:[{role:'system',content:'Seja objetivo, confiável e nunca invente dados não verificados.'},{role:'user',content:prompt}],max_tokens:700});const text=result?.response||result?.result||'';await env.DB.prepare('INSERT INTO ai_usage(id,user_id,provider,operation,units,success,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),user?.id||null,'cloudflare-workers-ai',kind,null,1,now()).run().catch(()=>{});if(kind==='classify-style')return json({style:String(text).trim(),provider:'Cloudflare Workers AI'});return json({text,provider:'Cloudflare Workers AI',quota:'free-tier-first'})}catch(err){await env.DB.prepare('INSERT INTO ai_usage(id,user_id,provider,operation,units,success,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),user?.id||null,'cloudflare-workers-ai',kind,null,0,now()).run().catch(()=>{});const msg=String(err?.message||err);if(/quota|limit|429|neurons/i.test(msg))return json({error:'Limite gratuito de IA atingido',quota_exhausted:true,resetAt:nextUtcReset(),fallback:'device-ai-when-authorized'},429);return json({error:'IA temporariamente indisponível',fallback:'device-ai-when-authorized'},503)}}

async function oauthStart(req,env,user,provider){const p=provider.toLowerCase();if(p!=='spotify')return json({error:`OAuth de ${provider} ainda não configurado no backend.`},501);if(!env.SPOTIFY_CLIENT_ID)return json({error:'SPOTIFY_CLIENT_ID não configurado.'},503);if(!env.TOKEN_ENCRYPTION_KEY)return json({error:'TOKEN_ENCRYPTION_KEY não configurado no Cloudflare Secrets.'},503);const origin=new URL(req.url).origin,redirect=`${origin}/api/oauth/spotify/callback`;const state=b64url(crypto.getRandomValues(new Uint8Array(32))),verifier=b64url(crypto.getRandomValues(new Uint8Array(64))),challenge=b64url(await sha256Bytes(verifier)),stateHash=await sha256(state),expires=new Date(Date.now()+10*60*1000).toISOString();await env.DB.prepare('DELETE FROM oauth_states WHERE expires_at<=?').bind(now()).run().catch(()=>{});await env.DB.prepare('INSERT INTO oauth_states(id,user_id,provider,state_hash,code_verifier,redirect_uri,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid(),user.id,'spotify',stateHash,verifier,redirect,expires,now()).run();await env.DB.prepare(`INSERT INTO connections(id,user_id,provider,status,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET status='pending',updated_at=excluded.updated_at`).bind(uid(),user.id,'spotify','pending',now()).run();const q=new URLSearchParams({client_id:env.SPOTIFY_CLIENT_ID,response_type:'code',redirect_uri:redirect,scope:SPOTIFY_SCOPES,state,code_challenge_method:'S256',code_challenge:challenge});return json({url:'https://accounts.spotify.com/authorize?'+q.toString(),provider:'spotify',redirect_uri:redirect})}

async function spotifyCallback(req,env){const u=new URL(req.url),code=u.searchParams.get('code')||'',state=u.searchParams.get('state')||'',oauthError=u.searchParams.get('error')||'';if(oauthError)return oauthRedirect(req,'error',oauthError);if(!code||!state)return oauthRedirect(req,'error','missing_code_or_state');if(!env.SPOTIFY_CLIENT_ID||!env.TOKEN_ENCRYPTION_KEY)return oauthRedirect(req,'error','backend_not_configured');const stateHash=await sha256(state);const row=await env.DB.prepare(`SELECT * FROM oauth_states WHERE provider='spotify' AND state_hash=? AND expires_at>? LIMIT 1`).bind(stateHash,now()).first();if(!row)return oauthRedirect(req,'error','invalid_or_expired_state');await env.DB.prepare('DELETE FROM oauth_states WHERE id=?').bind(row.id).run();try{const form=new URLSearchParams({client_id:env.SPOTIFY_CLIENT_ID,grant_type:'authorization_code',code,redirect_uri:row.redirect_uri,code_verifier:row.code_verifier});const tokenRes=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!tokenRes.ok){await env.DB.prepare(`UPDATE connections SET status='error',updated_at=? WHERE user_id=? AND provider='spotify'`).bind(now(),row.user_id).run();return oauthRedirect(req,'error','token_exchange_failed')}const token=await tokenRes.json();if(!token.access_token)return oauthRedirect(req,'error','missing_access_token');let accountId='';try{const meRes=await fetch('https://api.spotify.com/v1/me',{headers:{authorization:`Bearer ${token.access_token}`}});if(meRes.ok){const me=await meRes.json();accountId=String(me.id||me.display_name||'')}}catch(_){}const accessEnc=await encryptToken(token.access_token,env),refreshEnc=token.refresh_token?await encryptToken(token.refresh_token,env):null,expiresAt=new Date(Date.now()+Math.max(60,Number(token.expires_in||3600)-60)*1000).toISOString();await env.DB.prepare(`INSERT INTO connections(id,user_id,provider,status,access_token_enc,refresh_token_enc,expires_at,scopes,provider_account,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET status=excluded.status,access_token_enc=excluded.access_token_enc,refresh_token_enc=COALESCE(excluded.refresh_token_enc,connections.refresh_token_enc),expires_at=excluded.expires_at,scopes=excluded.scopes,provider_account=excluded.provider_account,updated_at=excluded.updated_at`).bind(uid(),row.user_id,'spotify','connected',accessEnc,refreshEnc,expiresAt,token.scope||SPOTIFY_SCOPES,accountId,now()).run();return oauthRedirect(req,'connected')}catch(_){await env.DB.prepare(`UPDATE connections SET status='error',updated_at=? WHERE user_id=? AND provider='spotify'`).bind(now(),row.user_id).run().catch(()=>{});return oauthRedirect(req,'error','callback_failed')}}

async function oauthStatus(env,user){const rows=await env.DB.prepare('SELECT provider,status,expires_at,provider_account FROM connections WHERE user_id=?').bind(user.id).all();const out={};for(let c of rows.results||[]){if(c.provider==='spotify'){const full=await env.DB.prepare('SELECT * FROM connections WHERE user_id=? AND provider=? LIMIT 1').bind(user.id,'spotify').first();if(full)c=await refreshSpotifyConnection(env,full)}out[c.provider]={status:c.status,expires_at:c.expires_at||null,account:c.provider_account||null}}return json({ok:true,connections:out})}
async function oauthDisconnect(env,user,provider){const p=provider.toLowerCase();await env.DB.prepare('UPDATE connections SET status=?,access_token_enc=NULL,refresh_token_enc=NULL,expires_at=NULL,scopes=NULL,provider_account=NULL,updated_at=? WHERE user_id=? AND provider=?').bind('disconnected',now(),user.id,p).run();return json({ok:true,provider:p,status:'disconnected'})}

async function publish(req,env,user){const x=await body(req);return json({ok:false,error:'Publicadores oficiais ainda não configurados. O LAMOU não registra como publicado sem confirmação real.',mode:x.mode||null},501)}

export default {
  async fetch(req,env){
    const url=new URL(req.url),path=url.pathname;
    let schema=null;
    if(env.DB&&(path==='/api/health'||path.startsWith('/api/auth/')||path.startsWith('/api/oauth/')))schema=await ensureSchema(env.DB);
    if(path==='/api/health')return json({ok:true,service:'lamou-v10',time:now(),db:!!env.DB,db_ready:!!schema?.ready,db_tables:schema?.tables||0,db_error:schema?.error||null,ai:!!env.AI,vector:!!env.MUSIC_VECTOR,spotify_oauth:!!(env.SPOTIFY_CLIENT_ID&&env.TOKEN_ENCRYPTION_KEY)});
    if(path==='/api/ai/health')return json({ok:!!env.AI,provider:env.AI?'Cloudflare Workers AI':'not-bound'});
    if((path.startsWith('/api/auth/')||path.startsWith('/api/oauth/'))&&env.DB&&!schema?.ready)return json({error:'Banco D1 conectado, mas o esquema ainda não ficou pronto.',detail:schema?.error||null},503);
    if(path==='/api/auth/register'&&req.method==='POST')return register(req,env);
    if(path==='/api/auth/login'&&req.method==='POST')return login(req,env);
    if(path==='/api/auth/forgot'&&req.method==='POST')return forgot(req,env);
    if(path==='/api/oauth/spotify/callback'&&req.method==='GET')return spotifyCallback(req,env);
    if(path.startsWith('/api/')&&!env.DB&&path!=='/api/health'&&path!=='/api/ai/health')return json({error:'Banco D1 não conectado.'},503);
    const user=await currentUser(req,env);
    if(path.startsWith('/api/')&&!user&&path!=='/api/health'&&path!=='/api/ai/health')return json({error:'Não autenticado.'},401);
    if(path==='/api/auth/logout'&&req.method==='POST')return logout(req,env);
    if(path==='/api/auth/change-password'&&req.method==='POST')return changePassword(req,env,user);
    if(path==='/api/profile/summary'&&req.method==='GET')return profile(req,env,user);
    if(path==='/api/oauth/status'&&req.method==='GET')return oauthStatus(env,user);
    if(path==='/api/ai'&&req.method==='POST')return ai(req,env,user);
    if(path==='/api/publish'&&req.method==='POST')return publish(req,env,user);
    const start=path.match(/^\/api\/oauth\/([^/]+)\/start$/);if(start&&req.method==='GET')return oauthStart(req,env,user,start[1]);
    const disconnect=path.match(/^\/api\/oauth\/([^/]+)\/disconnect$/);if(disconnect&&req.method==='POST')return oauthDisconnect(env,user,disconnect[1]);
    if(path.startsWith('/api/'))return json({error:'Rota não encontrada.'},404);
    return env.ASSETS?env.ASSETS.fetch(req):new Response('LAMOU backend ativo; assets não vinculados.',{status:503});
  }
};
