import fs from 'node:fs';
import assert from 'node:assert/strict';

const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app-core.js','utf8');
const integrations=fs.readFileSync('integrations-v10.js','utf8');
const worker=fs.readFileSync('backend/worker-entry-app.js','utf8');
const reach=fs.readFileSync('backend/worker-entry-reach.js','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');
const sw=fs.readFileSync('sw.js','utf8');

assert.match(index,/Nova música/);
assert.match(index,/Histórico/);
assert.match(index,/Resultados/);
assert.match(index,/app-core\.js/);
assert.match(index,/app-core\.css/);
assert.doesNotMatch(index,/shell-v10\.js|app\.js|bootstrap-v11|migration-v11|stability-v12|ui-polish-v12|lamou-v10\.js/);
assert.match(index,/nav-icon/);

assert.match(app,/DASHBOARD · SPOTIFY/);
assert.match(app,/DASHBOARD · LAMOU/);
assert.match(app,/Divulgação rápida/);
assert.match(app,/Criar campanha/);
assert.match(app,/APROVAÇÃO FINAL/);
assert.match(app,/APROVAR E CONCLUIR/);
assert.match(app,/Gerar outra versão/);
assert.match(app,/Não quer receber mais/);
assert.match(app,/recipient_opt_out/);
assert.match(app,/suppressed/);
assert.match(app,/RANKING TÉCNICO IA/);
assert.match(app,/Global e por estilo — sem plays, views ou crítica/);
assert.match(app,/technicalScore/);
assert.match(app,/fingerprintFile/);
assert.match(app,/A posição global só é publicada com amostra mínima/);
assert.match(app,/artistImage/);
assert.match(app,/releases/);
assert.match(app,/CD \/ álbum \/ projeto de origem/);
assert.match(app,/\['1:1','Capa'\]/);
assert.match(app,/\['9:16','Stories \/ vertical'\]/);
assert.doesNotMatch(app,/Instagram|TikTok|YouTube Shorts|Facebook|Threads/);

assert.match(integrations,/supported:\['spotify'\]/);
assert.doesNotMatch(integrations,/instagram|tiktok|youtube|facebook|threads/i);
assert.match(worker,/\/artists\/\$\{artistId\}/);
assert.match(worker,/\/artists\/\$\{artistId\}\/albums/);
assert.match(worker,/ai_rank_reference/);
assert.match(worker,/criteria:'technical-only'/);
assert.match(worker,/popularity:false/);
assert.match(reach,/Publicação em redes sociais foi removida/);
assert.match(wrangler,/worker-entry-app\.js/);
assert.match(sw,/lamou-clean-core-ranking-v4/);
console.log('LAMOU clean core + Spotify profile + opt-out + AI ranking: OK');
