import fs from 'node:fs';
import assert from 'node:assert/strict';

const index=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app-core.js','utf8');
const integrations=fs.readFileSync('integrations-v10.js','utf8');
const runtime=fs.readFileSync('runtime-v13.js','utf8');
const emailRuntime=fs.readFileSync('runtime-v14.js','utf8');
const worker=fs.readFileSync('backend/worker-entry-app.js','utf8');
const reach=fs.readFileSync('backend/worker-entry-reach.js','utf8');
const v13=fs.readFileSync('backend/worker-entry-v13.js','utf8');
const v14=fs.readFileSync('backend/worker-entry-v14.js','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const ignore=fs.readFileSync('.assetsignore','utf8');

assert.match(index,/Nova música/);
assert.match(index,/Histórico/);
assert.match(index,/Resultados/);
assert.match(index,/app-core\.js\?v=14/);
assert.match(index,/runtime-v14\.js\?v=14/);
assert.doesNotMatch(index,/shell-v10\.js|app\.js|bootstrap-v11|migration-v11|stability-v12|ui-polish-v12|lamou-v10\.js/);
assert.match(index,/nav-icon/);

assert.match(app,/DASHBOARD · SPOTIFY/);
assert.match(app,/DASHBOARD · LAMOU/);
assert.match(app,/Divulgação rápida/);
assert.match(app,/Criar campanha/);
assert.match(app,/APROVAÇÃO FINAL/);
assert.match(app,/APROVAR E CONCLUIR/);
assert.match(app,/Gerar outra versão/);
assert.match(app,/Não quer receber mais/);
assert.match(app,/recipient_opt_out/);
assert.match(app,/suppressed/);
assert.match(app,/RANKING TÉCNICO IA/);
assert.match(app,/technicalScore/);
assert.match(app,/fingerprintFile/);
assert.match(app,/artistImage/);
assert.match(app,/releases/);
assert.match(app,/CD \/ álbum \/ projeto de origem/);
assert.doesNotMatch(app,/Instagram|TikTok|YouTube Shorts|Facebook|Threads/);

assert.match(integrations,/supported:\['spotify'\]/);
assert.match(worker,/ai_rank_reference/);
assert.match(reach,/Publicação em redes sociais foi removida/);
assert.match(v13,/Never replace a valid account cookie/);
assert.match(v13,/\/api\/auth\/me/);
assert.match(v13,/\/api\/spotify\/track/);
assert.match(v13,/CREATE TABLE IF NOT EXISTS app_state/);
assert.match(runtime,/Diagnóstico real/);
assert.match(runtime,/computeRealHooks/);
assert.match(runtime,/persistState/);

assert.match(v14,/CREATE TABLE IF NOT EXISTS email_outbox/);
assert.match(v14,/https:\/\/api\.resend\.com\/emails/);
assert.match(v14,/idempotency-key/);
assert.match(v14,/EMAIL_DAILY_LIMIT/);
assert.match(v14,/RESEND_API_KEY/);
assert.match(v14,/EMAIL_FROM/);
assert.match(v14,/dailyplaylists[\s\S]*autoEmail:false/);
assert.match(v14,/progressive[\s\S]*requiresSoundCloud:true/);
assert.match(v14,/\/api\/outreach\/email\/send-batch/);
assert.match(v14,/\/api\/outreach\/email\/status/);
assert.match(emailRuntime,/Enviar e-mails verificados/);
assert.match(emailRuntime,/Aceito pelo provedor/);
assert.match(emailRuntime,/Abrir canal oficial/);
assert.match(emailRuntime,/soundcloud\.com/);
assert.match(emailRuntime,/refreshStatuses/);
assert.match(emailRuntime,/Lamou\.markSent=\(hid,cid\)=>send/);

assert.match(wrangler,/worker-entry-v14\.js/);
assert.match(wrangler,/EMAIL_PROVIDER/);
assert.match(wrangler,/EMAIL_DAILY_LIMIT/);
assert.match(wrangler,/2026-08-15/);
assert.match(wrangler,/nodejs_compat/);
assert.match(sw,/lamou-runtime-v14/);
assert.match(ignore,/^backend$/m);
assert.match(ignore,/^wrangler\.jsonc$/m);
assert.match(ignore,/^tests$/m);

console.log('LAMOU runtime v14: verified email sending + status + anti-duplicate checks OK');
