const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='lamou-central-official-data-v1', AUTH='lamou-central-auth-v1', SESSION='lamou-central-session';
const canonicalLogo='https://raw.githubusercontent.com/rafalamounier1805-ship-it/LifeOfucam/main/brand/LAMOU-IA-logo-oficial.png';
const defaultApps=[
 {id:'diagnostico360',name:'LAMOU IA Diagnóstico 360',mark:'360',category:'Inteligência & Consultoria',status:'dev',version:'Oficial',color:'linear-gradient(135deg,#2555c7,#753de2)',desc:'Diagnóstico executivo de empresas, reuniões, indicadores, evidências, ações e apresentações com IA.',url:'',core:62,history:['Protótipo inicial','Diagnóstico 360 v2 (arquivado como versão anterior)'],tags:['IA','Consultoria','360']},
 {id:'testeia',name:'Teste, Teste, Teste IA',mark:'TTT',category:'Software Readiness',status:'dev',version:'Oficial',color:'linear-gradient(135deg,#00a2b8,#1766d6)',desc:'Digital Workforce Simulation com personas sintéticas funcionais, QA/E2E, performance, acessibilidade e Human Fit.',url:'',core:58,history:['Conceito técnico 24/08/2026'],tags:['QA','Personas','Human Fit']},
 {id:'agenda',name:'LAMOU Agenda',mark:'AG',category:'Produtividade & Projetos',status:'plan',version:'Oficial',color:'linear-gradient(135deg,#15795f,#33b88a)',desc:'Agenda operacional com rotina, projetos, evolução, estudos, negócio LAMOU IA e execução diária conectada.',url:'',core:35,history:['Conceito de agenda de projetos'],tags:['Agenda','Projetos','Rotina']},
 {id:'musicpromoter',name:'LAMOU Music Promoter',mark:'MP',category:'Música & Mercado',status:'live',version:'Oficial',color:'linear-gradient(135deg,#a32687,#4931af)',desc:'Gestão profissional das músicas, catálogo, produção, divulgação, distribuição, comercial e evolução artística.',url:'https://github.com/rafalamounier1805-ship-it/lamoumusicpromoter1',core:82,history:['v1.7.0','Core 2.0 consolidado','Versões de UX e cache'],tags:['Música','Marketing','IA']},
 {id:'composer',name:'Composer OS',mark:'CO',category:'Música & Criação',status:'live',version:'v2.1 Oficial',color:'linear-gradient(135deg,#d76b25,#a43874)',desc:'Sistema operacional do compositor: repertório, produção, direitos, pitching, organização e decisões com IA.',url:'https://composer-os-v21.vercel.app',core:70,history:['Composer OS MVP','Composer OS test','Shape test','Composer OS base'],tags:['Composição','Catálogo','IA']},
 {id:'chargeme',name:'CHARGE.ME',mark:'CM',category:'Conteúdo & Humor',status:'live',version:'Oficial',color:'linear-gradient(135deg,#e04f54,#e0912b)',desc:'Charges personalizadas com IA, humor, sarcasmo, perfis, compartilhamento e criação persistente.',url:'https://charge-me-final.vercel.app',core:64,history:['Premium','Premium v2 test','v3 check','v4 public','Canva resize check','Path tests'],tags:['Humor','Imagem','Social']},
 {id:'hq',name:'HQ Interativo O LAMOU IA',mark:'HQ',category:'Storytelling',status:'live',version:'Oficial',color:'linear-gradient(135deg,#1e65ad,#5b2f9e)',desc:'Histórias em quadrinhos interativas, cenas clicáveis, narrativa multimídia e publicação para compartilhamento.',url:'https://hq-operacao-recomeco.vercel.app',core:52,history:['Operação Recomeço','Path test HQ'],tags:['HQ','Interativo','Story']},
 {id:'teconvido',name:'TE CONVIDO',mark:'TC',category:'Convites Digitais',status:'live',version:'Oficial',color:'linear-gradient(135deg,#98713a,#d6b25f)',desc:'Convites digitais interativos com mídia, música, localização, agenda, efeitos, compartilhamento e IA.',url:'https://convite-lamou.vercel.app',core:69,history:['Convite Viviane & Geraldo','Buraco de Minhoca','Testes de assets'],tags:['Convite','Eventos','PWA']},
 {id:'ranking',name:'LAMOU Ranking AI',mark:'RA',category:'Música & Avaliação',status:'live',version:'Oficial',color:'linear-gradient(135deg,#14859c,#3f43c8)',desc:'Ranking e avaliação de músicas por critérios de produção, letra, melodia, composição, remix, master e vocais.',url:'https://lamou-ranking-ai-public.vercel.app',core:60,history:['Ranking AI público'],tags:['Ranking','Música','IA']},
 {id:'projete',name:'Projete — Treinamento e Desenvolvimento',mark:'TD',category:'T&D Corporativo',status:'dev',version:'Oficial',color:'linear-gradient(135deg,#176dce,#16a4a7)',desc:'Onboarding, LNT, plano de aula, avaliação, PDI, feedback, carreira, evidências, calendário, certificados e projetos.',url:'',core:55,history:['Início executável','Módulos consolidados 20–24/08'],tags:['T&D','RH','Gestão']},
 {id:'lifeos',name:'LifeOS',mark:'LO',category:'Vida & Organização',status:'live',version:'Oficial',color:'linear-gradient(135deg,#46753b,#35a6a4)',desc:'Sistema pessoal integrado para organização de vida, rotinas, objetivos e execução.',url:'https://lifeos.vercel.app',core:48,history:['LifeOfucam','LifeOS2'],tags:['Vida','Rotina','Organização']},
 {id:'boracrescer',name:'Bora Crescer',mark:'BC',category:'Desenvolvimento',status:'live',version:'Oficial',color:'linear-gradient(135deg,#087a7a,#69a531)',desc:'Plataforma de desenvolvimento e evolução com foco em crescimento estruturado.',url:'https://boracrescer.vercel.app',core:44,history:['Versão GitHub atual'],tags:['Crescimento','Desenvolvimento']},
 {id:'oasis',name:'Oásis',mark:'OA',category:'Produto & Serviços',status:'plan',version:'Oficial',color:'linear-gradient(135deg,#2d9479,#1a5d89)',desc:'Produto LAMOU IA em estruturação, conectado ao CORE e ao modelo comercial da empresa.',url:'',core:30,history:['Conceito consolidado 24/08'],tags:['Produto','SaaS']},
 {id:'condominio',name:'Condomínio Reclame',mark:'CR',category:'SaaS Condominial',status:'plan',version:'Oficial',color:'linear-gradient(135deg,#515d8f,#3843a8)',desc:'Produto SaaS com base Essencial e add-ons para comunicação, administração, analytics, pesquisas, reservas e IA.',url:'',core:40,history:['Packaging v4'],tags:['SaaS','Condomínio','Add-ons']}
];
const defaultProjects=[
 {id:'p1',name:'Central LAMOU IA',area:'Tecnologia',status:'Em execução',owner:'LAMOU IA',next:'Consolidar PWA e autenticação de produção'},
 {id:'p2',name:'Marca & operação LAMOU IA',area:'Empresa',status:'Em execução',owner:'Rafael',next:'Organizar portfólio e oferta comercial'},
 {id:'p3',name:'CORE transversal',area:'Arquitetura',status:'Contínuo',owner:'Produto',next:'Aumentar cobertura nos apps oficiais'}
];
const defaultClients=[];
const defaultLeads=[];
const coreModules=[
 ['Identidade & Design System','done','Logo canônica + shell responsivo'],['Autenticação','partial','Lock local funcionando; backend pendente'],['Usuários & RBAC/ABAC','partial','Estrutura definida; backend pendente'],['Workspaces/Tenants','partial','Modelo definido; persistência server-side pendente'],['Persistência & Autosave','done','LocalStorage + export/import'],['Auditoria','done','Trilha local de ações'],['PWA / Mobile','done','Manifest + service worker + instalação'],['Atualização automática','done','Service worker verifica versão oficial'],['App Health','done','Checklist local e status'],['Product Critic','partial','Checklist base; motor completo pendente'],['AI Gateway','partial','Arquitetura definida; secrets server-side pendentes'],['Billing & Quotas','partial','Modelo comercial presente; cobrança real pendente'],['LGPD & Segurança','partial','Regras aplicadas; backend de produção pendente'],['Backup / DR','partial','Backup JSON local; DR server-side pendente'],['CI/CD','done','GitHub Pages oficial automático'],['Test Mode','done','Ambiente local de teste identificado']
];
let state=loadState(); let currentView='apps'; let deferredInstallPrompt=null; let swReg=null;
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORE));if(s&&s.apps)return s}catch(e){}return {apps:structuredClone(defaultApps),projects:structuredClone(defaultProjects),clients:structuredClone(defaultClients),leads:structuredClone(defaultLeads),audit:[],settings:{autoUpdate:true,compact:false}}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state));}
function audit(action,detail=''){state.audit.unshift({ts:new Date().toISOString(),action,detail});state.audit=state.audit.slice(0,120);saveState();renderAudit();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function statusLabel(s){return s==='live'?'Publicado':s==='dev'?'Em desenvolvimento':s==='issue'?'Atenção':'Planejado'}
function statusDot(s){return `<span class="dot ${s}"></span>${statusLabel(s)}`}
function hashString(str){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(str)).then(buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join(''))}
function initAuth(){const auth=localStorage.getItem(AUTH);$('#setupAccess').classList.toggle('hidden',!!auth);$('#loginAccess').classList.toggle('hidden',!auth);if(sessionStorage.getItem(SESSION)==='1')unlockApp()}
async function createAccess(){const n=$('#setupName').value.trim()||'Admin',p=$('#setupPassword').value,p2=$('#setupPassword2').value;if(p.length<6)return toast('Crie uma senha com pelo menos 6 caracteres.');if(p!==p2)return toast('As senhas não coincidem.');const salt=crypto.randomUUID(),hash=await hashString(salt+p);localStorage.setItem(AUTH,JSON.stringify({name:n,salt,hash,createdAt:new Date().toISOString()}));sessionStorage.setItem(SESSION,'1');audit('Autenticação','Acesso administrativo local criado');unlockApp()}
async function doLogin(){const a=JSON.parse(localStorage.getItem(AUTH)||'null'),p=$('#loginPassword').value;if(!a)return initAuth();const h=await hashString(a.salt+p);if(h!==a.hash)return toast('Senha incorreta.');sessionStorage.setItem(SESSION,'1');audit('Autenticação','Login local realizado');unlockApp()}
function unlockApp(){$('#loginGate').classList.add('hidden');renderAll()}
function lockApp(){sessionStorage.removeItem(SESSION);$('#loginPassword').value='';$('#loginGate').classList.remove('hidden');initAuth();audit('Autenticação','Central bloqueada')}
function resetAccess(){if(!confirm('Redefinir o acesso local? Seus dados da Central serão mantidos.'))return;localStorage.removeItem(AUTH);sessionStorage.removeItem(SESSION);initAuth();toast('Acesso local redefinido.')}
