const dossierTemplates=[
  ['produto-resumo','Resumo executivo do produto','Produto'],
  ['produto-requisitos','Requisitos, escopo e funcionalidades','Produto'],
  ['tecnico-arquitetura','Arquitetura e estrutura de software','Estrutura'],
  ['tecnico-componentes','Inventário de componentes, APIs e licenças','Estrutura'],
  ['governanca-seguranca','Segurança, LGPD e tratamento de dados','Governança'],
  ['qualidade-testes','Plano de testes, validação e evidências','Qualidade'],
  ['versionamento-changelog','Histórico de versões e changelog','Versionamento'],
  ['direitos-autoria','Dossiê de autoria e propriedade intelectual','Direitos'],
  ['direitos-evidencias','Registro de evidências de criação e titularidade','Direitos'],
  ['operacao-manual','Manual técnico e operacional','Operação'],
  ['marketing-plano','Plano de marketing','Marketing'],
  ['marketing-posicionamento','Posicionamento, público e proposta de valor','Marketing'],
  ['governanca-backup','Plano de continuidade, backup e recuperação','Governança'],
  ['direitos-licenciamento','Licenciamento, termos de uso e distribuição','Direitos']
];

function dossierEsc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dossierSlug(v='arquivo'){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'arquivo'}
function dossierDate(v){if(!v)return '—';try{return new Date(v).toLocaleString('pt-BR')}catch(e){return v}}
function dossierDocContent(templateId,a){
  const today=new Date().toLocaleDateString('pt-BR');
  const base=`# ${a.name}\n\n**Categoria:** ${a.category}\n**Versão atual:** ${a.version}\n**Status:** ${statusLabel(a.status)}\n**Atualizado em:** ${today}\n\n${a.desc}\n\n`;
  const parts={
    'produto-resumo':`## Objetivo\nDescrever de forma objetiva o problema que o produto resolve, quem utiliza e qual resultado entrega.\n\n## Escopo atual\n- Produto: ${a.name}\n- Proposta: ${a.desc}\n- URL oficial: ${a.url||'A definir'}\n- CORE aplicado: ${a.core}%\n\n## Observações\nManter este resumo alinhado à versão oficial vigente.`,
    'produto-requisitos':`## Escopo funcional\nRegistrar módulos, funcionalidades, entradas, saídas, integrações e critérios de aceite.\n\n## Requisitos não funcionais\nRegistrar segurança, disponibilidade, desempenho, acessibilidade, compatibilidade, backup e observabilidade.\n\n## Fora de escopo\nDocumentar explicitamente o que não pertence à versão atual.`,
    'tecnico-arquitetura':`## Arquitetura\nDocumentar frontend, backend, banco de dados, autenticação, armazenamento, integrações, APIs, IA, filas, cache e deploy.\n\n## Ambientes\n- Desenvolvimento\n- Teste / homologação\n- Produção\n\n## Fluxo de dados\nMapear origem, processamento, persistência, compartilhamento e descarte dos dados.`,
    'tecnico-componentes':`## Componentes e dependências\nRegistrar bibliotecas, frameworks, plugins, APIs, modelos de IA, serviços externos e respectivas versões/licenças.\n\n## Regra\nNenhum componente de terceiro deve ficar sem origem, licença e finalidade documentadas.`,
    'governanca-seguranca':`## Segurança e privacidade\nRegistrar autenticação, autorização, RBAC/ABAC, gestão de segredos, criptografia, logs, auditoria, backup, retenção e resposta a incidentes.\n\n## LGPD\nMapear dados pessoais, finalidade, base legal quando aplicável, operadores/controladores, compartilhamentos, retenção e direitos do titular.\n\n**Nota:** este documento organiza evidências e decisões; não substitui parecer jurídico quando necessário.`,
    'qualidade-testes':`## Estratégia de qualidade\nRegistrar testes unitários, integração, E2E, regressão, acessibilidade, performance, segurança e smoke tests.\n\n## Evidências\nAnexar relatórios, screenshots, vídeos, logs, resultados e links de execução.\n\n## Critério de release\nDefinir o que precisa estar aprovado antes de uma versão ser marcada como oficial.`,
    'versionamento-changelog':`## Versão atual\n${a.version}\n\n## Histórico existente\n${(a.history||[]).map(x=>`- ${typeof x==='string'?x:(x.label||x.version||'Versão')}`).join('\n')||'- Sem versões anteriores registradas'}\n\n## Regra\nUma única versão oficial aparece no catálogo; versões anteriores permanecem preservadas neste dossiê.`,
    'direitos-autoria':`## Titularidade e autoria\nRegistrar autores, titulares, colaboradores, datas de criação e cessões/licenças relevantes.\n\n## Ativos protegíveis\n- Código-fonte\n- Interface e elementos visuais originais\n- Documentação\n- Marca/nome quando aplicável\n- Conteúdo autoral\n\n## Comprovação\nRelacionar commits, repositórios, arquivos datados, contratos, registros, recibos, domínios e demais evidências.\n\n**Importante:** este dossiê ajuda a organizar prova de criação e titularidade, mas não cria sozinho um registro formal de direito.`,
    'direitos-evidencias':`## Cadeia de evidências\nRegistrar em ordem cronológica: ideia/documento inicial, arquivos, commits, branches, releases, deploys, domínios, contratos, e-mails e registros formais.\n\n## Integridade\nSempre que possível, guardar data, origem, hash/commit e cópia de segurança.`,
    'operacao-manual':`## Operação\nDocumentar como instalar, configurar, acessar, administrar, atualizar, fazer backup, restaurar e encerrar o produto.\n\n## Suporte\nRegistrar erros conhecidos, diagnóstico, procedimentos de recuperação e contatos responsáveis.`,
    'marketing-plano':`## Plano de marketing do produto\nDocumentar objetivo, público, canais, mensagens, conteúdo, calendário, métricas, orçamento, experimentos e aprendizado.\n\n## Ativos\nRelacionar site, landing page, demonstração, screenshots, vídeos, apresentações, press kit e materiais de divulgação.`,
    'marketing-posicionamento':`## Posicionamento\nDefinir problema, público, categoria, diferencial, benefícios, provas e principais objeções.\n\n## Proposta de valor\nEscrever uma versão curta, uma executiva e uma comercial da proposta de valor.\n\n## Concorrência e alternativas\nRegistrar alternativas existentes e diferenças relevantes sem promessas não comprovadas.`,
    'governanca-backup':`## Continuidade\nRegistrar backup, restauração, recuperação de desastre, RPO/RTO quando aplicável, dependências críticas e plano de saída de fornecedores.`,
    'direitos-licenciamento':`## Licenciamento e distribuição\nDocumentar licença do software, permissões de uso, restrições, propriedade de customizações, componentes de terceiros, distribuição e termos aplicáveis.\n\n## Entrega\nDefinir o que acompanha cada release: executável/link, código quando aplicável, documentação, changelog e evidências.``
  };
  return base+(parts[templateId]||'## Conteúdo\nDocumentar este item para a versão oficial do produto.');
}

function createDefaultDossier(a){
  return {
    currentArtifact:'',
    archived:(a.history||[]).map((h,i)=>({id:`legacy-${i}-${Date.now()}`,label:typeof h==='string'?h:(h.label||h.version||`Versão ${i+1}`),date:'',url:'',artifact:'',notes:'Importado do histórico existente.'})),
    docs:dossierTemplates.map(([id,title,category])=>({id,title,category,status:'base',link:'',updatedAt:new Date().toISOString(),content:dossierDocContent(id,a)})),
    ownership:{authorOwner:'LAMOU IA',creationDate:'',repoUrl:a.url?.includes('github.com')?a.url:'',sourceArchiveUrl:'',registrationRefs:'',trademarkRefs:'',licenses:'',notes:''},
    evidence:[],
    sent:[]
  };
}
function ensureDossier(a,persist=true){
  if(!a.dossier){a.dossier=createDefaultDossier(a);if(persist)saveState()}
  a.dossier.archived=Array.isArray(a.dossier.archived)?a.dossier.archived:[];
  a.dossier.docs=Array.isArray(a.dossier.docs)?a.dossier.docs:[];
  a.dossier.evidence=Array.isArray(a.dossier.evidence)?a.dossier.evidence:[];
  a.dossier.sent=Array.isArray(a.dossier.sent)?a.dossier.sent:[];
  a.dossier.ownership=a.dossier.ownership||createDefaultDossier(a).ownership;
  return a.dossier;
}
function dossierApp(id){return state.apps.find(x=>x.id===id)}
function dossierDownload(name,text,type='text/markdown;charset=utf-8'){
  const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),el=document.createElement('a');el.href=url;el.download=name;el.click();setTimeout(()=>URL.revokeObjectURL(url),500);
}
function dossierCopy(v){navigator.clipboard?.writeText(v).then(()=>toast('Link copiado.')).catch(()=>toast('Não foi possível copiar.'))}
function dossierMail(app,itemType,itemTitle,subject,body){
  const email=prompt('E-mail do destinatário:','');
  if(!email)return;
  if(!/^\S+@\S+\.\S+$/.test(email))return toast('Informe um e-mail válido.');
  const d=ensureDossier(app);d.sent.unshift({id:crypto.randomUUID(),when:new Date().toISOString(),email,itemType,itemTitle,status:'Preparado no cliente de e-mail'});saveState();audit('Compartilhamento preparado',`${app.name} • ${itemTitle} • ${email}`);
  location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body.slice(0,5000))}`;
  toast('Envio registrado e cliente de e-mail aberto.');
}
function dossierSummary(app){
  const d=ensureDossier(app,false),o=d.ownership||{};
  return `# Dossiê — ${app.name}\n\nVersão atual: ${app.version}\nStatus: ${statusLabel(app.status)}\nURL oficial: ${app.url||'A definir'}\nArtefato atual: ${d.currentArtifact||'A definir'}\nCORE: ${app.core}%\n\n## Propriedade\nTitular/autoria: ${o.authorOwner||'A definir'}\nRepositório: ${o.repoUrl||'A definir'}\nRegistros/referências: ${o.registrationRefs||'A definir'}\n\n## Documentos\n${d.docs.map(x=>`- ${x.title} — ${x.status}${x.link?` — ${x.link}`:''}`).join('\n')}\n\n## Versões anteriores\n${d.archived.map(x=>`- ${x.label}${x.date?` (${x.date})`:''}${x.url?` — ${x.url}`:''}`).join('\n')||'- Nenhuma'}\n`;
}

function appCard(a){
  const d=ensureDossier(a,false),done=d.docs.filter(x=>x.status==='final').length;
  return `<article class="app-card"><div class="app-cover" style="background:${a.color}"><span class="badge-official">OFICIAL</span><div class="app-mark">${a.mark}</div><div class="app-title"><h3>${a.name}</h3><small>${a.category}</small></div></div><div class="card-body"><p>${a.desc}</p><div class="tags">${a.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="card-meta"><span class="status">${statusDot(a.status)}</span><span>${a.version}</span></div><div class="card-meta"><span>${d.docs.length} documentos</span><span>${d.archived.length} versão(ões) anterior(es)</span></div><div class="card-actions"><button class="btn primary small" data-manage="${a.id}">Abrir dossiê</button><button class="btn small" data-open="${a.id}">${a.url?'Abrir aplicativo':'Versão atual'}</button></div></div></article>`
}

function manageApp(id){renderDossier(id,'overview')}
function renderDossier(id,tab='overview'){
  const a=dossierApp(id);if(!a)return;const d=ensureDossier(a);modalTitle.textContent=`${a.name} — Dossiê`;
  const tabs=[['overview','Visão geral'],['versions','Versões'],['docs','Documentos'],['rights','Direitos & provas'],['structure','Estrutura'],['marketing','Marketing'],['sent','Envios']];
  modalBody.innerHTML=`<div class="dossier-head"><div><span class="official-badge">DOSSIÊ DO PRODUTO</span><h3>${dossierEsc(a.name)}</h3><p>Informação técnica e documental do aplicativo. Área independente do Comercial.</p></div><div class="dossier-quick"><button class="btn small" id="dDownloadAll">Baixar resumo</button><button class="btn small" id="dSendAll">Enviar resumo</button>${a.url?'<button class="btn primary small" id="dOpenApp">Abrir atual</button>':''}</div></div><div class="dossier-tabs">${tabs.map(([k,n])=>`<button class="dossier-tab ${k===tab?'active':''}" data-dtab="${k}">${n}</button>`).join('')}</div><div id="dossierPanel"></div>`;
  showModal();$$('[data-dtab]').forEach(b=>b.onclick=()=>renderDossier(id,b.dataset.dtab));dDownloadAll.onclick=()=>dossierDownload(`${dossierSlug(a.name)}-dossie.md`,dossierSummary(a));dSendAll.onclick=()=>dossierMail(a,'Dossiê','Resumo do dossiê',`${a.name} — dossiê`,dossierSummary(a));if($('#dOpenApp'))dOpenApp.onclick=()=>openOfficial(a.id);
  if(tab==='overview')renderDossierOverview(a);if(tab==='versions')renderDossierVersions(a);if(tab==='docs')renderDossierDocs(a);if(tab==='rights')renderDossierRights(a);if(tab==='structure')renderDossierDocGroup(a,'Estrutura');if(tab==='marketing')renderDossierDocGroup(a,'Marketing');if(tab==='sent')renderDossierSent(a);
}
function renderDossierOverview(a){
  const d=ensureDossier(a),final=d.docs.filter(x=>x.status==='final').length;
  dossierPanel.innerHTML=`<div class="dossier-stats"><div class="stat"><small>Versão atual</small><b>${dossierEsc(a.version)}</b><em>${statusLabel(a.status)}</em></div><div class="stat"><small>Versões preservadas</small><b>${d.archived.length}</b><em>Histórico interno</em></div><div class="stat"><small>Documentos</small><b>${d.docs.length}</b><em>${final} finalizado(s)</em></div><div class="stat"><small>Envios registrados</small><b>${d.sent.length}</b><em>Por documento/versão</em></div></div><div class="grid2"><div class="box"><h3>Versão oficial atual</h3><div class="field"><label>Versão</label><input id="dVersion" value="${dossierEsc(a.version)}"></div><div class="form-grid" style="margin-top:8px"><div class="field"><label>Status</label><select id="dStatus"><option value="live">Publicado</option><option value="dev">Em desenvolvimento</option><option value="plan">Planejado</option><option value="issue">Atenção</option></select></div><div class="field"><label>CORE (%)</label><input id="dCore" type="number" min="0" max="100" value="${a.core}"></div></div><div class="field" style="margin-top:8px"><label>URL oficial / executável</label><input id="dUrl" value="${dossierEsc(a.url||'')}"></div><div class="field" style="margin-top:8px"><label>Link do pacote/arquivo para download</label><input id="dArtifact" value="${dossierEsc(d.currentArtifact||'')}"></div><button class="btn primary" id="dSaveCurrent" style="margin-top:10px">Salvar versão atual</button></div><div class="box"><h3>O que este dossiê guarda</h3><p>Versões, documentos, arquitetura, propriedade intelectual, evidências, marketing, links, arquivos e histórico de compartilhamento. Nenhum dado comercial entra aqui.</p><div class="metric"><span>Direitos & titularidade</span><b>${d.ownership.authorOwner?'Configurado':'Pendente'}</b></div><div class="metric"><span>Links de documentos</span><b>${d.docs.filter(x=>x.link).length}</b></div><div class="metric"><span>Evidências anexadas</span><b>${d.evidence.length}</b></div></div></div>`;
  dStatus.value=a.status;dSaveCurrent.onclick=()=>{a.version=dVersion.value.trim()||a.version;a.status=dStatus.value;a.core=Math.max(0,Math.min(100,+dCore.value||0));a.url=dUrl.value.trim();d.currentArtifact=dArtifact.value.trim();saveState();audit('Dossiê atualizado',`${a.name} • versão atual`);toast('Versão atual salva.');renderDossier(a.id,'overview')}
}
function renderDossierVersions(a){
  const d=ensureDossier(a);dossierPanel.innerHTML=`<div class="box dossier-current"><h3>Atual — ${dossierEsc(a.version)}</h3><p>${statusLabel(a.status)} • ${a.url?`<a href="${dossierEsc(a.url)}" target="_blank" rel="noopener">Abrir executável</a>`:'Sem URL oficial'} ${d.currentArtifact?`• <a href="${dossierEsc(d.currentArtifact)}" target="_blank" rel="noopener">Baixar pacote</a>`:''}</p></div><div class="panel dossier-subpanel"><div class="panel-head"><div><h2>Versões anteriores preservadas</h2><p>Continuam disponíveis, mas não viram novos produtos no painel principal.</p></div><button class="btn primary small" id="dAddVersion">+ Arquivar versão</button></div><div class="dossier-list">${d.archived.length?d.archived.map(v=>`<div class="dossier-row"><div><b>${dossierEsc(v.label)}</b><small>${v.date?dossierEsc(v.date):'Data não informada'}${v.notes?` • ${dossierEsc(v.notes)}`:''}</small></div><div class="row-actions">${v.url?`<button class="btn small" data-vopen="${v.id}">Abrir</button>`:''}${v.artifact?`<button class="btn small" data-vart="${v.id}">Arquivo</button>`:''}<button class="btn small" data-vdown="${v.id}">Baixar ficha</button><button class="btn small" data-vsend="${v.id}">Enviar</button><button class="btn danger small" data-vdel="${v.id}">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhuma versão anterior cadastrada.</div>'}</div></div>`;
  dAddVersion.onclick=()=>newDossierVersion(a.id);$$('[data-vopen]').forEach(b=>b.onclick=()=>{const v=d.archived.find(x=>x.id===b.dataset.vopen);if(v?.url)open(v.url,'_blank','noopener')});$$('[data-vart]').forEach(b=>b.onclick=()=>{const v=d.archived.find(x=>x.id===b.dataset.vart);if(v?.artifact)open(v.artifact,'_blank','noopener')});$$('[data-vdown]').forEach(b=>b.onclick=()=>downloadVersionRecord(a,b.dataset.vdown));$$('[data-vsend]').forEach(b=>b.onclick=()=>sendVersionRecord(a,b.dataset.vsend));$$('[data-vdel]').forEach(b=>b.onclick=()=>{if(!confirm('Excluir esta versão do histórico?'))return;d.archived=d.archived.filter(x=>x.id!==b.dataset.vdel);saveState();renderDossier(a.id,'versions')})
}
function newDossierVersion(id){const a=dossierApp(id),d=ensureDossier(a);modalTitle.textContent=`${a.name} — Arquivar versão`;modalBody.innerHTML=`<button class="btn small" id="dBackVersion">← Voltar</button><div class="form-grid" style="margin-top:12px"><div class="field"><label>Nome/versão</label><input id="vLabel" placeholder="Ex.: v1.6.0"></div><div class="field"><label>Data</label><input id="vDate" type="date"></div><div class="field"><label>Link executável</label><input id="vUrl"></div><div class="field"><label>Link do arquivo/pacote</label><input id="vArtifact"></div></div><div class="field" style="margin-top:8px"><label>Notas</label><textarea id="vNotes"></textarea></div><button class="btn primary" id="vSave" style="margin-top:10px">Salvar no histórico</button>`;dBackVersion.onclick=()=>renderDossier(id,'versions');vSave.onclick=()=>{const label=vLabel.value.trim();if(!label)return toast('Informe a versão.');d.archived.unshift({id:crypto.randomUUID(),label,date:vDate.value,url:vUrl.value.trim(),artifact:vArtifact.value.trim(),notes:vNotes.value.trim()});saveState();audit('Versão arquivada',`${a.name} • ${label}`);renderDossier(id,'versions')}}
function versionRecord(a,v){return `# ${a.name} — ${v.label}\n\nData: ${v.date||'Não informada'}\nExecutável: ${v.url||'Não informado'}\nArquivo/pacote: ${v.artifact||'Não informado'}\nNotas: ${v.notes||'—'}\n`}
function downloadVersionRecord(a,id){const v=ensureDossier(a).archived.find(x=>x.id===id);if(v)dossierDownload(`${dossierSlug(a.name)}-${dossierSlug(v.label)}.md`,versionRecord(a,v))}
function sendVersionRecord(a,id){const v=ensureDossier(a).archived.find(x=>x.id===id);if(v)dossierMail(a,'Versão',v.label,`${a.name} — ${v.label}`,versionRecord(a,v))}
function renderDossierDocs(a){
  const d=ensureDossier(a);dossierPanel.innerHTML=`<div class="panel dossier-subpanel"><div class="panel-head"><div><h2>Documentação do aplicativo</h2><p>Todos os documentos e links pertencentes a este produto ficam aqui.</p></div><button class="btn primary small" id="dAddDoc">+ Documento</button></div><div class="dossier-list">${d.docs.map(doc=>`<div class="dossier-row"><div><b>${dossierEsc(doc.title)}</b><small>${dossierEsc(doc.category)} • ${doc.status==='final'?'Finalizado':doc.status==='review'?'Em revisão':'Base'}${doc.link?' • Link anexado':''}</small></div><div class="row-actions">${doc.link?`<button class="btn small" data-dopen="${doc.id}">Abrir link</button><button class="btn small" data-dcopy="${doc.id}">Copiar</button>`:''}<button class="btn small" data-dedit="${doc.id}">Editar</button><button class="btn small" data-ddown="${doc.id}">Baixar</button><button class="btn small" data-dsend="${doc.id}">Enviar</button></div></div>`).join('')}</div></div>`;
  dAddDoc.onclick=()=>editDossierDoc(a.id,null);$$('[data-dedit]').forEach(b=>b.onclick=()=>editDossierDoc(a.id,b.dataset.dedit));$$('[data-ddown]').forEach(b=>b.onclick=()=>downloadDossierDoc(a,b.dataset.ddown));$$('[data-dsend]').forEach(b=>b.onclick=()=>sendDossierDoc(a,b.dataset.dsend));$$('[data-dopen]').forEach(b=>b.onclick=()=>{const x=d.docs.find(y=>y.id===b.dataset.dopen);if(x?.link)open(x.link,'_blank','noopener')});$$('[data-dcopy]').forEach(b=>b.onclick=()=>{const x=d.docs.find(y=>y.id===b.dataset.dcopy);if(x?.link)dossierCopy(x.link)})
}
function editDossierDoc(appId,docId){
  const a=dossierApp(appId),d=ensureDossier(a),existing=docId?d.docs.find(x=>x.id===docId):null,doc=existing||{id:crypto.randomUUID(),title:'',category:'Outros',status:'base',link:'',content:'',updatedAt:new Date().toISOString()};modalTitle.textContent=`${a.name} — Documento`;modalBody.innerHTML=`<button class="btn small" id="docBack">← Documentos</button><div class="form-grid" style="margin-top:12px"><div class="field"><label>Título</label><input id="docTitle" value="${dossierEsc(doc.title)}"></div><div class="field"><label>Categoria</label><input id="docCategory" value="${dossierEsc(doc.category)}"></div><div class="field"><label>Status</label><select id="docStatus"><option value="base">Base</option><option value="review">Em revisão</option><option value="final">Finalizado</option></select></div><div class="field"><label>Link do documento/arquivo</label><input id="docLink" value="${dossierEsc(doc.link||'')}"></div></div><div class="field" style="margin-top:8px"><label>Conteúdo / notas documentais</label><textarea id="docContent" class="doc-editor">${dossierEsc(doc.content||'')}</textarea></div><div class="row-actions" style="margin-top:10px"><button class="btn primary" id="docSave">Salvar</button>${existing?'<button class="btn danger" id="docDelete">Excluir documento</button>':''}</div>`;docStatus.value=doc.status;docBack.onclick=()=>renderDossier(appId,'docs');docSave.onclick=()=>{doc.title=docTitle.value.trim();if(!doc.title)return toast('Informe o título.');doc.category=docCategory.value.trim()||'Outros';doc.status=docStatus.value;doc.link=docLink.value.trim();doc.content=docContent.value;doc.updatedAt=new Date().toISOString();if(!existing)d.docs.push(doc);saveState();audit('Documento atualizado',`${a.name} • ${doc.title}`);renderDossier(appId,'docs')};if(existing)docDelete.onclick=()=>{if(!confirm('Excluir este documento?'))return;d.docs=d.docs.filter(x=>x.id!==doc.id);saveState();renderDossier(appId,'docs')}
}
function downloadDossierDoc(a,id){const doc=ensureDossier(a).docs.find(x=>x.id===id);if(!doc)return;dossierDownload(`${dossierSlug(a.name)}-${dossierSlug(doc.title)}.md`,doc.content||`# ${doc.title}\n\n${doc.link||''}`)}
function sendDossierDoc(a,id){const doc=ensureDossier(a).docs.find(x=>x.id===id);if(!doc)return;const body=`${doc.content||''}\n\nLink do documento/arquivo: ${doc.link||'Não informado'}`;dossierMail(a,'Documento',doc.title,`${a.name} — ${doc.title}`,body)}
function renderDossierRights(a){
  const d=ensureDossier(a),o=d.ownership;dossierPanel.innerHTML=`<div class="grid2"><div class="box"><h3>Titularidade e propriedade intelectual</h3><div class="field"><label>Autor/titular principal</label><input id="rOwner" value="${dossierEsc(o.authorOwner||'')}"></div><div class="field" style="margin-top:8px"><label>Data de criação / marco inicial</label><input id="rCreation" value="${dossierEsc(o.creationDate||'')}" placeholder="Ex.: 24/08/2026"></div><div class="field" style="margin-top:8px"><label>Repositório principal</label><input id="rRepo" value="${dossierEsc(o.repoUrl||'')}"></div><div class="field" style="margin-top:8px"><label>Arquivo-fonte / backup imutável</label><input id="rArchive" value="${dossierEsc(o.sourceArchiveUrl||'')}"></div><div class="field" style="margin-top:8px"><label>Registros, protocolos ou referências</label><textarea id="rRegs">${dossierEsc(o.registrationRefs||'')}</textarea></div><div class="field" style="margin-top:8px"><label>Marca / nome / protocolos</label><textarea id="rTrade">${dossierEsc(o.trademarkRefs||'')}</textarea></div><div class="field" style="margin-top:8px"><label>Licenças e cessões relevantes</label><textarea id="rLic">${dossierEsc(o.licenses||'')}</textarea></div><div class="field" style="margin-top:8px"><label>Observações</label><textarea id="rNotes">${dossierEsc(o.notes||'')}</textarea></div><button class="btn primary" id="rSave" style="margin-top:10px">Salvar direitos & titularidade</button></div><div class="box"><h3>Evidências de criação e titularidade</h3><p>Ex.: commit, release, documento datado, contrato, registro, domínio, e-mail, recibo ou arquivo com hash.</p><div class="form-grid"><div class="field"><label>Descrição</label><input id="eLabel"></div><div class="field"><label>Link / referência</label><input id="eUrl"></div></div><button class="btn small" id="eAdd" style="margin-top:8px">+ Adicionar evidência</button><div class="dossier-list compact-list">${d.evidence.length?d.evidence.map(e=>`<div class="dossier-row"><div><b>${dossierEsc(e.label)}</b><small>${dossierDate(e.when)}</small></div><div class="row-actions"><button class="btn small" data-eopen="${e.id}">Abrir</button><button class="btn danger small" data-edel="${e.id}">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhuma evidência cadastrada.</div>'}</div><p class="legal-note">Organizar evidências aqui fortalece a rastreabilidade, mas não equivale por si só a registro formal de software, marca ou obra.</p></div></div>`;
  rSave.onclick=()=>{Object.assign(o,{authorOwner:rOwner.value.trim(),creationDate:rCreation.value.trim(),repoUrl:rRepo.value.trim(),sourceArchiveUrl:rArchive.value.trim(),registrationRefs:rRegs.value.trim(),trademarkRefs:rTrade.value.trim(),licenses:rLic.value.trim(),notes:rNotes.value.trim()});saveState();audit('Direitos atualizados',a.name);toast('Titularidade salva.')};eAdd.onclick=()=>{const label=eLabel.value.trim(),url=eUrl.value.trim();if(!label||!url)return toast('Informe descrição e link.');d.evidence.unshift({id:crypto.randomUUID(),label,url,when:new Date().toISOString()});saveState();renderDossier(a.id,'rights')};$$('[data-eopen]').forEach(b=>b.onclick=()=>{const e=d.evidence.find(x=>x.id===b.dataset.eopen);if(e?.url)open(e.url,'_blank','noopener')});$$('[data-edel]').forEach(b=>b.onclick=()=>{d.evidence=d.evidence.filter(x=>x.id!==b.dataset.edel);saveState();renderDossier(a.id,'rights')})
}
function renderDossierDocGroup(a,category){
  const docs=ensureDossier(a).docs.filter(x=>x.category===category);dossierPanel.innerHTML=`<div class="panel dossier-subpanel"><div class="panel-head"><div><h2>${category}</h2><p>${category==='Marketing'?'Plano, posicionamento e materiais do produto.':'Arquitetura, componentes, APIs, integrações e licenças.'}</p></div></div><div class="dossier-list">${docs.map(doc=>`<div class="dossier-row"><div><b>${dossierEsc(doc.title)}</b><small>${doc.status==='final'?'Finalizado':doc.status==='review'?'Em revisão':'Base'}${doc.link?' • Link anexado':''}</small></div><div class="row-actions"><button class="btn small" data-gredit="${doc.id}">Editar</button><button class="btn small" data-grdown="${doc.id}">Baixar</button><button class="btn small" data-grsend="${doc.id}">Enviar</button></div></div>`).join('')}</div></div>`;$$('[data-gredit]').forEach(b=>b.onclick=()=>editDossierDoc(a.id,b.dataset.gredit));$$('[data-grdown]').forEach(b=>b.onclick=()=>downloadDossierDoc(a,b.dataset.grdown));$$('[data-grsend]').forEach(b=>b.onclick=()=>sendDossierDoc(a,b.dataset.grsend))
}
function renderDossierSent(a){
  const d=ensureDossier(a);dossierPanel.innerHTML=`<div class="panel dossier-subpanel"><div class="panel-head"><div><h2>Histórico de compartilhamento</h2><p>Registra o que foi preparado para envio, para qual e-mail e quando. O frontend não consegue confirmar a entrega final do provedor de e-mail.</p></div></div><div class="tablewrap"><table class="table"><thead><tr><th>Quando</th><th>Tipo</th><th>Item</th><th>Destinatário</th><th>Status</th></tr></thead><tbody>${d.sent.length?d.sent.map(s=>`<tr><td>${dossierDate(s.when)}</td><td>${dossierEsc(s.itemType)}</td><td>${dossierEsc(s.itemTitle)}</td><td>${dossierEsc(s.email)}</td><td>${dossierEsc(s.status)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum compartilhamento registrado.</td></tr>'}</tbody></table></div></div>`
}

if(typeof renderApps==='function')renderApps();