export const B144_CANDIDATE = {
  version: "B144",
  state: "CANDIDATE_NOT_PROMOTED",
  branch: "candidate/B144-owner-modules-products-2026-09-23",
  baseCommit: "eaa9941abf357cce268bc13f869b2598ab30a794",
  locked: true,
  rules: [
    "NO_OVERWRITE",
    "DERIVE_ONLY",
    "HASH_REQUIRED_BEFORE_USE",
    "SALVAR != PROMOVER",
    "OWNER_APPROVAL_REQUIRED",
  ],
} as const;

export const B144_PRODUCT_TAXONOMY = [
  {
    kind: "PROPRIETARIO",
    label: "Proprietário",
    description: "Identidade, conta e responsabilidade do owner.",
  },
  {
    kind: "MODULO",
    label: "Módulo",
    description: "Software funcional independente exposto dentro do ecossistema.",
  },
  {
    kind: "APLICATIVO_LEGADO",
    label: "Aplicativo legado",
    description: "Identidade histórica preservada para compatibilidade e linhagem.",
  },
  {
    kind: "CORE",
    label: "CORE",
    description:
      "Plataforma/capacidades técnicas compartilhadas; não absorve o escopo dos módulos.",
  },
  {
    kind: "PLUGIN_PROVIDER",
    label: "Plugin / Provider",
    description: "Integração externa ou capability conectável.",
  },
  {
    kind: "FERRAMENTA",
    label: "Ferramenta",
    description: "Utilitário operacional que não é módulo de negócio.",
  },
] as const;

export type B144ProductKind = (typeof B144_PRODUCT_TAXONOMY)[number]["kind"];

export const B144_MODULE_CATALOG = [
  {
    id: "B144-MOD-001",
    name: "LAMU IA — Meu Desenvolvimento",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Aplicativo móvel / desenvolvimento do colaborador",
    model: "APP_OWNED_INTEGRATED",
    version: "v1 COMPLETO",
    stage: "APPROVED_REFERENCE",
    placement: ["HEADER", "PRODUTOS"],
    route: "/owner/my-development",
  },
  {
    id: "B144-MOD-002",
    name: "LAMOU Orbit",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Agenda / rotina / diário / follow-up",
    model: "APP_OWNED_INTEGRATED",
    version: "V5.9 OWNER",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["HEADER", "PRODUTOS"],
    route: "/apps/orbit",
  },
  {
    id: "B144-MOD-003",
    name: "LAMOU App Processo",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Engenharia de processos",
    model: "APP_OWNED_INTEGRATED",
    version: "V0.2 DESIGN GOLD",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: null,
  },
  {
    id: "B144-MOD-004",
    name: "Certificações / Assurance 360",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Certificações e assurance",
    model: "APP_OWNED_INTEGRATED",
    version: "V0.3",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: null,
  },
  {
    id: "B144-MOD-005",
    name: "Treinamento",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Treinamento e capacitação",
    model: "APP_OWNED_INTEGRATED",
    version: "A_RECONCILIAR",
    stage: "DOCUMENTED_ONLY",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: "/core/trainings",
  },
  {
    id: "B144-MOD-006",
    name: "Seleção",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Seleção / pessoas",
    model: "APP_OWNED_INTEGRATED",
    version: "A_RECONCILIAR",
    stage: "DOCUMENTED_ONLY",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: null,
  },
  {
    id: "B144-MOD-007",
    name: "Perfil & Avaliação",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Perfil da pessoa / avaliação",
    model: "APP_OWNED_INTEGRATED",
    version: "RECOVERED_PREVIOUS",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: null,
  },
  {
    id: "B144-MOD-008",
    name: "PROJECT PRIME MASTER",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Gestão e sistema operacional de projetos",
    model: "APP_OWNED_INTEGRATED",
    version: "V1",
    stage: "APPROVED_REFERENCE",
    placement: ["PLANOS_DE_ACAO", "PRODUTOS"],
    route: null,
  },
  {
    id: "B144-MOD-009",
    name: "Metraction 360",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Indicadores / métricas / rastreabilidade",
    model: "APP_OWNED_INTEGRATED",
    version: "V0.4 VISUAL BASELINE",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["INDICADORES", "PRODUTOS"],
    route: "/core/health",
  },
  {
    id: "B144-MOD-010",
    name: "LAMOU Showroom",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Showroom comercial / demonstração",
    model: "APP_OWNED_INTEGRATED",
    version: "V0.4 DESIGN C",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["COMERCIAL", "PRODUTOS"],
    route: "/apps/showroom",
  },
  {
    id: "B144-MOD-011",
    name: "Teste³ IA",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Execução de testes e evidências",
    model: "APP_OWNED_INTEGRATED",
    version: "V0.2",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["LABTEST", "PRODUTOS"],
    route: "/apps/teste3",
  },
  {
    id: "B144-MOD-012",
    name: "Validation Gate",
    kind: "MODULO",
    ownership: "PROPRIETARIO",
    software: "Validação por gates e evidências",
    model: "APP_OWNED_INTEGRATED",
    version: "CANDIDATE",
    stage: "CANDIDATE_NOT_PROMOTED",
    placement: ["LABTEST", "PRODUTOS"],
    route: "/apps/validation-gate",
  },
  {
    id: "B144-CORE-001",
    name: "LAMOU CORE",
    kind: "CORE",
    ownership: "PROPRIETARIO",
    software: "Plataforma técnica compartilhada",
    model: "CORE_PLATFORM",
    version: "CURRENT_CANDIDATE_LINEAGE",
    stage: "PARTIAL",
    placement: ["PRODUTOS", "CORE"],
    route: "/core",
  },
] as const;

export const B144_ACTION_PLAN_MODULES = B144_MODULE_CATALOG.filter((item) =>
  item.placement.includes("PLANOS_DE_ACAO"),
);

export const B144_LABTEST_MODULES = B144_MODULE_CATALOG.filter((item) =>
  item.placement.includes("LABTEST"),
);

export const B144_HEADER_MODULES = B144_MODULE_CATALOG.filter((item) =>
  item.placement.includes("HEADER"),
);

export const RADAR_OPPORTUNITY_PROMPT = {
  id: "PROMPT-RADAR-OPPORTUNITY-B144",
  version: "B144",
  state: "DOCUMENTED_ONLY",
  runtime: "NOT_CONNECTED",
  owner: "LAMOU IA Central / Proprietário",
  consumers: ["CENTRAL:commercial", "CENTRAL:opportunities", "APP:opportunity-intelligence"],
  purpose:
    "Ler sinais comerciais e de mercado, estruturar oportunidades com evidência e encaminhar para Comercial e Radar de Oportunidades sem inventar fatos.",
  requiredInput: [
    "source_id",
    "signal",
    "freshness",
    "evidence_ids",
    "client_or_market_context",
    "problem_or_need",
  ],
  output: [
    "opportunity_id",
    "signal_summary",
    "problem_or_need",
    "hypothesis",
    "fit",
    "risk",
    "evidence_ids",
    "freshness",
    "recommended_next_step",
  ],
  promptContract: [
    "Use somente sinais e evidências com origem identificada.",
    "Separe fato, hipótese e inferência.",
    "Não transforme similaridade em probabilidade.",
    "Marque informação ausente como NÃO VERIFICADO.",
    "Não promova oportunidade automaticamente.",
    "Entregue o mesmo opportunity_id para Comercial e Radar de Oportunidades.",
  ],
} as const;
