import {
  Boxes,
  CreditCard,
  Image,
  Brain,
  Database,
  DollarSign,
  Eye,
  Flag,
  Plug,
  Server,
  ShieldCheck,
  Sun,
  Timer,
} from "lucide-react";

import type { SettingsSection } from "@/lib/lamou/settings-data";

/** Configurações técnicas do CORE PROPRIETÁRIO.
 *  Item 9 do menu canônico. Reúne ambientes, runtime, providers/modelos,
 *  APIs/scopes, integrações, segurança/tenants, observabilidade, backup,
 *  limites, custos, feature flags e comportamento de falha.
 *  Nada aqui aplica mudança em serviço externo: SALVAR ≠ PROMOVER. */
export const CORE_SETTINGS_SECTIONS: SettingsSection[] = [
  {
    id: "environments",
    label: "Ambientes & Runtime",
    icon: Server,
    title: "Ambientes & Runtime",
    subtitle:
      "Ambientes técnicos do CORE, runtime de execução e destino de cada build. Registro local governado.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Ambiente de desenvolvimento (oficina)",
        definition: "Ambiente onde a candidata é construída e alterada.",
        source: "Runtime da candidata em execução",
        truth: "IMPLEMENTED_VERIFIED",
        reason: "É o ambiente que serve esta interface agora.",
        nextStep: "Acompanhar builds e rollback em Versões & Atualizações.",
        destination: "/core/versions",
        actionLabel: "Abrir Versões",
      },
      {
        title: "Homologação / pré-promoção",
        definition: "Ambiente onde a candidata é testada antes de qualquer promoção.",
        source: "LABTEST — fila de próxima versão",
        truth: "PARTIAL",
        reason: "A fila existe, mas a promoção permanece bloqueada por gate.",
        nextStep: "Revisar itens READY e evidências na fila de promoção.",
        destination: "/labtest",
        actionLabel: "Abrir LABTEST",
      },
      {
        title: "Produção do proprietário",
        definition: "Ambiente publicado do console do proprietário.",
        source: "Publicação do projeto",
        truth: "NOT_CONNECTED",
        reason: "A candidata não foi publicada nem promovida.",
        nextStep: "Publicar somente após os gates de validação.",
      },
    ],
    crud: {
      id: "core-environments",
      title: "Registro de ambientes",
      description:
        "Cadastro local dos ambientes técnicos reconhecidos pelo CORE. Não provisiona infraestrutura.",
      fields: [
        { key: "name", label: "Ambiente", type: "text", required: true },
        {
          key: "kind",
          label: "Tipo",
          type: "select",
          options: ["Desenvolvimento", "Homologação", "Produção"],
          required: true,
        },
        {
          key: "state",
          label: "Estado",
          type: "select",
          options: ["Ativo", "Bloqueado", "Não conectado"],
          required: true,
        },
        { key: "owner", label: "Responsável", type: "text" },
      ],
      seed: [
        { name: "Oficina (candidata)", kind: "Desenvolvimento", state: "Ativo", owner: "Rafael" },
        { name: "Homologação LABTEST", kind: "Homologação", state: "Bloqueado", owner: "Rafael" },
        { name: "Produção Owner", kind: "Produção", state: "Não conectado", owner: "Rafael" },
      ],
    },
  },
  {
    id: "providers",
    label: "Providers & Modelos",
    icon: Brain,
    title: "Providers, Modelos & Agentes",
    subtitle:
      "Slots técnicos de IA, prompts e agentes. Qualquer troca passa pela prévia de impacto Atual → Novo.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Provider de IA do CORE",
        definition: "Serviço que executa análises, prompts e agentes do ecossistema.",
        source: "Gateway de IA do ambiente · chamada medida e registrada",
        truth: "PARTIAL",
        reason:
          "O provider está ligado e responde a teste real; a evidência depende de executar a chamada nesta tela.",
        nextStep: "Executar o teste real abaixo e definir o modelo em referência (SOL).",
        destination: "/core/ai",
        actionLabel: "Abrir IA, Prompts & Agentes",
      },
      {
        title: "Latência medida por modelo",
        definition: "Tempo real de resposta registrado por chamada executada.",
        source: "Registro de chamadas do CORE",
        truth: "PARTIAL",
        reason: "A latência é medida a cada teste; qualidade comparada ainda não foi avaliada.",
        nextStep: "Executar o teste no SOL e no candidato para comparar latência real.",
      },
      {
        title: "Benchmark de qualidade dos modelos",
        definition: "Comparação medida entre modelos candidatos e o modelo atual.",
        source: "Testes & Qualidade do CORE",
        truth: "NOT_VERIFIED",
        reason: "Sem execução real, nenhum percentual pode ser afirmado.",
        nextStep: "Rodar a bateria de testes e anexar evidência antes de decidir.",
        destination: "/core/tests",
        actionLabel: "Abrir Testes & Qualidade",
      },
    ],
    substitution: true,
    live: "providers",
  },
  {
    id: "apis",
    label: "APIs, Scopes & CALLs",
    icon: Plug,
    title: "APIs, Scopes & CALLs",
    subtitle:
      "Contratos técnicos de entrada e saída: origem, destino, autenticação, timeout, retry e fallback.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "CALL Registry",
        definition: "Catálogo dos contratos de chamada entre apps, CORE e serviços.",
        source: "Registry técnico do CORE",
        truth: "PARTIAL",
        reason: "Os contratos estão documentados; as execuções reais não foram evidenciadas.",
        nextStep: "Abrir o registry e anexar evidência por CALL.",
        destination: "/core/calls",
        actionLabel: "Abrir CALLs & Contratos",
      },
      {
        title: "Chaves e escopos de API",
        definition: "Credenciais e permissões concedidas a cada integração.",
        source: "Segredos do ambiente",
        truth: "NOT_CONNECTED",
        reason: "Nenhuma credencial externa foi cadastrada para a candidata.",
        nextStep: "Cadastrar credenciais no ambiente antes de habilitar a integração.",
      },
    ],
    crud: {
      id: "core-apis",
      title: "Registro de contratos de API",
      description: "Cadastro local de contratos técnicos. Não emite chamada externa.",
      fields: [
        { key: "name", label: "Contrato", type: "text", required: true },
        { key: "direction", label: "Direção", type: "select", options: ["Entrada", "Saída"] },
        {
          key: "auth",
          label: "Autenticação",
          type: "select",
          options: ["Bearer", "OAuth", "Assinatura", "Não definida"],
        },
        { key: "fallback", label: "Fallback", type: "text" },
      ],
      seed: [
        {
          name: "CALL-0001 Mapa Vivo ← Observabilidade",
          direction: "Entrada",
          auth: "Não definida",
          fallback: "Exibir NOT_VERIFIED",
        },
      ],
    },
  },
  {
    id: "security",
    label: "Segurança & Tenants",
    icon: ShieldCheck,
    title: "Segurança, Identidade & Tenants",
    subtitle:
      "Identidade do proprietário, isolamento por tenant, políticas de acesso e trilha de auditoria técnica.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Identidade e acesso do proprietário",
        definition: "Cadastro, entrada, recuperação e segundo fator do proprietário.",
        source: "Autenticação real do ambiente",
        truth: "PARTIAL",
        reason:
          "Cadastro, entrada, recuperação e perfil estão verificados; o segundo fator exige e-mail confirmado.",
        nextStep: "Concluir a confirmação de e-mail e registrar o autenticador.",
        destination: "/install/owner",
        actionLabel: "Abrir instalação",
      },
      {
        title: "Isolamento por tenant",
        definition: "Garantia de que cada cliente só acessa os próprios dados.",
        source: "Políticas de acesso do banco",
        truth: "PARTIAL",
        reason:
          "As políticas existem para o perfil do proprietário; tenants de cliente não existem ainda.",
        nextStep: "Revisar Segurança & Tenants antes do primeiro provisionamento real.",
        destination: "/core/security",
        actionLabel: "Abrir Segurança & Tenants",
      },
    ],
  },
  {
    id: "data",
    label: "Dados & Fontes",
    icon: Database,
    title: "Dados, Fontes & Conhecimento",
    subtitle:
      "Biblioteca de fontes com origem, responsável, atualização e consumidores. Toda informação deve voltar à fonte.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Registry de dados e fontes",
        definition: "Catálogo das fontes que alimentam telas, métricas e análises.",
        source: "Registry de dados do CORE",
        truth: "PARTIAL",
        reason: "As fontes estão catalogadas; a maior parte ainda é demonstração sintética.",
        nextStep: "Abrir o registry e conectar as fontes reais uma a uma.",
        destination: "/core/data",
        actionLabel: "Abrir Dados & Fontes",
      },
      {
        title: "Dados de demonstração",
        definition: "Conteúdo criado para demonstrar a interface, não medição real.",
        source: "Fixtures da candidata",
        truth: "SYNTHETIC_DEMO",
        reason: "Sem integração, o conteúdo exibido é demonstração declarada.",
        nextStep: "Substituir por fonte real e registrar evidência.",
      },
    ],
  },
  {
    id: "observability",
    label: "Observabilidade",
    icon: Eye,
    title: "Observabilidade & Sinais",
    subtitle:
      "Logs, métricas, incidentes, latência e custo operacional com caminho de volta à fonte.",
    truth: "NOT_CONNECTED",
    statuses: [
      {
        title: "Coleta de sinais",
        definition: "Recebimento contínuo de logs, métricas e incidentes.",
        source: "Plataforma de observabilidade",
        truth: "NOT_CONNECTED",
        reason: "Nenhuma plataforma de observabilidade foi conectada.",
        nextStep: "Conectar a coleta e validar o primeiro sinal real.",
        destination: "/core/observability",
        actionLabel: "Abrir Observabilidade",
      },
    ],
  },
  {
    id: "backup",
    label: "Backup & Recuperação",
    icon: Boxes,
    title: "Backup, Restauração & Rollback",
    subtitle: "Cópias, retenção, teste de restauração e retorno para a versão anterior.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Rollback de versão",
        definition: "Retorno controlado para a versão anterior do CORE.",
        source: "Versões & Atualizações",
        truth: "PARTIAL",
        reason: "O caminho existe na candidata; nenhuma restauração real foi executada.",
        nextStep: "Executar um teste de restauração e anexar evidência.",
        destination: "/core/versions",
        actionLabel: "Abrir Versões",
      },
      {
        title: "Cópia externa de segurança",
        definition: "Backup guardado fora do ambiente de execução.",
        source: "Serviço de backup",
        truth: "NOT_CONNECTED",
        reason: "Nenhum serviço de backup externo foi conectado.",
        nextStep: "Definir destino, retenção e responsável antes de ativar.",
      },
    ],
  },
  {
    id: "limits",
    label: "Limites & Falhas",
    icon: Timer,
    title: "Limites, Timeout & Comportamento de Falha",
    subtitle: "Como o CORE deve se comportar em lentidão, erro, indisponibilidade e recuperação.",
    truth: "DOCUMENTED_ONLY",
    statuses: [
      {
        title: "Política de timeout e retry",
        definition: "Tempo máximo de espera e número de novas tentativas por chamada.",
        source: "Contrato de cada CALL",
        truth: "DOCUMENTED_ONLY",
        reason: "A política está descrita nos contratos, sem execução medida.",
        nextStep: "Validar por CALL em Testes & Qualidade.",
        destination: "/core/tests",
        actionLabel: "Abrir Testes & Qualidade",
      },
      {
        title: "Comportamento em indisponibilidade",
        definition: "O que a interface mostra quando a fonte não responde.",
        source: "Regra de exibição da candidata",
        truth: "IMPLEMENTED_VERIFIED",
        reason: "Sem fonte, a interface mostra estado NOT_CONNECTED em vez de inventar número.",
        nextStep: "Manter a regra em toda nova superfície.",
      },
    ],
    crud: {
      id: "core-limits",
      title: "Registro de limites",
      description: "Cadastro local dos limites técnicos acordados por área.",
      fields: [
        { key: "area", label: "Área", type: "text", required: true },
        { key: "limit", label: "Limite", type: "text", required: true },
        { key: "onFail", label: "Em falha", type: "text" },
      ],
      seed: [
        {
          area: "Análise de IA",
          limit: "Sem provider conectado",
          onFail: "Exibir IA não conectada",
        },
        { area: "Métricas do Mapa Vivo", limit: "Sem medição real", onFail: "Exibir NOT_VERIFIED" },
      ],
    },
  },
  {
    id: "costs",
    label: "Custos & Consumo",
    icon: DollarSign,
    title: "Custos & Consumo",
    subtitle: "Consumo por provider, área e ambiente, sempre com origem declarada.",
    truth: "NOT_VERIFIED",
    statuses: [
      {
        title: "Consumo por provider",
        definition: "Custo medido de cada serviço usado pelo CORE.",
        source: "Faturamento do provider de IA",
        truth: "NOT_VERIFIED",
        reason:
          "As chamadas ao provider já são registradas com latência, mas o custo por chamada não é importado.",
        nextStep: "Importar o consumo do provider antes de afirmar qualquer valor.",
        destination: "/core/ai",
        actionLabel: "Abrir IA, Prompts & Agentes",
      },
    ],
  },
  {
    id: "sol",
    label: "SOL — Referência",
    icon: Sun,
    title: "SOL — Referência Operacional Corrente",
    subtitle:
      "O que hoje é referência de operação: ambiente, modelo de IA, identidade, faturamento e publicação. LUA vive no LABTEST.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Regra SOL × LUA",
        definition: "SOL é a referência corrente; LUA são candidatas e experimentos.",
        source: "Governança da candidata",
        truth: "IMPLEMENTED_VERIFIED",
        reason: "A separação está aplicada na navegação e nas superfícies.",
        nextStep: "Comparar candidata no LABTEST antes de qualquer promoção.",
        destination: "/labtest",
        actionLabel: "Abrir LABTEST",
      },
    ],
    live: "sol",
  },
  {
    id: "billing",
    label: "Faturamento & Planos",
    icon: CreditCard,
    title: "Faturamento, Planos & Cobrança",
    subtitle:
      "Planos e cobranças registrados em base real com isolamento por proprietário. Emissão por gateway permanece desconectada.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Registro de planos e cobranças",
        definition: "Cadastro persistente de planos, valores, ciclos e cobranças por cliente.",
        source: "Base de dados do proprietário (RLS por auth.uid())",
        truth: "IMPLEMENTED_VERIFIED",
        reason: "Os registros gravam e leem na base real da candidata.",
        nextStep: "Vincular os planos aos contratos em Comercial & Contratos.",
        destination: "/owner/commercial",
        actionLabel: "Abrir Comercial",
      },
      {
        title: "Gateway de pagamento",
        definition: "Serviço que emite e concilia a cobrança de verdade.",
        source: "Provedor de pagamento",
        truth: "NOT_CONNECTED",
        reason: "Nenhum provedor de pagamento foi conectado à candidata.",
        nextStep: "Conectar o provedor de pagamento antes de emitir qualquer cobrança.",
      },
    ],
    live: "billing",
  },
  {
    id: "storage",
    label: "Armazenamento",
    icon: Image,
    title: "Armazenamento de Imagem & Arquivos",
    subtitle:
      "Bucket privado do proprietário com leitura por link assinado. Nenhum arquivo público.",
    truth: "IMPLEMENTED_VERIFIED",
    statuses: [
      {
        title: "Bucket privado do proprietário",
        definition: "Espaço de arquivos restrito à pasta do próprio proprietário.",
        source: "Armazenamento do ambiente · políticas por auth.uid()",
        truth: "IMPLEMENTED_VERIFIED",
        reason: "O bucket existe com limite de 5 MB e acesso restrito por política.",
        nextStep: "Enviar a imagem do proprietário e conferir o vínculo no perfil.",
        destination: "/install/owner",
        actionLabel: "Abrir instalação",
      },
    ],
    live: "storage",
  },
  {
    id: "flags",
    label: "Feature Flags",
    icon: Flag,
    title: "Feature Flags & Experimentos",
    subtitle:
      "Chaves que ligam ou desligam comportamento. Experimentos vivem no LABTEST, nunca no menu operacional.",
    truth: "PARTIAL",
    statuses: [
      {
        title: "Experimentos e candidatas",
        definition: "Conceitos em teste que ainda não são referência operacional.",
        source: "LABTEST",
        truth: "PARTIAL",
        reason: "Existem candidatas registradas, nenhuma promovida.",
        nextStep: "Comparar com a referência atual antes de qualquer promoção.",
        destination: "/labtest",
        actionLabel: "Abrir LABTEST",
      },
    ],
    crud: {
      id: "core-flags",
      title: "Registro de flags",
      description: "Cadastro local de chaves de comportamento. Não altera o runtime.",
      fields: [
        { key: "key", label: "Chave", type: "text", required: true },
        { key: "state", label: "Estado", type: "select", options: ["Ligada", "Desligada"] },
        { key: "scope", label: "Escopo", type: "text" },
      ],
      seed: [
        { key: "core.ai.analysis", state: "Desligada", scope: "Mapa Vivo, Planos" },
        { key: "labtest.promotion", state: "Desligada", scope: "Fila de próxima versão" },
      ],
    },
  },
];
