import type {
  ActionPlan,
  AppProduct,
  AssetItem,
  CaseNode,
  ClientAccount,
  Contract,
  Improvement,
  ModuleCard,
  Scenario,
  SecurityAlert,
  TestRun,
  VersionEntry,
} from "./types";

const ev = (id: string, kind: import("./types").Evidence["kind"], label: string) => ({
  id,
  kind,
  label,
  demo: true,
});

export const MODULES: ModuleCard[] = [
  {
    id: "mapa",
    name: "Mapa Vivo",
    route: "/mapa",
    summary: "Cidade viva do ecossistema, casos e ocorrências em tempo de análise.",
    severity: "critico",
    pendings: [
      {
        id: "p-map-1",
        label: "2 ocorrências piscando sem destino definido",
        severity: "critico",
        resolved: false,
      },
      {
        id: "p-map-2",
        label: "1 sinal de tendência sem evidência anexada",
        severity: "tendencia",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Casos abertos", value: "6", demo: true },
      { label: "Ocorrências ativas", value: "3", demo: true },
    ],
  },
  {
    id: "aplicativos",
    name: "Aplicativos",
    route: "/aplicativos",
    summary: "Catálogo dos produtos LAMOU com canais OFICIAL, DEMO e TESTE.",
    severity: "tendencia",
    pendings: [
      {
        id: "p-app-1",
        label: "Canal DEMO sem rota real em 2 produtos",
        severity: "tendencia",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Produtos", value: "5", demo: true },
      { label: "Em homologação", value: "2", demo: true },
    ],
  },
  {
    id: "clientes",
    name: "Clientes",
    route: "/clientes",
    summary: "Cliente 360, ambientes TESTE e OFICIAL, preview client-safe.",
    severity: "probabilidade",
    pendings: [
      {
        id: "p-cli-1",
        label: "Implantação parada na etapa de storage isolado",
        severity: "probabilidade",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Clientes", value: "4", demo: true },
      { label: "Ambientes OFICIAL", value: "2", demo: true },
    ],
  },
  {
    id: "comercial",
    name: "Comercial & Contratos",
    route: "/comercial",
    summary: "Contratos, planos, entitlements, licenças, pagamentos e uso.",
    severity: "tendencia",
    pendings: [
      {
        id: "p-com-1",
        label: "1 contrato sem entitlement mapeado",
        severity: "tendencia",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Contratos ativos", value: "3", demo: true },
      { label: "Em negociação", value: "1", demo: true },
    ],
  },
  {
    id: "testes",
    name: "Testes & Qualidade",
    route: "/testes",
    summary: "Teste³ IA como executor transversal, evidências e reteste.",
    severity: "critico",
    pendings: [
      {
        id: "p-tst-1",
        label: "1 reteste pendente após correção",
        severity: "critico",
        resolved: false,
      },
      {
        id: "p-tst-2",
        label: "1 resultado marcado como falso positivo sem revisão",
        severity: "probabilidade",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Execuções registradas", value: "7", demo: true },
      { label: "Reprovados", value: "2", demo: true },
    ],
  },
  {
    id: "planos",
    name: "Planos de Ação & Melhorias",
    route: "/planos",
    summary: "Itens de ação com definição obrigatória e trilhas de melhoria.",
    severity: "critico",
    pendings: [
      {
        id: "p-pln-1",
        label: "2 planos em AGUARDANDO DEFINIÇÃO",
        severity: "critico",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Planos abertos", value: "3", demo: true },
      { label: "Oportunidades", value: "3", demo: true },
    ],
  },
  {
    id: "core",
    name: "CORE",
    route: "/core",
    summary: "CORE Padrão e CORE Cubo como camadas distintas.",
    severity: "probabilidade",
    pendings: [
      {
        id: "p-core-1",
        label: "Caleidoscópio com cenário adormecido a revalidar",
        severity: "probabilidade",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Recursos experimentais", value: "6", demo: true },
      { label: "Cenários de resiliência", value: "5", demo: true },
    ],
  },
  {
    id: "seguranca",
    name: "Segurança",
    route: "/seguranca",
    summary: "Visão defensiva: integridade, isolamento, incidentes e evidências.",
    severity: "critico",
    pendings: [
      {
        id: "p-sec-1",
        label: "1 alerta de integridade aberto",
        severity: "critico",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Alertas abertos", value: "2", demo: true },
      { label: "Snapshots íntegros", value: "4", demo: true },
    ],
  },
  {
    id: "versoes",
    name: "Versões",
    route: "/versoes",
    summary: "Baseline preservada, candidata, gate de promoção e rollback.",
    severity: "tendencia",
    pendings: [
      {
        id: "p-ver-1",
        label: "Candidata aguardando gate de promoção",
        severity: "tendencia",
        resolved: false,
      },
    ],
    metrics: [
      { label: "Builds", value: "5", demo: true },
      { label: "Baseline FROZEN", value: "1", demo: true },
    ],
  },
  {
    id: "configuracoes",
    name: "Configurações",
    route: "/configuracoes",
    summary: "Identidade, permissões, IA, integrações, LGPD, quotas e Modo Painel/TV.",
    severity: "normal",
    pendings: [],
    metrics: [
      { label: "Integrações reais", value: "0", demo: false },
      { label: "Áreas configuráveis", value: "14", demo: true },
    ],
  },
  {
    id: "biblioteca",
    name: "Biblioteca Visual",
    route: "/biblioteca",
    summary: "Inventário de imagens, ícones e logos com código imutável e versão.",
    severity: "normal",
    pendings: [],
    metrics: [
      { label: "Assets catalogados", value: "16", demo: true },
      { label: "Congelados", value: "4", demo: true },
    ],
  },
];

export const CASES: CaseNode[] = [
  {
    id: "CASO-0001",
    title: "Latência anômala no gateway de IA",
    district: "CORE — Bairro de Plataforma",
    layer: "padrao",
    x: 30,
    y: 34,
    severity: "critico",
    occurrence: true,
    stage: "evidencia",
    classification: "Desempenho / dependência externa",
    origin: "Telemetria do CORE Padrão",
    signal: "Tempo de resposta subiu de forma sustentada em janelas consecutivas",
    description:
      "Sinal recorrente de latência no caminho de inferência. Ainda não há método fechado para converter recorrência em probabilidade.",
    evidences: [
      ev("e1", "log", "Amostra de logs sintéticos de latência"),
      ev("e2", "métrica", "Série temporal DEMO"),
    ],
    metrics: [
      { label: "Recorrência", value: "4 janelas", demo: true },
      { label: "Impacto percebido", value: "médio", demo: true },
    ],
    actors: ["CORE Padrão", "Provider de IA (não conectado)"],
    hypotheses: ["Fila do provider", "Payload maior que o previsto", "Retry mal calibrado"],
    probability: null,
    history: [
      { at: "2026-09-05", text: "Sinal detectado e classificado" },
      { at: "2026-09-07", text: "Evidências sintéticas anexadas" },
    ],
    destination: null,
  },
  {
    id: "CASO-0002",
    title: "Divergência de snapshot entre baseline e candidata",
    district: "CORE Cubo — Distrito Experimental",
    layer: "cubo",
    x: 63,
    y: 26,
    severity: "falha",
    occurrence: true,
    stage: "teste",
    classification: "Integridade / versionamento",
    origin: "Comparação de snapshot",
    signal: "Hash divergente em artefato que deveria estar congelado",
    description:
      "Cubo Fantasma indicou divergência entre baseline FROZEN e candidata. Requer bloqueio de promoção até evidência conclusiva.",
    evidences: [ev("e3", "documento", "Relatório de comparação (simulado)")],
    metrics: [{ label: "Artefatos divergentes", value: "2", demo: true }],
    actors: ["Snapshot", "Cubo Fantasma", "Gate de promoção"],
    hypotheses: ["Escrita fora do fluxo", "Build não determinístico"],
    probability: null,
    history: [{ at: "2026-09-08", text: "Divergência registrada pelo Cubo Fantasma" }],
    destination: null,
  },
  {
    id: "CASO-0003",
    title: "Cliente com implantação parada em storage isolado",
    district: "Clientes — Zona de Implantação",
    layer: "padrao",
    x: 46,
    y: 58,
    severity: "probabilidade",
    occurrence: true,
    stage: "sinal",
    classification: "Implantação / isolamento",
    origin: "Checklist de implantação",
    signal: "Etapa de storage isolado sem confirmação há 3 ciclos",
    description:
      "A implantação não avança sem confirmação de isolamento de arquivos. Sem integração real conectada, a etapa só pode ser marcada manualmente.",
    evidences: [ev("e4", "relato", "Anotação de implantação (DEMO)")],
    metrics: [{ label: "Ciclos parados", value: "3", demo: true }],
    actors: ["Cliente Meridiano", "Equipe de implantação"],
    hypotheses: ["Falta de política de bucket", "Pendência contratual"],
    probability: null,
    history: [{ at: "2026-09-06", text: "Etapa sinalizada como parada" }],
    destination: null,
  },
  {
    id: "CASO-0004",
    title: "Oportunidade: padronizar corte de ícones de módulo",
    district: "Biblioteca Visual — Ateliê",
    layer: "padrao",
    x: 78,
    y: 62,
    severity: "tendencia",
    occurrence: false,
    stage: "decisao",
    classification: "Padronização visual",
    origin: "Revisão de assets",
    signal: "Identificação dentro da área de recorte em ícones antigos",
    description: "Oportunidade de melhoria com efeito direto em consistência de interface.",
    evidences: [ev("e5", "print", "Comparativo de recorte (DEMO)")],
    metrics: [{ label: "Ícones afetados", value: "5", demo: true }],
    actors: ["Biblioteca Visual"],
    hypotheses: ["Falta de guia de recorte versionado"],
    probability: null,
    history: [{ at: "2026-09-02", text: "Registrado como oportunidade" }],
    destination: null,
  },
  {
    id: "CASO-0005",
    title: "Falso positivo suspeito em teste de integração",
    district: "Testes — Laboratório",
    layer: "padrao",
    x: 18,
    y: 70,
    severity: "tendencia",
    occurrence: false,
    stage: "resultado",
    classification: "Qualidade / confiabilidade de teste",
    origin: "Teste³ IA",
    signal: "Reprovação sem reprodução manual",
    description: "Resultado marcado como falso positivo aguardando segunda opinião e reteste.",
    evidences: [ev("e6", "log", "Execução divergente (simulada)")],
    metrics: [{ label: "Reproduções", value: "0/3", demo: true }],
    actors: ["Teste³ IA"],
    hypotheses: ["Ambiente sujo", "Timeout curto"],
    probability: null,
    history: [{ at: "2026-09-04", text: "Classificado para revisão" }],
    destination: null,
  },
  {
    id: "CASO-0006",
    title: "Cenário adormecido do Caleidoscópio sem revalidação",
    district: "CORE Cubo — Caleidoscópio",
    layer: "cubo",
    x: 68,
    y: 44,
    severity: "probabilidade",
    occurrence: false,
    stage: "origem",
    classification: "Resiliência",
    origin: "Rotina de drills",
    signal: "Cenário sem drill dentro da janela definida",
    description:
      "Cenário de resiliência precisa de revalidação antes de ser considerado confiável.",
    evidences: [],
    metrics: [{ label: "Dias sem drill", value: "62", demo: true }],
    actors: ["Caleidoscópio"],
    hypotheses: ["Janela de drill não agendada"],
    probability: null,
    history: [{ at: "2026-09-01", text: "Marcado para revalidação" }],
    destination: null,
  },
];

export const APPS: AppProduct[] = [
  {
    id: "app-condominio",
    name: "Condomínio Reclame",
    summary: "Registro, prova e acompanhamento de ocorrências em condomínios.",
    status: "homologação",
    version: "0.9.4",
    health: "tendencia",
    coreUsed: ["padrao"],
    tech: ["TanStack Start", "TypeScript", "Tailwind", "Postgres"],
    channels: [
      { channel: "OFICIAL", route: null },
      { channel: "DEMO", route: null },
      { channel: "TESTE", route: null },
    ],
    clients: ["Residencial Meridiano", "Edifício Aurora"],
    tests: { passed: 24, failed: 3, demo: true },
    docs: ["Escopo funcional", "Matriz de privacidade", "Guia de implantação"],
    history: [{ at: "2026-08-28", text: "Candidata 0.9.4 gerada" }],
  },
  {
    id: "app-lamou-core",
    name: "LAMOU CORE (Owner)",
    summary: "Este ambiente: núcleo proprietário e global, nunca entregue a cliente.",
    status: "desenvolvimento",
    version: "1.0.0-owner",
    health: "normal",
    coreUsed: ["padrao", "cubo"],
    tech: ["TanStack Start", "TypeScript", "Tailwind", "shadcn/ui"],
    channels: [
      { channel: "OFICIAL", route: "/" },
      { channel: "DEMO", route: null },
      { channel: "TESTE", route: null },
    ],
    clients: [],
    tests: { passed: 12, failed: 0, demo: true },
    docs: ["Arquitetura Owner", "Separação Owner × Cliente"],
    history: [{ at: "2026-09-09", text: "Primeira versão navegável" }],
  },
  {
    id: "app-lamuya-maps",
    name: "LAMOU IA Mapa Vivo",
    summary: "Camada visual de cidade/ecossistema para leitura de casos.",
    status: "desenvolvimento",
    version: "0.4.1",
    health: "probabilidade",
    coreUsed: ["cubo"],
    tech: ["React", "SVG", "TypeScript"],
    channels: [
      { channel: "OFICIAL", route: "/mapa" },
      { channel: "DEMO", route: null },
      { channel: "TESTE", route: null },
    ],
    clients: [],
    tests: { passed: 6, failed: 2, demo: true },
    docs: ["Modelo do CASO"],
    history: [{ at: "2026-09-03", text: "Painel lateral do caso implementado" }],
  },
  {
    id: "app-teste3",
    name: "Teste³ IA",
    summary: "Executor transversal de testes com registro de evidência e eficácia.",
    status: "produção",
    version: "2.1.0",
    health: "normal",
    coreUsed: ["padrao", "cubo"],
    tech: ["TypeScript", "Runner próprio"],
    channels: [
      { channel: "OFICIAL", route: "/testes" },
      { channel: "DEMO", route: null },
      { channel: "TESTE", route: null },
    ],
    clients: ["Residencial Meridiano"],
    tests: { passed: 41, failed: 1, demo: true },
    docs: ["Manual do executor"],
    history: [{ at: "2026-07-19", text: "Promovido para produção" }],
  },
  {
    id: "app-caleidoscopio",
    name: "Caleidoscópio",
    summary: "Motor de cenários, resiliência, drills e pós-falha preditivo.",
    status: "desenvolvimento",
    version: "0.2.7",
    health: "probabilidade",
    coreUsed: ["cubo"],
    tech: ["TypeScript", "Simulação determinística"],
    channels: [
      { channel: "OFICIAL", route: "/core" },
      { channel: "DEMO", route: null },
      { channel: "TESTE", route: null },
    ],
    clients: [],
    tests: { passed: 3, failed: 1, demo: true },
    docs: ["Cenários A/B/C/D/SAFE"],
    history: [{ at: "2026-08-11", text: "Cenários adormecidos introduzidos" }],
  },
];

export const CLIENTS: ClientAccount[] = [
  {
    id: "cli-meridiano",
    name: "Residencial Meridiano",
    segment: "Condomínio residencial",
    environment: "OFICIAL",
    plan: "profissional",
    deployment: [
      { step: "Contrato assinado", done: true },
      { step: "Tenant provisionado", done: true },
      { step: "Identidade visual aplicada", done: true },
      { step: "Storage isolado confirmado", done: false },
      { step: "Usuários iniciais", done: false },
      { step: "Homologação com cliente", done: false },
    ],
    apps: ["Condomínio Reclame", "Teste³ IA"],
    core: ["padrao"],
    contractId: "CT-2026-014",
    billing: [{ label: "Mensalidade corrente", status: "em dia", demo: true }],
    updates: [{ at: "2026-09-02", text: "Atualização 0.9.3 aplicada no ambiente OFICIAL" }],
    tests: ["TST-0002", "TST-0005"],
    docs: ["Contrato", "Termo de privacidade", "Ata de homologação"],
    support: [{ at: "2026-09-06", text: "Dúvida sobre prova de envio", open: true }],
    history: [{ at: "2026-06-10", text: "Cliente criado" }],
  },
  {
    id: "cli-aurora",
    name: "Edifício Aurora",
    segment: "Condomínio residencial",
    environment: "TESTE",
    plan: "essencial",
    deployment: [
      { step: "Contrato assinado", done: true },
      { step: "Tenant provisionado", done: true },
      { step: "Identidade visual aplicada", done: false },
      { step: "Storage isolado confirmado", done: false },
    ],
    apps: ["Condomínio Reclame"],
    core: ["padrao"],
    contractId: "CT-2026-021",
    billing: [{ label: "Piloto sem cobrança", status: "em análise", demo: true }],
    updates: [{ at: "2026-08-30", text: "Ambiente TESTE criado" }],
    tests: ["TST-0003"],
    docs: ["Proposta"],
    support: [],
    history: [{ at: "2026-08-29", text: "Piloto iniciado" }],
  },
  {
    id: "cli-vertex",
    name: "Vertex Administradora",
    segment: "Administradora multi-condomínio",
    environment: "OFICIAL",
    plan: "premium",
    deployment: [
      { step: "Contrato assinado", done: true },
      { step: "Tenant provisionado", done: true },
      { step: "Identidade visual aplicada", done: true },
      { step: "Storage isolado confirmado", done: true },
      { step: "Usuários iniciais", done: true },
      { step: "Homologação com cliente", done: true },
    ],
    apps: ["Condomínio Reclame", "Teste³ IA"],
    core: ["padrao", "cubo"],
    contractId: "CT-2025-097",
    billing: [{ label: "Mensalidade corrente", status: "em dia", demo: true }],
    updates: [{ at: "2026-09-05", text: "Rollout de 0.9.3 concluído" }],
    tests: ["TST-0001"],
    docs: ["Contrato", "Anexo de entitlements", "Plano de backup"],
    support: [{ at: "2026-08-20", text: "Solicitação de relatório consolidado", open: false }],
    history: [{ at: "2025-11-02", text: "Cliente criado" }],
  },
  {
    id: "cli-nimbus",
    name: "Nimbus Corporate",
    segment: "Corporativo privado",
    environment: "TESTE",
    plan: "privado",
    deployment: [
      { step: "NDA assinado", done: true },
      { step: "Escopo validado", done: true },
      { step: "Tenant isolado dedicado", done: false },
    ],
    apps: [],
    core: ["cubo"],
    contractId: "CT-2026-033",
    billing: [{ label: "Proposta em avaliação", status: "pendente", demo: true }],
    updates: [],
    tests: [],
    docs: ["NDA"],
    support: [],
    history: [{ at: "2026-09-01", text: "Prospecção qualificada" }],
  },
];

export const CONTRACTS: Contract[] = [
  {
    id: "CT-2026-014",
    company: "Residencial Meridiano",
    plan: "profissional",
    entitlements: ["Ocorrências", "Prova de comunicação", "Relatórios", "Teste³ IA (leitura)"],
    licenses: { users: 40, devices: 60, demo: true },
    payments: [{ label: "Ciclo corrente", status: "em dia", demo: true }],
    usage: [
      { label: "Usuários ativos", value: "27", demo: true },
      { label: "Armazenamento", value: "3,1 GB", demo: true },
    ],
    status: "ativo",
    value: {
      current: "Receita recorrente contratada (valor não informado no app)",
      potential: "Expansão para módulos de analytics e comunicação",
      method:
        "Valor atual = contrato assinado. Potencial = módulos elegíveis ainda não contratados.",
      evidence: "Contrato CT-2026-014 e catálogo de add-ons vigente.",
    },
  },
  {
    id: "CT-2025-097",
    company: "Vertex Administradora",
    plan: "premium",
    entitlements: [
      "Ocorrências",
      "Prova de comunicação",
      "Analytics de participação",
      "Branding por tenant",
      "CORE Cubo (experimental, restrito)",
    ],
    licenses: { users: 180, devices: 240, demo: true },
    payments: [{ label: "Ciclo corrente", status: "em dia", demo: true }],
    usage: [
      { label: "Usuários ativos", value: "142", demo: true },
      { label: "Armazenamento", value: "22,4 GB", demo: true },
    ],
    status: "ativo",
    value: {
      current: "Contrato premium multi-condomínio",
      potential: "Consolidação de novas unidades administradas",
      method: "Potencial estimado por unidades sob administração ainda não ativadas.",
      evidence: "Lista de unidades informada pelo cliente (não auditada).",
    },
  },
  {
    id: "CT-2026-021",
    company: "Edifício Aurora",
    plan: "essencial",
    entitlements: ["Ocorrências", "Relatórios básicos"],
    licenses: { users: 12, devices: 15, demo: true },
    payments: [{ label: "Piloto", status: "sem cobrança no período", demo: true }],
    usage: [{ label: "Usuários ativos", value: "5", demo: true }],
    status: "ativo",
    value: {
      current: "Piloto sem receita",
      potential: "Conversão para Essencial pago após homologação",
      method: "Potencial condicionado à conversão do piloto.",
      evidence: "Proposta comercial e ata de piloto.",
    },
  },
  {
    id: "CT-2026-033",
    company: "Nimbus Corporate",
    plan: "privado",
    entitlements: [],
    licenses: { users: 0, devices: 0, demo: true },
    payments: [{ label: "Não iniciado", status: "pendente", demo: true }],
    usage: [],
    status: "em negociação",
    value: {
      current: "Sem receita",
      potential: "Enterprise privado com isolamento dedicado",
      method: "Sem método fechado: escopo em definição.",
      evidence: "Sem evidência suficiente para estimativa.",
    },
  },
];

export const TESTS: TestRun[] = [
  {
    id: "TST-0001",
    subject: "app",
    target: "Condomínio Reclame 0.9.3",
    executor: "Teste³ IA",
    result: "aprovado",
    effectiveness: "Cobertura funcional do fluxo de ocorrência",
    retest: false,
    evidences: [ev("t1", "log", "Execução completa (simulada)")],
    at: "2026-09-02",
    notes: "Fluxo principal estável no ambiente de homologação.",
  },
  {
    id: "TST-0002",
    subject: "integracao",
    target: "Provider de e-mail transacional",
    executor: "Manual",
    result: "reprovado",
    effectiveness: "Falha antes do envio; prova de entrega não verificável",
    retest: true,
    evidences: [ev("t2", "print", "Tela de erro (DEMO)")],
    at: "2026-09-04",
    notes: "Nenhuma integração real está conectada neste ambiente.",
  },
  {
    id: "TST-0003",
    subject: "core-padrao",
    target: "CORE Padrão 1.0.0",
    executor: "Teste³ IA",
    result: "aprovado",
    effectiveness: "Escala operacional respondendo conforme regra",
    retest: false,
    evidences: [],
    at: "2026-09-05",
    notes: "",
  },
  {
    id: "TST-0004",
    subject: "core-cubo",
    target: "Cubo Fantasma",
    executor: "Híbrido",
    result: "inconclusivo",
    effectiveness: "Sem método fechado para converter similaridade em probabilidade",
    retest: true,
    evidences: [ev("t3", "documento", "Nota técnica (DEMO)")],
    at: "2026-09-06",
    notes: "Similaridade não é probabilidade.",
  },
  {
    id: "TST-0005",
    subject: "algoritmo-ia",
    target: "Classificador de ocorrência",
    executor: "Teste³ IA",
    result: "falso positivo",
    effectiveness: "Reprovação não reproduzida manualmente",
    retest: true,
    evidences: [ev("t4", "log", "Execução divergente (simulada)")],
    at: "2026-09-07",
    notes: "Aguardando segunda opinião.",
  },
  {
    id: "TST-0006",
    subject: "processo",
    target: "Checklist de implantação",
    executor: "Manual",
    result: "aprovado",
    effectiveness: "Etapas rastreáveis com responsável",
    retest: false,
    evidences: [],
    at: "2026-08-25",
    notes: "",
  },
  {
    id: "TST-0007",
    subject: "solucao-terceiro",
    target: "Biblioteca de OCR avaliada",
    executor: "Manual",
    result: "reprovado",
    effectiveness: "Incompatível com o runtime de borda",
    retest: false,
    evidences: [ev("t5", "documento", "Parecer técnico (DEMO)")],
    at: "2026-08-18",
    notes: "Dependência nativa não suportada.",
  },
];

export const ACTION_PLANS: ActionPlan[] = [
  {
    id: "PA-0001",
    title: "Bloquear promoção com snapshot divergente",
    originCaseId: "CASO-0002",
    origin: "Mapa Vivo / Cubo Fantasma",
    problem: "Baseline FROZEN pode ser sobrescrita silenciosamente.",
    evidences: [ev("pa1", "documento", "Relatório de comparação (simulado)")],
    status: "AGUARDANDO DEFINIÇÃO",
    owner: "",
    dueDate: "",
    priority: "",
    objective: "",
    expectedEvidence: "",
    completionCriteria: "",
    closure: null,
    createdAt: "2026-09-08",
  },
  {
    id: "PA-0002",
    title: "Reteste do provider de e-mail",
    originCaseId: null,
    origin: "Testes & Qualidade",
    problem: "Reprovação sem prova de entrega verificável.",
    evidences: [ev("pa2", "print", "Tela de erro (DEMO)")],
    status: "DEFINIDO",
    owner: "Rafael Lamounier",
    dueDate: "2026-09-20",
    priority: "alta",
    objective: "Reexecutar o teste após configuração de provedor real.",
    expectedEvidence: "Log de envio com identificador do provedor.",
    completionCriteria: "Envio confirmado com prova e reteste aprovado.",
    closure: null,
    createdAt: "2026-09-04",
  },
  {
    id: "PA-0003",
    title: "Guia versionado de recorte de ícones",
    originCaseId: "CASO-0004",
    origin: "Biblioteca Visual",
    problem: "Identificação dentro da área de corte em ícones antigos.",
    evidences: [],
    status: "EM EXECUÇÃO",
    owner: "Rafael Lamounier",
    dueDate: "2026-09-30",
    priority: "média",
    objective: "Publicar guia de recorte e revisar a família de módulos.",
    expectedEvidence: "Assets revisados com versão incrementada.",
    completionCriteria: "Nenhum ícone ativo com identificação dentro do recorte.",
    closure: null,
    createdAt: "2026-09-02",
  },
];

export const IMPROVEMENTS: Improvement[] = [
  {
    id: "OP-0001",
    title: "Modo Painel/TV por área",
    description: "Rotação de telas com interrupção por evento crítico.",
    route: "projeto",
    origin: "Configurações",
    createdAt: "2026-08-22",
  },
  {
    id: "OP-0002",
    title: "Cubo da Relação entre clientes e falhas",
    description: "Explorar relação entre padrões de falha e perfis de tenant.",
    route: "experimento-cubo",
    origin: "CORE Cubo",
    createdAt: "2026-08-27",
  },
  {
    id: "OP-0003",
    title: "Selo DEMO visível em todo dado sintético",
    description: "Reforçar marcação para não confundir dado simulado com real.",
    route: null,
    origin: "Cockpit",
    createdAt: "2026-09-01",
  },
];

export const SECURITY: SecurityAlert[] = [
  {
    id: "SEC-0001",
    title: "Divergência de integridade em artefato congelado",
    severity: "critico",
    area: "integridade",
    evidence: "Comparação de hash (simulada)",
    status: "aberto",
    at: "2026-09-08",
  },
  {
    id: "SEC-0002",
    title: "Permissão ampla em papel operacional",
    severity: "probabilidade",
    area: "permissões",
    evidence: "Matriz de papéis revisada manualmente",
    status: "aberto",
    at: "2026-09-06",
  },
  {
    id: "SEC-0003",
    title: "Revisão de isolamento por tenant",
    severity: "normal",
    area: "isolamento",
    evidence: "Checklist de isolamento",
    status: "contido",
    at: "2026-09-03",
  },
  {
    id: "SEC-0004",
    title: "Snapshot de segurança validado",
    severity: "normal",
    area: "snapshot",
    evidence: "Registro de snapshot (DEMO)",
    status: "encerrado",
    at: "2026-08-30",
  },
];

export const VERSIONS: VersionEntry[] = [
  {
    id: "VER-0005",
    build: "1.0.0-owner+build.512",
    label: "Owner Core — primeira versão navegável",
    state: "CANDIDATA",
    at: "2026-09-09",
    evidences: [ev("v1", "documento", "Notas de build (DEMO)")],
    gate: [
      { label: "Testes obrigatórios aprovados", ok: false },
      { label: "Evidências anexadas", ok: true },
      { label: "Backup e restore validados", ok: false },
      { label: "Baseline preservada", ok: true },
    ],
    notes: "SALVAR ≠ PROMOVER. Promoção exige gate completo.",
  },
  {
    id: "VER-0004",
    build: "0.9.4+build.498",
    label: "Condomínio Reclame — candidata",
    state: "CANDIDATA",
    at: "2026-08-28",
    evidences: [],
    gate: [
      { label: "Testes obrigatórios aprovados", ok: true },
      { label: "Evidências anexadas", ok: false },
    ],
    notes: "",
  },
  {
    id: "VER-0003",
    build: "0.9.3+build.471",
    label: "Condomínio Reclame — produção",
    state: "PROMOVIDA",
    at: "2026-08-05",
    evidences: [ev("v2", "log", "Log de promoção (DEMO)")],
    gate: [{ label: "Gate completo", ok: true }],
    notes: "",
  },
  {
    id: "VER-0002",
    build: "0.9.0+build.402",
    label: "Baseline preservada",
    state: "BASELINE FROZEN",
    at: "2026-06-30",
    evidences: [ev("v3", "documento", "Assinatura de baseline (DEMO)")],
    gate: [{ label: "Congelada", ok: true }],
    notes: "Nunca sobrescrever silenciosamente.",
  },
  {
    id: "VER-0001",
    build: "0.8.6+build.377",
    label: "Rollback aplicado",
    state: "ROLLBACK",
    at: "2026-05-14",
    evidences: [],
    gate: [{ label: "Restore validado", ok: true }],
    notes: "",
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: "CEN-A",
    name: "Degradação de provider de IA",
    track: "A",
    state: "ativo",
    description: "Rota alternativa com degradação controlada de recurso.",
    lastDrill: "2026-08-20",
  },
  {
    id: "CEN-B",
    name: "Perda de storage de tenant",
    track: "B",
    state: "revalidar",
    description: "Restore por tenant com evidência de integridade.",
    lastDrill: "2026-06-11",
  },
  {
    id: "CEN-C",
    name: "Divergência de baseline",
    track: "C",
    state: "pós-falha",
    description: "Análise pós-falha preditiva após divergência de snapshot.",
    lastDrill: "2026-09-08",
  },
  {
    id: "CEN-D",
    name: "Pico de uso multi-tenant",
    track: "D",
    state: "adormecido",
    description: "Cenário adormecido aguardando janela de drill.",
    lastDrill: "2026-07-09",
  },
  {
    id: "CEN-SAFE",
    name: "Modo SAFE do CORE",
    track: "SAFE",
    state: "ativo",
    description: "Operação mínima garantida com funções críticas apenas.",
    lastDrill: "2026-09-01",
  },
];

export const ASSETS: AssetItem[] = [
  {
    code: "LMU-BRAND-CUBE-001",
    name: "Cubo cristalino CORE",
    family: "marca",
    version: "v3",
    status: "CONGELADO",
    provenance: "interno",
    usage: "Marca principal do CORE",
    screens: ["Sidebar", "Topbar", "Fluxos institucionais"],
    icon: "cube",
    changeRequestRequired: true,
    cropSafe: true,
  },
  {
    code: "LMU-BRAND-HEX-002",
    name: "Hexágono cristalino",
    family: "marca",
    version: "v2",
    status: "CONGELADO",
    provenance: "interno",
    usage: "Variante compacta da marca",
    screens: ["Favicon", "Sidebar recolhida"],
    icon: "hexagon",
    changeRequestRequired: true,
    cropSafe: true,
  },
  {
    code: "LMU-MOD-COCKPIT-010",
    name: "Ícone Cockpit",
    family: "modulos",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Navegação principal",
    screens: ["Sidebar", "Cockpit"],
    icon: "gauge",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-MAP-CITY-020",
    name: "Ícone Mapa Vivo",
    family: "mapa",
    version: "v2",
    status: "ATIVO",
    provenance: "interno",
    usage: "Mapa vivo e navegação",
    screens: ["Sidebar", "Mapa"],
    icon: "map",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-CORE-SUN-030",
    name: "Sol — CORE Padrão",
    family: "core-padrao",
    version: "v1",
    status: "CONGELADO",
    provenance: "interno",
    usage: "Marcação de camada CORE Padrão sem texto na tela",
    screens: ["Mapa", "CORE"],
    icon: "sun",
    changeRequestRequired: true,
    cropSafe: true,
  },
  {
    code: "LMU-CORE-MOON-031",
    name: "Lua — CORE Cubo",
    family: "core-cubo",
    version: "v1",
    status: "CONGELADO",
    provenance: "interno",
    usage: "Marcação de camada CORE Cubo sem texto na tela",
    screens: ["Mapa", "CORE"],
    icon: "moon",
    changeRequestRequired: true,
    cropSafe: true,
  },
  {
    code: "LMU-STATUS-NORMAL-040",
    name: "Status Normal",
    family: "status",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Escala operacional",
    screens: ["Cockpit", "CORE", "Mapa"],
    icon: "check",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-STATUS-CRIT-043",
    name: "Status Crítico",
    family: "status",
    version: "v2",
    status: "ATIVO",
    provenance: "interno",
    usage: "Escala operacional",
    screens: ["Cockpit", "Segurança"],
    icon: "alert",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-ACT-SEND-050",
    name: "Ação: enviar para Plano",
    family: "acoes",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Destinos do caso",
    screens: ["Mapa", "Planos"],
    icon: "send",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-SEC-SHIELD-060",
    name: "Escudo defensivo",
    family: "seguranca",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Segurança defensiva",
    screens: ["Segurança"],
    icon: "shield",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-TST-FLASK-070",
    name: "Laboratório de testes",
    family: "testes",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Testes & Qualidade",
    screens: ["Testes"],
    icon: "flask",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-CLI-BUILD-080",
    name: "Cliente / edificação",
    family: "clientes",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Clientes e implantação",
    screens: ["Clientes"],
    icon: "building",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-COM-CONTRACT-090",
    name: "Contrato",
    family: "comercial",
    version: "v1",
    status: "EM REVISÃO",
    provenance: "interno",
    usage: "Comercial & Contratos",
    screens: ["Comercial"],
    icon: "contract",
    changeRequestRequired: false,
    cropSafe: false,
  },
  {
    code: "LMU-VER-BRANCH-100",
    name: "Versão / build",
    family: "versoes",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Versões e promoção",
    screens: ["Versões"],
    icon: "branch",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-CFG-GEAR-110",
    name: "Configuração",
    family: "configuracoes",
    version: "v1",
    status: "ATIVO",
    provenance: "interno",
    usage: "Configurações",
    screens: ["Configurações"],
    icon: "gear",
    changeRequestRequired: false,
    cropSafe: true,
  },
  {
    code: "LMU-MOD-CUBE-EXP-120",
    name: "Recursos experimentais do Cubo",
    family: "core-cubo",
    version: "v1",
    status: "EM REVISÃO",
    provenance: "interno",
    usage: "Prisma, Snapshot, Cubo Fantasma, Cubo da Relação, Caleidoscópio",
    screens: ["CORE"],
    icon: "prism",
    changeRequestRequired: false,
    cropSafe: false,
  },
];
