/**
 * MASTER APP LOCK CATALOG — candidate 2026-09-23.
 *
 * This catalog closes application identity inside LAMOU without promoting versions.
 * It reconciles V7.5, source-binding evidence and explicit later decisions.
 */

export type MasterAppClass = "LOCKED_APP" | "SAME_APP_LINEAGE_ALIAS" | "HOLD_CLASSIFICATION" | "NOT_APP";

export type LamouArea =
  | "personal-productivity"
  | "people-learning"
  | "music"
  | "commercial"
  | "diagnostic-improvement"
  | "operations"
  | "projects"
  | "process"
  | "quality-validation"
  | "documents-governance"
  | "security-tools"
  | "design-system"
  | "other";

export interface MasterAppLockItem {
  id: string;
  name: string;
  classification: MasterAppClass;
  lamouArea: LamouArea;
  canonicalKey?: string;
  predecessorOf?: string;
  sourceState: string;
  versionTruth: string;
  bindingTruth: "NOT_VERIFIED" | "NOT_CONNECTED" | "PARTIAL" | "VERIFIED";
  scopeLock: "LOCKED" | "HOLD" | "NOT_APPLICABLE";
  reason: string;
}

export const MASTER_APP_LOCK_CATALOG: MasterAppLockItem[] = [
  {
    id: "APP-001",
    name: "LAMOU LifeOS",
    classification: "SAME_APP_LINEAGE_ALIAS",
    lamouArea: "personal-productivity",
    canonicalKey: "APP-007",
    sourceState: "IDENTITY_OVERLAP_WITH_ORBITE_AGENDA",
    versionTruth: "HOLD_RECONCILIATION",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "HOLD",
    reason: "Não contar separado de Orbit/Agenda até reconciliação de identidade.",
  },
  {
    id: "APP-002",
    name: "Bora Crescer",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "SOURCE_REPO_VERIFICADO",
    versionTruth:
      "produção declarada no catálogo; build produtivo não reverificado nesta candidata",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo do catálogo anterior com fonte de produto verificada.",
  },
  {
    id: "APP-003",
    name: "Araujo People & Learning Suite",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "REPOS_RELACIONADOS_VERIFICADOS",
    versionTruth: "suite binding pendente",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Macroproduto/aplicativo; preservar ownership entre os sources relacionados.",
  },
  {
    id: "APP-004",
    name: "Lamou Music Promoter / Composer OS",
    classification: "LOCKED_APP",
    lamouArea: "music",
    sourceState: "REPO_VERIFICADO_MONOREPO",
    versionTruth: "produto oficial consolidado",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo/produto oficial; monorepo não autoriza fragmentação do produto.",
  },
  {
    id: "APP-005",
    name: "LAMOU Ranking AI",
    classification: "LOCKED_APP",
    lamouArea: "music",
    sourceState: "MATERIALIZADO",
    versionTruth: "produção declarada no catálogo anterior",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-006",
    name: "PROJETE — Treinamento e Desenvolvimento",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "ESCOPO_RECUPERADO_SOURCE_LEGADO_NAO_LOCALIZADO",
    versionTruth: "produto estruturado",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Produto/aplicativo confirmado; source antigo ausente não muda classificação.",
  },
  {
    id: "APP-007",
    name: "Orbit / LAMOU Agenda / LifeOS",
    classification: "LOCKED_APP",
    lamouArea: "personal-productivity",
    sourceState: "LINEAGE_RECONCILIATION",
    versionTruth:
      "app confirmado; identidade canônica desta candidata para a linhagem Agenda/Orbit",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Agenda, diário, rotina e follow-up permanecem dentro do aplicativo.",
  },
  {
    id: "APP-008",
    name: "TE CONVIDO",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "MATERIALIZADO_V4_7",
    versionTruth: "produto em consolidação",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-009",
    name: "CHARGE.ME",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "SOURCE_REAL_RECUPERADO",
    versionTruth: "produção declarada no catálogo anterior",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-010",
    name: "Teste³ IA",
    classification: "LOCKED_APP",
    lamouArea: "quality-validation",
    sourceState: "CATALOGADO",
    versionTruth: "produto oficial em desenvolvimento",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo executor de testes; não fundir com Lab ou Validation Gate.",
  },
  {
    id: "APP-011",
    name: "LAMOU IA — Diagnóstico 360",
    classification: "LOCKED_APP",
    lamouArea: "diagnostic-improvement",
    sourceState: "CATALOGADO",
    versionTruth: "produto oficial em desenvolvimento",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo de diagnóstico; não confundir com Meeting Architect.",
  },
  {
    id: "APP-012",
    name: "LAMOU Digital Improvement",
    classification: "LOCKED_APP",
    lamouArea: "diagnostic-improvement",
    sourceState: "CATALOGADO",
    versionTruth: "produto em desenvolvimento",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo completo de melhoria.",
  },
  {
    id: "APP-013",
    name: "LAMOU Compra IA",
    classification: "LOCKED_APP",
    lamouArea: "commercial",
    sourceState: "UX_PROTOTIPO_SCOPE",
    versionTruth: "produto oficial em desenvolvimento",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-014",
    name: "Presente Box",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "MATERIALIZADO_V2_1",
    versionTruth: "protótipo funcional em evolução",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-015",
    name: "LAMOU Apoio / Recuperação",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "DOCUMENTADO_SOURCE_ANTIGO_NAO_RECUPERADO",
    versionTruth: "V1 em construção",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado; não inferir capacidades clínicas.",
  },
  {
    id: "APP-016",
    name: "Condomínio Reclame",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "UX_PROTOTIPO",
    versionTruth: "piloto em desenvolvimento",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-017",
    name: "HQ Interativo — Operação Recomeço",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "RUNTIME_DOCUMENTADO_SOURCE_BUILD_NAO_LOCALIZADO",
    versionTruth: "produção declarada; build não reverificado",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-018",
    name: "KDBS",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "SOURCE_NOT_FOUND",
    versionTruth: "identidade de app preservada; source a reconciliar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason:
      "Catálogo já o identifica como aplicativo; ausência de source bloqueia binding/promoção, não apaga a identidade.",
  },
  {
    id: "APP-019",
    name: "Pararaujo",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "SOURCE_NOT_FOUND",
    versionTruth: "identidade de app preservada; source a reconciliar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Catálogo já o identifica como aplicativo; manter até reconciliação.",
  },
  {
    id: "APP-020",
    name: "PHARMÉDICE OPS 360",
    classification: "LOCKED_APP",
    lamouArea: "operations",
    sourceState: "MATERIALIZADO_MULTI_FILE",
    versionTruth: "design/integrações em validação",
    bindingTruth: "PARTIAL",
    scopeLock: "LOCKED",
    reason: "Aplicativo operacional confirmado.",
  },
  {
    id: "APP-021",
    name: "Smart Sourcing Ranking",
    classification: "LOCKED_APP",
    lamouArea: "commercial",
    sourceState: "SOURCE_REAL_V0_1_TEST_DEMO",
    versionTruth: "em teste/protótipo",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-022",
    name: "Kayambi OS",
    classification: "LOCKED_APP",
    lamouArea: "personal-productivity",
    sourceState: "CATALOGADO",
    versionTruth: "estruturação",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-023",
    name: "Liga A Onboarding 52",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "REPO_VERIFICADO",
    versionTruth: "a consolidar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado e separado de PROJETE.",
  },
  {
    id: "APP-024",
    name: "Avaliação Farma Desenvolvimento",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "PRODUTO_ENCONTRADO_CODE_NAO_RECUPERADO",
    versionTruth: "a consolidar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado; não fundir com PROJETE/Araujo.",
  },
  {
    id: "APP-025",
    name: "LAMOU PUSH 360 / Metraction 360",
    classification: "LOCKED_APP",
    lamouArea: "operations",
    sourceState: "LINEAGE_RECONCILIATION",
    versionTruth: "PUSH é evolução/alias de Metraction nesta linhagem",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Um aplicativo/linhagem; não contar Metraction e PUSH como dois.",
  },
  {
    id: "APP-026",
    name: "VECTRA Intelligence 360 V4",
    classification: "LOCKED_APP",
    lamouArea: "operations",
    predecessorOf: "VECTRA-V4",
    sourceState: "BELGO_TO_VECTRA_LINEAGE",
    versionTruth: "V4 oficial aprovado; BELGO preservado como predecessor/linhagem",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Mapa Vivo e operação permanecem no aplicativo; rebrand não duplica produto.",
  },
  {
    id: "APP-027",
    name: "LAMOU Quest 360",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "PROTOTIPO_EXECUTAVEL",
    versionTruth: "protótipo/executável",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-028",
    name: "OmniArquiteto Studio",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "BASELINE_STUDIO_APROVADA",
    versionTruth: "executável oficial a reconciliar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-029",
    name: "LAMOU Showroom",
    classification: "LOCKED_APP",
    lamouArea: "commercial",
    sourceState: "SPEC",
    versionTruth: "especificação / implementação a verificar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado; não confundir com Comercial & Contratos.",
  },
  {
    id: "APP-030",
    name: "LAMOU Diagnostic / Meeting Architect",
    classification: "LOCKED_APP",
    lamouArea: "operations",
    sourceState: "SPEC",
    versionTruth: "especificação / implementação a verificar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado; governa reunião/decisão/follow-up.",
  },
  {
    id: "APP-031",
    name: "LAMOU Persona Lab",
    classification: "LOCKED_APP",
    lamouArea: "other",
    sourceState: "SPEC",
    versionTruth: "especificação / implementação a verificar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado.",
  },
  {
    id: "APP-032",
    name: "Toca Minha Música",
    classification: "HOLD_CLASSIFICATION",
    lamouArea: "music",
    sourceState: "APP_VS_MODULE_UNRESOLVED",
    versionTruth: "não classificar automaticamente",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "HOLD",
    reason: "O próprio catálogo anterior marcou app vs módulo como não resolvido.",
  },
  {
    id: "APP-033",
    name: "Portal / Wormhole Pitch",
    classification: "HOLD_CLASSIFICATION",
    lamouArea: "music",
    sourceState: "PORTAL_VS_MODULE_UNRESOLVED",
    versionTruth: "não classificar automaticamente",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "HOLD",
    reason: "O próprio catálogo anterior marcou portal vs módulo como não resolvido.",
  },
  {
    id: "APP-LAMOU-VERSION",
    name: "LAMOU Version",
    classification: "LOCKED_APP",
    lamouArea: "documents-governance",
    sourceState: "MATERIALIZED_CANDIDATE_WINDOWS_NATIVE",
    versionTruth: "V0.6 candidate; promoção separada",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo de versionamento confirmado.",
  },
  {
    id: "APP-LAMOU-DESIGN-LIBRARY",
    name: "LAMOU Design Library",
    classification: "NOT_APP",
    lamouArea: "design-system",
    sourceState: "MATERIALIZED_LIBRARY",
    versionTruth: "biblioteca reutilizável",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "NOT_APPLICABLE",
    reason:
      "Biblioteca/design system reutilizável; executável de catálogo não a transforma em app.",
  },
  {
    id: "APP-034-CANDIDATE",
    name: "LAMOU Research Scout",
    classification: "LOCKED_APP",
    lamouArea: "commercial",
    sourceState: "EXECUTABLE_CANDIDATE",
    versionTruth: "CANDIDATE_NOT_PROMOTED",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo confirmado; versão candidata continua não promovida.",
  },
  {
    id: "APP-ID-AMUDOC",
    name: "A-MuDoc / MuDoc",
    classification: "LOCKED_APP",
    lamouArea: "documents-governance",
    sourceState: "V0_4_EXECUTABLE_CANDIDATE_RECOVERED",
    versionTruth: "APP-ID final a reconciliar",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Aplicativo documental confirmado; aliases devem convergir para um único ID.",
  },
  {
    id: "APP-ID-PLGO",
    name: "PLGO Mineiro",
    classification: "HOLD_CLASSIFICATION",
    lamouArea: "other",
    sourceState: "SOURCE_NOT_FOUND",
    versionTruth: "requested / identity insufficient",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "HOLD",
    reason: "Não classificar apenas porque foi solicitado; falta source/identidade suficiente.",
  },

  // Confirmed after V7.5
  {
    id: "APP-PROJECT-PRIME",
    name: "PROJECT PRIME MASTER V1",
    classification: "LOCKED_APP",
    lamouArea: "projects",
    sourceState: "APPROVED_EXTERNAL_SOURCE",
    versionTruth: "V1 approved reference",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "LOCKED",
    reason: "Aplicativo completo de projetos.",
  },
  {
    id: "APP-MEU-DESENVOLVIMENTO",
    name: "LAMU IA — Meu Desenvolvimento v1 COMPLETO",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "APPROVED_EXTERNAL_SOURCE",
    versionTruth: "v1 COMPLETO approved",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "LOCKED",
    reason: "Aplicativo do colaborador; não virar módulo de RH/T&D.",
  },
  {
    id: "APP-PROCESSO",
    name: "LAMOU App Processo",
    classification: "LOCKED_APP",
    lamouArea: "process",
    sourceState: "V0_3_CANDIDATE_EXTERNAL_SOURCE",
    versionTruth: "CANDIDATE_NOT_PROMOTED",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "LOCKED",
    reason: "Decisão explícita: Processo é aplicativo completo.",
  },
  {
    id: "APP-VALIDATION-GATE",
    name: "Validation Gate / Validação",
    classification: "LOCKED_APP",
    lamouArea: "quality-validation",
    sourceState: "OWNER_ROUTE_AND_VALIDATION_CONTRACT",
    versionTruth: "candidate/not promoted",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason: "Decisão explícita: Validação é aplicativo.",
  },
  {
    id: "APP-OBSERVER-360",
    name: "APP Observer 360",
    classification: "LOCKED_APP",
    lamouArea: "operations",
    sourceState: "V2_EXECUTABLE_CANDIDATE",
    versionTruth: "CANDIDATE_NOT_PROMOTED",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "LOCKED",
    reason:
      "Foi definido e tratado como APP de observação; não confundir com CORE Observabilidade.",
  },
  {
    id: "APP-CERTIFICACOES",
    name: "Certificações",
    classification: "LOCKED_APP",
    lamouArea: "people-learning",
    sourceState: "APP_ID_SOURCE_TO_RECONCILE",
    versionTruth: "identity/scope locked; source/version to reconcile",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "LOCKED",
    reason:
      "Aplicativo citado explicitamente como ciclo completo de certificações; não fragmentar.",
  },

  // Non-app entities explicitly kept outside Apps
  {
    id: "MOD-PLANO-ACAO",
    name: "Plano de Ação",
    classification: "NOT_APP",
    lamouArea: "operations",
    sourceState: "DOCUMENTED_MODULE",
    versionTruth: "module contract",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Módulo; pode encaminhar para PROJECT sem virar aplicativo por inferência.",
  },
  {
    id: "SYS-LAMOU-LAB",
    name: "LAMOU Lab",
    classification: "NOT_APP",
    lamouArea: "quality-validation",
    sourceState: "SYSTEM_LAB_SURFACE",
    versionTruth: "candidate lab runtime",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Laboratório/superfície do sistema, não contado no catálogo de Apps nesta candidata.",
  },
  {
    id: "CORE-PULSE",
    name: "LAMOU Pulse CORE",
    classification: "NOT_APP",
    lamouArea: "operations",
    sourceState: "TRANSVERSAL_CORE_LAYER",
    versionTruth: "architecture/proposal",
    bindingTruth: "NOT_VERIFIED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Camada transversal CORE, não aplicativo.",
  },
  {
    id: "TOOL-SHIELD",
    name: "LAMOU Shield Local",
    classification: "NOT_APP",
    lamouArea: "security-tools",
    sourceState: "LOCAL_UTILITY_PACKAGE",
    versionTruth: "local utility",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Utilitário de segurança local; pacote executável não implica app.",
  },
  {
    id: "TOOL-COMPUTER-SCAN",
    name: "LAMOU Computer Scan",
    classification: "NOT_APP",
    lamouArea: "security-tools",
    sourceState: "LOCAL_SCAN_UTILITY",
    versionTruth: "local utility",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Ferramenta/scanner técnico.",
  },
  {
    id: "TOOL-CONFIDENTIAL-GUARDIAN",
    name: "Confidential Guardian",
    classification: "NOT_APP",
    lamouArea: "security-tools",
    sourceState: "SECURITY_UTILITY_CANDIDATE",
    versionTruth: "candidate utility",
    bindingTruth: "NOT_CONNECTED",
    scopeLock: "NOT_APPLICABLE",
    reason: "Utilitário/camada de proteção; não adicionar em Apps sem decisão futura explícita.",
  },
];

export const LOCKED_MASTER_APPS = MASTER_APP_LOCK_CATALOG.filter(
  (item) => item.classification === "LOCKED_APP",
);

export const APP_LINEAGE_ALIASES = MASTER_APP_LOCK_CATALOG.filter(
  (item) => item.classification === "SAME_APP_LINEAGE_ALIAS",
);

export const APP_CLASSIFICATION_HOLDS = MASTER_APP_LOCK_CATALOG.filter(
  (item) => item.classification === "HOLD_CLASSIFICATION",
);

export const MASTER_NON_APPS = MASTER_APP_LOCK_CATALOG.filter(
  (item) => item.classification === "NOT_APP",
);

export const MASTER_APP_LOCK_POLICY = {
  classificationLock: true,
  identityLock: true,
  fullScopeLock: true,
  sourceTruthRequired: true,
  lineageRequired: true,
  silentMergeForbidden: true,
  silentFragmentationForbidden: true,
  catalogDoesNotEqualBinding: true,
  lockDoesNotEqualPromotion: true,
} as const;
