/**
 * Metric contract registry — definitions only.
 *
 * No metric receives a numeric value unless a real source has measured it.
 * Registering a metric is not evidence that it is connected or populated.
 */

export type MetricCategory =
  | "runtime"
  | "reliability"
  | "security"
  | "network"
  | "flow"
  | "evidence"
  | "action"
  | "project"
  | "process"
  | "people"
  | "test"
  | "document";

export interface MetricDefinition {
  id: string;
  name: string;
  category: MetricCategory;
  unit: "count" | "percent" | "ms" | "seconds" | "minutes" | "hours" | "days" | "ratio";
  source: string;
  cadence: "event" | "minute" | "hour" | "day" | "run" | "release";
  formula: string;
  truthRule: string;
  appliesTo: string[];
}

export const METRICS_REGISTRY: MetricDefinition[] = [
  {
    id: "MET-APP-001",
    name: "Acionamentos do aplicativo",
    category: "runtime",
    unit: "count",
    source: "telemetria de abertura/ação",
    cadence: "event",
    formula: "count(app_invoked)",
    truthRule: "Valor somente com evento persistido e app_id/version_id.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-APP-002",
    name: "Sessões iniciadas",
    category: "runtime",
    unit: "count",
    source: "telemetria de sessão",
    cadence: "event",
    formula: "count(session_started)",
    truthRule: "Não inferir usuário ativo a partir de page view.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-APP-003",
    name: "Taxa de conclusão do fluxo principal",
    category: "runtime",
    unit: "percent",
    source: "eventos start/completed por workflow_id",
    cadence: "day",
    formula: "completed_workflows / started_workflows * 100",
    truthRule: "Exige definição explícita de início e conclusão do fluxo.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-001",
    name: "Erros de programação",
    category: "reliability",
    unit: "count",
    source: "error capture / exception telemetry",
    cadence: "event",
    formula: "count(unhandled_exception + handled_error_severity>=error)",
    truthRule:
      "Erro precisa de timestamp, version_id, route/action e stack/fingerprint quando permitido.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-002",
    name: "Quedas / crashes",
    category: "reliability",
    unit: "count",
    source: "runtime crash / abnormal termination",
    cadence: "event",
    formula: "count(abnormal_termination)",
    truthRule: "Não contar navegação/fechamento normal como crash.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-003",
    name: "Taxa de erro",
    category: "reliability",
    unit: "percent",
    source: "telemetria de ações",
    cadence: "hour",
    formula: "failed_actions / total_actions * 100",
    truthRule: "Numerador e denominador precisam do mesmo escopo/versão/janela.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-004",
    name: "Latência p50",
    category: "reliability",
    unit: "ms",
    source: "traces de ação/call",
    cadence: "hour",
    formula: "p50(duration_ms)",
    truthRule: "Somente sobre eventos medidos; indicar operação e ambiente.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-005",
    name: "Latência p95",
    category: "reliability",
    unit: "ms",
    source: "traces de ação/call",
    cadence: "hour",
    formula: "p95(duration_ms)",
    truthRule: "Somente sobre eventos medidos; indicar operação e ambiente.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-REL-006",
    name: "Falhas de deploy/build",
    category: "reliability",
    unit: "count",
    source: "CI/CD",
    cadence: "release",
    formula: "count(build_or_deploy_result=FAIL)",
    truthRule: "Associar commit, workflow_run_id e artefato.",
    appliesTo: ["all-apps", "version"],
  },
  {
    id: "MET-REL-007",
    name: "Rollbacks",
    category: "reliability",
    unit: "count",
    source: "Version / release registry",
    cadence: "release",
    formula: "count(rollback_executed)",
    truthRule: "Rollback planejado/teste deve ser distinguido de rollback por incidente.",
    appliesTo: ["all-apps", "version"],
  },
  {
    id: "MET-NET-001",
    name: "Falhas de comunicação/rede",
    category: "network",
    unit: "count",
    source: "CALL/network telemetry",
    cadence: "event",
    formula: "count(network_error + dns_error + connection_reset)",
    truthRule: "Separar rede local, provider, timeout e erro HTTP/aplicação.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-NET-002",
    name: "Timeouts",
    category: "network",
    unit: "count",
    source: "CALL registry runtime",
    cadence: "event",
    formula: "count(call_timeout)",
    truthRule: "Registrar call_id, provider, timeout configurado e retry.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-NET-003",
    name: "Falhas de sincronização",
    category: "network",
    unit: "count",
    source: "sync/storage telemetry",
    cadence: "event",
    formula: "count(sync_failed)",
    truthRule: "Distinguir conflito, indisponibilidade, permissão e schema.",
    appliesTo: ["all-apps", "version", "documents"],
  },
  {
    id: "MET-SEC-001",
    name: "Eventos de segurança",
    category: "security",
    unit: "count",
    source: "security/audit telemetry",
    cadence: "event",
    formula: "count(security_event)",
    truthRule:
      "Classificar severidade, regra acionada, tenant e evidência; sem inferir comprometimento.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-SEC-002",
    name: "Falhas de autenticação",
    category: "security",
    unit: "count",
    source: "auth telemetry",
    cadence: "event",
    formula: "count(auth_failed)",
    truthRule: "Não expor credenciais ou dados sensíveis no evento.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-SEC-003",
    name: "Negativas de autorização",
    category: "security",
    unit: "count",
    source: "RBAC/ABAC audit",
    cadence: "event",
    formula: "count(permission_denied)",
    truthRule: "Registrar policy/scope sem vazar dado protegido.",
    appliesTo: ["all-apps"],
  },
  {
    id: "MET-FLOW-001",
    name: "Sucesso de handoff entre módulos/apps",
    category: "flow",
    unit: "percent",
    source: "handoff events",
    cadence: "day",
    formula: "accepted_handoffs / emitted_handoffs * 100",
    truthRule: "Handoff precisa de from, to, event_id, entity_id e acknowledgement.",
    appliesTo: ["architecture"],
  },
  {
    id: "MET-FLOW-002",
    name: "Registros órfãos",
    category: "flow",
    unit: "count",
    source: "relationship validator",
    cadence: "day",
    formula: "count(entity where required_parent_or_owner_missing)",
    truthRule: "Só contar relações obrigatórias definidas no contrato.",
    appliesTo: ["architecture"],
  },
  {
    id: "MET-FLOW-003",
    name: "Duplicidades candidatas",
    category: "flow",
    unit: "count",
    source: "dedup/reconciliation",
    cadence: "day",
    formula: "count(potential_duplicate not reconciled)",
    truthRule: "Similaridade não autoriza merge; registrar decisão humana.",
    appliesTo: ["architecture", "documents", "version"],
  },
  {
    id: "MET-FLOW-004",
    name: "Idade p95 da fila de handoff",
    category: "flow",
    unit: "hours",
    source: "handoff queue",
    cadence: "hour",
    formula: "p95(accepted_at - emitted_at)",
    truthRule: "Somente eventos com timestamp confiável.",
    appliesTo: ["architecture"],
  },
  {
    id: "MET-FLOW-005",
    name: "Lead time sinal → decisão",
    category: "flow",
    unit: "hours",
    source: "case/decision timeline",
    cadence: "day",
    formula: "decision_at - signal_at",
    truthRule: "Mesmo case_id; sinal e decisão precisam de proveniência.",
    appliesTo: ["opportunity-intelligence", "diagnostico-360", "meeting-architect"],
  },
  {
    id: "MET-FLOW-006",
    name: "Lead time decisão → ação",
    category: "flow",
    unit: "hours",
    source: "decision/action timeline",
    cadence: "day",
    formula: "action_started_at - decision_approved_at",
    truthRule: "Não usar decisão pendente como início.",
    appliesTo: ["meeting-architect", "plano-acao"],
  },
  {
    id: "MET-FLOW-007",
    name: "Lead time ação → eficácia",
    category: "flow",
    unit: "days",
    source: "action/effectiveness timeline",
    cadence: "day",
    formula: "effectiveness_verified_at - action_completed_at",
    truthRule: "Concluído ≠ eficaz; eficácia requer critério e evidência.",
    appliesTo: ["plano-acao", "teste3", "lab"],
  },
  {
    id: "MET-EVD-001",
    name: "Cobertura de evidência",
    category: "evidence",
    unit: "percent",
    source: "evidence registry",
    cadence: "day",
    formula: "required_fields_with_evidence / required_evidence_fields * 100",
    truthRule: "Link vazio/fixture não conta como evidência real.",
    appliesTo: ["all-apps", "validation-gate"],
  },
  {
    id: "MET-EVD-002",
    name: "Freshness de evidência",
    category: "evidence",
    unit: "hours",
    source: "evidence timestamps",
    cadence: "hour",
    formula: "now - evidence_collected_at",
    truthRule: "Exibir fonte, timestamp e política de validade.",
    appliesTo: ["all-apps", "documents"],
  },
  {
    id: "MET-ACT-001",
    name: "Planos abertos",
    category: "action",
    unit: "count",
    source: "Plano de Ação",
    cadence: "day",
    formula: "count(status not in CLOSED/CANCELLED)",
    truthRule: "Plano precisa de action_plan_id único.",
    appliesTo: ["plano-acao"],
  },
  {
    id: "MET-ACT-002",
    name: "Planos vencidos",
    category: "action",
    unit: "count",
    source: "Plano de Ação",
    cadence: "day",
    formula: "count(due_date < now and status not closed)",
    truthRule: "Sem prazo definido deve aparecer em métrica separada, não como vencido.",
    appliesTo: ["plano-acao"],
  },
  {
    id: "MET-ACT-003",
    name: "Decisões aguardando autoridade/OK",
    category: "action",
    unit: "count",
    source: "Decision/approval registry",
    cadence: "day",
    formula: "count(required_approvals > received_approvals)",
    truthRule: "Registrar nível de autoridade e approver; não autoaprovar.",
    appliesTo: ["meeting-architect", "plano-acao"],
  },
  {
    id: "MET-ACT-004",
    name: "Ações eficazes",
    category: "action",
    unit: "percent",
    source: "effectiveness verification",
    cadence: "day",
    formula: "actions_effective / actions_evaluated * 100",
    truthRule: "Somente ações com avaliação pós-implementação entram no denominador.",
    appliesTo: ["plano-acao"],
  },
  {
    id: "MET-ACT-005",
    name: "Recorrência após ação",
    category: "action",
    unit: "percent",
    source: "case recurrence",
    cadence: "day",
    formula: "recurrent_cases / closed_cases_with_followup * 100",
    truthRule: "Definir janela e equivalência de caso.",
    appliesTo: ["plano-acao", "diagnostico-360"],
  },
  {
    id: "MET-PRJ-001",
    name: "Marcos no prazo",
    category: "project",
    unit: "percent",
    source: "PROJECT PRIME",
    cadence: "day",
    formula: "milestones_on_time / milestones_due * 100",
    truthRule: "Baseline do cronograma deve estar versionada.",
    appliesTo: ["project-prime"],
  },
  {
    id: "MET-PRJ-002",
    name: "Idade de bloqueios",
    category: "project",
    unit: "hours",
    source: "PROJECT PRIME",
    cadence: "hour",
    formula: "now - blocker_opened_at",
    truthRule: "Bloqueio precisa de owner e status.",
    appliesTo: ["project-prime"],
  },
  {
    id: "MET-PRJ-003",
    name: "Aceitação de entregas",
    category: "project",
    unit: "percent",
    source: "PROJECT PRIME + Teste³",
    cadence: "run",
    formula: "accepted_deliverables / tested_deliverables * 100",
    truthRule: "Critério de aceite deve existir antes do teste.",
    appliesTo: ["project-prime", "teste3"],
  },
  {
    id: "MET-PCS-001",
    name: "Tempo de ciclo do processo",
    category: "process",
    unit: "minutes",
    source: "App Processo",
    cadence: "run",
    formula: "process_end - process_start",
    truthRule: "Definir início/fim, amostra, método e contexto.",
    appliesTo: ["processo"],
  },
  {
    id: "MET-PCS-002",
    name: "Tempo de espera",
    category: "process",
    unit: "minutes",
    source: "App Processo",
    cadence: "run",
    formula: "sum(wait_segments)",
    truthRule: "Separar manual, máquina, espera e deslocamento.",
    appliesTo: ["processo"],
  },
  {
    id: "MET-PCS-003",
    name: "First Pass Yield",
    category: "process",
    unit: "percent",
    source: "App Processo",
    cadence: "run",
    formula: "units_right_first_time / total_units * 100",
    truthRule: "Aplicar apenas quando unidade/defeito estão definidos.",
    appliesTo: ["processo"],
  },
  {
    id: "MET-PCS-004",
    name: "Gaps de competência ligados ao processo",
    category: "process",
    unit: "count",
    source: "App Processo + ficha de pessoa/cargo",
    cadence: "day",
    formula: "count(required_competency where evidence < requirement)",
    truthRule: "Gap não equivale a causa humana; exige contexto/evidência.",
    appliesTo: ["processo", "meu-desenvolvimento"],
  },
  {
    id: "MET-PPL-001",
    name: "Fechamento de gaps de competência",
    category: "people",
    unit: "percent",
    source: "Meu Desenvolvimento",
    cadence: "day",
    formula: "closed_competency_gaps / evaluated_competency_gaps * 100",
    truthRule: "Fechamento requer evidência, não apenas curso concluído.",
    appliesTo: ["meu-desenvolvimento"],
  },
  {
    id: "MET-PPL-002",
    name: "Conclusão de treinamentos",
    category: "people",
    unit: "percent",
    source: "Treinamentos / Meu Desenvolvimento",
    cadence: "day",
    formula: "completed_trainings / assigned_trainings * 100",
    truthRule: "Separar conclusão de eficácia/aplicação.",
    appliesTo: ["meu-desenvolvimento"],
  },
  {
    id: "MET-PPL-003",
    name: "Aplicação com evidência",
    category: "people",
    unit: "percent",
    source: "Meu Desenvolvimento + processo",
    cadence: "day",
    formula: "development_actions_with_application_evidence / completed_development_actions * 100",
    truthRule: "Evidência precisa estar ligada a competência/atividade/processo.",
    appliesTo: ["meu-desenvolvimento", "processo"],
  },
  {
    id: "MET-TST-001",
    name: "Taxa de aprovação de testes",
    category: "test",
    unit: "percent",
    source: "Teste³",
    cadence: "run",
    formula: "passed_tests / executed_tests * 100",
    truthRule: "PASS somente com evidence_id do mesmo run/build/ambiente.",
    appliesTo: ["teste3"],
  },
  {
    id: "MET-TST-002",
    name: "Taxa de sucesso em reteste",
    category: "test",
    unit: "percent",
    source: "Teste³",
    cadence: "run",
    formula: "passed_retests / executed_retests * 100",
    truthRule: "Vincular reteste ao test_run anterior e correção.",
    appliesTo: ["teste3"],
  },
  {
    id: "MET-TST-003",
    name: "Falso positivo",
    category: "test",
    unit: "percent",
    source: "Teste³ / revisão",
    cadence: "run",
    formula: "confirmed_false_positives / reviewed_positive_results * 100",
    truthRule: "Requer revisão/ground truth; não inferir.",
    appliesTo: ["teste3", "lab"],
  },
  {
    id: "MET-TST-004",
    name: "Falso negativo",
    category: "test",
    unit: "percent",
    source: "Teste³ / revisão",
    cadence: "run",
    formula: "confirmed_false_negatives / reviewed_negative_results * 100",
    truthRule: "Requer revisão/ground truth; não inferir.",
    appliesTo: ["teste3", "lab"],
  },
  {
    id: "MET-TST-005",
    name: "Cobertura de casos obrigatórios",
    category: "test",
    unit: "percent",
    source: "Test Master Plan",
    cadence: "release",
    formula: "executed_required_cases / required_cases * 100",
    truthRule: "Caso NOT_RUN não conta como coberto.",
    appliesTo: ["teste3", "validation-gate"],
  },
  {
    id: "MET-DOC-001",
    name: "Documentos desatualizados",
    category: "document",
    unit: "count",
    source: "Documento Central / Version",
    cadence: "day",
    formula: "count(doc where freshness_policy_expired)",
    truthRule: "Política de freshness deve existir por classe documental.",
    appliesTo: ["documents", "version"],
  },
  {
    id: "MET-DOC-002",
    name: "Links/referências quebradas",
    category: "document",
    unit: "count",
    source: "document link checker",
    cadence: "day",
    formula: "count(unresolvable_reference)",
    truthRule: "Distinguir permissão negada de referência inexistente.",
    appliesTo: ["documents", "version"],
  },
  {
    id: "MET-DOC-003",
    name: "Divergência CURRENT/PINNED",
    category: "document",
    unit: "count",
    source: "Version / document registry",
    cadence: "day",
    formula: "count(reference where pinned_expected != resolved_version)",
    truthRule: "Comparar IDs/versões, nunca apenas nome de arquivo.",
    appliesTo: ["documents", "version"],
  },
];

export const METRIC_PROFILES: Record<string, string[]> = {
  "all-apps": [
    "MET-APP-001",
    "MET-APP-002",
    "MET-APP-003",
    "MET-REL-001",
    "MET-REL-002",
    "MET-REL-003",
    "MET-REL-004",
    "MET-REL-005",
    "MET-NET-001",
    "MET-NET-002",
    "MET-SEC-001",
    "MET-SEC-002",
    "MET-SEC-003",
    "MET-EVD-001",
    "MET-EVD-002",
  ],
  "plano-acao": ["MET-ACT-001", "MET-ACT-002", "MET-ACT-003", "MET-ACT-004", "MET-ACT-005"],
  "project-prime": ["MET-PRJ-001", "MET-PRJ-002", "MET-PRJ-003"],
  processo: ["MET-PCS-001", "MET-PCS-002", "MET-PCS-003", "MET-PCS-004"],
  "meu-desenvolvimento": ["MET-PPL-001", "MET-PPL-002", "MET-PPL-003"],
  teste3: ["MET-TST-001", "MET-TST-002", "MET-TST-003", "MET-TST-004", "MET-TST-005"],
  documents: ["MET-DOC-001", "MET-DOC-002", "MET-DOC-003"],
  architecture: [
    "MET-FLOW-001",
    "MET-FLOW-002",
    "MET-FLOW-003",
    "MET-FLOW-004",
    "MET-FLOW-005",
    "MET-FLOW-006",
    "MET-FLOW-007",
  ],
};
