const NAV=[['home','⌂','Início'],['companies','▦','Empresas'],['meetings','◷','Reuniões'],['diagnostics','◎','Diagnósticos'],['projects','◇','Projetos'],['actions','✓','Planos de Ação'],['indicators','↗','Indicadores'],['presentations','▤','Apresentações'],['evidence','◫','Evidências'],['settings','⚙','Configurações']];
const today=()=>new Date().toISOString().slice(0,10);const uid=(p='id')=>p+'_'+Math.random().toString(36).slice(2,9);
const DEMO={
 companies:[
  {id:'c1',name:'Clínica Alfa',segment:'Saúde',description:'Clínica multidisciplinar com atendimento presencial e digital.',size:'Médio',location:'Belo Horizonte, MG',objective:'Reduzir tempo de atendimento e perdas comerciais',notes:'Diagnóstico em andamento',health:72,evolution:14,alerts:3,created:'2026-07-18'},
  {id:'c2',name:'Varejo Horizonte',segment:'Varejo',description:'Rede regional de lojas com operação omnichannel.',size:'Médio',location:'Minas Gerais',objective:'Melhorar conversão e reduzir rupturas de estoque',notes:'Aguardando dados de estoque',health:61,evolution:7,alerts:5,created:'2026-07-30'}
 ],
 meetings:[
  {id:'m1',companyId:'c1',theme:'Tempo elevado no atendimento pelo WhatsApp',objective:'Entender causas e perdas de conversão',date:'2026-08-12',status:'Finalizada',duration:'00:43:18',notes:'Equipe relata demora no período da tarde.',problems:[{id:'p1',title:'Tempo de primeira resposta elevado',known:'Liderança relata demora principalmente no período da tarde.',evidence:'Relato em reunião; CRM ainda não recebido.',hypothesis:'Distribuição inadequada ou capacidade insuficiente.',missing:'Tempo por faixa horária e volume de contatos.',next:'Solicitar relatório de atendimento por hora.',confidence:58,status:'Hipótese'}],evidences:['Relato da liderança sobre demora no período da tarde'],hypotheses:['Distribuição inadequada de contatos'],indicators:['Tempo médio de primeira resposta'],pending:['Relatório de atendimento dos últimos 90 dias'],snapshot:true},
  {id:'m2',companyId:'c2',theme:'Ruptura de estoque e queda de conversão',objective:'Localizar gargalos entre compra, estoque e loja',date:'2026-08-18',status:'Finalizada',duration:'00:51:05',notes:'Rupturas recorrentes em itens de alto giro.',problems:[{id:'p2',title:'Ruptura em itens de alto giro',known:'Gerentes relatam falta recorrente em lojas específicas.',evidence:'Relato e relatório parcial de lojas.',hypothesis:'Parâmetros de reposição e previsão podem estar inadequados.',missing:'Cobertura, lead time e ruptura por SKU/loja.',next:'Cruzar lead time com vendas e estoque mínimo.',confidence:65,status:'Evidência parcial'}],evidences:['Relatório parcial de ruptura'],hypotheses:['Estoque mínimo descalibrado'],indicators:['Taxa de ruptura'],pending:['Exportação do ERP por SKU e loja'],snapshot:true}
 ],
 evidence:[
  {id:'e1',companyId:'c1',title:'Relato de demora no atendimento',source:'Reunião 12/08/2026',date:'2026-08-12',context:'Atendimento comercial',confidence:'Média',related:'Tempo de primeira resposta elevado',status:'Registrada'},
  {id:'e2',companyId:'c2',title:'Relatório parcial de ruptura',source:'Arquivo interno',date:'2026-08-18',context:'Estoque / lojas',confidence:'Média',related:'Ruptura em itens de alto giro',status:'Registrada'}
 ],
 projects:[{id:'pr1',companyId:'c1',name:'Transformação do Atendimento',status:'Em diagnóstico',progress:28},{id:'pr2',companyId:'c2',name:'Disponibilidade de Estoque',status:'Levantamento',progress:18}],
 actions:[{id:'a1',companyId:'c1',title:'Extrair relatório de atendimento',owner:'Cliente',due:'2026-08-27',status:'Em andamento',priority:'P1'},{id:'a2',companyId:'c2',title:'Exportar estoque por SKU/loja',owner:'Cliente',due:'2026-08-29',status:'Aguardando',priority:'P1'}],
 indicators:[{id:'i1',companyId:'c1',name:'Tempo médio de 1ª resposta',baseline:'27 min',current:'19 min',target:'10 min',trend:'Melhora'},{id:'i2',companyId:'c1',name:'Conversão de leads',baseline:'8,0%',current:'10,4%',target:'15%',trend:'Melhora'},{id:'i3',companyId:'c2',name:'Taxa de ruptura',baseline:'12,8%',current:'11,9%',target:'6%',trend:'Melhora'}],
 presentations:[{id:'s1',companyId:'c1',name:'Diagnóstico preliminar',version:'v1',date:'2026-08-12',type:'Prévia executiva'},{id:'s2',companyId:'c2',name:'Diagnóstico de estoque',version:'v1',date:'2026-08-18',type:'Prévia executiva'}],
 providers:[{cap:'IA / LLM',provider:'Default econômico',mode:'Free / Default',status:'Ativo'},{cap:'Transcrição',provider:'Engine padrão',mode:'Free / Default',status:'Ativo'},{cap:'OCR',provider:'Local / básico',mode:'Free / Default',status:'Ativo'},{cap:'Armazenamento',provider:'Local demo',mode:'Free / Default',status:'Ativo'},{cap:'E-mail',provider:'Não conectado',mode:'Free / Default',status:'Pendente'},{cap:'Analytics',provider:'Local',mode:'Free / Default',status:'Ativo'}]
};
let state=load();let view='home',selectedCompany=null,companyTab='overview',activeMeeting=null,meetingStartedAt=null,timerHandle=null;
function load(){try{const s=JSON.parse(localStorage.getItem('lamou360_state'));if(s&&s.companies)return s}catch(e){}return structuredClone(DEMO)}
function save(){localStorage.setItem('lamou360_state',JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function company(id){return state.companies.find(c=>c.id===id)}
function dateBR(d){if(!d)return '—';const [y,m,day]=d.slice(0,10).split('-');return `${day}/${m}/${y}`}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.getElementById('toastwrap').appendChild(d);setTimeout(()=>d.remove(),3000)}
function toggleMenu(open){document.body.classList.toggle('menu-open',open)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('lamou_theme',document.body.classList.contains('dark')?'dark':'light')}
if(localStorage.getItem('lamou_theme')==='dark')document.body.classList.add('dark');
function renderNav(){document.getElementById('nav').innerHTML=NAV.map(([id,ico,label])=>`<button class="navbtn ${view===id?'active':''}" onclick="go('${id}')"><span class="navico">${ico}</span>${label}</button>`).join('')}
function go(v){view=v;selectedCompany=null;companyTab='overview';if(v!=='meetings')stopTimer();toggleMenu(false);render()}
function render(){renderNav();const root=document.getElementById('content');root.innerHTML=({home:homeView,companies:companiesView,meetings:meetingsView,diagnostics:diagnosticsView,projects:projectsView,actions:actionsView,indicators:indicatorsView,presentations:presentationsView,evidence:evidenceView,settings:settingsView}[view]||homeView)();if(view==='meetings'&&activeMeeting)startTimer()}
function pageHead(title,sub,actions=''){return `<div class="pagehead"><div><div class="eyebrow">LAMOU IA · Diagnóstico 360</div><h1>${title}</h1><div class="muted">${sub}</div></div><div class="actions">${actions}</div></div>`}
function metric(ico,val,label,delta=''){return `<div class="card metric"><div class="metricico">${ico}</div><div class="metricval">${val}</div><div class="metriclabel">${label}</div>${delta?`<div class="metricdelta">${delta}</div>`:''}</div>`}
function homeView(){return pageHead('Executive Intelligence Workspace','Visão executiva do portfólio de transformação.',`<button class="btn" onclick="openAnalysis()">＋ Nova análise</button><button class="btn primary" onclick="openNewMeeting()">◉ Nova reunião</button><button class="btn" onclick="openNewCompany()">＋ Nova empresa</button><button class="btn" onclick="openImport()">⇧ Importar dados</button>`) +
`<div class="grid metrics">${metric('▦',state.companies.length,'Empresas ativas','2 em acompanhamento')}${metric('◷',state.meetings.length,'Reuniões registradas','memória preservada')}${metric('◎',state.companies.filter(c=>c.alerts>0).length,'Diagnósticos com alertas','dados pendentes')}${metric('✓',state.actions.filter(a=>a.status!=='Concluída').length,'Ações abertas','prioridade operacional')}</div>
<div class="grid split"><div class="grid"><div class="card"><div class="section-title"><h2>Empresas que precisam de atenção</h2><button class="btn small" onclick="go('companies')">Ver todas</button></div><div class="list">${state.companies.map(c=>`<div class="row"><div class="company-logo">${esc(c.name).split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div class="grow"><div class="rowtitle">${esc(c.name)}</div><div class="rowsub">${esc(c.objective)}</div></div><span class="badge ${c.alerts>3?'b-red':'b-yellow'}"><span class="dot"></span>${c.alerts} alertas</span><button class="btn small" onclick="openCompany('${c.id}')">Abrir</button></div>`).join('')}</div></div>
<div class="card"><div class="section-title"><h2>Próximas entregas</h2><span class="headerNote">Plano vivo</span></div><div class="list">${state.actions.map(a=>`<div class="row"><div class="grow"><div class="rowtitle">${esc(a.title)}</div><div class="rowsub">${esc(company(a.companyId)?.name||'')} · ${dateBR(a.due)}</div></div><span class="badge ${a.priority==='P1'?'b-red':'b-yellow'}">${a.priority}</span></div>`).join('')}</div></div></div>
<div class="grid"><div class="card ai-panel"><div class="ai-head"><div class="ai-orb">IA</div><div><h2 style="margin:0">Copiloto executivo</h2><div class="muted">Sinais que merecem atenção.</div></div></div><div class="list" style="margin-top:14px"><div class="row" style="background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.12)"><div class="grow"><div class="rowtitle">Clínica Alfa</div><div class="rowsub" style="color:#d6e4f3">Relatório de atendimento segue pendente.</div></div></div><div class="row" style="background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.12)"><div class="grow"><div class="rowtitle">Varejo Horizonte</div><div class="rowsub" style="color:#d6e4f3">Ruptura melhorou, mas ainda longe da meta.</div></div></div></div></div>
<div class="card"><div class="section-title"><h2>Diagnósticos aguardando dados</h2></div>${state.meetings.map(m=>`<div class="need"><span>${esc(company(m.companyId)?.name||'')} · ${esc(m.theme)}</span><span class="badge b-yellow">${m.pending?.length||0} pend.</span></div>`).join('')}</div></div></div>`}
function companiesView(){if(selectedCompany)return companyWorkspace();return pageHead('Empresas','Ambientes segregados por cliente, com memória e evolução próprias.',`<button class="btn primary" onclick="openNewCompany()">＋ Nova empresa</button>`) + `<div class="grid company-grid">${state.companies.map(c=>`<div class="card company-card" onclick="openCompany('${c.id}')"><div class="company-top"><div class="company-logo">${esc(c.name).split(' ').map(x=>x[0]).slice(0,2).join('')}</div><span class="badge ${c.alerts>3?'b-red':'b-yellow'}">${c.alerts} alertas</span></div><h2 style="margin:13px 0 4px">${esc(c.name)}</h2><div class="muted" style="font-size:12px">${esc(c.segment)} · ${esc(c.location)}</div><div class="company-meta"><span class="badge b-blue">Saúde ${c.health}/100</span><span class="badge b-green">+${c.evolution} evolução</span><span class="badge b-gray">${esc(c.size)}</span></div><p class="muted" style="font-size:12px;margin:14px 0 0">${esc(c.objective)}</p></div>`).join('')}</div>`}
function openCompany(id){selectedCompany=id;view='companies';companyTab='overview';render()}
function companyWorkspace(){const c=company(selectedCompany),ms=state.meetings.filter(m=>m.companyId===c.id),ev=state.evidence.filter(e=>e.companyId===c.id),acts=state.actions.filter(a=>a.companyId===c.id),inds=state.indicators.filter(i=>i.companyId===c.id);const tabs=[['overview','Visão Geral'],['meetings','Reuniões'],['diagnostics','Diagnósticos'],['projects','Projetos'],['indicators','Indicadores'],['evidence','Evidências'],['actions','Ações'],['presentations','Apresentações']];let body='';if(companyTab==='overview')body=`<div class="grid split"><div class="grid"><div class="card"><div class="section-title"><h2>Onde estamos</h2><span class="badge b-blue">Saúde ${c.health}/100</span></div><div class="barrow"><span>Estratégia</span><div class="progress"><i style="width:76%"></i></div><b>76</b></div><div class="barrow"><span>Processos</span><div class="progress"><i style="width:64%"></i></div><b>64</b></div><div class="barrow"><span>Dados</span><div class="progress"><i style="width:57%"></i></div><b>57</b></div><div class="barrow"><span>Execução</span><div class="progress"><i style="width:71%"></i></div><b>71</b></div></div><div class="card"><h2>O que mudou</h2><div class="list">${inds.length?inds.map(i=>`<div class="row"><div class="grow"><div class="rowtitle">${esc(i.name)}</div><div class="rowsub">Inicial ${esc(i.baseline)} → Atual ${esc(i.current)}</div></div><span class="badge b-green">${esc(i.trend)}</span></div>`).join(''):'<div class="empty">Sem indicadores comparáveis ainda.</div>'}</div></div><div class="card"><h2>Problemas prioritários</h2><div class="list">${ms.flatMap(m=>m.problems||[]).slice(0,4).map(p=>`<div class="row"><div class="grow"><div class="rowtitle">${esc(p.title)}</div><div class="rowsub">Confiança ${p.confidence}% · ${esc(p.status)}</div></div><span class="badge b-red">P1</span></div>`).join('')||'<div class="empty">Nenhum problema registrado.</div>'}</div></div></div><div class="grid"><div class="card"><h2>Dados faltantes</h2>${ms.flatMap(m=>m.pending||[]).map(x=>`<div class="need"><span>${esc(x)}</span><span class="badge b-yellow">Pendente</span></div>`).join('')||'<div class="empty">Nenhuma pendência de dados.</div>'}</div><div class="card"><h2>Próximos passos</h2>${acts.map(a=>`<div class="need"><span>${esc(a.title)}</span><span class="badge b-blue">${dateBR(a.due)}</span></div>`).join('')||'<div class="empty">Sem ações.</div>'}</div><div class="card"><h2>Timeline da evolução</h2><div class="timeline">${timelineFor(c.id)}</div></div></div></div>`;
else body=companyTabContent(c,companyTab);
return `<button class="btn small" onclick="selectedCompany=null;render()">← Empresas</button><div class="card" style="margin:10px 0 14px"><div class="company-hero"><div class="company-logo">${c.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><div class="eyebrow">Workspace da empresa</div><h1 style="margin:0">${esc(c.name)}</h1><div class="muted" style="font-size:12px">${esc(c.segment)} · ${esc(c.location)}</div></div><div class="hero-stats"><div class="hero-stat"><small class="muted">Saúde</small><b>${c.health}</b></div><div class="hero-stat"><small class="muted">Evolução</small><b style="color:var(--green)">+${c.evolution}</b></div><div class="hero-stat"><small class="muted">Alertas</small><b style="color:var(--red)">${c.alerts}</b></div></div></div></div><div class="tabs">${tabs.map(([id,l])=>`<button class="tab ${companyTab===id?'active':''}" onclick="companyTab='${id}';render()">${l}</button>`).join('')}</div>${body}`}
function companyTabContent(c,t){if(t==='meetings'){const a=state.meetings.filter(x=>x.companyId===c.id);return `<div class="card"><div class="section-title"><h2>Reuniões</h2><button class="btn small primary" onclick="openNewMeeting('${c.id}')">Nova reunião</button></div>${a.map(m=>meetingRow(m)).join('')||'<div class="empty">Sem reuniões.</div>'}</div>`}if(t==='evidence'){return evidenceCards(c.id)}if(t==='indicators'){return indicatorTable(c.id)}if(t==='actions'){return actionsCards(c.id)}if(t==='presentations'){return presentationCards(c.id)}if(t==='projects'){return projectCards(c.id)}if(t==='diagnostics'){return diagnosticBlock(c.id)}return ''}
function timelineFor(cid){const arr=[];state.meetings.filter(x=>x.companyId===cid).forEach(m=>arr.push({d:m.date,t:'Reunião',x:m.theme}));state.evidence.filter(x=>x.companyId===cid).forEach(e=>arr.push({d:e.date,t:'Evidência',x:e.title}));state.actions.filter(x=>x.companyId===cid).forEach(a=>arr.push({d:a.due,t:'Ação',x:a.title}));return arr.sort((a,b)=>b.d.localeCompare(a.d)).map(x=>`<div class="timeitem"><b>${x.t} · ${dateBR(x.d)}</b><p>${esc(x.x)}</p></div>`).join('')||'<div class="empty">Timeline vazia.</div>'}
