(function(){
const REGISTRY={
 analytics:{stateful:false,preferred:'posthog-free',providers:{'posthog-free':{label:'PostHog Free',configured:false,quota:true,fallback:'umami-selfhosted'},'umami-selfhosted':{label:'Umami self-hosted',configured:false,quota:false,fallback:'local-audit'},'local-audit':{label:'Auditoria local',configured:true,quota:false}}},
 errorMonitoring:{stateful:false,preferred:'sentry-free',providers:{'sentry-free':{label:'Sentry Free',configured:false,quota:true,fallback:'glitchtip-selfhosted'},'glitchtip-selfhosted':{label:'GlitchTip self-hosted',configured:false,quota:false,fallback:'local-audit'},'local-audit':{label:'Auditoria local',configured:true,quota:false}}},
 dataAuth:{stateful:true,preferred:'supabase-free',providers:{'supabase-free':{label:'Supabase Free',configured:false,quota:true,fallback:'local-offline'},'appwrite-free':{label:'Appwrite Free',configured:false,quota:true,fallback:'local-offline'},'pocketbase-selfhosted':{label:'PocketBase self-hosted',configured:false,quota:false,fallback:'local-offline'},'local-offline':{label:'Modo local/offline',configured:true,quota:false}}},
 ai:{stateful:false,preferred:'gemini-free',providers:{'gemini-free':{label:'Gemini Free',configured:false,quota:true,fallback:'transformers-local'},'transformers-local':{label:'Transformers.js local',configured:false,quota:false,fallback:'local-rules'},'local-rules':{label:'Regras locais',configured:true,quota:false}}}
};
class PluginRouter{
 constructor(core){this.core=core;this.handlers={};this.state=core.get('plugins:state',{overrides:{},health:{}});this._registerLocal()}
 _save(){this.core.set('plugins:state',this.state)}
 _cfg(cap,id){return REGISTRY[cap]&&REGISTRY[cap].providers[id]}
 _health(cap,id){const k=cap+':'+id;return this.state.health[k]||(this.state.health[k]={status:'ok',failures:0,quotaPercent:null,blockedUntil:0})}
 register(cap,id,handler){const cfg=this._cfg(cap,id);if(!cfg)throw new Error('Provider não registrado: '+cap+'/'+id);this.handlers[cap+':'+id]=handler;cfg.configured=true;this.core.audit('plugin:registered',{capability:cap,provider:id});return true}
 _usable(cap,id){const cfg=this._cfg(cap,id);if(!cfg||!cfg.configured)return false;const h=this._health(cap,id);return !h.blockedUntil||h.blockedUntil<=Date.now()}
 selected(cap){const c=REGISTRY[cap];if(!c)return null;const override=this.state.overrides[cap];if(override&&this._usable(cap,override))return override;if(this._usable(cap,c.preferred))return c.preferred;return Object.keys(c.providers).find(id=>this._usable(cap,id))||null}
 select(cap,id){const c=REGISTRY[cap],cfg=this._cfg(cap,id);if(!c||!cfg)return{ok:false,reason:'unknown-provider'};if(!cfg.configured)return{ok:false,requiresSetup:true,capability:cap,provider:id};const current=this.selected(cap);if(c.stateful&&current&&current!==id&&id!=='local-offline')return{ok:false,requiresMigration:true,capability:cap,from:current,to:id};this.state.overrides[cap]=id;this._save();this.core.audit('plugin:selected',{capability:cap,provider:id});return{ok:true,capability:cap,provider:id}}
 _fallback(cap,from,reason){const c=REGISTRY[cap],cfg=this._cfg(cap,from);if(!c)return null;const candidates=[];if(cfg&&cfg.fallback)candidates.push(cfg.fallback);for(const id of Object.keys(c.providers))if(id!==from&&!candidates.includes(id))candidates.push(id);const next=candidates.find(id=>this._usable(cap,id));if(next){this.state.overrides[cap]=next;this._save();this.core.audit('plugin:fallback',{capability:cap,from,to:next,reason});return next}return null}
 reportQuota(cap,id,percent){const h=this._health(cap,id);h.quotaPercent=Math.max(0,Math.min(100,Number(percent)||0));h.status=h.quotaPercent>=95?'quota-fallback':h.quotaPercent>=80?'quota-warning':'ok';if(h.quotaPercent>=95){h.blockedUntil=Date.now()+60*60*1000;this._fallback(cap,id,'quota>=95%')}this._save();return h}
 reportFailure(cap,id,error){const h=this._health(cap,id),text=String(error&&error.message||error||'');h.failures=(h.failures||0)+1;const quota=/\b(402|429)\b|quota|rate.?limit/i.test(text);if(quota||h.failures>=3){h.status=quota?'quota-or-rate-limit':'circuit-open';h.blockedUntil=Date.now()+(quota?60*60*1000:5*60*1000);this._fallback(cap,id,h.status)}else h.status='degraded';this._save();this.core.audit('plugin:failure',{capability:cap,provider:id,status:h.status,message:text.slice(0,240)});return h}
 async execute(cap,operation,payload){let id=this.selected(cap);if(!id)return{ok:false,degraded:true,reason:'no-provider'};let handler=this.handlers[cap+':'+id];if(!handler){const next=this._fallback(cap,id,'handler-not-registered');if(!next)return{ok:false,degraded:true,reason:'provider-not-ready',provider:id};id=next;handler=this.handlers[cap+':'+id]}if(!handler)return{ok:false,degraded:true,reason:'fallback-not-ready',provider:id};try{return await handler(operation,payload)}catch(err){this.reportFailure(cap,id,err);const next=this.selected(cap);if(next&&next!==id&&this.handlers[cap+':'+next]){try{return await this.handlers[cap+':'+next](operation,payload)}catch(e){this.reportFailure(cap,next,e)}}return{ok:false,degraded:true,provider:id,error:String(err&&err.message||err)}}}
 list(){const out={};for(const [cap,c] of Object.entries(REGISTRY)){out[cap]={selected:this.selected(cap),stateful:c.stateful,providers:Object.entries(c.providers).map(([id,p])=>({id,label:p.label,configured:p.configured,quotaBased:p.quota,health:this._health(cap,id)}))}}return out}
 _registerLocal(){this.register('analytics','local-audit',async(op,payload)=>{this.core.audit('analytics:'+op,payload||{});return{ok:true,provider:'local-audit'}});this.register('errorMonitoring','local-audit',async(op,payload)=>{this.core.audit('error:'+op,payload||{});return{ok:true,provider:'local-audit'}});this.register('dataAuth','local-offline',async(op,payload)=>{if(op==='queue'){const q=this.core.get('plugins:offlineQueue',[]);q.push({payload,ts:new Date().toISOString()});this.core.set('plugins:offlineQueue',q.slice(-1000));return{ok:true,queued:true,provider:'local-offline'}}return{ok:true,degraded:true,provider:'local-offline'}});this.register('ai','local-rules',async(op,payload)=>({ok:true,degraded:true,provider:'local-rules',operation:op,input:payload||null}))}
 openCenter(){let el=document.getElementById('lamou-plugin-center');if(el){el.remove();return}el=document.createElement('div');el.id='lamou-plugin-center';el.style.cssText='position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.68);display:grid;place-items:center;padding:16px;font-family:system-ui,sans-serif';const panel=document.createElement('div');panel.style.cssText='width:min(760px,100%);max-height:88vh;overflow:auto;background:#fff;color:#111;border-radius:18px;padding:20px;box-shadow:0 24px 80px #0008';panel.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><b style="font-size:20px">LAMOU Plugin Center</b><div style="font-size:12px;color:#666">CORE 2.1 · gratuito primeiro · sem cobrança automática</div></div><button id="lamou-pc-close" style="border:0;background:#eee;border-radius:10px;padding:8px 12px">Fechar</button></div><div id="lamou-pc-list" style="margin-top:16px;display:grid;gap:12px"></div>';el.appendChild(panel);document.body.appendChild(el);panel.querySelector('#lamou-pc-close').onclick=()=>el.remove();el.addEventListener('click',e=>{if(e.target===el)el.remove()});const list=panel.querySelector('#lamou-pc-list');const names={analytics:'Analytics',errorMonitoring:'Erros/observabilidade',dataAuth:'Banco e autenticação',ai:'IA'};for(const [cap,c] of Object.entries(REGISTRY)){const row=document.createElement('div');row.style.cssText='border:1px solid #ddd;border-radius:14px;padding:14px';const selected=this.selected(cap);row.innerHTML='<div style="font-weight:800;margin-bottom:8px">'+names[cap]+'</div><select style="width:100%;padding:10px;border-radius:10px;border:1px solid #bbb"></select><div class="note" style="margin-top:7px;font-size:12px;color:#666"></div>';const sel=row.querySelector('select'),note=row.querySelector('.note');for(const [id,p] of Object.entries(c.providers)){const o=document.createElement('option');o.value=id;o.textContent=p.label+(p.configured?'':' · requer configuração');o.selected=id===selected;sel.appendChild(o)}note.textContent=c.stateful?'Troca de banco/login exige verificação de migração; em limite, o app degrada para modo local/offline.':'Falha ou cota crítica pode acionar fallback automaticamente.';sel.onchange=()=>{const r=this.select(cap,sel.value);if(!r.ok){alert(r.requiresMigration?'Troca de dados exige migração segura antes de ativar.':'Esse provedor precisa ser configurado antes de ser ativado.');sel.value=this.selected(cap)||''}};list.appendChild(row)}return true}
}
class AppCoreRuntime{
 constructor(){this.appId='lamoumusicpromoter1';this.version='2.1.0';this.started=false;this.plugins=new PluginRouter(this)}
 get(k,f=null){try{const r=localStorage.getItem(`${this.appId}:${k}`);return r===null?f:JSON.parse(r)}catch{return f}}
 set(k,v){try{localStorage.setItem(`${this.appId}:${k}`,JSON.stringify(v))}catch{}return v}
 audit(action,meta={}){const log=this.get('audit',[]);log.push({action,meta,ts:new Date().toISOString()});this.set('audit',log.slice(-500));return log[log.length-1]}
 health(){let storage=true;try{localStorage.setItem('__core_test','1');localStorage.removeItem('__core_test')}catch{storage=false}return{ok:storage,appId:this.appId,version:this.version,online:navigator.onLine,storage:storage?'localStorage':'unavailable',plugins:this.plugins.list(),policy:{freeOnly:true,neverBlockApp:true,paidAutoUpgrade:false},ts:new Date().toISOString()}}
 bootstrap(){if(this.started)return this.health();this.started=true;this.audit('core:bootstrap',{href:location.href});addEventListener('error',e=>{this.plugins.execute('errorMonitoring','capture',{message:e.message,source:e.filename,line:e.lineno}).catch(()=>{})});addEventListener('unhandledrejection',e=>{this.plugins.execute('errorMonitoring','capture',{reason:String(e.reason)}).catch(()=>{})});this.plugins.execute('analytics','capture',{event:'core_bootstrap',href:location.href}).catch(()=>{});return this.health()}
 smoke(){const result={ok:!!document.body&&this.health().ok,health:this.health(),ts:new Date().toISOString()};this.audit('core:smoke',result);return result}
 openPluginCenter(){return this.plugins.openCenter()}
}
window.APP_CORE=new AppCoreRuntime();window.APP_CORE.bootstrap();
})();
