/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppsBenchmarkerRouteImport } from './routes/apps.benchmarker'
import { Route as AppsDiagnostico360RouteImport } from './routes/apps.diagnostico-360'
import { Route as AppsDigitalImprovementRouteImport } from './routes/apps.digital-improvement'
import { Route as AppsLabRouteImport } from './routes/apps.lab'
import { Route as AppsMeetingArchitectRouteImport } from './routes/apps.meeting-architect'
import { Route as AppsOpportunityIntelligenceRouteImport } from './routes/apps.opportunity-intelligence'
import { Route as AppsOrbitRouteImport } from './routes/apps.orbit'
import { Route as AppsResearchScoutRouteImport } from './routes/apps.research-scout'
import { Route as AppsShowroomRouteImport } from './routes/apps.showroom'
import { Route as AppsTeste3RouteImport } from './routes/apps.teste3'
import { Route as AppsValidationGateRouteImport } from './routes/apps.validation-gate'
import { Route as AppsVersionRouteImport } from './routes/apps.version'
import { Route as CoreIndexRouteImport } from './routes/core.index'
import { Route as CoreAiRouteImport } from './routes/core.ai'
import { Route as CoreAppsRouteImport } from './routes/core.apps'
import { Route as CoreArchitectureRouteImport } from './routes/core.architecture'
import { Route as CoreCallsRouteImport } from './routes/core.calls'
import { Route as CoreDataRouteImport } from './routes/core.data'
import { Route as CoreHealthRouteImport } from './routes/core.health'
import { Route as CoreLabRouteImport } from './routes/core.lab'
import { Route as CoreObservabilityRouteImport } from './routes/core.observability'
import { Route as CoreProblemsRouteImport } from './routes/core.problems'
import { Route as CoreSecurityRouteImport } from './routes/core.security'
import { Route as CoreSettingsRouteImport } from './routes/core.settings'
import { Route as CoreSolLuaRouteImport } from './routes/core.sol-lua'
import { Route as CoreTestsRouteImport } from './routes/core.tests'
import { Route as CoreTrainingsRouteImport } from './routes/core.trainings'
import { Route as CoreVersionsRouteImport } from './routes/core.versions'
import { Route as InstallClientRouteImport } from './routes/install/client'
import { Route as InstallOwnerRouteImport } from './routes/install/owner'
import { Route as LabtestIndexRouteImport } from './routes/labtest.index'
import { Route as LabtestNextRouteImport } from './routes/labtest.next'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAppsRouteImport } from './routes/owner.apps'
import { Route as OwnerClientsRouteImport } from './routes/owner.clients'
import { Route as OwnerCommercialRouteImport } from './routes/owner.commercial'
import { Route as OwnerDocumentsRouteImport } from './routes/owner.documents'
import { Route as OwnerIntegrationsRouteImport } from './routes/owner.integrations'
import { Route as OwnerMapaVivoRouteImport } from './routes/owner.mapa-vivo'
import { Route as OwnerOpportunitiesRouteImport } from './routes/owner.opportunities'
import { Route as OwnerPlansRouteImport } from './routes/owner.plans'
import { Route as OwnerProductsRouteImport } from './routes/owner.products'
import { Route as OwnerSecurityRouteImport } from './routes/owner.security'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerTestsRouteImport } from './routes/owner.tests'
import { Route as OwnerVersionsRouteImport } from './routes/owner.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsBenchmarkerRoute = AppsBenchmarkerRouteImport.update({
  id: '/apps/benchmarker',
  path: '/apps/benchmarker',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDiagnostico360Route = AppsDiagnostico360RouteImport.update({
  id: '/apps/diagnostico-360',
  path: '/apps/diagnostico-360',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsDigitalImprovementRoute = AppsDigitalImprovementRouteImport.update({
  id: '/apps/digital-improvement',
  path: '/apps/digital-improvement',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsLabRoute = AppsLabRouteImport.update({
  id: '/apps/lab',
  path: '/apps/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsMeetingArchitectRoute = AppsMeetingArchitectRouteImport.update({
  id: '/apps/meeting-architect',
  path: '/apps/meeting-architect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsOpportunityIntelligenceRoute =
  AppsOpportunityIntelligenceRouteImport.update({
    id: '/apps/opportunity-intelligence',
    path: '/apps/opportunity-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppsOrbitRoute = AppsOrbitRouteImport.update({
  id: '/apps/orbit',
  path: '/apps/orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsResearchScoutRoute = AppsResearchScoutRouteImport.update({
  id: '/apps/research-scout',
  path: '/apps/research-scout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsShowroomRoute = AppsShowroomRouteImport.update({
  id: '/apps/showroom',
  path: '/apps/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTeste3Route = AppsTeste3RouteImport.update({
  id: '/apps/teste3',
  path: '/apps/teste3',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsValidationGateRoute = AppsValidationGateRouteImport.update({
  id: '/apps/validation-gate',
  path: '/apps/validation-gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsVersionRoute = AppsVersionRouteImport.update({
  id: '/apps/version',
  path: '/apps/version',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreIndexRoute = CoreIndexRouteImport.update({
  id: '/core/',
  path: '/core/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreAiRoute = CoreAiRouteImport.update({
  id: '/core/ai',
  path: '/core/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreAppsRoute = CoreAppsRouteImport.update({
  id: '/core/apps',
  path: '/core/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreArchitectureRoute = CoreArchitectureRouteImport.update({
  id: '/core/architecture',
  path: '/core/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreCallsRoute = CoreCallsRouteImport.update({
  id: '/core/calls',
  path: '/core/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreDataRoute = CoreDataRouteImport.update({
  id: '/core/data',
  path: '/core/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreHealthRoute = CoreHealthRouteImport.update({
  id: '/core/health',
  path: '/core/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreLabRoute = CoreLabRouteImport.update({
  id: '/core/lab',
  path: '/core/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreObservabilityRoute = CoreObservabilityRouteImport.update({
  id: '/core/observability',
  path: '/core/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreProblemsRoute = CoreProblemsRouteImport.update({
  id: '/core/problems',
  path: '/core/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSecurityRoute = CoreSecurityRouteImport.update({
  id: '/core/security',
  path: '/core/security',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSettingsRoute = CoreSettingsRouteImport.update({
  id: '/core/settings',
  path: '/core/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreSolLuaRoute = CoreSolLuaRouteImport.update({
  id: '/core/sol-lua',
  path: '/core/sol-lua',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreTestsRoute = CoreTestsRouteImport.update({
  id: '/core/tests',
  path: '/core/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreTrainingsRoute = CoreTrainingsRouteImport.update({
  id: '/core/trainings',
  path: '/core/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreVersionsRoute = CoreVersionsRouteImport.update({
  id: '/core/versions',
  path: '/core/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallClientRoute = InstallClientRouteImport.update({
  id: '/install/client',
  path: '/install/client',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallOwnerRoute = InstallOwnerRouteImport.update({
  id: '/install/owner',
  path: '/install/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LabtestIndexRoute = LabtestIndexRouteImport.update({
  id: '/labtest/',
  path: '/labtest/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabtestNextRoute = LabtestNextRouteImport.update({
  id: '/labtest/next',
  path: '/labtest/next',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAppsRoute = OwnerAppsRouteImport.update({
  id: '/owner/apps',
  path: '/owner/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerClientsRoute = OwnerClientsRouteImport.update({
  id: '/owner/clients',
  path: '/owner/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCommercialRoute = OwnerCommercialRouteImport.update({
  id: '/owner/commercial',
  path: '/owner/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDocumentsRoute = OwnerDocumentsRouteImport.update({
  id: '/owner/documents',
  path: '/owner/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIntegrationsRoute = OwnerIntegrationsRouteImport.update({
  id: '/owner/integrations',
  path: '/owner/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMapaVivoRoute = OwnerMapaVivoRouteImport.update({
  id: '/owner/mapa-vivo',
  path: '/owner/mapa-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOpportunitiesRoute = OwnerOpportunitiesRouteImport.update({
  id: '/owner/opportunities',
  path: '/owner/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPlansRoute = OwnerPlansRouteImport.update({
  id: '/owner/plans',
  path: '/owner/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/owner/products',
  path: '/owner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSecurityRoute = OwnerSecurityRouteImport.update({
  id: '/owner/security',
  path: '/owner/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerTestsRoute = OwnerTestsRouteImport.update({
  id: '/owner/tests',
  path: '/owner/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVersionsRoute = OwnerVersionsRouteImport.update({
  id: '/owner/versions',
  path: '/owner/versions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/apps/benchmarker': typeof AppsBenchmarkerRoute
  '/apps/diagnostico-360': typeof AppsDiagnostico360Route
  '/apps/digital-improvement': typeof AppsDigitalImprovementRoute
  '/apps/lab': typeof AppsLabRoute
  '/apps/meeting-architect': typeof AppsMeetingArchitectRoute
  '/apps/opportunity-intelligence': typeof AppsOpportunityIntelligenceRoute
  '/apps/orbit': typeof AppsOrbitRoute
  '/apps/research-scout': typeof AppsResearchScoutRoute
  '/apps/showroom': typeof AppsShowroomRoute
  '/apps/teste3': typeof AppsTeste3Route
  '/apps/validation-gate': typeof AppsValidationGateRoute
  '/apps/version': typeof AppsVersionRoute
  '/core/ai': typeof CoreAiRoute
  '/core/apps': typeof CoreAppsRoute
  '/core/architecture': typeof CoreArchitectureRoute
  '/core/calls': typeof CoreCallsRoute
  '/core/data': typeof CoreDataRoute
  '/core/health': typeof CoreHealthRoute
  '/core/lab': typeof CoreLabRoute
  '/core/observability': typeof CoreObservabilityRoute
  '/core/problems': typeof CoreProblemsRoute
  '/core/security': typeof CoreSecurityRoute
  '/core/settings': typeof CoreSettingsRoute
  '/core/sol-lua': typeof CoreSolLuaRoute
  '/core/tests': typeof CoreTestsRoute
  '/core/trainings': typeof CoreTrainingsRoute
  '/core/versions': typeof CoreVersionsRoute
  '/install/client': typeof InstallClientRoute
  '/install/owner': typeof InstallOwnerRoute
  '/labtest/next': typeof LabtestNextRoute
  '/owner/apps': typeof OwnerAppsRoute
  '/owner/clients': typeof OwnerClientsRoute
  '/owner/commercial': typeof OwnerCommercialRoute
  '/owner/documents': typeof OwnerDocumentsRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/mapa-vivo': typeof OwnerMapaVivoRoute
  '/owner/opportunities': typeof OwnerOpportunitiesRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tests': typeof OwnerTestsRoute
  '/owner/versions': typeof OwnerVersionsRoute
  '/core/': typeof CoreIndexRoute
  '/labtest/': typeof LabtestIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/apps/benchmarker': typeof AppsBenchmarkerRoute
  '/apps/diagnostico-360': typeof AppsDiagnostico360Route
  '/apps/digital-improvement': typeof AppsDigitalImprovementRoute
  '/apps/lab': typeof AppsLabRoute
  '/apps/meeting-architect': typeof AppsMeetingArchitectRoute
  '/apps/opportunity-intelligence': typeof AppsOpportunityIntelligenceRoute
  '/apps/orbit': typeof AppsOrbitRoute
  '/apps/research-scout': typeof AppsResearchScoutRoute
  '/apps/showroom': typeof AppsShowroomRoute
  '/apps/teste3': typeof AppsTeste3Route
  '/apps/validation-gate': typeof AppsValidationGateRoute
  '/apps/version': typeof AppsVersionRoute
  '/core/ai': typeof CoreAiRoute
  '/core/apps': typeof CoreAppsRoute
  '/core/architecture': typeof CoreArchitectureRoute
  '/core/calls': typeof CoreCallsRoute
  '/core/data': typeof CoreDataRoute
  '/core/health': typeof CoreHealthRoute
  '/core/lab': typeof CoreLabRoute
  '/core/observability': typeof CoreObservabilityRoute
  '/core/problems': typeof CoreProblemsRoute
  '/core/security': typeof CoreSecurityRoute
  '/core/settings': typeof CoreSettingsRoute
  '/core/sol-lua': typeof CoreSolLuaRoute
  '/core/tests': typeof CoreTestsRoute
  '/core/trainings': typeof CoreTrainingsRoute
  '/core/versions': typeof CoreVersionsRoute
  '/install/client': typeof InstallClientRoute
  '/install/owner': typeof InstallOwnerRoute
  '/labtest/next': typeof LabtestNextRoute
  '/owner/apps': typeof OwnerAppsRoute
  '/owner/clients': typeof OwnerClientsRoute
  '/owner/commercial': typeof OwnerCommercialRoute
  '/owner/documents': typeof OwnerDocumentsRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/mapa-vivo': typeof OwnerMapaVivoRoute
  '/owner/opportunities': typeof OwnerOpportunitiesRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tests': typeof OwnerTestsRoute
  '/owner/versions': typeof OwnerVersionsRoute
  '/core': typeof CoreIndexRoute
  '/labtest': typeof LabtestIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/apps/benchmarker': typeof AppsBenchmarkerRoute
  '/apps/diagnostico-360': typeof AppsDiagnostico360Route
  '/apps/digital-improvement': typeof AppsDigitalImprovementRoute
  '/apps/lab': typeof AppsLabRoute
  '/apps/meeting-architect': typeof AppsMeetingArchitectRoute
  '/apps/opportunity-intelligence': typeof AppsOpportunityIntelligenceRoute
  '/apps/orbit': typeof AppsOrbitRoute
  '/apps/research-scout': typeof AppsResearchScoutRoute
  '/apps/showroom': typeof AppsShowroomRoute
  '/apps/teste3': typeof AppsTeste3Route
  '/apps/validation-gate': typeof AppsValidationGateRoute
  '/apps/version': typeof AppsVersionRoute
  '/core/ai': typeof CoreAiRoute
  '/core/apps': typeof CoreAppsRoute
  '/core/architecture': typeof CoreArchitectureRoute
  '/core/calls': typeof CoreCallsRoute
  '/core/data': typeof CoreDataRoute
  '/core/health': typeof CoreHealthRoute
  '/core/lab': typeof CoreLabRoute
  '/core/observability': typeof CoreObservabilityRoute
  '/core/problems': typeof CoreProblemsRoute
  '/core/security': typeof CoreSecurityRoute
  '/core/settings': typeof CoreSettingsRoute
  '/core/sol-lua': typeof CoreSolLuaRoute
  '/core/tests': typeof CoreTestsRoute
  '/core/trainings': typeof CoreTrainingsRoute
  '/core/versions': typeof CoreVersionsRoute
  '/install/client': typeof InstallClientRoute
  '/install/owner': typeof InstallOwnerRoute
  '/labtest/next': typeof LabtestNextRoute
  '/owner/apps': typeof OwnerAppsRoute
  '/owner/clients': typeof OwnerClientsRoute
  '/owner/commercial': typeof OwnerCommercialRoute
  '/owner/documents': typeof OwnerDocumentsRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/mapa-vivo': typeof OwnerMapaVivoRoute
  '/owner/opportunities': typeof OwnerOpportunitiesRoute
  '/owner/plans': typeof OwnerPlansRoute
  '/owner/products': typeof OwnerProductsRoute
  '/owner/security': typeof OwnerSecurityRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/tests': typeof OwnerTestsRoute
  '/owner/versions': typeof OwnerVersionsRoute
  '/core/': typeof CoreIndexRoute
  '/labtest/': typeof LabtestIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/apps/benchmarker'
    | '/apps/diagnostico-360'
    | '/apps/digital-improvement'
    | '/apps/lab'
    | '/apps/meeting-architect'
    | '/apps/opportunity-intelligence'
    | '/apps/orbit'
    | '/apps/research-scout'
    | '/apps/showroom'
    | '/apps/teste3'
    | '/apps/validation-gate'
    | '/apps/version'
    | '/core/ai'
    | '/core/apps'
    | '/core/architecture'
    | '/core/calls'
    | '/core/data'
    | '/core/health'
    | '/core/lab'
    | '/core/observability'
    | '/core/problems'
    | '/core/security'
    | '/core/settings'
    | '/core/sol-lua'
    | '/core/tests'
    | '/core/trainings'
    | '/core/versions'
    | '/install/client'
    | '/install/owner'
    | '/labtest/next'
    | '/owner/apps'
    | '/owner/clients'
    | '/owner/commercial'
    | '/owner/documents'
    | '/owner/integrations'
    | '/owner/mapa-vivo'
    | '/owner/opportunities'
    | '/owner/plans'
    | '/owner/products'
    | '/owner/security'
    | '/owner/settings'
    | '/owner/tests'
    | '/owner/versions'
    | '/core/'
    | '/labtest/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/apps/benchmarker'
    | '/apps/diagnostico-360'
    | '/apps/digital-improvement'
    | '/apps/lab'
    | '/apps/meeting-architect'
    | '/apps/opportunity-intelligence'
    | '/apps/orbit'
    | '/apps/research-scout'
    | '/apps/showroom'
    | '/apps/teste3'
    | '/apps/validation-gate'
    | '/apps/version'
    | '/core/ai'
    | '/core/apps'
    | '/core/architecture'
    | '/core/calls'
    | '/core/data'
    | '/core/health'
    | '/core/lab'
    | '/core/observability'
    | '/core/problems'
    | '/core/security'
    | '/core/settings'
    | '/core/sol-lua'
    | '/core/tests'
    | '/core/trainings'
    | '/core/versions'
    | '/install/client'
    | '/install/owner'
    | '/labtest/next'
    | '/owner/apps'
    | '/owner/clients'
    | '/owner/commercial'
    | '/owner/documents'
    | '/owner/integrations'
    | '/owner/mapa-vivo'
    | '/owner/opportunities'
    | '/owner/plans'
    | '/owner/products'
    | '/owner/security'
    | '/owner/settings'
    | '/owner/tests'
    | '/owner/versions'
    | '/core'
    | '/labtest'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/apps/benchmarker'
    | '/apps/diagnostico-360'
    | '/apps/digital-improvement'
    | '/apps/lab'
    | '/apps/meeting-architect'
    | '/apps/opportunity-intelligence'
    | '/apps/orbit'
    | '/apps/research-scout'
    | '/apps/showroom'
    | '/apps/teste3'
    | '/apps/validation-gate'
    | '/apps/version'
    | '/core/ai'
    | '/core/apps'
    | '/core/architecture'
    | '/core/calls'
    | '/core/data'
    | '/core/health'
    | '/core/lab'
    | '/core/observability'
    | '/core/problems'
    | '/core/security'
    | '/core/settings'
    | '/core/sol-lua'
    | '/core/tests'
    | '/core/trainings'
    | '/core/versions'
    | '/install/client'
    | '/install/owner'
    | '/labtest/next'
    | '/owner/apps'
    | '/owner/clients'
    | '/owner/commercial'
    | '/owner/documents'
    | '/owner/integrations'
    | '/owner/mapa-vivo'
    | '/owner/opportunities'
    | '/owner/plans'
    | '/owner/products'
    | '/owner/security'
    | '/owner/settings'
    | '/owner/tests'
    | '/owner/versions'
    | '/core/'
    | '/labtest/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AppsBenchmarkerRoute: typeof AppsBenchmarkerRoute
  AppsDiagnostico360Route: typeof AppsDiagnostico360Route
  AppsDigitalImprovementRoute: typeof AppsDigitalImprovementRoute
  AppsLabRoute: typeof AppsLabRoute
  AppsMeetingArchitectRoute: typeof AppsMeetingArchitectRoute
  AppsOpportunityIntelligenceRoute: typeof AppsOpportunityIntelligenceRoute
  AppsOrbitRoute: typeof AppsOrbitRoute
  AppsResearchScoutRoute: typeof AppsResearchScoutRoute
  AppsShowroomRoute: typeof AppsShowroomRoute
  AppsTeste3Route: typeof AppsTeste3Route
  AppsValidationGateRoute: typeof AppsValidationGateRoute
  AppsVersionRoute: typeof AppsVersionRoute
  CoreAiRoute: typeof CoreAiRoute
  CoreAppsRoute: typeof CoreAppsRoute
  CoreArchitectureRoute: typeof CoreArchitectureRoute
  CoreCallsRoute: typeof CoreCallsRoute
  CoreDataRoute: typeof CoreDataRoute
  CoreHealthRoute: typeof CoreHealthRoute
  CoreLabRoute: typeof CoreLabRoute
  CoreObservabilityRoute: typeof CoreObservabilityRoute
  CoreProblemsRoute: typeof CoreProblemsRoute
  CoreSecurityRoute: typeof CoreSecurityRoute
  CoreSettingsRoute: typeof CoreSettingsRoute
  CoreSolLuaRoute: typeof CoreSolLuaRoute
  CoreTestsRoute: typeof CoreTestsRoute
  CoreTrainingsRoute: typeof CoreTrainingsRoute
  CoreVersionsRoute: typeof CoreVersionsRoute
  InstallClientRoute: typeof InstallClientRoute
  InstallOwnerRoute: typeof InstallOwnerRoute
  LabtestNextRoute: typeof LabtestNextRoute
  OwnerAppsRoute: typeof OwnerAppsRoute
  OwnerClientsRoute: typeof OwnerClientsRoute
  OwnerCommercialRoute: typeof OwnerCommercialRoute
  OwnerDocumentsRoute: typeof OwnerDocumentsRoute
  OwnerIntegrationsRoute: typeof OwnerIntegrationsRoute
  OwnerMapaVivoRoute: typeof OwnerMapaVivoRoute
  OwnerOpportunitiesRoute: typeof OwnerOpportunitiesRoute
  OwnerPlansRoute: typeof OwnerPlansRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  OwnerSecurityRoute: typeof OwnerSecurityRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerTestsRoute: typeof OwnerTestsRoute
  OwnerVersionsRoute: typeof OwnerVersionsRoute
  CoreIndexRoute: typeof CoreIndexRoute
  LabtestIndexRoute: typeof LabtestIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/benchmarker': {
      id: '/apps/benchmarker'
      path: '/apps/benchmarker'
      fullPath: '/apps/benchmarker'
      preLoaderRoute: typeof AppsBenchmarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/diagnostico-360': {
      id: '/apps/diagnostico-360'
      path: '/apps/diagnostico-360'
      fullPath: '/apps/diagnostico-360'
      preLoaderRoute: typeof AppsDiagnostico360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/digital-improvement': {
      id: '/apps/digital-improvement'
      path: '/apps/digital-improvement'
      fullPath: '/apps/digital-improvement'
      preLoaderRoute: typeof AppsDigitalImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/lab': {
      id: '/apps/lab'
      path: '/apps/lab'
      fullPath: '/apps/lab'
      preLoaderRoute: typeof AppsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/meeting-architect': {
      id: '/apps/meeting-architect'
      path: '/apps/meeting-architect'
      fullPath: '/apps/meeting-architect'
      preLoaderRoute: typeof AppsMeetingArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/opportunity-intelligence': {
      id: '/apps/opportunity-intelligence'
      path: '/apps/opportunity-intelligence'
      fullPath: '/apps/opportunity-intelligence'
      preLoaderRoute: typeof AppsOpportunityIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/orbit': {
      id: '/apps/orbit'
      path: '/apps/orbit'
      fullPath: '/apps/orbit'
      preLoaderRoute: typeof AppsOrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/research-scout': {
      id: '/apps/research-scout'
      path: '/apps/research-scout'
      fullPath: '/apps/research-scout'
      preLoaderRoute: typeof AppsResearchScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/showroom': {
      id: '/apps/showroom'
      path: '/apps/showroom'
      fullPath: '/apps/showroom'
      preLoaderRoute: typeof AppsShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/teste3': {
      id: '/apps/teste3'
      path: '/apps/teste3'
      fullPath: '/apps/teste3'
      preLoaderRoute: typeof AppsTeste3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/validation-gate': {
      id: '/apps/validation-gate'
      path: '/apps/validation-gate'
      fullPath: '/apps/validation-gate'
      preLoaderRoute: typeof AppsValidationGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/version': {
      id: '/apps/version'
      path: '/apps/version'
      fullPath: '/apps/version'
      preLoaderRoute: typeof AppsVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/': {
      id: '/core/'
      path: '/core'
      fullPath: '/core/'
      preLoaderRoute: typeof CoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/ai': {
      id: '/core/ai'
      path: '/core/ai'
      fullPath: '/core/ai'
      preLoaderRoute: typeof CoreAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/apps': {
      id: '/core/apps'
      path: '/core/apps'
      fullPath: '/core/apps'
      preLoaderRoute: typeof CoreAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/architecture': {
      id: '/core/architecture'
      path: '/core/architecture'
      fullPath: '/core/architecture'
      preLoaderRoute: typeof CoreArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/calls': {
      id: '/core/calls'
      path: '/core/calls'
      fullPath: '/core/calls'
      preLoaderRoute: typeof CoreCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/data': {
      id: '/core/data'
      path: '/core/data'
      fullPath: '/core/data'
      preLoaderRoute: typeof CoreDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/health': {
      id: '/core/health'
      path: '/core/health'
      fullPath: '/core/health'
      preLoaderRoute: typeof CoreHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/lab': {
      id: '/core/lab'
      path: '/core/lab'
      fullPath: '/core/lab'
      preLoaderRoute: typeof CoreLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/observability': {
      id: '/core/observability'
      path: '/core/observability'
      fullPath: '/core/observability'
      preLoaderRoute: typeof CoreObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/problems': {
      id: '/core/problems'
      path: '/core/problems'
      fullPath: '/core/problems'
      preLoaderRoute: typeof CoreProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/security': {
      id: '/core/security'
      path: '/core/security'
      fullPath: '/core/security'
      preLoaderRoute: typeof CoreSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/settings': {
      id: '/core/settings'
      path: '/core/settings'
      fullPath: '/core/settings'
      preLoaderRoute: typeof CoreSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/sol-lua': {
      id: '/core/sol-lua'
      path: '/core/sol-lua'
      fullPath: '/core/sol-lua'
      preLoaderRoute: typeof CoreSolLuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/tests': {
      id: '/core/tests'
      path: '/core/tests'
      fullPath: '/core/tests'
      preLoaderRoute: typeof CoreTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/trainings': {
      id: '/core/trainings'
      path: '/core/trainings'
      fullPath: '/core/trainings'
      preLoaderRoute: typeof CoreTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/versions': {
      id: '/core/versions'
      path: '/core/versions'
      fullPath: '/core/versions'
      preLoaderRoute: typeof CoreVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/client': {
      id: '/install/client'
      path: '/install/client'
      fullPath: '/install/client'
      preLoaderRoute: typeof InstallClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/owner': {
      id: '/install/owner'
      path: '/install/owner'
      fullPath: '/install/owner'
      preLoaderRoute: typeof InstallOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labtest/': {
      id: '/labtest/'
      path: '/labtest'
      fullPath: '/labtest/'
      preLoaderRoute: typeof LabtestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labtest/next': {
      id: '/labtest/next'
      path: '/labtest/next'
      fullPath: '/labtest/next'
      preLoaderRoute: typeof LabtestNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/apps': {
      id: '/owner/apps'
      path: '/owner/apps'
      fullPath: '/owner/apps'
      preLoaderRoute: typeof OwnerAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/clients': {
      id: '/owner/clients'
      path: '/owner/clients'
      fullPath: '/owner/clients'
      preLoaderRoute: typeof OwnerClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/commercial': {
      id: '/owner/commercial'
      path: '/owner/commercial'
      fullPath: '/owner/commercial'
      preLoaderRoute: typeof OwnerCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/documents': {
      id: '/owner/documents'
      path: '/owner/documents'
      fullPath: '/owner/documents'
      preLoaderRoute: typeof OwnerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/integrations': {
      id: '/owner/integrations'
      path: '/owner/integrations'
      fullPath: '/owner/integrations'
      preLoaderRoute: typeof OwnerIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/mapa-vivo': {
      id: '/owner/mapa-vivo'
      path: '/owner/mapa-vivo'
      fullPath: '/owner/mapa-vivo'
      preLoaderRoute: typeof OwnerMapaVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/opportunities': {
      id: '/owner/opportunities'
      path: '/owner/opportunities'
      fullPath: '/owner/opportunities'
      preLoaderRoute: typeof OwnerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/plans': {
      id: '/owner/plans'
      path: '/owner/plans'
      fullPath: '/owner/plans'
      preLoaderRoute: typeof OwnerPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/owner/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/security': {
      id: '/owner/security'
      path: '/owner/security'
      fullPath: '/owner/security'
      preLoaderRoute: typeof OwnerSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/tests': {
      id: '/owner/tests'
      path: '/owner/tests'
      fullPath: '/owner/tests'
      preLoaderRoute: typeof OwnerTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/versions': {
      id: '/owner/versions'
      path: '/owner/versions'
      fullPath: '/owner/versions'
      preLoaderRoute: typeof OwnerVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AppsBenchmarkerRoute: AppsBenchmarkerRoute,
  AppsDiagnostico360Route: AppsDiagnostico360Route,
  AppsDigitalImprovementRoute: AppsDigitalImprovementRoute,
  AppsLabRoute: AppsLabRoute,
  AppsMeetingArchitectRoute: AppsMeetingArchitectRoute,
  AppsOpportunityIntelligenceRoute: AppsOpportunityIntelligenceRoute,
  AppsOrbitRoute: AppsOrbitRoute,
  AppsResearchScoutRoute: AppsResearchScoutRoute,
  AppsShowroomRoute: AppsShowroomRoute,
  AppsTeste3Route: AppsTeste3Route,
  AppsValidationGateRoute: AppsValidationGateRoute,
  AppsVersionRoute: AppsVersionRoute,
  CoreAiRoute: CoreAiRoute,
  CoreAppsRoute: CoreAppsRoute,
  CoreArchitectureRoute: CoreArchitectureRoute,
  CoreCallsRoute: CoreCallsRoute,
  CoreDataRoute: CoreDataRoute,
  CoreHealthRoute: CoreHealthRoute,
  CoreLabRoute: CoreLabRoute,
  CoreObservabilityRoute: CoreObservabilityRoute,
  CoreProblemsRoute: CoreProblemsRoute,
  CoreSecurityRoute: CoreSecurityRoute,
  CoreSettingsRoute: CoreSettingsRoute,
  CoreSolLuaRoute: CoreSolLuaRoute,
  CoreTestsRoute: CoreTestsRoute,
  CoreTrainingsRoute: CoreTrainingsRoute,
  CoreVersionsRoute: CoreVersionsRoute,
  InstallClientRoute: InstallClientRoute,
  InstallOwnerRoute: InstallOwnerRoute,
  LabtestNextRoute: LabtestNextRoute,
  OwnerAppsRoute: OwnerAppsRoute,
  OwnerClientsRoute: OwnerClientsRoute,
  OwnerCommercialRoute: OwnerCommercialRoute,
  OwnerDocumentsRoute: OwnerDocumentsRoute,
  OwnerIntegrationsRoute: OwnerIntegrationsRoute,
  OwnerMapaVivoRoute: OwnerMapaVivoRoute,
  OwnerOpportunitiesRoute: OwnerOpportunitiesRoute,
  OwnerPlansRoute: OwnerPlansRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  OwnerSecurityRoute: OwnerSecurityRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerTestsRoute: OwnerTestsRoute,
  OwnerVersionsRoute: OwnerVersionsRoute,
  CoreIndexRoute: CoreIndexRoute,
  LabtestIndexRoute: LabtestIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
