const CORE_VERSION='2.1.0';

const PLUGINS={
  native:{name:'Nativo LAMOU CORE',role:'Implementação interna sem dependência obrigatória de provedor',alternatives:['Sem substituição necessária'],switching:'N/A',continuity:'Funciona localmente; integração externa é opcional.',versionPolicy:'Versionado junto com o CORE.'},
  supabase:{name:'Supabase',role:'Postgres, Auth, Storage e Realtime',alternatives:['Neon + Auth.js + armazenamento compatível S3','Firebase','Appwrite'],switching:'Manual com adaptadores e migração de dados',continuity:'Nunca bloquear o app: manter interface de dados desacoplada e exportação/backup.',versionPolicy:'Registrar SDK e schema por aplicativo.'},
  authjs:{name:'Auth.js',role:'Autenticação web baseada em provedores e sessões',alternatives:['Supabase Auth','Clerk','Firebase Auth'],switching:'Manual por impacto em identidade/sessão',continuity:'Fallback local somente em TESTE; produção exige provedor válido.',versionPolicy:'Fixar versão no lockfile do app.'},
  cloudflare:{name:'Cloudflare',role:'CDN, Workers, R2, KV, proteção e edge',alternatives:['Vercel','Netlify','AWS compatível'],switching:'Manual/semiautomática conforme camada',continuity:'Arquivos e rotas críticas devem ter configuração portável.',versionPolicy:'Registrar APIs/Workers/Wrangler usados.'},
  vercel:{name:'Vercel',role:'Deploy web, Functions, CDN e previews',alternatives:['Cloudflare Pages/Workers','Netlify','Render'],switching:'Manual via adaptador de deploy',continuity:'Repositório e build devem permanecer portáveis.',versionPolicy:'Registrar CLI/build runtime quando aplicável.'},
  openai:{name:'OpenAI',role:'Modelos e recursos de IA',alternatives:['Gemini','Anthropic','Workers AI','Ollama/modelos locais'],switching:'Automática quando o AI Gateway suporta o mesmo contrato; manual se a capacidade divergir',continuity:'Circuit breaker + fallback determinístico/local para funções não críticas.',versionPolicy:'Registrar modelo e API por recurso, não hardcode global.'},
  gemini:{name:'Google Gemini',role:'Provedor alternativo de IA',alternatives:['OpenAI','Anthropic','Workers AI','Ollama/modelos locais'],switching:'Via AI Gateway',continuity:'Troca por capacidade e custo, sem quebrar fluxo principal.',versionPolicy:'Registrar modelo e API por recurso.'},
  anthropic:{name:'Anthropic',role:'Provedor alternativo de IA',alternatives:['OpenAI','Gemini','Workers AI'],switching:'Via AI Gateway',continuity:'Recurso deve degradar de forma explícita quando indisponível.',versionPolicy:'Registrar modelo e API por recurso.'},
  workersai:{name:'Cloudflare Workers AI',role:'Inferência de IA no edge',alternatives:['OpenAI','Gemini','Anthropic','Ollama'],switching:'Via AI Gateway',continuity:'Útil como rota econômica/fallback quando compatível.',versionPolicy:'Registrar modelo usado por função.'},
  ollama:{name:'Ollama / modelos locais',role:'Inferência local ou self-hosted',alternatives:['OpenAI','Gemini','Anthropic','Workers AI'],switching:'Via AI Gateway',continuity:'Fallback sem custo por chamada quando hardware permitir.',versionPolicy:'Registrar modelo e quantização.'},
  stripe:{name:'Stripe',role:'Billing e pagamentos',alternatives:['Mercado Pago','Pagar.me','PagSeguro'],switching:'Manual; contratos de cobrança não devem ser trocados silenciosamente',continuity:'Separar entitlement do provedor de pagamento.',versionPolicy:'Registrar SDK/API por app.'},
  mercadopago:{name:'Mercado Pago',role:'Pagamentos e cobrança',alternatives:['Stripe','Pagar.me','PagSeguro'],switching:'Manual',continuity:'Entitlements continuam internos ao CORE.',versionPolicy:'Registrar SDK/API por app.'},
  resend:{name:'Resend',role:'E-mail transacional',alternatives:['Brevo','SMTP próprio','Amazon SES'],switching:'Semiautomática via adaptador de e-mail',continuity:'Fila/retry e segundo provedor quando necessário.',versionPolicy:'Registrar SDK e template versionado.'},
  fcm:{name:'Firebase Cloud Messaging',role:'Push notifications',alternatives:['Web Push nativo','OneSignal'],switching:'Semiautomática',continuity:'Notificação não pode ser requisito único para concluir fluxo.',versionPolicy:'Registrar SDK por app.'},
  fullcalendar:{name:'FullCalendar',role:'Interface de calendário',alternatives:['React Big Calendar','UI própria + API de calendário'],switching:'Manual de UI',continuity:'Dados de agenda devem ficar separados do componente visual.',versionPolicy:'Fixar versão no front-end.'},
  yjs:{name:'Yjs',role:'Colaboração em tempo real/CRDT',alternatives:['Automerge','Liveblocks'],switching:'Manual',continuity:'Colaboração é camada opcional; persistência base continua íntegra.',versionPolicy:'Fixar versão e provider usado.'},
  posthog:{name:'PostHog',role:'Analytics, feature flags e experimentos',alternatives:['Umami','Plausible','GrowthBook + analytics próprio'],switching:'Semiautomática para eventos padronizados',continuity:'Aplicativo funciona sem analytics.',versionPolicy:'Versionar schema de eventos.'},
  sentry:{name:'Sentry',role:'Erros, performance e observabilidade',alternatives:['OpenTelemetry + backend próprio','Better Stack','Grafana stack'],switching:'Semiautomática',continuity:'Falha de observabilidade nunca bloqueia operação.',versionPolicy:'Fixar SDK por runtime.'},
  otel:{name:'OpenTelemetry',role:'Padrão aberto de traces, métricas e logs',alternatives:['Sentry SDK','Grafana stack'],switching:'Semiautomática',continuity:'Preferir instrumentação vendor-neutral.',versionPolicy:'Registrar packages por runtime.'},
  upstash:{name:'Upstash Redis',role:'Cache, rate limit e filas leves',alternatives:['Cloudflare KV/Queues','Redis self-hosted','Vercel Runtime Cache'],switching:'Semiautomática por adapter',continuity:'Cache nunca é fonte única da verdade.',versionPolicy:'Registrar cliente/protocolo.'},
  workbox:{name:'Workbox',role:'Service worker/PWA',alternatives:['vite-plugin-pwa','Service Worker nativo'],switching:'Manual de build',continuity:'App web continua funcional sem modo offline completo.',versionPolicy:'Fixar versão do build plugin.'},
  axe:{name:'axe-core',role:'Testes de acessibilidade',alternatives:['Lighthouse Accessibility','Pa11y'],switching:'Automática no pipeline de qualidade',continuity:'Manter mais de um verificador quando possível.',versionPolicy:'Fixar no ambiente de teste.'},
  lighthouse:{name:'Lighthouse',role:'Performance, PWA, SEO e acessibilidade',alternatives:['WebPageTest','PageSpeed Insights','checks próprios'],switching:'Automática no pipeline',continuity:'Métrica auxiliar; não bloqueia runtime.',versionPolicy:'Registrar versão do CI/tool.'},
  i18next:{name:'i18next',role:'Internacionalização',alternatives:['FormatJS','Lingui'],switching:'Manual por formato de mensagens',continuity:'Idioma padrão precisa funcionar sem serviço externo.',versionPolicy:'Fixar versão no app.'},
  papaparse:{name:'Papa Parse',role:'Importação/exportação CSV',alternatives:['Parser nativo/streaming','SheetJS para planilhas'],switching:'Manual por formato',continuity:'JSON aberto continua como formato de backup universal.',versionPolicy:'Fixar no app.'},
  sheetjs:{name:'SheetJS',role:'Leitura/escrita de planilhas',alternatives:['ExcelJS','CSV + Papa Parse'],switching:'Manual por recursos usados',continuity:'Exportação CSV/JSON deve existir como rota simples.',versionPolicy:'Fixar no app.'},
  growthbook:{name:'GrowthBook',role:'Feature flags e experimentação',alternatives:['PostHog Feature Flags','Unleash'],switching:'Semiautomática via adapter de flags',continuity:'Defaults locais obrigatórios para cada flag.',versionPolicy:'Versionar definições de flags.'},
  chatwoot:{name:'Chatwoot',role:'Suporte/chat self-hosted',alternatives:['tawk.to','Crisp','formulário/e-mail interno'],switching:'Manual de canal',continuity:'Suporte básico por e-mail/formulário permanece disponível.',versionPolicy:'Registrar integração por app.'},
  githubactions:{name:'GitHub Actions',role:'CI/CD e automação de repositório',alternatives:['GitLab CI','Cloudflare/Vercel build hooks'],switching:'Manual do pipeline',continuity:'Build local documentado é fallback obrigatório.',versionPolicy:'Workflows versionados no repositório.'},
  playwright:{name:'Playwright',role:'E2E, smoke e automação de navegador',alternatives:['Cypress','WebdriverIO'],switching:'Manual de suíte',continuity:'Smoke mínimo pode usar checks nativos.',versionPolicy:'Fixar versão no ambiente de teste.'},
  vitest:{name:'Vitest',role:'Testes unitários/integração JS/TS',alternatives:['Jest','Node test runner'],switching:'Manual de runner',continuity:'Contratos de teste independem do runner.',versionPolicy:'Fixar versão no projeto.'},
  msw:{name:'MSW',role:'Mocks de API no TESTE/DEMO',alternatives:['Mocks do framework','servidor fake local'],switching:'Manual de testes',continuity:'Nunca carregar mocks no OFICIAL/PRODUÇÃO.',versionPolicy:'Fixar no ambiente de teste.'},
  zap:{name:'OWASP ZAP',role:'Varredura de segurança dinâmica',alternatives:['Nuclei','Burp Community + checks manuais'],switching:'Pipeline de segurança',continuity:'Segurança possui checklist mesmo sem scanner.',versionPolicy:'Registrar versão da imagem/ferramenta.'},
  renovate:{name:'Renovate',role:'Atualização automatizada de dependências',alternatives:['Dependabot','atualização manual programada'],switching:'Automática/manual',continuity:'Atualização nunca entra em produção sem testes.',versionPolicy:'Config versionada.'}
};

const C={
  access:'Identidade & Acesso',ui:'UI & Experiência',data:'Dados & Conteúdo',productivity:'Produtividade & Comunicação',ai:'IA & Automação',business:'Comercial reutilizável',integration:'Integrações & APIs',governance:'Segurança & Governança',reliability:'Confiabilidade & Observabilidade',delivery:'Entrega & Qualidade',core:'Governança do CORE'
};

function mod(id,name,cat,kind,does,depends=[],plugins=['native']){return{id,name,category:C[cat],kind,does,depends,plugins,version:'CORE 2.1 baseline',history:['Inventariado no manifesto CORE 2.1'],status:'Ativo no catálogo'}}

const CORE_MODULES=[
  mod('identity','Identidade','access','CORE','Nome, marca, tema, metadados, tenant e identidade visual base.'),
  mod('auth','Autenticação','access','CORE','Login, logout, recuperação, sessão, OAuth e políticas de acesso.',['identity'],['authjs','supabase']),
  mod('users','Usuários & Perfis','access','CORE','Cadastro, perfil, preferências, status e ciclo de vida do usuário.',['auth'],['supabase']),
  mod('workspaces','Organizações / Workspaces','access','CORE','Isolamento por empresa, equipe ou workspace.',['users'],['supabase']),
  mod('rbac-abac','RBAC / ABAC','access','CORE','Papéis, permissões, políticas e autorização granular.',['auth','users','workspaces'],['native','supabase']),
  mod('ui-shell','App Shell / Navegação','ui','CORE','Estrutura padrão de sidebar, topbar, rotas, modais, feedback e responsividade.',['identity'],['native']),
  mod('design-system','Design System','ui','CORE','Tokens, componentes, estados, tipografia, ícones, spacing e padrões de interação.',['ui-shell'],['native']),
  mod('accessibility','Acessibilidade','ui','CORE','Teclado, foco, contraste, ARIA, leitores, Libras quando aplicável e auditoria a11y.',['design-system'],['axe','lighthouse']),
  mod('i18n','Internacionalização','ui','OPTIONAL','Idiomas, formatos locais, traduções e fallback de locale.',['design-system'],['i18next']),
  mod('onboarding','Onboarding','ui','RECOMMENDED','Primeiro acesso, tours, setup inicial e progressão guiada.',['users','design-system'],['native']),
  mod('persistence','Banco / Persistência','data','CORE','CRUD, schema, queries, migrações, consistência e políticas de retenção.',['workspaces'],['supabase']),
  mod('autosave-versioning','Autosave & Versionamento','data','CORE','Salvar automaticamente, rascunhos, snapshots e recuperação de alterações.',['persistence'],['native','supabase']),
  mod('files-media','Arquivos & Mídia','data','CORE','Upload, download, metadados, permissões, preview e armazenamento.',['persistence'],['supabase','cloudflare']),
  mod('search-filters','Busca & Filtros','data','RECOMMENDED','Busca textual, filtros, ordenação, paginação e indexação.',['persistence'],['supabase']),
  mod('import-export','Importação / Exportação','data','CORE','JSON, CSV, planilhas e formatos portáveis para entrada/saída de dados.',['persistence'],['papaparse','sheetjs']),
  mod('notifications','Notificações','productivity','RECOMMENDED','Central de avisos, e-mail, push e preferências por canal.',['users'],['resend','fcm']),
  mod('calendar-tasks','Agenda & Tarefas','productivity','OPTIONAL','Eventos, compromissos, prazos, recorrência e tarefas.',['users','notifications'],['fullcalendar']),
  mod('collaboration','Colaboração','productivity','OPTIONAL','Edição simultânea, presença, comentários e conflitos.',['users','persistence'],['yjs']),
  mod('communications','Comunicação','productivity','OPTIONAL','E-mail, push, links de WhatsApp e mensagens transacionais.',['notifications'],['resend','fcm']),
  mod('support','Suporte','productivity','OPTIONAL','Ajuda, tickets, chat, base de conhecimento e contato.',['users'],['chatwoot']),
  mod('ai-gateway','AI Core / Gateway','ai','CORE','Roteamento multi-modelo, fallback, BYOK, política de custo, segurança e logs.',['settings','security'],['openai','gemini','anthropic','workersai','ollama']),
  mod('prompt-library','Biblioteca de Prompts','ai','RECOMMENDED','Prompts versionados, variáveis, testes, status e auditoria.',['ai-gateway','persistence'],['native']),
  mod('billing-quotas','Billing / Planos / Quotas','business','OPTIONAL','Planos, limites, uso, medição e regras de entitlement.',['users','workspaces'],['stripe','mercadopago']),
  mod('commercial-entitlements','Entitlements Comerciais','business','OPTIONAL','Liga contrato/plano a módulos e permissões sem acoplar pagamento ao produto.',['billing-quotas','rbac-abac'],['native']),
  mod('client-contracts','Contratos / Clientes reutilizáveis','business','OPTIONAL','Estrutura genérica de cliente, contrato, vigência e módulos contratados.',['workspaces','commercial-entitlements'],['native']),
  mod('mrr','Receita Recorrente / MRR','business','OPTIONAL','Indicadores recorrentes quando o produto exigir gestão de receita.',['client-contracts'],['native']),
  mod('integrations','Integrações','integration','CORE','Catálogo de integrações, credenciais, adapters e status.',['settings'],['native']),
  mod('api-webhooks','API & Webhooks','integration','CORE','Contratos de API, autenticação, webhooks, retry e idempotência.',['auth','integrations'],['native','cloudflare']),
  mod('security','Segurança','governance','CORE','Segredos, headers, proteção, rate limit, hardening, isolamento e resposta a incidentes.',['auth','persistence'],['cloudflare','upstash','zap']),
  mod('lgpd','LGPD / Privacidade','governance','CORE','Finalidade, consentimento quando aplicável, retenção, exclusão, exportação e direitos do titular.',['users','persistence','security'],['native']),
  mod('audit-logs','Auditoria','governance','CORE','Quem fez o quê, quando, onde e qual objeto foi alterado.',['users','persistence'],['native','otel']),
  mod('admin','Painel Admin','governance','CORE','Administração de usuários, workspaces, módulos, suporte e políticas.',['rbac-abac','audit-logs'],['native']),
  mod('settings','Configurações','governance','CORE','Configuração por usuário, workspace, ambiente e aplicação.',['users','workspaces'],['native']),
  mod('feature-flags','Feature Flags','governance','RECOMMENDED','Ativação gradual, rollback e experimentos sem redeploy obrigatório.',['settings'],['posthog','growthbook']),
  mod('analytics','Analytics','reliability','RECOMMENDED','Eventos, funil, adoção, retenção e uso de funcionalidades.',['users'],['posthog']),
  mod('observability','Observabilidade','reliability','CORE','Logs, traces, métricas, correlação e diagnóstico operacional.',['analytics'],['otel','sentry']),
  mod('error-handling','Tratamento de Erros','reliability','CORE','Erros padronizados, retry, mensagens úteis e captura técnica.',['observability'],['sentry']),
  mod('backup-dr','Backup & DR','reliability','CORE','Backup, restauração, RPO/RTO quando aplicável e saída de fornecedor.',['persistence','files-media'],['supabase','cloudflare']),
  mod('performance-cache','Performance / Cache / CDN','reliability','CORE','Cache, CDN, compressão, lazy loading, rate limit e otimização.',['persistence'],['cloudflare','upstash','vercel']),
  mod('app-health','APP HEALTH','reliability','CORE','Saúde do app, checks, dependências, status de integrações e alertas.',['observability','error-handling'],['native','sentry']),
  mod('pwa-mobile','PWA / Mobile','delivery','CORE','Manifest, instalação, service worker, atualização e comportamento mobile.',['ui-shell'],['workbox']),
  mod('environments','Ambientes DEV / TESTE / STG / PROD','delivery','CORE','Isola configuração, dados, segredos e comportamento por ambiente.',['settings','security'],['native']),
  mod('ci-cd','CI / CD','delivery','CORE','Build, lint, testes, gates, artefatos e publicação controlada.',['environments','automated-tests'],['githubactions']),
  mod('automated-tests','Testes Automatizados','delivery','CORE','Unitário, integração, E2E, regressão, smoke e acessibilidade.',['environments'],['vitest','playwright','axe']),
  mod('deployment','Deploy','delivery','CORE','Publicação, previews, rollback, domínios e release.',['ci-cd'],['vercel','cloudflare']),
  mod('pre-production-check','PRE-PRODUCTION CHECK','delivery','CORE','Gate obrigatório antes de promover TESTE para OFICIAL.',['automated-tests','security','lgpd','app-health'],['playwright','lighthouse','zap']),
  mod('official-version-registry','Registro de Versão Oficial','delivery','CORE','Mantém uma versão oficial, histórico, changelog, artefato e rastreabilidade.',['pre-production-check'],['native']),
  mod('auto-update','Canal de Atualização','delivery','CORE','Detecta e aplica atualização PWA/app de forma controlada.',['official-version-registry','pwa-mobile'],['workbox']),
  mod('test-mode','TEST MODE / Sandbox','core','CORE','Ambiente permanente para simulação, dados fictícios, mocks e homologação.',['environments','automated-tests'],['msw','playwright']),
  mod('product-critic','PRODUCT CRITIC','core','CORE','Audita UX, UI, arquitetura, segurança, acessibilidade, performance e coerência do produto.',['test-mode','app-health'],['lighthouse','axe','playwright']),
  mod('improve-mode','IMPROVE MODE','core','CORE','Transforma achados do critic em fila priorizada de correções com evidência.',['product-critic','audit-logs'],['native']),
  mod('module-manager','MODULE MANAGER','core','CORE','Catálogo de módulos, dependências, plugins, alternativas, compatibilidade e impacto de mudança.',['official-version-registry'],['native','renovate']),
  mod('core-update-center','CORE UPDATE CENTER','core','CORE','Controla mudanças do CORE, versões, compatibilidade, migrações e rollout para aplicativos.',['module-manager','automated-tests'],['githubactions','renovate'])
];

window.CORE_VERSION=CORE_VERSION;
window.CORE_PLUGINS=PLUGINS;
window.CORE_MODULES=CORE_MODULES;
